### ISSUE TITLE
report handshake errors when doing stateless packet handling

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1002]
mint returns an internal error, so we never send out a response to an Initial packet, so the client will eventually run into a connection timeout. In fact, this is what happens in the corresponding integration test: https://github.com/lucas-clemente/quic-go/blob/master/integrationtests/self/handshake_test.go#L98-L102

**Comment by marten-seemann** [comment]
This issue would be resolved if https://github.com/bifurcation/mint/pull/155 was merged.

**Comment by marten-seemann** [comment]
I just realized that the issue here is that the stateless part of the server never sends CONNECTION_CLOSEs. While it is the right thing to ignore packets that cannot be unpacked (i.e. that return an error while unpacking), from a certain point on we should inform the client about errors.

**Comment by jadekler** [comment]
Is this bug related to these sorts of errors `panic: HandshakeTimeout: Crypto handshake did not complete in time.`? I'm seeing a bunch of them at the moment

**Comment by marten-seemann** [comment]
Probably not. This in the TLS 1.3 code path, which is experimental at this moment.

Which server are you trying to connect to when you get these errors?

**Comment by jadekler** [comment]
Aha, ok. Just a local server @marten-seemann

**Comment by marten-seemann** [comment]
That shouldn't happen. You can try [increasing the log level](https://github.com/lucas-clemente/quic-go/wiki/Logging) to see what's going on. If you think you found a bug, please feel free to open a new issue.

**Comment by jadekler** [comment]
@marten-seemann I shall do so!
