### ISSUE TITLE
directly queue control frames from the stream

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1004]
Currently, the sending WINDOW_UPDATEs works like this: When data is `Read` from a stream, we call the `onData()` callback, which schedules the sending of a new packet, which then will go through all the streams and get the WINDOW_UPDATEs.
This is not optimal for two reasons:
1. We're calling `onData()` for every `Read`, even if no WINDOW_UPDATE needs to be sent. This will result in unnecessary attempts to send an empty packet.
2. For every time we send a packet, we're going through all open streams and ask them if they have window updates to send.

Note that 1. can trivially be fixed by asking the flow controller if there are window updates before calling `onData()`.

My suggestion for fixing this is the following:
We add a callback to the stream: `queueControlFrame(wire.Frame)`. This callback allows the stream to pass any control frame to the session (which would then pass it on to the `packetPacker`). The callback would be used to queue WINDOW_UPDATEs, BLOCKED frames as well as RST_STREAM frames.
When packing a packet, there's no need to ask every stream for WINDOW_UPDATEs and BLOCKED_FRAMEs (we only need to ask the connection flow controller for the corresponding connection-level frames). This will solve both issues mentioned above.

**Comment by lucas-clemente** [comment]
SGTM
