### ISSUE TITLE
cannot convert "ServerStateStart" to type mint.State

### ISSUE THREAD

**Issue by huowa222** [lucas-clemente/quic-go#1014]
internal/handshake/crypto_setup_tls.go:213:8: cannot convert "ServerStateStart" to type mint.State

**Comment by julienschmidt** [comment]
Seems like your copy of go-quic is outdated. The type of server states were recently changed.
If `go get -u  github.com/lucas-clemente/quic-go` doesn't fix it `rm -rf $GOPATH/pkg/github.com/lucas-clemente/quic-go` (compiler cache of the package).

**Comment by marten-seemann** [comment]
@julienschmidt, thanks for providing the fix.
@huowa222, I’m closing this issue. Feel free to comment or open a new one should you have any further problems.
