### ISSUE TITLE
Remove second parameter from session.Close

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#102]
It should be inferred from the internal session state by Close().

**Comment by marten-seemann** [comment]
Possible duplicate of #86.

**Comment by lucas-clemente** [comment]
I don't think so. #86 is about sending the correct error codes, which involves changes to crypto, parsing, … This issue is about the question when to send connection close frames, which should be auto-detected by session.

**Comment by marten-seemann** [comment]
Yeah, but it requires a way to set the correct error code within the session, for the Close() method to send them with the ConnectionClose Frame.

So it probably makes sense to fix #86 first.

**Comment by lucas-clemente** [comment]
We already have that! Just return a `protocol.QuicError`. We just need to use them throughout the server ;)
