### ISSUE TITLE
Error when run example server !

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1039]
Hi guys,
I am a newbie about QUIC. I follow the instructions to install and update the dependencies. I use go v1.9. However, I get some errors when running the example server.
This is my error:

_example/main.go:22:2: use of internal package not allowed
example/main.go:23:2: use of internal package not allowed_

Anybody know how to fix this?
Thank you in advance !

**Comment by marten-seemann** [comment]
It's probably a problem with your GOPATH. Please check your Go installation.
