### ISSUE TITLE
Change the private key and certificate !

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1077]
Hi.
I am a newbie about QUIC. I built and run the example successfully. And I want to add another  private key and  certificate for other domain name.
Anybody know how to change the key and certificate?
Thank you in advance!

**Comment by marten-seemann** [comment]
You can pass a tls.Config to the Listen and Dial functions, see https://godoc.org/github.com/lucas-clemente/quic-go.

**Comment by shinichikudo987** [comment]
Hi marten-seemann,

Is there anyway to create another fullchain.pem and privkey.pem?

**Comment by marten-seemann** [comment]
This is not a QUIC-related issue, it’s the same way you would do that to set up a tls.Conn, or a https server.
You can use the search engine of your preference to find out more about TLS and how to use it with Go.
