### ISSUE TITLE
Store window update values for later

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#108]
If the frame opening a new stream gets lost, and the window update arrives before, we currently discard it. We should keep it for later use.

**Comment by marten-seemann** [comment]
How could that happen? The client won't send us an WindowUpdate unless we already sent him enough data to fill the flow control window. However, this won't happen before we create the stream.

**Comment by lucas-clemente** [comment]
The client could in theory send a window update immediately; at least I don't see anything in the spec forbidding that. I don't think Chrome does that, so this issue is not of high priority.

**Comment by marten-seemann** [comment]
Chrome checks for the amount of data read from a stream, so this won't happen.

Furthermore, after fixing #100, we will send a Blocked frame for a stream that is flow control blocked, and the client will probably respond to this by repeating the WindowUpdate.
