### ISSUE TITLE
Ability to specify a fastcgi socket/address for processing cgi scripts at example server

### ISSUE THREAD

**Issue by Henrocker** [lucas-clemente/quic-go#1107]
Hi,

despite caddy being able to handle fastcgi requests, I would also like to specify a fastcgi socket when starting the example server from the command line. 

Is that possible?

Because I'm currently running an nginx webserver and parallel to that the example server of quic-go is running for visitors to be directed to the quic version of my site.

Thanks.

**Comment by marten-seemann** [comment]
I don't know a lot about fastcgi, so I'm probably misunderstanding your problem.
Does it work if you use [https://godoc.org/github.com/lucas-clemente/quic-go#Listen](quic.Listen)? You can provide a `net.PacketConn` to listen on there.

**Comment by Henrocker** [comment]
My question was referring to the ability to specify a fastcgi socket or TCP Address for php and lua to get processed when starting the example quic server via command line. E.g:

go run example/main.go -www /etc/nginx/html -bind my.ip.ad.dr:443 -v -certpath /etc/nginx ***-fastcgi unix:/var/run/php7.0-fpm.sock***

So when a php site instead of a html document is requested to the quic server it knows where to send it to to process the request.

Is that possible?

Thanks

**Comment by marten-seemann** [comment]
There's no point in running QUIC on top of TCP.

The example server is not intended to cover every possible use case, but to give people an idea how to use our API for their specific use case.
