### ISSUE TITLE
Support single server session

### ISSUE THREAD

**Issue by r0l1** [lucas-clemente/quic-go#1115]
It would be great to be able to pass an already connected net.PacketConn to quic and create a single server session without the listener overhead.

This is already possible with go's TLS package.

### Client:
```go
	conn = tls.Client(innerConn, config)
	err = (conn.(*tls.Conn)).Handshake()
```

### Server:
```go
	conn = tls.Server(innerConn, config)
	err = (conn.(*tls.Conn)).Handshake()
```

**Comment by marten-seemann** [comment]
I'm not sure if this is possible, because there's no "connected" net.PacketConn in the sense that you can have connected TCP connection.
QUIC version negotiation and remote address validation can be performed statelessly, so a QUIC server necessarily needs to accept packets from new connections.

**Comment by r0l1** [comment]
net.PacketConn is just an interface. A client UDP session is bound to its own socket port. The same can be done with a server UDP session. In my case, I have a complete stack behind the packet handling. But this is hidden behind the implemented net.PacketConn.

Instead of having the overhead of a complete listener/server with multiple session maps, I would appreciate, if we could work out a solution to remove the unnecessary bloat.

**Comment by marten-seemann** [comment]
We recently moved in the opposite direction by implementing the [multiplexer](https://github.com/lucas-clemente/quic-go/blob/master/multiplexer.go) and the [packetHandlerMap](https://github.com/lucas-clemente/quic-go/blob/master/packet_handler_map.go), and using those for clients as well as servers.
