### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by r0l1** [lucas-clemente/quic-go#1121]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x6a3ca7]

goroutine 201 [running]:

github.com/lucas-clemente/quic-go.(*streamFramer).maybePopNormalFrames(0xc4204c2620, 0x49b, 0x0, 0x0, 0x0)
	...vendor/src/github.com/lucas-clemente/quic-go/stream_framer.go:121 +0x1a7
github.com/lucas-clemente/quic-go.(*streamFramer).PopStreamFrames(0xc4204c2620, 0x49b, 0xc42003fa80, 0x411a57, 0xc4203e8bd0)
	...vendor/src/github.com/lucas-clemente/quic-go/stream_framer.go:57 +0x91
github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket(0xc4200b8480, 0x499, 0xc451303301, 0xb, 0x0, 0x0, 0xc42003fbc0, 0xc42003fbb8)
	...vendor/src/github.com/lucas-clemente/quic-go/packet_packer.go:269 +0x312
github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket(0xc4200b8480, 0x0, 0x0, 0x0)
	...vendor/src/github.com/lucas-clemente/quic-go/packet_packer.go:159 +0x1a5
github.com/lucas-clemente/quic-go.(*session).sendPacket(0xc420238000, 0x1, 0x0, 0x0)
	...vendor/src/github.com/lucas-clemente/quic-go/session.go:826 +0x605
github.com/lucas-clemente/quic-go.(*session).run(0xc420238000, 0x0, 0x0)
	...vendor/src/github.com/lucas-clemente/quic-go/session.go:430 +0x11a
github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession.func1(0x98d840, 0xc420238000, 0xc4200ac000, 0x92a386ac494a977e)
	...vendor/src/github.com/lucas-clemente/quic-go/server.go:388 +0x34
created by github.com/lucas-clemente/quic-go.(*server).runHandshakeAndSession
	...vendor/src/github.com/lucas-clemente/quic-go/server.go:387 +0x61
```

**Comment by r0l1** [comment]
Might be caused by a duplicate close call...

**Comment by marten-seemann** [comment]
Thanks for the bug report. This should definitely not happen.
Can you tell me what exactly I need to do to reproduce this bug? It would be awesome if you could post the code that leads to the panic.

**Comment by r0l1** [comment]
Sorry for the little description. Was too tired. I didn't dig into this, because I had to get this fixed and I can't reproduce it right now. However, I assume that this was caused by the fact, that the server was running a slightly older version of the quic server. Commit state from last week....

**Comment by r0l1** [comment]
Oh, and I did massive network performance tests... It crashed always during a very high load.

**Comment by marten-seemann** [comment]
Thanks for the update. Please let me know if this ever occurs again. I recently rewrote a lot of the code relating to streams, and maybe I missed a corner case. A nil pointer derefernce is a severe bug (and potentially security relevant), so I really appreciate any information about that.

**Comment by lucas-clemente** [comment]
I only had a brief look, but I think we should check str != nil [here](https://github.com/lucas-clemente/quic-go/blob/ca0f9f4a12199124e27a0c8d8f3bcd7b96c2efc7/stream_framer.go#L121), as there are cases where we return nil, nil from the [stream_map](https://github.com/lucas-clemente/quic-go/blob/ca0f9f4a12199124e27a0c8d8f3bcd7b96c2efc7/streams_map.go#L105).
