### ISSUE TITLE
Does this support for v 39?

### ISSUE THREAD

**Issue by wanghui0720** [lucas-clemente/quic-go#1133]
Does this support for v 39?

I used the caddy for a simple server, but i see "alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"" from the response header.

**Comment by marten-seemann** [comment]
Yes, we've been supporting Q039 for about half a year.
The problem is that Caddy hasn't updated its vendored quic-go for such a long time, see https://github.com/mholt/caddy/pull/1968.
