### ISSUE TITLE
Wrong UsesIETFFrameFormat() result in receiveStream.CancelRead

### ISSUE THREAD

**Issue by lins05** [lucas-clemente/quic-go#1147]
## What is Observed

When the h2quic based http2 server returns an error code (e.g. with `http.Error`) directly without reading the request body, the client would error with "unknown type byte 0xc".

## My Naive Debugging

"0xc" is the IETF `StopSendingFrame` sent by the server. But this should not happen because the client/server are using gQUIC version 39.

https://github.com/lucas-clemente/quic-go/blob/d9d384b6ed2af3246312683e2f676064232435c6/h2quic/server.go#L229-L234

https://github.com/lucas-clemente/quic-go/blob/d9d384b6ed2af3246312683e2f676064232435c6/receive_stream.go#L182-L186

I added a print statement here and the result shows s.version is "whatever", which is 0. But it should be version39. So it looks like a bug to me.

**Comment by marten-seemann** [comment]
Thanks for the bug report, and the excellent debugging work!
It looks like we're not passing the version number to the `receiveStream` constructor in https://github.com/lucas-clemente/quic-go/blob/master/receive_stream.go#L54-L66, so that the `version` is initialized to its default value (0).
