### ISSUE TITLE
use a pseudo-random function to determine skipped packet numbers

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1149]
As Kazuho pointed out in https://github.com/quicwg/base-drafts/issues/1092#issuecomment-362574769, we can use a pseudo-random function to determine which packet numbers to skip.

**Comment by mikkelfj** [comment]
If such a function is formalized, with an unpredictable key, of course, it would remove a class of attacks on the receivers indexing of received packets, for example by simply dropping a connection if the index starts to use too much space per packet on average. It would also put a bound the gap size so large gap jumps are ruled out. This would alleviate some of my concerns regarding gaps.

**Comment by mikkelfj** [comment]
I thought this was a general QUIC issue, not quic-go, but I would actually recommend making this a general QUIC proposal for the above reason.

**Comment by marten-seemann** [comment]
I'm not sure any more if this actually is an improvement to what we have at the moment. Evaluating a cryptographic hash function every single time we send a packet and multiple times when we receive an ACK might be slow (and cause a lot of unnecessary allocations).
The main advantage of the pseudo-random function seems to be that it doesn't require any per-connection state. However, it's not clear how we could defend against the DoS attack where a peer sends us an ACK for a large number of packets, without keeping a slice of skipped packet numbers around. If that's the case, we might as well keep using real random to generate the skips.

**Comment by marten-seemann** [comment]
Using dummy-packets in the packet history (as implemented in #2753) is probably the easier solution.
