### ISSUE TITLE
benchmark test very slow

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1160]
This is probably due to RTOs happening during the test.

**Comment by marten-seemann** [comment]
The benchmark tests seem quite predictable now, so I guess this issue was resolved by *something*.

**Comment by lnykww** [comment]
@marten-seemann 
I'm using your benchmark project from github.com/marten-seemann/quic-go-benchmarks.
And It looks like the performance is terrible. Is this test result correct?

• [MEASUREMENT]
File Transfers
  QUIC: transfering 100 MB of data

  Ran 3 samples:
  runtime:
    Fastest Time: 2.586s
    Slowest Time: 2.728s
    Average Time: 2.660s ± 0.058s
------------------------------
• [MEASUREMENT]
File Transfers
  TCP: transfering 100 MB of data

  Ran 3 samples:
  runtime:
    Fastest Time: 0.102s
    Slowest Time: 0.105s
    Average Time: 0.103s ± 0.001s

**Comment by Fabse333** [comment]
@marten-seemann 
I have the same issue as @lnykww :
• [MEASUREMENT]
File Transfers
  QUIC: transfering 100 MB of data

  Ran 3 samples:
  runtime:
    Fastest Time: 2.611s
    Slowest Time: 2.740s
    Average Time: 2.676s ± 0.053s
------------------------------
• [MEASUREMENT]
File Transfers
  TCP: transfering 100 MB of data

  Ran 3 samples:
  runtime:
    Fastest Time: 0.160s
    Slowest Time: 0.204s
    Average Time: 0.178s ± 0.019s
------------------------------

It looks like quic-go limits UDP packets to a length of 1251 bytes (according to wireshark), making it much more inefficient than TCP which uses larger packet sizes.
I also could verify it with h2quic with a ~5MB response, where the difference increases with larger response payload:
HTTPS(QUIC): Needed 147.163026 ms
HTTPS(TCP):  Needed 43.492046 ms
HTTP(TCP):   Needed 34.801348 ms

**Comment by Fabse333** [comment]
It seems the [missing path MTU discovery](https://github.com/lucas-clemente/quic-go/issues/94) is causing the [limited packet size](https://github.com/lucas-clemente/quic-go/issues/882).
But even if I set the MaxPacketSizeIPv4 variable in internal/protocol/params.go value to 10000 bytes, it is not sending larger UDP packets than 1451bytes.
@marten-seemann Do you have any suggestions on how to increase packet size manually, so we could check if this is the performance bottleneck and I could increase it for controlled local environements?
