### ISSUE TITLE
set Don't Fragment flag in IPv4 packets

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#117]

**Comment by marten-seemann** [comment]
This only makes sense if we do PMTUD (#94). At the moment, we're better of having our packets fragmented than dropped.

**Comment by tobyxdd** [comment]
I believe this now makes sense and is worth revisiting since PMTUD has been implemented

**Comment by marten-seemann** [comment]
@tobyxdd I think most operating systems already set the DF bit. What system have you observed it not being set on?

**Comment by tobyxdd** [comment]
@marten-seemann Windows. I'm not getting DF bit (at least on both of my Windows 10 machines) so I currently use this code:

```go
func SetDontFragment(conn *net.UDPConn) error {
	rawConn, err := conn.SyscallConn()
	if err != nil {
		return err
	}
	var err1, err2 error
	err1 = rawConn.Control(func(fd uintptr) {
		// https://docs.microsoft.com/en-us/troubleshoot/windows/win32/header-library-requirement-socket-ipproto-ip
		// #define IP_DONTFRAGMENT        14     /* don't fragment IP datagrams */
		err2 = syscall.SetsockoptInt(syscall.Handle(fd), syscall.IPPROTO_IP, 14, 1)
	})
	if err1 != nil {
		return err1
	}
	return err2
}
```

**Comment by marten-seemann** [comment]
@tobyxdd Could you send us a PR for this? As far as I can see, the platform-dependent code is already in place (`newConn` *conn_windows.go*). The logic would probably be somewhat similar to what we have for `newConn` in *conn_oob.go*.

**Comment by tobyxdd** [comment]
No problem. Should I implement it for Linux too? I'm getting the DF bit by default on Ubuntu 20.04 but I don't know if this behavior is consistent across different kernel versions & distros. To explicitly set it we can use `syscall.SetsockoptInt(int(fd), syscall.IPPROTO_IP, syscall.IP_MTU_DISCOVER, syscall.IP_PMTUDISC_PROBE)`.

I don't have much experience with macOS but it seems there is no easy way on that...

**Comment by marten-seemann** [comment]
I guess it doesn’t hurt to set it on Linux as well.
