### ISSUE TITLE
quic.Session's use of `internal` package means it can't be mocked

### ISSUE THREAD

**Issue by lthibault** [lucas-clemente/quic-go#1175]
As stated in the title, the fact that `quic.Session` relies on `handshake.ConnectionState` means that it's impossible to write a struct that satisfies `quic.Session`.

This is problematic for unit-testing code that uses quic-go internally.

**Comment by marten-seemann** [comment]
The `quic.Session` doesn't depend on the `handshake.ConnectionState`, but on the `quic.ConnectionState` (which is a type alias).
Therefore it can be mocked, and in fact, I'm doing this in the [quic-conn](https://github.com/marten-seemann/quic-conn).
