### ISSUE TITLE
Support for Apps

### ISSUE THREAD

**Issue by Jabervan** [lucas-clemente/quic-go#1183]
How can i implement the library for the apps?
I am a newer of golang.
Please give me some guidance, thank you very much!

**Comment by marten-seemann** [comment]
Please refer to the README, the Godoc and the examples. 
Feel free to open a new issue if you have any specific questions.

**Comment by Jabervan** [comment]
Appreciate your quick reply!
I try to build a dependency library by Gomobile, and it's been a long time. but failed.
I very much want to integrate quic-go in our apps to solve the problems we facing.
Please share me a sample, thanks very much!
