### ISSUE TITLE
Connection refused from Chrome browser

### ISSUE THREAD

**Issue by ByungjinJun** [lucas-clemente/quic-go#1208]
Hi, 

First of all, thank you for providing such a good lib for quic-server. 

I have used quic-go to implement my own Quic server. I succeeded to establish quic connection between example-server and example-client without going through clemente.io. Beyond this, I want to client can access to my Quic server from Chrome, but have failed so far. I tried two different things like below.

1. Connect to the server in Chrome browser (using Domain name)
 - server itself serves fine -> I was able to make a client connect to my Quic server thru TCP connection in Chrome when server is running with -tcp option. CA cert is also fine.
 - but server never respond to the client thru Quic (without -tcp option). Connection refused.

2. Connect to the server launching Chrome from command line with -origin-to-force-quic-on option.
 - With this setting, server respond to the request.
 - However, the server keep close the connection with this msg "CryptoMessageParameterNotFound: SNI required". I found that in my case, SNI is not empty, it is !ok.

Could you give me any clue to solve this problem?

**Comment by ByungjinJun** [comment]
I found a solution for the problem from second approach. I sent request to the server pointing server's IP from client. As I change it as server's domain name, it works fine.
However, I am still not sure why the connection is completely refused from the first approach. I would really appreciate if you give me any simple clue or approach to try.

**Comment by marten-seemann** [comment]
Can you run the server with debug logging enabled (see wiki)? Maybe there's something on the path to your server that's blocking UDP packets.

**Comment by ByungjinJun** [comment]
Thank you for your swift response. There might a blocking port issue in my server. I don't exactly remember what I did, but now I can connect to my server throught Chrome browser.

But another issue showed up. Connecting from Chrome browser works fine, and connecting from command-line launching Chrome looks fine at browser. However, when I actually see the server log, server doesn't respond with any http response code to the request from command-line launching Chrome. Do you have any clue for this issue?

**Comment by marten-seemann** [comment]
I don't really understand. If the browser shows your site, clearly quic-go must have served the HTTP response, right?

**Comment by ByungjinJun** [comment]
Yes. I don't understand the result as well. At the first few times, my server responds with Http response code for the request from command-line launching Chrome, but after a few request, it stops showing log line "**responding with XXX**", but keep showing my site. At the moment, server doens't return any error msg, so I put a few logging lines in **h2quic/server.go** to track where it stuck.

I found that server.go stucks in "**stream, err := session.AcceptStream()**" in **handleHeaderStream** func before it goes to **handleRequest** func. After a while, it goes into if statement right after the line (meaning have **an error from AcceptStream**), and the server closes connection before "**qerr**" returns the error, "**InvalidHeadersStreamData**".

I did not touch much from original example server code, and now suspecting the line below in "example/main.go" shows my site, but it doesn't actually serve the HTTP response though not very sure about this.
"**http.Handle("/", http.FileServer(http.Dir(*www)))**"

**Comment by marten-seemann** [comment]
`AcceptStream` blocks until there's a stream to accept. If the connection is closed, it will error, and make that goroutine in h2quic return.

**Comment by marten-seemann** [comment]
Closing this issue. Feel free to open a new one if you encounter any more problems.
