### ISSUE TITLE
P2P usage

### ISSUE THREAD

**Issue by empirefox** [lucas-clemente/quic-go#1221]
How to run quic-go over p2p based net.PacketConn? Or how to hack to approach that, if both peers have curve25519 key pair and can signal public key to each other?

**Comment by marten-seemann** [comment]
[quic.Dial](https://godoc.org/github.com/lucas-clemente/quic-go#Dial) and [quic.Listen](https://godoc.org/github.com/lucas-clemente/quic-go#Listen) both take a `net.PacketConn`.

Google QUIC doesn't support client authentication, but this will change as soon as we'll move to TLS 1.3 (quic-go provides experimental support for that).

**Comment by empirefox** [comment]
Thanks @marten-seemann !
Yes, I've learnt quic.Dial and quic.Listen. But i did not find a way to set shared_key.

**Comment by marten-seemann** [comment]
I'm not sure what you mean by shared_key, but as I said, the current QUIC version doesn't allow client authentication. I'm working on deploying quic-go for libp2p using the IETF WG QUIC version (which uses TLS 1.3), but this is not yet accessible via the public API.

**Comment by empirefox** [comment]
I understand now. Thank you @marten-seemann !

**Comment by marten-seemann** [comment]
Feel free to open a new issue if you have any more questions!
