### ISSUE TITLE
concurrent map read and map wirte

### ISSUE THREAD

**Issue by pursueTAO** [lucas-clemente/quic-go#1224]
Use Go1.9.2 (>=1.6), concurrent map read and write must lock it.

**panic logger**
<img width="1457" alt="screen shot 2018-03-07 at 11 09 07 am" src="https://user-images.githubusercontent.com/15121388/37071564-05506a82-21f8-11e8-87e8-b5845b6f95f6.png">

**map read place in server.go**
<img width="689" alt="screen shot 2018-03-07 at 11 10 24 am" src="https://user-images.githubusercontent.com/15121388/37071620-51543f62-21f8-11e8-809c-7d646e208688.png">

**map write place in server.go**
<img width="513" alt="screen shot 2018-03-07 at 11 10 47 am" src="https://user-images.githubusercontent.com/15121388/37071622-536c3e9e-21f8-11e8-8188-6193e0370f85.png">

**Comment by marten-seemann** [comment]
Thanks for reporting! That's definitely a race condition there.
