### ISSUE TITLE
Improve HTTP API

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#124]
We should probably keep close to or directly embed [`http.Server`](https://golang.org/pkg/net/http/#Server). The problem there is [`net.Listener`](https://golang.org/pkg/net/#Listener), which only works for TCP.

**Comment by lucas-clemente** [comment]
Also see the discussion happening at https://github.com/mholt/caddy/issues/47.

**Comment by lucas-clemente** [comment]
We now have an API very similar to `http.Server`. We still need to think about graceful shutdowns though, as we cannot simply Close() the net.Listener, or wrap the TCP connections as some [libraries](https://github.com/tylerb/graceful/) do.

**Comment by mholt** [comment]
Does QUIC really *need* graceful shutdowns / restarts?

**Comment by lucas-clemente** [comment]
Well…

There's obviously state in a connection (crypto keys, streams, …), that cannot easily be migrated to e.g. a new process. So, if a server goes away, it cannot simply pass the connection to another server, but has to close it first. Now, QUIC has two ways of shutting down a connection. The first one is a `CONNECTION_CLOSE`, which immediately terminates the connection (~ TCP RST). The second, a `GOAWAY` frame is different, and basically allows current requests to finish, but does not allow new requests, similar to H2's GOAWAY frame. By graceful shutdown, I mean that we should have an API that sends GOAWAYs, possibly with some timeout, and makes the server stop responding to new connections. I will implement this behavior soon, see #153.

However, since the kernel doesn't do as much work for UDP, I'm not sure how a 0-downtime restart would be done. In particular, there's only one socket in total, not one per connection. That means there has to be some instant where *all* incoming packets are passed to the new server, and the old one doesn't receive any packets anymore. Right now, I don't see how a 0-downtime restart is possible in this setup.

**Comment by mholt** [comment]
You're probably right, but if it helps give clarity to the graceful restart process, let me share [how Caddy does it](https://github.com/mholt/caddy/blob/e340cf3b69e749ef51b81ec43ecca4059ab0a48b/caddy.go#L470-L478):

```go
file, err := old.listener.File()
if err != nil {
	return err
}
ln, err = net.FileListener(file)
if err != nil {
	return err
}
file.Close()
```

We then use `ln` and pass it into the call to `Serve()`. Good news, *UDPConn [has a File() method](https://golang.org/pkg/net/#UDPConn.File). Granted, we're using a `net.Listener` which is what Caddy uses, but if you scroll up in that file a bit, you'll see [a comment where I am considering a pattern for supporting UDP with net.Listener](https://github.com/mholt/caddy/blob/e340cf3b69e749ef51b81ec43ecca4059ab0a48b/caddy.go#L179-L199):

```go
type UDPListener struct {
	*net.UDPConn
}
func (u UDPListener) Accept() (net.Conn, error) {
	return u.UDPConn, nil
}
func (u UDPListener) Close() error {
	return u.UDPConn.Close()
}
func (u UDPListener) Addr() net.Addr {
	return u.UDPConn.LocalAddr()
}
var _ net.Listener = UDPListener{}
```

I haven't worked with UDP in ~10 years (!) so I am not fresh on the technicalities here, so you should tell me if this is ludicrous (if not a little unusual) or if maybe it's something that can work. :sweat_smile:

**Comment by lucas-clemente** [comment]
I have to admit, I haven't worked with 0-downtime restarts yet, but this is my understanding:

With TCP, you get a listener socket, and a new socket (with its own FD) for each connection. That way, you can pass the listener socket to a new server instance and have new connections served there, but continue to handle (and possibly shutdown) old connections in the old process. Only when they are all closed, the old process terminates.

With UDP, the situation is different. You only get a single socket (FD), where you handle the packets for both new and known connections. Therefore, as soon as you pass the socket to the new process, the old one stops being able to receive packets, and therefore practically stops working. Since the graceful shutdown possibly takes time to allow for large downloads to complete, there either is downtime when switching to the new process, or old connections are not gracefully terminated.

One thing to note, this is not a problem when using a load balancer that is aware of QUIC (which Google is probably doing). There, you can of course simply stop forwarding new connections to the stale server, and wait until it properly stops.

It is quite possible that I'm missing something; it might make sense to ask this on the QUIC mailing list.

**Comment by mholt** [comment]
Okay, that makes sense. Do you have a link to said mailing list?

FWIW, I'm not married to the idea of having Caddy support graceful restarts with QUIC, at least not right away. I'd be happy to ship Caddy 0.9 with optional, experimental QUIC support using this library!

**Comment by lucas-clemente** [comment]
I've asked the question on the mailing list: https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/w4tL3AuZkww

I also agree that 0-downtime restarts are not important for experimental QUIC support in 0.9, I was just curious ;)

**Comment by lucas-clemente** [comment]
I think that with the new [`CloseGracefully`](https://godoc.org/github.com/lucas-clemente/quic-go/h2quic#Server.CloseGracefully) function (which exists, but currently does nothing, see #153) we've got everything we need for now. Closing this issue.

**Comment by mholt** [comment]
Cool. It looks like, from the response on the mailing list, a graceful UDP restart will be a little tricky (connection IDs and all that) -- again, not something I as a user of the library would need right away, but I guess you can add it to the long-term list of things to consider. :+1: Nice work!
