### ISSUE TITLE
HTML5 videos getting stuck

### ISSUE THREAD

**Issue by midzer** [lucas-clemente/quic-go#1243]
Hi all,
I'm using latest Caddy 0.10.11 with `-quic` enabled and experience HTML5 `video` stream getting stuck after a while all of a sudden.

With regular Caddy instance without `-quic` everything is working fine.

I'm not familiar with the QUIC protocol at all, just a guess that it might have to be related with this library.

Cheers
midzer

**Comment by marten-seemann** [comment]
Could you capture a log, see https://github.com/lucas-clemente/quic-go/wiki/Logging?

**Comment by jared2501** [comment]
I saw a (perhaps?) similar thing where a connection would go dead after about an hour and a bit. Will try and get relevant logs next time this happens.

**Comment by marten-seemann** [comment]
Closing this issue for now. Feel free to open a new one once you captured a log.
