### ISSUE TITLE
recv error with big packet

### ISSUE THREAD

**Issue by bonly** [lucas-clemente/quic-go#1249]
when i send a big packet from the server (size: 10466)
the client get the wrong packet at the last part.

**Comment by marten-seemann** [comment]
Works as intended. The maximum packet size is defined in https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/protocol.go#L67-L71.

Google QUIC doesn't have any way to communicate this value, but any implementation that is intending to send packets larger than the ethernet MTU should probably do path MTU discovery anyway.
In IETF QUIC this value can be sent explicitly in the QUIC transport parameters (see https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.6.4), and should be used as an upper bound for a path MTU discovery algorithm.

**Comment by bonly** [comment]
it is MTU, large packets should be automatically split into little packets?!

**Comment by marten-seemann** [comment]
You usually don't want this. The fragments can get lost individually, so you're introducing additional head-of-line blocking by splitting them. That's why people do PMTUD in order to find the maximum packet size that doesn't get split.

**Comment by bonly** [comment]
so, 
quic.Stream.Write(buf)
len(buf) must be smaller then 1452 ?

**Comment by bonly** [comment]
thx
