### ISSUE TITLE
Figure out slow download speed

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#125]
Currently we download with ~20 MB/s and 200% CPU over loopback, compared to ~180MB/s and ~90% CPU using TCP (without TLS). We should at least move to the same order of magnitude.

**Comment by lucas-clemente** [comment]
Fixing #126 and #128 increased our speed to ~30MB/s.

**Comment by lucas-clemente** [comment]
Many different tools, many different results:

go tool pprof says:
```
      flat  flat%   sum%        cum   cum%
   19880ms 53.04% 53.04%    19880ms 53.04%  syscall.Syscall6
    7560ms 20.17% 73.21%     7560ms 20.17%  runtime.mach_semaphore_signal
    2270ms  6.06% 79.27%     2270ms  6.06%  runtime.mach_semaphore_timedwait
    1760ms  4.70% 83.96%     1890ms  5.04%  runtime.scanobject
    1420ms  3.79% 87.75%     1420ms  3.79%  runtime.kevent
     900ms  2.40% 90.15%     2870ms  7.66%  syscall.Recvfrom
     510ms  1.36% 91.52%      620ms  1.65%  runtime.gcFlushBgCredit
     510ms  1.36% 92.88%      510ms  1.36%  syscall.Syscall
     290ms  0.77% 93.65%      290ms  0.77%  runtime.memmove
     250ms  0.67% 94.32%      250ms  0.67%  nanotime
```

Instruments.app says:

<img width="745" alt="screenshot 2016-05-19 18 02 36" src="https://cloud.githubusercontent.com/assets/918034/15400458/e3017b04-1deb-11e6-8baf-c15ab09cee2a.png">

dtruss says: 5.2% send_to elapsed time

**Comment by lucas-clemente** [comment]
The last commit improves the speed to about 35 MB/s.

**Comment by lucas-clemente** [comment]
The following benchmark shows that a processing time of 20µs between sending packets is sufficient to break down to 35MB/s. Maybe we should move sending to a separate go-routine.

```go
package bench_test

import (
	"net"
	"testing"
	"time"
)

var conn *net.UDPConn

func init() {
	serverAddr, _ := net.ResolveUDPAddr("udp", "localhost:4000")
	conn, _ = net.ListenUDP("udp", serverAddr)
}

func BenchmarkUDP(b *testing.B) {
	destAddr, _ := net.ResolveUDPAddr("udp", "localhost:4001")
	for i := 0; i < b.N; i++ {
		data := make([]byte, 1400)
		time.Sleep(20 * time.Microsecond)
		conn.WriteToUDP(data, destAddr)
		b.SetBytes(int64(len(data)))
	}
}
```

**Comment by marten-seemann** [comment]
Good job.

**Comment by lucas-clemente** [comment]
2feb376 should improve this some more.

I tried an alternative with a dedicated go-routine for sending packets, but that introduces some complexity which I think is not really needed. In a realistic setup, we'll be serving more than a single connection anyway, and 40MB/s *per peer* is probably enough for now.

I think it makes sense to leave it at that. I don't see any easy gains left, and we'll be doing a number of performance optimizations throughout the code anyway. Let's have a look at the download rate from time to time, and get back to this in case it stays a problem in the future.
