### ISSUE TITLE
Can I use `Golang TLS` library? 

### ISSUE THREAD

**Issue by pursueTAO** [lucas-clemente/quic-go#1250]
Environment:
Golang 1.9
quic-go version(101)

I want use quic-go as a server replace tcp server. When I use quic-go mock client, 500 TLS request per second, many "Handshake timeout". 

Can I use Golang TLS library? not use the "mint" library.

**Comment by marten-seemann** [comment]
`VersionTLS` is still highly experimental and should not be used in production.
You can't use the Go TLS library, since it doesn't support TLS 1.3.
