### ISSUE TITLE
stream implementation of Read/Write should be thread safe

### ISSUE THREAD

**Issue by jared2501** [lucas-clemente/quic-go#1254]
I saw some weird read/write issues and had to synchronize calls to Stream.Read() and Stream.Write() to get rid of them. 

Reading documentation on `stream` I see:

```
Read() and Write() may be called concurrently, but multiple calls to Read() or Write() individually must be synchronized manually.
```

And reading documentation on `net.Conn` I see:

```
Multiple goroutines may invoke methods on a Conn simultaneously.
```

My understanding of net.Conn lead me to believe that a `Stream` should be thread-safe, but this appears to not be the case.

**Comment by jared2501** [comment]
Ahh I forgot that a Stream does not implement `net.Connet`, but implements `io.Reader` and `io.Writer`.

**Comment by marten-seemann** [comment]
Since `Read` doesn't give you an offset, and you don't provide an offset for `Write`, there's no point to call these functions concurrently.

**Comment by jared2501** [comment]
Makes sense. 

My application was using `Write()` to write application-level frames of data concurrently, and since `Write()` writes all the bytes (and net.Conn provides synchronization) my application would work with TCP but not quic. It's a pretty easy change (and probably the right one) to do synchronization in the application though!
