### ISSUE TITLE
Expose connection statistics 

### ISSUE THREAD

**Issue by jared2501** [lucas-clemente/quic-go#1258]
Things like congestion control parameters, packets lost, etc would be very useful for monitoring purposes.

**Comment by marten-seemann** [comment]
That's a difficult one. We already though about exposing of statistics, but there are so many different things that could be of interest. It seems hard to define something that fits all requirements, especially not knowing what requirements people have.
Can you tell us a bit about what you're planning to do, and what kind of stats would be useful for you?

**Comment by jared2501** [comment]
Yeah sure! I'm building a mesh network over LTE and 2.4Ghz wireless and need to be able to set quality of service policies between the different services that run on each node. I'm using a single quic connection between each connected node and have built a reverse proxy that maps the a service <-> service connection to a quic stream.

Since the connections are wireless, and therefore lossy, it's useful to see information such as:

- packet losses
- current congestion window / slow start threshold
- bytes sent / received for a connection

**Comment by marten-seemann** [comment]
I talked about this with @lucas-clemente today, and we agreed that the following interface is probably the best solution:
```go
type Metrics interface {
    IncrementCounter(label string)
    RecordMeasurement(label string, value float64)
}
```
The counter would be used when sending a packet, sending a retransmission, receiving a packet etc.
The measurements would be used to export values, e.g. the duration of the handshake, the current RTT estimate, and the slow start threshold.

We will need to agree on a naming convention for the labels, e.g. "handshake.total_time" and "sent.packet". Haven't really thought a lot about this, please feel free to suggest something better.

What do you think? Would that work for you? Are you interested in implementing this?

**Comment by jared2501** [comment]
Sorry, didn't see this response until now. This seems good to me! I can have a look at this some time this week.

Do you think that the user should be able to provide a `Metrics` implementation in the `quic.Config`? Or do you think a method should be provided on a `Session` to query the current values for all the metrics? Based on the interface you describe above, I believe you're leaning more towards the former.

**Comment by marten-seemann** [comment]
Yes, I think the best way would be a field in the `quic.Config`. That way, you'll get notified of new events immediately, and not just every time you poll the session for new values.
We should make it clear in the API docs, that the `Metrics` field is still experimental, and we might add / remove / rename values, so we can experiment with what works best.

**Comment by mkrawczuk** [comment]
Hello! What is the current status of this issue? I am very interested in having connection metrics and are eager to move this task further. I have plenty of time for that.

**Comment by jinleileiking** [comment]
What about using Prometheus？？

**Comment by marten-seemann** [comment]
We now support qlog, which should allow you to get a wide range of connection metrics.
