### ISSUE TITLE
Expose version information

### ISSUE THREAD

**Issue by fholzer** [lucas-clemente/quic-go#1271]
At the moment all the protocol version related structs are concealed in `internal/protocol` so applications using this library have no way of
1. detecting supported version (might be useful for printing a server's version information via e.g. ` caddy -version`)
2. specifying which versions the server should support via `h2quic.Server{ QuicConfig: &quic.Config{Versions: versions} }`

**Comment by marten-seemann** [comment]
We have aliases for the versions in the quic package, so this shouldn’t be a problem. M

**Comment by fholzer** [comment]
Sorry, I'm not familiar with you codebase. I only found how I can get version information on a running server... but not how I can get a list of supported versions without creating a server.

Could you point me to the file where this is aliased?

**Comment by marten-seemann** [comment]
The `VersionNumber` type is exposed here: https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L16-L17.

I just noticed that we don't export any specific versions currently. I shouldn't have closed this issue so early, sorry for that!
We probably should do that, although at the moment, the only supported version is gQUIC 39, so users could put that in their `quic.Config`.

We thought about exposing some version information on the `Session`, and we might need to do that once we support both gQUIC and IETF QUIC (because there are some version specific differences that a user of the library would care about, most importantly if unidirectional streams are available).

**Comment by jared2501** [comment]
Hey @marten-seemann - was wondering what the timeline on exposing VersionTLS is? We require it for it's support for client auth.

**Comment by fholzer** [comment]
It would be great if there was an array/slice containing all the currently supported versions.

**Comment by marten-seemann** [comment]
What would be the use case for that (other than printing it on caddy -v, which I don’t consider useful)?

**Comment by fholzer** [comment]
It would reduce the effort in projects using this library, as one wouldn't need to check whether there's a version change in the library. Especially until Google QUIC is replaced by IETF QUIC - if that's even planned...
Applications could just use this array to iterate over the supported versions, and, using the methods provided by the version interface, e.g. convert it to string to find a match for what is specified in a config file. Or in the future, match versions that implement the IETF spec to ensure that TLS client authentication is supported if specified by the application's config.

**Comment by marten-seemann** [comment]
The functions on the version number are not part of the public API and should not be used by applications.
IETF QUIC support is still highly experimental and is not exposed so far for good reason, although I’ll expose some milestone versions (which are still experimental) later on.

**Comment by lucas-clemente** [comment]
I think the main argument here is that new QUIC versions will be rare once things have converged. E.g., once QUIC is standardized and Google implements it, there will only be a single QUIC version supported. BTW, Go's stdlib doesn't expose a slice of supported TLS or HTTP versions.

I'm not totally opposed to exposing the supported versions slice while there's still a lot of active development going on. The example you mention (config files that specify QUIC versions) sounds dangerous though: How would that then work once QUIC has converged and we could remove the slice again?

That being said, easier experimentation is one of the selling points of QUIC, so we should probably think about a mechanism for "experimental" versions, even when we only support a single stable version.

**Comment by marten-seemann** [comment]
That’s exactly why we are exposing the version numbers, so that you can choose which versions you want to support via the quic.Config.

**Comment by fholzer** [comment]
When I write "config", I mean an application's config file.

I think of this like the the ssl cipher config option in most web servers. Should servers provide a sane default: yes. Should users have the option to override it via config: yes. Will this be needed rarely: hopefully. Should they know what they're doing: absolutely.

**Comment by marten-seemann** [comment]
Please have another look at the quic.Config. This is already possible.
