### ISSUE TITLE
Error golang (import path does not begin with hostname)

### ISSUE THREAD

**Issue by tiagoliveira9** [lucas-clemente/quic-go#1284]
I'm trying to start this project but all I get is this golang error, "import path does not begin with hostname". I'm using docker with ubuntu 16.04 and golang 1.6 (installed with software package manager). I've already tried with Fedora as well and I got the same error. And because there is no more documentation besides the README, can someone point me in the right direction?

**Comment by marten-seemann** [comment]
You’ll need at least Go 1.9. I believe we have that somewhere in the README.

**Comment by ocastx** [comment]
This issue can occur if you didn't download the project folder inside your GOPATH. So, for example if your GOPATH is set to `$HOME/go` (default) then you should download/unzip the project to 
`$HOME/go/src/github.com/lucas-clement/quic-go` and try then to install the dependencies.

**Comment by RAAVK** [comment]
For Mac OS you need to set GOROOT to "/usr/local/Cellar/go/1.5.1/libexec". Change the Go version with your local version. I have used brew to install Go FYI

**Comment by marten-seemann** [comment]
> For Mac OS you need to set GOROOT to "/usr/local/Cellar/go/1.5.1/libexec". Change the Go version with your local version. I have used brew to install Go FYI

Most certainly, you don't want to do that. Furthermore, you also don't want to use Go 1.5.1.

**Comment by lty5240** [comment]
> For Mac OS you need to set GOROOT to "/usr/local/Cellar/go/1.5.1/libexec". Change the Go version with your local version. I have used brew to install Go FYI

emmm，thanks , you're right , fxxk libexec

**Comment by kiennd-teko** [comment]
right

> > For Mac OS you need to set GOROOT to "/usr/local/Cellar/go/1.5.1/libexec". Change the Go version with your local version. I have used brew to install Go FYI
> 
> Most certainly, you don't want to do that. Furthermore, you also don't want to use Go 1.5.1.

right
