### ISSUE TITLE
Parameters of quic-go

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1288]
Hi all,

I am studying QUIC. As I find in server_parameters.go, DefaultMaxCongestionWindow  is [1000](https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/server_parameters.go), but this value is [2000 ](https://cs.chromium.org/chromium/src/net/quic/core/congestion_control/send_algorithm_interface.h?l=26)in chromium.

I want to know that whether this influence on the experiments or not? 

Thank you in advance.

**Comment by marten-seemann** [comment]
Depends on the experiment. Feel free to play around with this value, and see if it makes any difference. I'd be happy to change this value to 2000, if this can be shown to improve performance.

**Comment by shinichikudo987** [comment]
Why do you choose that value? I mean this value is suitable for quic-go or it is default value?

**Comment by marten-seemann** [comment]
Copied from Chromium at some point. As I said, feel free to experiment with it, report back the results, then we're happy to change this constant.
