### ISSUE TITLE
Curve25519 private key generation can be improved

### ISSUE THREAD

**Issue by ashi009** [lucas-clemente/quic-go#1292]
https://github.com/lucas-clemente/quic-go/blob/297a862753181428bcfd6140e0cbafc017ea87c1/internal/crypto/curve_25519.go#L24-L27

There is no need to clamp the generated private key, as it's handled in curve25519 package:

https://github.com/golang/crypto/blob/d6449816ce06963d9d136eee5a56fca5b0616e7e/curve25519/mont25519_amd64.go#L65-L67

**Comment by marten-seemann** [comment]
Thanks for reporting, @ashi009! This looks correct, and I prepared a PR (#1296) to remove these lines.
