### ISSUE TITLE
deadlock when receiving multiple diversification nonces

### ISSUE THREAD

**Issue by raulftang** [lucas-clemente/quic-go#1308]
I use gomobile to convert quic-go into a lib and running on android. Occasionally it will hang on the follwing DialAddr method.

config := &quic.Config{KeepAlive: true}
session, err := quic.DialAddr(ipAddressUrl, &tls.Config{InsecureSkipVerify: true}, config)
stream, err := session.OpenStreamSync()

After further investigation， it seems session.SetDiversificationNonce and cryptoSetupClient.HandleCryptoStream called from seesion.run() has a deadlock on channel divNonceChan and paramsChan. 

func (h *cryptoSetupClient) SetDiversificationNonce(data []byte) {
	h.divNonceChan <- data
}

func (h *cryptoSetupClient) HandleCryptoStream() error {
     ......
      case TagSHLO:
			params, err := h.handleSHLOMessage(message.Data)
			if err != nil {
				return err
			}
			// blocks until the session has received the parameters
			h.paramsChan <- *params
			h.handshakeEvent <- struct{}{}
			close(h.handshakeEvent)
   ......
}

Please suggest, thanks

**Comment by marten-seemann** [comment]
Does #1299 solve the problem?

**Comment by raulftang** [comment]
The issue still exists.

When it happens, the execution will block on 
"h.divNonceChan <- data" and "h.paramsChan <- *params". I added log info as following:

func (h *cryptoSetupClient) SetDiversificationNonce(data []byte) {
  log.Printf("SetDiversificationNonce before.")
  h.divNonceChan <- data
  log.Printf("SetDiversificationNonce end.")
}

func (h *cryptoSetupClient) HandleCryptoStream() error {
....
  log.Printf("HandleCryptoStream paramsChannel before.")
  h.paramsChan <- *params
  log.Printf("HandleCryptoStream paramsChannel end.")
....
}

Will output "SetDiversificationNonce before." and "HandleCryptoStream paramsChannel before.", but "SetDiversificationNonce end." and "HandleCryptoStream paramsChannel end." won't.

#1299 is related to handshakeEvent channel, this issue should relate divNonceChan and paramsChan.

Thanks.

**Comment by marten-seemann** [comment]
When reporting issues, please make sure you're running the current version of the code. `SetDiversificationNonce` was removed 3 weeks ago in #1264.

When I ask you if a certain PR resolves the issue, please rerun your test before confirming that it does.

**Comment by marten-seemann** [comment]
Looks like the issue still exists, even in the current code.

**Comment by raulftang** [comment]
Got it.
Thanks
