### ISSUE TITLE
How can i release stream when i make the stream with session.OpenStreamSync() ?

### ISSUE THREAD

**Issue by free1139** [lucas-clemente/quic-go#1326]
How can i release stream when i make the stream with session.OpenStreamSync() ?
I have tried to call s.streamMap.DeleteStream(id), but it's not work.

**Comment by free1139** [comment]
// Start a server that echos all data on the first stream opened by the client
func echoServer() error {
    listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
    if err != nil {
        return err 
    }   
    sess, err := listener.Accept()
    if err != nil {
        return err 
    }   
    for {
        stream, err := sess.AcceptStream()
        if err != nil {
            panic(err)
        }   
        // Echo through the loggingWriter
        _, err = io.Copy(loggingWriter{stream}, stream)
        if err != nil {
            stream.Close()
            return err 
        }   
        stream.Close()
    }   
}

func clientMain() error {
    session, err := quic.DialAddr(addr, &tls.Config{InsecureSkipVerify: true}, nil)
    if err != nil {
        return err 
    }   

    for i := 1000; i > 0; i-- {
        fmt.Printf("%d\n", i)
        stream, err := session.OpenStreamSync()
        if err != nil {
            return err 
        }   

        fmt.Printf("Client: Sending '%s'\n", message)
        _, err = stream.Write([]byte(message))
        if err != nil {
            stream.Close()
            return err 
        }   

        buf := make([]byte, len(message))
        _, err = io.ReadFull(stream, buf)
        if err != nil {
            stream.Close()
            return err 
        }   
        fmt.Printf("Client: Got '%s'\n", buf)
        stream.Close()
    }   

    return nil 
}

**Comment by marten-seemann** [comment]
Works as intended. If you have too many streams open, OpenStream() will error. Use OpenStreamSync() if you want the call to block until more streams are available.

**Comment by marten-seemann** [comment]
The streams need a to be closed from both sides.

**Comment by free1139** [comment]
When I saw that the previous test was ok in the new version, I tried to set up an HTTPS to quic distribution agent in the Intranet, but failed in the test of HTTP client. When a client instance makes its 99th request, it gets stuck. The place I see stuck debugging is still in the OpenStreamSync() method, since I'm not familiar with quic yet, please help @marten-seemann .


Here is an example that can be reproduced. The version of quic-go is:

pkg/mod/github.com/lucas-clemente/quic-go@v0.7.1-0.20190301012327-c00eb1f5b55d/h2quic/server.go


Golang version go1.12rc


The main.go
---------------------------------
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"math/big"
	"net/http"
	"net/http/httputil"
	"os"
	"os/signal"

	"github.com/lucas-clemente/quic-go/h2quic"
)

func main() {
	go runServer()

	go runClient()

	// exit event
	fmt.Println("[ctrl+c to exit]")
	end := make(chan os.Signal, 2)
	signal.Notify(end, os.Interrupt, os.Kill)
	<-end

}

// Setup a bare-bones TLS config for the server
func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{Certificates: []tls.Certificate{tlsCert}}
}

var tlsCfg = generateTLSConfig()

func runServer() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// todo
		reqData, err := httputil.DumpRequest(r, true)
		if err != nil {
			println(err.Error())
			return
		}
		fmt.Printf("req:\n%s\n", string(reqData))
	})
	addr := "localhost:4242"

	server := &h2quic.Server{
		Server: &http.Server{
			Addr:      addr,
			TLSConfig: tlsCfg,
		},
	}
	server.Serve(nil)
}

func runClient() {
	client := http.Client{
		Transport: &h2quic.RoundTripper{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}
	for i := 0; i < 1000; i++ {
		println(i)
		resp, err := client.Get(fmt.Sprintf("https://localhost:4242/test?data=%d", i))
		if err != nil {
			panic(err)
		}
		defer resp.Body.Close()
		respData, err := httputil.DumpResponse(resp, true)
		if err != nil {
			panic(err)
		}
		fmt.Printf("resp:\n%s\n", string(respData))
	}
}

**Comment by marten-seemann** [comment]
Duplicate of #1756. This issue won't be fixed in h2quic.

**Comment by free1139** [comment]
Ok, thanks for your reply.
