### ISSUE TITLE
panic problem

### ISSUE THREAD

**Issue by jackerlu** [lucas-clemente/quic-go#1359]
Hi,Lucas
I have download the latest quic-go,when i execute "go run example/client/main.go https://clemente.io",The following problem occurs,Can you help me?
[root@cirrus quic-go]# go run example/client/main.go https://clemente.io
GET https://clemente.io
Starting new connection to clemente.io ([::]:48012 -> 188.68.52.107:443), source connection ID 0x8caa34a48ba49a55, destination connection ID 0x8caa34a48ba49a55, version gQUIC 39
Received a Version Negotiation Packet. Supported Versions: [gQUIC 37 gQUIC 36 gQUIC 35]
Closing session with error: InvalidVersion
Connection 0x8caa34a48ba49a55 closed.
panic: Get https://clemente.io: InvalidVersion

goroutine 5 [running]:
main.main.func1(0xc420083290, 0x924c40, 0xc4200e4300, 0xc420016660, 0x7ffd32ef84f0, 0x13)
        /home/luta/golang/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:51 +0x3ab
created by main.main
        /home/luta/golang/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:48 +0x339
exit status 2

**Comment by marten-seemann** [comment]
`client.Get` returns an error because no matching QUIC version can be found in
https://github.com/lucas-clemente/quic-go/blob/407a563c73ad24115f0ac1e7df5f6097353642db/example/client/main.go#L49-L52

**Comment by jackerlu** [comment]
Thanks for the quick reply! By the way,Do you guys have any plan to implement BBR congestion control algorithm this year?

**Comment by marten-seemann** [comment]
Maybe. It's on the todo-list, but doesn't have very high priority.

**Comment by jackerlu** [comment]
I wrote a test program to test the transmission speed In the LAN,The transmission speed is approximately 13850 kbytes/s through TCP,The transmission speed is approximately 4616kbytes/s through quic-go,Why are the speeds so different?

**Comment by jackerlu** [comment]
client.go
package main

import (
	"crypto/tls"
	"fmt"
	"io"

	quic "github.com/lucas-clemente/quic-go"
	"flag"

	"log"
	"os"
	"crypto/md5"
	"bytes"
	"time"
)


const message = "foobar"

var(
	serveraddr     = flag.String("serveraddr", "localhost:4242", "")
)

// We start a server echoing data on the first stream the client opens,
// then connect with a client, send the message, and wait for its receipt.
func main() {
	flag.Parse()
	err := clientMain()
	if err != nil {
		panic(err)
	}
}

func BytesToHexString(b []byte) string {
	buf := new(bytes.Buffer)
	for _, v := range b {
		//buf.WriteString(strconv.FormatInt(int64(v&0xff), 16))
		buf.WriteString(fmt.Sprintf("%02x", v))
	}
	return buf.String()
}

func writeData(stream quic.Stream) error{
	filefd, err := os.Open("test.txt")
	if err != nil {
		fmt.Printf("opening file fail:%v\n",err.Error())
		return err
	}
	if(err != nil){
		log.Printf("ReadFile failed:%s\n",err.Error())
	}
	buf := make([]byte, 40*1024)
	hash := md5.New()
	_start := time.Now()
	var totalReadLen = 0
	for{
		readlen, err := filefd.Read(buf)
		if(err != nil){
			if err == io.EOF {
				usedTime := int(time.Since(_start) / time.Second)
				var speed float64
				if usedTime > 0 {
					speed = float64(totalReadLen * 1.0 / usedTime / 1024)
				}
				log.Printf("read file end,totalReadLen:%d usedTime:%d speed:%f kbytes/s,filehash:%s\n",totalReadLen,usedTime,speed,BytesToHexString(hash.Sum(nil)))
				return nil
			}else{
				log.Printf("ReadFile failed:%s\n",err.Error())
				return err
			}
		}else{
			totalReadLen += readlen
			_, err = stream.Write([]byte(buf[:readlen]))
			if err != nil {
				return err
			}
			_, err = hash.Write(buf[:readlen])
			if err != nil {
				log.Printf("hash.Write failed:%s\n",err.Error())
				return err
			}
		}
	}
	return nil
}

func clientMain() error {
	fmt.Printf("serveraddr:%s\n",*serveraddr)
	session, err := quic.DialAddr(*serveraddr, &tls.Config{InsecureSkipVerify: true}, nil)
	if err != nil {
		fmt.Printf("DialAddr failed\n")
		return err
	}

	stream, err := session.OpenStreamSync()
	if err != nil {
		fmt.Printf("OpenStreamSync failed\n")
		return err
	}

	writeData(stream)
	session.Close(nil)
	
	return nil
}

**Comment by jackerlu** [comment]
This is client.go

**Comment by jackerlu** [comment]
This is server.go

**Comment by jackerlu** [comment]
client

**Comment by marten-seemann** [comment]
This is expected. QUIC's advantages don't come into play for bulk data transfer on a local connection.

This is not a general Q&A issue though. If you found an actual bug, please feel free to open a new issue.
