### ISSUE TITLE
Support loading a server config from file

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#137]
## Problem

During the QUIC handshake, a QUIC server sends a "server config" (basically a public key + some crypto parameters) to the client. The client may store the config for re-use in later connections, thus achieving 0-RTT handshakes (since it already knows the server's pubkey).

To allow load-balancing, many QUIC server processes have to share a single (or a set of) server configs plus their private keys. Note that this privkey is temporary and different from the one associated to the SSL certificate.

We should support saving and loading these server configs.
## Ideas

By default, I would propose to re-generate a new config for each server, thus allowing 0-RTT as long as the server doesn't reboot.

While it would be possible to supply all server configs from the outside (and I suspect that's how Google solves this problem), I don't think it's very ergonomic to require that of smaller users. I'd like to think about having servers auto-generate configs also in a multiple-server setup.

For servers to share configs, we need some kind of communication between servers. A simple solution would be a directory of server configs that is shared across nodes.

With multiple servers, having each server generate its own server config would lead to a race condition, where we end up with a large number of active server configs. This could be mitigated by generating a new config some random time before the old one expires, so that races become unlikely.
## Implementation

The following is a proposal how to implement this:
- Add an API for generating a new server config.
- Add an interface (e.g. `ServerConfigPool`), which supports loading and storing server configs.
- Add an implementation of `ServerConfigPool` which uses a local directory to store and load server configs.
- When a server is created without a config pool, have it fallback to an in-memory pool.
- When a server is using a "real" config pool, generate new server configs some random time before the old ones expire (a few minutes e.g.), so that we don't race there.
- When a server is created with a "real" config pool and the pool doesn't have a valid config, generate a new one on the spot. Unfortunately, this would race when staring many servers at once, and we'd end up with a lot of configs :/

Comments / ideas?

**Comment by marten-seemann** [comment]
This issue is now obsolete, since we don't support gQUIC any more.
