### ISSUE TITLE
Random writing fail with high packet loss

### ISSUE THREAD

**Issue by raulftang** [lucas-clemente/quic-go#1374]
Use iPhone network conditioner to set 30% packet loss. Connection setup always success, but after running for several minutes, it will sometimes fail to write and can't restore randomly. Following are logs, I just set up a connection and send a custom keep-live message every 10 seconds.

```
2018/05/23 02:06:00 Start sending
2018/05/23 02:06:00 Quic has sent data from L/[::]:50984-R/115.28.78.200:8080.
2018/05/23 02:06:01 Quic has received data from L/[::]:50984-R/115.28.78.200:8080.

2018/05/23 02:06:10 Start sending
2018/05/23 02:06:10 Quic has sent data from L/[::]:50984-R/115.28.78.200:8080.
2018/05/23 02:06:13 Quic has received data from L/[::]:50984-R/115.28.78.200:8080.

2018/05/23 02:06:20 Start sending

2018/05/23 02:06:30 Start sending

2018/05/23 02:06:40 Start sending

2018/05/23 02:06:43 Quic Sent got an error.
NetworkIdleTimeout: No recent network activity.

2018/05/23 02:06:43 Quic Sent got an error.
NetworkIdleTimeout: No recent network activity.

2018/05/23 02:06:43 Quic Sent got an error.
NetworkIdleTimeout: No recent network activity.
```

**Comment by raulftang** [comment]
Code to connect and send/receive data:
'
func (q *QuicConn) Connect(add string) (err error) {
    q.sync.Lock()
    defer q.sync.Unlock()
    log.Printf("Quic is trying to connect " + add + " ...")
    config := &quic.Config{KeepAlive: true}
    session, err := quic.DialAddr(add, &tls.Config{InsecureSkipVerify: true}, config)
    if err != nil {
        return err
    }

    stream, err := session.OpenStreamSync()
    if err != nil {
        return err
    }
    q.session = session
    q.stream = stream
    q.ladd = session.LocalAddr().String()
    q.radd = session.RemoteAddr().String()
    q.callback.OnConnected(q)
    go q.onQuicDataReceived()
    return nil
}

func (q *QuicConn) Write(b []byte) (n int, err error) {
    log.Printf("Start sending")
    q.sync.Lock()
    defer q.sync.Unlock()
    n, err = q.stream.Write(b)
    if err != nil {
        log.Printf("Quic Sent got an error.\n" + err.Error())
        return 0, err
    }
    log.Printf("Quic has sent data from %s.\n%s", q.String(), hex.EncodeToString(b))
    return n, err
}

func (q *QuicConn) onQuicDataReceived() {
    for {
        b := make([]byte, 1500)
        i, err := q.stream.Read(b)
        if err != nil {
            quicErr, ok := err.(*qerr.QuicError)
            if ok {
                if quicErr.ErrorCode == 16 {
                    log.Printf("Quic has been disconnected. " + q.String())
                    q.callback.OnDisconnected(q)
                }
                break
            }

            log.Printf("Quic got an error. " + q.String() + "\n" + err.Error())
            q.Disconnect()
            break
        }
        if i == 0 {
            continue
        }
        data := make([]byte, i)
        copy(data, b)
        log.Printf("Quic has received data from %s.\n%s", q.String(), hex.EncodeToString(data))
        q.callback.OnDataReceived(q, data)
    }
    log.Printf("Stop receiving\n")
}
'

**Comment by marten-seemann** [comment]
You can enable debug logging as described in the wiki. Then you can see what the loss recovery algorithm is doing.
I wouldn’t be surprised if you’re running in consecutive RTOs, which will eventually time out the connection. 30% is a super high loss rate.

Please let me know what you find out.

**Comment by raulftang** [comment]
Complete log attached.
[quic_packet_loss.txt](https://github.com/lucas-clemente/quic-go/files/2029808/quic_packet_loss.txt)

**Comment by marten-seemann** [comment]
Please **always** use the latest master when reporting issues. This log doesn’t contain loss recovery information.

**Comment by raulftang** [comment]
Thanks, please check new log with the latest master update
[quic_packet_loss.txt](https://github.com/lucas-clemente/quic-go/files/2029909/quic_packet_loss.txt)

**Comment by raulftang** [comment]
Any update on this?

Thanks

**Comment by marten-seemann** [comment]
Closing due to age. There have been a lot of changes to the loss recovery recently, so it's not clear if this still applies. Feel free to open a new issue if that's the case.
