### ISSUE TITLE
Change source address tokens to use Google's format

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#138]
This would allow parallel operation of Google's and our QUIC implementation.

**Comment by lucas-clemente** [comment]
This depends on #137, so I'm dropping it from 0.4 as well.

**Comment by marten-seemann** [comment]
We decided to implement our own encoding for STKs in #627 (mainly to be able to run on top of a `net.PacketConn`, where peers don't necessarily have an IP address). Closing this issue.
