### ISSUE TITLE
No io.EOF on reading from Stream

### ISSUE THREAD

**Issue by richp10** [lucas-clemente/quic-go#1381]
I am writing using a 'raw' (not http) client / server based roughly on the echo example. 

Am having a problem reading the incoming stream for large messages.  On the server end, I just Marshal the bytes and .Write them to the stream.  So on the client, I am trying to read the stream like this: 

```
nBytes, nChunks := int64(0), int64(0)
	r := bufio.NewReader(q.stream)
	buf := make([]byte, 0, 500)
	for {
		n, err := r.Read(buf[:cap(buf)])
		buf = buf[:n]
		if n == 0 {
			if err == nil {
				continue
			}
			if err == io.EOF {
				break
			}
			fmt.Println(err)
			return
		}
		log.Println(n)
		nChunks++
		nBytes += int64(len(buf))
	}

	log.Println("Bytes:", nBytes, "Chunks:", nChunks)
```

I then Unmarshal the data into a protobuf.  For small messages this is working perfectly, but I have added a 500k payload and it no longer works. 

Most of the data comes in, but then it 'freezes' on the .Read - waiting for more data.  As far as I can see the reason is that no io.EOF is received and .Read just sits their waiting.. 

This might be an elementary coding (I an fairly new to golang) - I am not sure - but cannot see a way around not getting an EOF.

**Comment by marten-seemann** [comment]
Are you closing the stream on the server side?

**Comment by richp10** [comment]
Thanks - I think that gets me closer.  I was trying to use bidirectional streams so I can pass a series of messages back and forth between client and server - so if I close a stream I cannot then use it for the next message.  Do I really need to open a new stream for each message - and close it to make sure EOF is sent? I feel like I am missing something at a conceptual level!

**Comment by marten-seemann** [comment]
If you want an EOF, you need to close the stream. There’s no such thing as closing the stream quickly. You can do that as soon as the Write() call returned. 

Are the messages you’re sending independent of each other? If so, you should use separate streams, because you’re avoiding head of line blocking.
If you need the messages to be delivered in order, a single stream is probably the best solution.

**Comment by richp10** [comment]
Sorry - I deleted my last comment to go away and think harder!

I am trying to use a single bi-directional stream - but if I send a 'request' to the server, how do I safely read that (ie. read until EOF) unless the client closes the stream.  And if I can, how can I send the 'response' to the client without closing the stream?  If stream.Write() does not ensure an EOF at the other end I don't see how I can use a bi-directional stream..

I have managed to get it working bi-direction with very small messages - but as soon as it is larger then the lack of EOF means I don't know when to stop waiting for more data. 

I guess I could use two streams but I would have thought there would be a way to do what I am trying to do using a bi-directional stream: send a message, get a reply is the basic use case!

**Comment by richp10** [comment]
(actually - I have just found an un-handled error that might have affected quic sending the EOF - I will try and get to the bottom of this before I bother anyone further..)

**Comment by richp10** [comment]
For my use case it is sufficient for now for the server to close the connection after sending the response - so with a bit of debugging I now have this working.  Thanks for your help @marten-seemann  .. if the mods want to remove the thread as relevant to quic I won't be offended!

**Comment by marten-seemann** [comment]
No problem. Feel free to open a new issue if you have any more questions!
