### ISSUE TITLE
TCP packets in QUIC server

### ISSUE THREAD

**Issue by purplehorse** [lucas-clemente/quic-go#1390]
I'm running the example server (example/main.go) with a subtle modification:

![screenshot 836](https://user-images.githubusercontent.com/39902415/40906748-0516f3ee-67e2-11e8-9954-663d65c3fc0f.jpg)
![screenshot 837](https://user-images.githubusercontent.com/39902415/40906749-05378712-67e2-11e8-88c4-5f34a5311e58.jpg)

To access it from outside.

When I access to it and sniff the packets, all I see is TCP packets:

![screenshot 838](https://user-images.githubusercontent.com/39902415/40906769-1ab357c4-67e2-11e8-8b73-ff38fae9a96c.jpg)

I'm using Chrome with quic-enabled flag, so I should see QUIC packets. why I am not seeing quic packets?

**Comment by marten-seemann** [comment]
You're connecting to the HTTP/TCP server (used for profiling data).
Please refer to the README how to connect to the QUIC server.
