### ISSUE TITLE
server error handling packet: Recieved an IETF QUIC Long Header

### ISSUE THREAD

**Issue by purplehorse** [lucas-clemente/quic-go#1391]
I have followed README and when I set up the server and the client:

![screenshot 846](https://user-images.githubusercontent.com/39902415/40966807-c8f4e292-68b1-11e8-9f75-f1a992e28cad.jpg)

I get an error:

![screenshot 847](https://user-images.githubusercontent.com/39902415/40966851-e7bcae3a-68b1-11e8-9bab-cb22deeea5e4.jpg)

(I have set up quic_client following /lucas-clemente/quic-clients)

Client as followed in readme doesn't work either:

![screenshot 848](https://user-images.githubusercontent.com/39902415/40967150-a4345c52-68b2-11e8-8181-b194cb1f3f14.jpg)

**Comment by marten-seemann** [comment]
Works as intended:
1st case: A server that only speaks gQUIC doesn't accept IETF QUIC packets.
2nd case: Version negotiation fails if no matching version is found.

**Comment by purplehorse** [comment]
How could I then make a proper communication with a server in a remote host and a client in QUIC? Because I have modified main.go to be accesible from outside but I only can access to TCP server (using Google Chrome) and if I use quic_client it is IETF QUIC and apparently I can't access it either.

**Comment by marten-seemann** [comment]
Please just follow the wiki: https://github.com/lucas-clemente/quic-go/wiki

**Comment by purplehorse** [comment]
I run exactly <<go run example/main.go -bind "0.0.0.0:6121">> but I can't access it from outside... Only in the same host...
