### ISSUE TITLE
Disable encryption

### ISSUE THREAD

**Issue by k3x** [lucas-clemente/quic-go#1402]
Hi,
i know the quic standard allows only encrypted traffic and this has many advantages. But i want to do bandwidth tests with random data not passing the internet. On these tests the bottleneck seems to be my cpu while encrypting and decrypting data.

is there an option or a flag to disable encryption?

If not: What would be the easiest way to remove the encryption in the sourcecode an which files have to be adjusted? 

Thanks in advance
K3X

**Comment by marten-seemann** [comment]
Closing this issue for now. Feel free to open a new one if you have any more questions.

**Comment by Sakuralala** [comment]
> 

> Hello k3x,
> 
> There’s no way to disable encryption, since QUIC is a secure-only transport.
> I’m surprised this is performance critical, since most modern processor should offload AES anyway.
> If you want to disable encryption for your benchmarking, have a look at the crypto package. The implementations of the AEAD Interface there is where the crypto happens.

Excuse me, I have similar idea about disable encryption, can you explain more in detail (which source files should be adjusted)? Thank you!

**Comment by marten-seemann** [comment]
Turning off encryption is a **very bad** idea, and QUIC is specifically designed as an always-secure protocol. If you’re looking for an unencrypted protocol, QUIC is not the right choice for you.

**Comment by Sakuralala** [comment]
Sorry, I just want to do some experiments for testing purposes, I know quic is designed as an secure protocol. And I just want to know how to modify from the source files since the source code looks a bit complicated, can you give me some advice?

**Comment by iriszero** [comment]
Here, I'd love to see an option to disable encryption, for the same reason. Any updates so far?

**Comment by marten-seemann** [comment]
No, we will not implement any way of disabling encryption in QUIC.

**Comment by saleyn** [comment]
When using in a private network without a concern about securing data in a performance sensitive application, the option with having no encryption would be highly beneficial.

**Comment by jellyterra** [comment]
There may is a cipher suite called TLS_NULL_WITH_NULL_NULL in TLS 1.3 which does not do encrpytion at all.
Has anybody tried this with `quic-go`?

**Comment by EndPositive** [comment]
I'm interested in this as well. @jellyterra did you get anything working?

**Comment by zhuqinghe** [comment]
Same interested in this question. Is there any progress?

**Comment by oddmario** [comment]
quic-go is just an implementation of the QUIC protocol. The QUIC protocol standards strictly mention that it's an encrypted-only protocol 

To make it simpler, If you disable encryption, the protocol is no longer QUIC since you're not meeting the standards of the protocol.

If you want to disable encryption it shall be better to look for alternative protocols
