### ISSUE TITLE
Unable to connect Quic from outside

### ISSUE THREAD

**Issue by purplehorse** [lucas-clemente/quic-go#1419]
I follow the wiki and I run:
`go run example/main.go -bind "0.0.0.0:6121"`

I'm running the server in a Ubuntu 16.04 virtual machine and I use port redirection of 11220 (my open port on the host) to 6121 (the port of the server in the virtual machine).

Then, I use another computer and I run

`chrome.exe --user-data-dir=C:\tnp --no-proxy-server --enable-quic --origin-to-force-quic-on=quic.clemente.io:443 --host-resolver-rules='MAP quic.clemente.io:443 X.X.X.X:11220' https://quic.clemente.io`

where X.X.X.X is my public IP. An I get a chrome error:
"Unable to access this web site: ERR_QUIC_PROTOCOL_ERROR"

PS:
I used to be able to perform the same steps in the VM and connect to the server, but when I do 
`Chrome --user-data-dir=/tmp/chrome --no-proxy-server --enable-quic --origin-to-force-quic-on=quic.clemente.io:443 --host-resolver-rules='MAP quic.clemente.io:443 127.0.0.1:6121' https://quic.clemente.io` 
now I get "ERR_CERT_DATE_INVALID"

**Comment by marten-seemann** [comment]
As the error message says, you need to provide a valid certificate.
