### ISSUE TITLE
Quic client support of different versions

### ISSUE THREAD

**Issue by delinage** [lucas-clemente/quic-go#1420]
Using:

`go run example/client/main.go https://quic.clemente.io
`

I get the output

```
go run example/client/main.go https://quic.clemente.io
GET https://quic.clemente.io
client Starting new connection to quic.clemente.io ([::]:42703 -> 188.68.52.107:443), source connection ID 0x32cfd41e0c1e1f43, destination connection ID 0x32cfd41e0c1e1f43, version gQUIC 42
client Received a Version Negotiation Packet. Supported Versions: [gQUIC 37 gQUIC 36 gQUIC 35]
client Closing session with error: InvalidVersion
client Connection 0x32cfd41e0c1e1f43 closed.
```

Because the client works with gQUIC 42 and the server supports gQUIC 37 gQUIC 36 gQUIC 35 as far as I understand. Is there a way to use a client that supports older versions to connect this server?

If not so, how could I connect to a public server like https://quic.clemente.io using quic?

**Comment by marten-seemann** [comment]
There's not really a point to use old QUIC versions, since basically no servers will support it.
If you still think this is a good idea, you can check out an old version of the code that supports older versions.

**Comment by delinage** [comment]
But how can I connect to your server https://quic.clemente.io using QUIC if your client is using a newer version than your server?

**Comment by marten-seemann** [comment]
Why do you care about quic.clemente.io? It runs a super old QUIC version, so why bother?

**Comment by purplehorse** [comment]
My only goal is to connect to a server to perform some testing of QUIC Protocol (if it has a newer version, better) for my project. I found https://quic.clemente.io and I thought it might be a good idea but if you could give me any alternative/guidance to connect to another QUIC server and have a QUIC communication I would really appreciate.

**Comment by delinage** [comment]
My only goal is to connect to a server to perform some testing of QUIC Protocol (if it has a newer version, better) for my project. I found https://quic.clemente.io and I thought it might be a good idea but if you could give me any alternative/guidance to connect to another QUIC server and have a QUIC communication I would really appreciate.
