### ISSUE TITLE
please tag v0.8.0 or v0.7.1 containing at least 5a0a231c0

### ISSUE THREAD

**Issue by rsc** [lucas-clemente/quic-go#1421]
The last tagged release was v0.7.0, from Feb 2018. 
For tools that prefer tagged releases (dep, vgo), there is no tagged release containing 5a0a231c0, which means quic-go fails to build against the newest golang.org/x/net (because golang.org/x/net/lex/httphex moved into golang.org/x/net/http/httpguts). Personally I think it was uncool to delete golang.org/x/net/lex/httplex, but that ship has sailed.

I don't know what else you've got going on, but when things are in a stable state (or if you remember a stable state) it would be helpful if you could tag a release containing (or cherry-picking) 5a0a231c0. Thanks.

**Comment by marten-seemann** [comment]
Hello @rsc, 
I was about to make a new release today anyway, so here it is: [v0.8.0.](https://github.com/lucas-clemente/quic-go/releases/tag/v0.8.0).
