### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by MeABc** [lucas-clemente/quic-go#1444]
Hi, Author

https://github.com/lucas-clemente/quic-go/blob/master/client_multiplexer.go#L74 AddHandler function missing sync.Mutex 

I think it should be like this:

`
 func (m *clientMultiplexer) AddHandler(c net.PacketConn, connID protocol.ConnectionID, handler packetHandler) error {
+	m.mutex.Lock()
+	defer m.mutex.Unlock()
 	p, ok := m.conns[c]
 	if !ok {
 		return errors.New("unknown packet conn %s")
 	}
 	p.manager.Add(connID, handler)
 	return nil
 }

`

my fork: https://github.com/MeABc/quic-go/commit/05ada786b8d434da7e78ce06f06d72589257c697

**Comment by marten-seemann** [comment]
Good catch, thanks for reporting!
Your fix looks correct. Do you want to send a pull request? I'll merge it right away.

**Comment by MeABc** [comment]
My repo is temporary. so,  I don't want to send a pull request. sorry!
you fix, I clone. I like this...

**Comment by marten-seemann** [comment]
Ok, I'll prepare the fix.
By the way, it doesn't matter if it's temporary or not. As soon as it's merged, the code is part of quic-go.
