### ISSUE TITLE
slow than tcphttp2

### ISSUE THREAD

**Issue by carr123** [lucas-clemente/quic-go#1447]
Hello, I tested quic-go which is based on udp, i find it slower much than http2 client(which is base on TCP).
what's wrong ?

	httpclient := &http.Client{
		Transport: &http2.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		//		Transport: &h2quic.RoundTripper{
		//			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		//		},
	}

  // i issued 100 goroutines to do the following test.
	req, _ := http.NewRequest("GET", `https://172.16.1.53:8083/api/test`, nil)
		resp, err := httpclient.Do(req)
		if err != nil {
			fmt.Println(err)
			return
		}
		defer resp.Body.Close()

		bin, _ := ioutil.ReadAll(resp.Body)

**Comment by marten-seemann** [comment]
The benefits of quic won’t show on lossless connections to local host.
