### ISSUE TITLE
Distance from an quic-tls draft 11 implementation

### ISSUE THREAD

**Issue by alichator** [lucas-clemente/quic-go#1448]
Hi quic-go maintainers,

I am working on a go implementation of a modified version of QUIC. However the modification requires at minimum a draft 11 implementation to build off of. Your project seems to be the most mature quic implementation in go I was able to find, but it seems that it has not reached the feature set of draft 11 yet. 

I was wondering if you have a rough idea where the quic-go project is in terms of having all the functionality of a draft 11 implementation, or which draft you would say the project is closest to.

Thanks,

Alishah

**Comment by marten-seemann** [comment]
We’re not aiming to implement a specific draft version, but to follow the current version of the draft. Since there were some big changes recently, a lot of work is needed to catch up. I’d say quic-go is roughly between 11 and 12 at the moment.

Which feature of draft 11 do you need that quic-go doesn’t implement yet?

**Comment by alichator** [comment]
Thank you for your response. The main features I need are those that relate to the handshake and packet protection. I saw that encrypted packet numbers are still an open issue, so I thought that there might be other features of draft 11 not yet implemented.

**Comment by marten-seemann** [comment]
I’ve been working on packet number encryption, but it’s complicated... however, this should only matter if you’re trying to interop with other implementations of the working group draft (which will likely fail because we’re already implementing some changes after draft-11).

**Comment by alichator** [comment]
I misread the changelog, encrypted packet numbers are a draft 11 feature. I will keep an eye out, but at least for now I don't see other draft 11 features that I need not implemented yet. 

I am hoping to interop with other wg implementations. My current objective is to be able to successfully handshake with another draft 11 implementation. Do you know some of the post draft 11 changes that have been implemented?

**Comment by marten-seemann** [comment]
I don't see a lot of value in doing interop with an outdated draft version. If you think this is worth pursuing, you'll have to go through the commit history and figure out the changes yourself.
