### ISSUE TITLE
Large downloads spuriously stop after some time

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#145]

**Comment by marten-seemann** [comment]
I can't reproduce it. Please check if be34c9e actually fixed this issue.

**Comment by lucas-clemente** [comment]
It does not. Will re-investigate this once the streams refactoring is complete.

**Comment by lucas-clemente** [comment]
Note: Removing connection level flow control does not resolve this problem. Still, we're blocking in `stream.Write`.

**Comment by lucas-clemente** [comment]
Seems fixed by ffacf2f3288ef4a05b9803b997b1b83a9cacddf4.
