### ISSUE TITLE
Is there an API to get bandwidth and packet loss?

### ISSUE THREAD

**Issue by alandtsang** [lucas-clemente/quic-go#1451]
Hello, does quic-go have API to directly get the bandwidth and packet loss rate?

I see that the bandwidth can be obtained through the BandwidthEstimate() function, and the packet loss can is defined in congestion, but the session and stream do not have exported functions to get directly. 

Any good suggestions? Thank you.

**Comment by marten-seemann** [comment]
quic-go doesn't expose these currently.
In #1258, we discussed how this could be implement.
