### ISSUE TITLE
bandwidth tests

### ISSUE THREAD

**Issue by KouChongYang** [lucas-clemente/quic-go#1459]
Hello,
 I am doing bandwidth testing through quic. When I use quic to achieve video download, the NIC utilization is worse than downloading files via tcp. Gigabit NIC tcp can measure 900M/s, but quic can only measure 580M/s, why is this, can give suggestions, thank you very much

**Comment by marten-seemann** [comment]
Are you using a single QUIC connection for your measurement?

**Comment by KouChongYang** [comment]
I use 200 quic connect, and each connect has 4 stream, when the server listens to one port, only 600M/S can only be used. When the server listens to multiple ports, the network card can be depleted (1024M/S)

**Comment by wheelcomplex** [comment]
@KouChongYang could you share the testing code?

**Comment by KouChongYang** [comment]
@wheelcomplex https://github.com/KouChongYang/quic-test

**Comment by marten-seemann** [comment]
This should probably have gotten a lot better with the recent fixes to our pacing algorithm (#1855 and #1857). Feel free to open a new issue if the problem still exists.

**Comment by cnkedao** [comment]
./quic-test -s -f /data/test/10m -b 0.0.0.0:9876 -n 3 -t 30

./quic-test -c 127.0.0.1:9876 -n 30 -cn 400

[root@sta_dev ~]# dstat -nN lo        
---net/lo--
 recv  send
   0     0 
  22M   22M
  18M   18M
  26M   26M
  20M   20M
  31M   31M
  24M   24M
  24M   24M
  10M   10M
  22M   22M
  25M   25M
  24M   24M
  14M   14M
  15M   15M
  25M   25M
  29M   29M
