### ISSUE TITLE
Dummy cert 

### ISSUE THREAD

**Issue by KouChongYang** [lucas-clemente/quic-go#1502]
hi, 
when I use quic-go for client and Google proto-quic as server，
i get "Closing session with error: InvalidCryptoMessageParameter: Certificate data invalid"
I find the reason for my error is that quic server use dummy Cert.
Are you compatible with dummy cert？
Thank you very much

**Comment by marten-seemann** [comment]
You can set any certificate via the `tls.Config` passed to the `Listener`.
