### ISSUE TITLE
prioritize Crypto-Stream and Header-Stream in StreamFramer

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#151]
We need to see if we're speaking HTTP2, only then prioritize Stream 3.

**Comment by lucas-clemente** [comment]
I'm not sure this is necessary with #148. The packets on streams 1 and 3 should usually be quite small compared to all other streams, and will certainly fit into a single packet. If we do round-robin, their queues will almost always be empty.

**Comment by marten-seemann** [comment]
Yeah, sure, you're right #148 definitely helps here.
However, the `StreamFrameQueue` is already capable of handling certain frames with priority (currently used for all retransmitted packets), so it'd be literally one `if` to implement this.

**Comment by marten-seemann** [comment]
Do this when implementing #207.
