### ISSUE TITLE
incorrect type assertion in h2quic server

### ISSUE THREAD

**Issue by jiji1995** [lucas-clemente/quic-go#1510]
if qerr, ok := err.(*qerr.QuicError); !ok{
    errorCode = qerr.ErrorCode  //  painc in here
    s.logger.Errorf("error handling h2 request: %s", err.Error())
}

**Comment by marten-seemann** [comment]
When does that panic occur?

**Comment by jiji1995** [comment]
when I  fix the above code : "!ok" -> "ok" in h2quic/server.go.144 , the error is InvalidHeadersStreamData: InternalError: TooManyOpenStreams.

**Comment by marten-seemann** [comment]
You're right. Good catch!
Can you send a Pull Request with the fix please?
