### ISSUE TITLE
add support for gQUIC 46

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1517]
QUIC 45 will add support for the MESSAGE frame (as an experimental feature?), see https://mailarchive.ietf.org/arch/msg/quic/p0SSsnlUi_m6xNvTmBEJ41UPYA0.

**Comment by marten-seemann** [comment]
Also see https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/L1Ye9KsLtcU.

**Comment by marten-seemann** [comment]
Prerequisite: https://github.com/lucas-clemente/quic-clients/pull/13.

**Comment by marten-seemann** [comment]
gQUIC 46 uses the old version of the invariants 🙄, so it will be difficult to share code with the current master branch. I won't have the time to add support for gQUIC 46, but would be happy to review a PR, if anyone is interested in tackling this.

**Comment by ironsteel** [comment]
Hi, 
just before I try to implement gQUIC 46, should we continue supporting gQUIC 44?

I assume yes but just wanted to ask.

**Comment by marten-seemann** [comment]
I don’t see a lot of value in supporting either of them, to be honest.
What’s your use case for gQUIC 46?

**Comment by ironsteel** [comment]
I have deployed quic-go in production for some webapps and right now gquic doesn't work because google updated chrome/chromium to prefer gQUIC 46. 
Turning on the debug logs in quic-go yields this line:
```
handling packet from [redacted-ip:redacted-port]: error parsing header: InvalidPacketHeader: Received packet with invalid packet type: 67
```
I'm not really sure if this can be worked around with version negotiation to force the client to choose another version? Also it seems that at least chromium does not obey the supported versions in the alt-svc header (Q39,Q43 in my case) and defaults to Q46.

**Comment by marten-seemann** [comment]
No, Chrome doesn't honor version negotiation packets.
Google went ahead and implemented an IETF QUIC header format that was already outdated by the time they actually deployed that version. It would be a lot of work to get that working in quic-go, and it will change again for the next gQUIC version.
If you want to invest the time and effort, feel free to send us a PR that adds support for gQUIC 46. I don't think you need to support 44 and 46 at the same time, afaik 44 has been outdated for some time already. But you probably have some statistics on that from your webapp.

**Comment by ironsteel** [comment]
So the PR should be posted against the ```gquic``` branch of quic-go right?
>It would be a lot of work to get that working in quic-go, and it will change again for the next gQUIC version.
As far I understand they changed the header format to draft-17 with implemented var length packet numbers and var length connection ids right?
Sorry for asking this, but what is your approximate estimate for adding gQUIC 46 if you were to  implement it? For me I would say like week to week and a half if I remove the gQUIC 44 support.
The invariant header parsing for gQUIC 44 is implemented, so the ground work for gQUIC 46 has been laid down as the main difference between the two is not so significant as I was looking trough
 the codebase of quicgo.

**Comment by marten-seemann** [comment]
From the answers to your question on the proto-quic mailing list, gQUIC 46 will make it necessary to disable a bunch of the multiplexing features of quic-go, since it doesn't support client connection IDs. So that's additional complexity due to Google's incomplete implementation of the spec.
Also keep in mind that the invariants recently changed, so you'll need to come of with a demultiplexing scheme for future gQUIC versions.

**Comment by iwanbk** [comment]
> QUIC 45 will add support for the MESSAGE frame 

Sorry, I don't get the discussion in this GitHub issue.
AFAIK, latest version is 22(https://tools.ietf.org/html/draft-ietf-quic-tls-22) . What do you mean by 45 here?

**Comment by klaasel** [comment]
@iwanbk There are 2 implementations/specifications of QUIC at the moment: IETF QUIC en gQUIC, the latter being the implementation Google started with in 2013. This was picked up by the IETF and is currently being standardised and is indeed at version 22 as you mention (or even 23 as we speak?). 

Still though the gQUIC version is used by Google Chrome, YouTube servers and with the Cronet library in Android/iOS, also [this](https://eng.uber.com/employing-quic-protocol/) being a notable example. GQUIC is currently at version 46 and hopefully closing the gap specification-wise with IETF QUIC.
