### ISSUE TITLE
Socket API for quic-go? 

### ISSUE THREAD

**Issue by taimooralam** [lucas-clemente/quic-go#1535]
Is there a plug-and-play socket API available for quic-go? Where I can do something like:

```
socket = socket(QUIC_SOCKET)
socket.send(buf)
socket.recv(buf)
```

**Comment by marten-seemann** [comment]
There's no socket API for quic-go.
Please refer to the [Godoc](https://godoc.org/github.com/lucas-clemente/quic-go) for the API quic-go exposes.
