### ISSUE TITLE
send PING frames

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#154]

**Comment by marten-seemann** [comment]
According to Chromium, PINGs are only sent by the client, but never by the server (see `QuicConnection::SetPingAlarm()`).
I'm wondering why the spec doesn't say anything about that...

**Comment by lucas-clemente** [comment]
I think as a server, we don't really have an interest in keeping connections open longer than needed. Also, this way, we don't have any network traffic when a client stops sending PING frames to us, e.g. because network connectivity was lost. But I agree, it should be added to the spec.
