### ISSUE TITLE
Using a validate certificate for chrome testing

### ISSUE THREAD

**Issue by heavenThunder** [lucas-clemente/quic-go#1546]
Hi, everybody. I am working over quic-go to serve a web page for my thesis.

I saw in "Certificates" that this was an issue, but I have implemented.

First, I generated a 'Let's Encrypt' certificate with certboot. Is very easy and I do it in standalone mode as is explained here: https://certbot.eff.org/.

After that, it will give you an fullchain.pem, privkey.pem, even a cert.pem and is just have to point in the main.go. It worked for me.

PS: It is imperative having a domain for this.

Cheers.

**Comment by marten-seemann** [comment]
That's how you use a certificate. Not sure why this should be an issue.

**Comment by heavenThunder** [comment]
Sorry, i should specify that it's not an issue. I just followed the developer asking in "About the certificate":
https://github.com/lucas-clemente/quic-go/tree/master/example
Regards and congratulations for this great job,
Alberto
