### ISSUE TITLE
Add Go modules support

### ISSUE THREAD

**Issue by kavirajk** [lucas-clemente/quic-go#1547]
Add go modules support as a part of Go 1.11. Easy setup without GOPATH.

**Comment by marten-seemann** [comment]
We definitely should do that. Thanks for raising this issue.

**Comment by backkem** [comment]
Leaving some more learnings here: It seems qtls re-based their commit causing `go get` to be unable to find it. You can see our solution in pions/webrtc#357. I'm not sure how go modules could protect against this ATM.

**Comment by marten-seemann** [comment]
If I see that correctly, you're deploying the development version of quic-go. There's little point to do that, since compatibility is not guaranteed. It would be a better idea to use one of our tagged releases.
