### ISSUE TITLE
fail to access the example server with chrome showing ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by MisssRain** [lucas-clemente/quic-go#1585]
Hello, I followed the instructions to run the example server, and tried to access the server through chrome. But I failed with chrome showing 

> ERR_QUIC_PROTOCOL_ERROR

.

if I add `-tcp true  ` when I run the example server, and delete `--origin-to-force-quic-on=quic.clemente.io:443` when I run chrome from the terminal, I could open the website through TCP with HTTPS, no problem with the certificate.

I wonder why quic did not work? Thank you in advance.

**Comment by marten-seemann** [comment]
Please use the code in the `gquic` branch, the `master` doesn't support gQUIC any more.
If you still get the error, try running the server in debug mode, the error message will tell you what's going wrong.

**Comment by MisssRain** [comment]
> Please use the code in the `gquic` branch, the `master` doesn't support gQUIC any more.
> If you still get the error, try running the server in debug mode, the error message will tell you what's going wrong.

Thank you for your reply! It helps me!
