### ISSUE TITLE
What's Stream.Close real do ? 

### ISSUE THREAD

**Issue by sintanial** [lucas-clemente/quic-go#1599]
I try to test it and i can't understand what Stream.Close real do.
How to close stream on client and on server ? 
I try to call on client side: 
Stream.Close AND Stream.CancelRead
but it's don't closing stream on server. 

Only when i call Stream.CancelWrite AND Stream.CancelRead then stream on server closed and deleted !

**Comment by marten-seemann** [comment]
Please refer to the [GoDoc](https://godoc.org/github.com/lucas-clemente/quic-go).

> Close closes the write-direction of the stream.

**Comment by sintanial** [comment]
So it’s closed only write direction in local stream ?

**Comment by sintanial** [comment]
@marten-seemann 
I can't understand how to close stream correct ? (with deleting from streamsMap) ! 

I did some tests and found out:

stream.Close - closing only write direction (as i understood this menthod flush write buffer and send fin bit), but it's not removed stream from system(streamsMap). 
stream.CancelRead() - ask peer to stop write data. But it's not removed stream from system too.

And stream.Close + stream.CancelRead() to my surprise, don't removed stream from system too. It's normal behavior ? 

I continued find proper way to close stream with deleting from streamsMap. So correct way is stream.CancelRead() + stream.CancelWrite() but this combination some times produce error StreamDataAfterTermination because some write data buffered and try to send later.

And finally proper way to close stream is 
```
stream.CancelRead()
stream.Close()
stream.CancelWrite() <- yep in the doc says that "do not call this method after stream.Close"
```
Only after this combination stream correctly removed from streamsMap on server and client side.

What am I doing wrong ? Maybe it's bug ?

**Comment by marten-seemann** [comment]
A bidirectional stream has to be closed from both sides.

**Comment by sintanial** [comment]
@marten-seemann 
Of course i try to close stream on both sides ! But streams don't removed from streamsMap
Ok, lets see example:

test_client.go
```go
package main

import (
	"github.com/lucas-clemente/quic-go"
	"crypto/tls"
	"time"
)

func main() {
	sess, err := quic.DialAddr("localhost:4242", &tls.Config{InsecureSkipVerify: true}, &quic.Config{
		KeepAlive: true,
	})

	if err != nil {
		panic(err)
	}

	go openStreams(sess)

	for {
		_, err := sess.AcceptStream()
		if err != nil {
			panic(err)
		}

	}
}

func openStreams(sess quic.Session) {
	for i := 0; i < 10; i++ {
		stream, err := sess.OpenStream()
		if err != nil {
			panic(err)
		}

		stream.CancelRead(0)
		stream.Close()
	}
}
```
Client logs:

[client.txt](https://github.com/lucas-clemente/quic-go/files/2588126/client.txt)

First in the head of client logs you can see another strange behaviour: "Starting new connection" and immediately "Closing session with error: closing session in response to a stateless retry".  Maybe it's normal, i don't no, but just in case i'll notice you, because it repeat every time

Second i set timer and every 15 second i log count of streams in streamMap, and in log you can see 
this message: "****************************************COUNT OUTGOING STREAMS**************************************** 5 [4 0 12 16 8]", this means that half of streams (5 out of 10) not deleted, but why ?




test_server.go
```go
package main

import (
	"github.com/lucas-clemente/quic-go"
	"crypto/rsa"
	"crypto/rand"
	"crypto/x509"
	"math/big"
	"encoding/pem"
	"crypto/tls"
	"fmt"
)

func main() {
	l, err := quic.ListenAddr("localhost:4242", generateTLSConfig(), &quic.Config{
		KeepAlive: true,
	})
	if err != nil {
		panic(err)
	}

	for {
		sess, err := l.Accept()
		if err != nil {
			panic(err)
		}

		go handleSess(sess)
	}
}

func handleSess(sess quic.Session) {
	for {
		stream, err := sess.AcceptStream()
		if err != nil {
			fmt.Println(err)
			return
		}

		stream.CancelRead(0)
		stream.Close()
	}
}

func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{Certificates: []tls.Certificate{tlsCert}}
}
```

Server logs:

[server.txt](https://github.com/lucas-clemente/quic-go/files/2588137/server.txt)

In server logs you can see message: "****************************************COUNT INCOMING STREAMS**************************************** 10 [12 16 28 32 0 4 24 36 8 20]", 
and that means that all streams on server side don't removed from streamsMap !

I waited 1 minute but streams don't cleared. I think it's wrong behaviour !!!

**Comment by sintanial** [comment]
@marten-seemann what do you think about my logs ? Maybe it’s a bug ?

**Comment by marten-seemann** [comment]
This works exactly as it should. I advise you again to have a look at the [stream state diagrams](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.3) in the specification.

A bidirectional stream has to be closed **in both directions**. You're only closing the stream **in one direction** only, which is why the stream stays in the map. 
If you want to use `CancelRead` as you do, you have to first accept the stream at the peer, and then read the EOF.

**Comment by sintanial** [comment]
@marten-seemann I apologize for my perseverance !
Yes i read it, but i can't understand one thing. Help me to understand it please :).

For example, client open UniStream, my server knows that client send first "handshake" stream as 10 bytes message and thats all, after receive 10 bytes i want to close stream. How to proper way to close this stream after read this 10 bytes ? You are suggest to read until accept io.EOF only !? Yes ?

client.go
```go
stream, err := session.OpenUniStream()
	if err != nil {
		panic(err)
	}
stream.Write([]byte("hello"))
stream.Close() // i complete to write and want to close stream
```

server.go
```go
stream, err := sess.AcceptUniStream()
	if err != nil {
		panic(err)
	}
chunk := make([]byte, 1024)
n, err := stream.Read(chunk) // i read handshake message and want to close stream !
if err != nil {
     panic(err)
}
fmt.Println("incoming handshake message", chunk[:n])
// at this time stream not closed yet, if i call stream.CancelRead(0), it's don't closed too
```
Why in my example only one way to proper close stream is read io.EOF ? It doesn't look pretty. So we always need to remember, that stream.CancelRead() don't closed stream, and we need to read io.EOF, and only AFTER that stream is proper close (or another way is call stream.CancelWrite on client side, but it's not right)

**Comment by marten-seemann** [comment]
Once again, I can only point you to the specification. It seems like you didn't understand the state machine of a stream. I know it's not an easy topic, but it makes sense if you take the time to think it through.

For a unidirectional stream, on the sender side it is deleted from the map as soon as you call `Close`.  For the receiver side, it is deleted from the map as soon as you read the EOF.
For a bidirectional stream, both sides have to call `Close` and read the EOF. Not that in the normal case, you don't need the `Cancel...` functions at all.

**Comment by sintanial** [comment]
Thank you so much for the explanation and your patience. Now I understand everything
