### ISSUE TITLE
Use quic for real-time communication

### ISSUE THREAD

**Issue by VaychLain** [lucas-clemente/quic-go#1603]
Is it possible to configure quic to allow packet loss in specific situations to adapt to real-time call scenarios?

**Comment by marten-seemann** [comment]
QUIC doesn't support unreliable delivery, see [QUIC specificiation](https://quicwg.org/).

**Comment by VaychLain** [comment]
I know QUIC is a Reliable transmission protocol.
I wander  will QUIC support this type of scenario in the future? Or I need to customize “myQUIC”.
Or do you know anyone who use other mechanisms to make quic accommodate this type of scenario？

**Comment by VaychLain** [comment]
> QUIC doesn't support unreliable delivery, see [QUIC specificiation](https://quicwg.org/).

I know QUIC is a Reliable transmission protocol.
I wander will QUIC support this type of scenario in the future? Or I need to customize “myQUIC”.
Or do you know anyone who use other mechanisms to make quic accommodate this type of scenario？
