### ISSUE TITLE
Error when install quic-go

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1606]
Hi all,

I am a newbie about QUIC. I am implementing quic-go via the instructions in the github: https://github.com/lucas-clemente/quic-go. However, I got this error:
**_# github.com/lucas-clemente/quic-go/vendor/github.com/marten-seemann/qtls
../../../go/src/github.com/lucas-clemente/quic-go/vendor/github.com/marten-seemann/qtls/common.go:300:18: undefined: tls.ECDSAWithSHA1_**

Anybody know why? How can I resolve this?
Thank you.

**Comment by marten-seemann** [comment]
Looks like a problem with your Go environment.

**Comment by Astone-Chou** [comment]
tls.ECDSAWithSHA1 define in go 1.10.
