### ISSUE TITLE
'cannot find package "crypto/internal/cipherhw"' etc when depending on master

### ISSUE THREAD

**Issue by danwashusen** [lucas-clemente/quic-go#1608]
Firstly, I'm a golang newbie so I apologise if this is an issue of ignorance...

I'm attempting to test out the fix for #1597. To do that I updated my Gopkg.toml with the following and then then ran 'dep ensure -update':
```
[[constraint]]
  branch = "master"
  #version = "0.10.0"
  name = "github.com/lucas-clemente/quic-go"
```
This change seems to break the build with the following output:
```
vendor/github.com/marten-seemann/qtls/common.go:10:2: cannot find package "crypto/internal/cipherhw" in any of:
	/home/dan/Development/Projects/go/src/github.com/quic-transfer/vendor/crypto/internal/cipherhw (vendor tree)
	/snap/go/3039/src/crypto/internal/cipherhw (from $GOROOT)
	/home/dan/Development/Projects/go/src/crypto/internal/cipherhw (from $GOPATH)
vendor/github.com/marten-seemann/qtls/13.go:24:2: cannot find package "github_com/cloudflare/sidh/sidh" in any of:
	/home/dan/Development/Projects/go/src/github.com/quic-transfer/vendor/github_com/cloudflare/sidh/sidh (vendor tree)
	/snap/go/3039/src/github_com/cloudflare/sidh/sidh (from $GOROOT)
	/home/dan/Development/Projects/go/src/github_com/cloudflare/sidh/sidh (from $GOPATH)
vendor/github.com/marten-seemann/qtls/cipher_suites.go:18:2: cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
	/home/dan/Development/Projects/go/src/github.com/quic-transfer/vendor/golang_org/x/crypto/chacha20poly1305 (vendor tree)
	/snap/go/3039/src/golang_org/x/crypto/chacha20poly1305 (from $GOROOT)
	/home/dan/Development/Projects/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOPATH)
vendor/github.com/marten-seemann/qtls/13.go:25:2: cannot find package "golang_org/x/crypto/curve25519" in any of:
	/home/dan/Development/Projects/go/src/github.com/quic-transfer/vendor/golang_org/x/crypto/curve25519 (vendor tree)
	/snap/go/3039/src/golang_org/x/crypto/curve25519 (from $GOROOT)
	/home/dan/Development/Projects/go/src/golang_org/x/crypto/curve25519 (from $GOPATH)
```

My golang novice detective skills seem to suggest that `github.com/marten-seemann/qtls` is a new dependency (its not listed when I depend on 0.10.0) which makes me think it might *not* be an issue with my dev environment.

My other line of investigation was around the differences between using 'dep' instead of the suggested `go get -t -u ./...` command but so far I'm just more confused than when I started... :)

Any thoughts?

**Comment by marten-seemann** [comment]
Looks like you’re not using the vendored dependencies.

**Comment by danwashusen** [comment]
Thanks. Just a little confusing because my project compiles and runs 'out of the box' using 'godep' with:
```
[[constraint]]
  version = "0.10.0"
  name = "github.com/lucas-clemente/quic-go"
```

However when I switch to 'master' branch I get the above compile errors:
```
[[constraint]]
  branch = "master"
  name = "github.com/lucas-clemente/quic-go"
```

So I guess that implies an issue with my dev environment, although I'm stumped as to what that might be? I even tried switching my project to gevendor (which is what quick-go seems to use?) with the same result... 

I notice the quic-go vendor directory contains committed files related to qtls (I was under the impression vendor/*/ was usually excluded from git) so maybe that's related to my problem.

Any chance anyone can expand a little to help me narrow my problem solving?
