### ISSUE TITLE
Get RTTStats from session ?

### ISSUE THREAD

**Issue by sintanial** [lucas-clemente/quic-go#1610]
Is it possible to get congestion.RTTStats from session ? Now it's non-exportable field !
It's very useful )). For example, in my case i want to close connection with high rtt and use only low rtt

**Comment by marten-seemann** [comment]
It's not possible, and we're not planning to provide an API for that. However, we might this kind of information as port of #1258.

**Comment by sintanial** [comment]
It would be cool

**Comment by lucas-clemente** [comment]
The problem here is that any field we make public is part of our external API, which means we can't change it anymore without breaking it for our users. In particular the RTT / congestion related code is bound to change in the future, so it's currently not a good candidate for the public API.

**Comment by sintanial** [comment]
Ok, thx for explain. Fork will help me ;)
