### ISSUE TITLE
Deadlock (missing RUnlock() in packetHandlerMap)

### ISSUE THREAD

**Issue by ltucker** [lucas-clemente/quic-go#1631]
Running into a deadlock, it appears there is a case in packetHandlerMap.handlePacket which returns while holding a read lock on the packetHandlerMap here (other cases release the lock before returning):

https://github.com/lucas-clemente/quic-go/blob/dd81dfdbdd39692ae790f4720558ffc60a452919/packet_handler_map.go#L195

It may indicate something else strange is going on that I'm hitting this case, but it fouls up all sorts of things once hit.

**Comment by marten-seemann** [comment]
That's definitely a bug. Thanks for reporting.
This needs to be fixed with a `defer`, otherwise it will creep in again eventually.
