### ISSUE TITLE
Panic in caddy.

### ISSUE THREAD

**Issue by david9991** [lucas-clemente/quic-go#1653]
Original issue: https://github.com/mholt/caddy/issues/2346

**Comment by marten-seemann** [comment]
Thanks for bringing this to my attention. I’ll have a look at this later today.

**Comment by marten-seemann** [comment]
This seems to be a problem with how Caddy is using quic-go, see https://github.com/mholt/caddy/issues/2346#issuecomment-442735023. However, we might want to throw an error right away when `Listen` is called without a `tls.Config`.
