### ISSUE TITLE
TooManyOpenStreams error in when client opens new stream for every message.

### ISSUE THREAD

**Issue by bkolad** [lucas-clemente/quic-go#1660]
This issue might be related to #1618  
I modified the echo example, the client now continuously creates new streams and the server 
continuously listens for new streams. 

https://gist.github.com/bkolad/67ebe60393b047f133adf969dda48455

After accepting couple of hundred of streams the client complains:
panic: TooManyOpenStreams

I close the stream on both  sides (but tried all combinations), the trick with 
```go 
io.Copy(ioutil.Discard, stream)
```
didn't help.

**Comment by bkolad** [comment]
ok seems like the problem is that client produces streams faster than server can consume them.
adding small 		
```go 
time.Sleep(10 * time.Millisecond) 
``` 
in the client loop fixed the issue, also 
```go
io.Copy(ioutil.Discard, stream)
``` 
is also mandatory

**Comment by marten-seemann** [comment]
I suggest you use `OpenStreamSync` instead of a `time.Sleep`. This call blocks until a new stream can be opened, which is probably the behavior you want, if you're opening a lot of streams.
