### ISSUE TITLE
Multiplexer never lets go of old connections --> memory leak

### ISSUE THREAD

**Issue by Eichhoernchen** [lucas-clemente/quic-go#1709]
When establishing many connections as a client or when running for a long time, the connection multiplexer consumes more and more memory.

New packet conns are added to the multiplexer but are never let go again even if the underlying socket is closed.
Probably one would like to cleanup the multiplexer when the underlying packetHandlerMap has no connections for a period of time.

**Comment by marten-seemann** [comment]
That's right, we need to clean up the map. I think the right time to do that is on `packetHandlerMap.close`. That way, the behavior would be completely deterministic.

**Comment by Eichhoernchen** [comment]
I tried out your proposed solution, this fixes my memory leak.
I added a ref counter to the `connManager` which I think is required to not remove a multiplexed connection and further added a `RemConn` method similar to the `AddConn` method (both accounting for the ref count) that is called from the `packetHandlerMap.close`.

If you deem this an appropriate solution I'm happy to file a PR.

**Comment by marten-seemann** [comment]
I'm not sure I understand everything from your description. Please send a PR, then we can do a proper review.

**Comment by marten-seemann** [comment]
Fixed by #1738.
