### ISSUE TITLE
document and be consistent about returning timeout errors

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#1720]
When the connection is closed due to a timeout, we should return return `net.Errors` with `Timeout() == true` and `Temporary() == false` on:
* `Dial{Addr}{Context}`
* `Session.Accept{Uni}Stream`
* `Session.Open{Uni}Stream{Sync}`
* `Stream.Read`
* `Stream.Write`

**Comment by apmattil** [comment]
now we need to parse the cause of timeout every time deadline is exceeded :
`if err.Timeout() {
			if strings.Contains(e.Error(), "deadline exceeded") {
				return 
			} else if strings.Contains(err.Error(), "No recent network activity") {
				return 
			}
		} else if e.Temporary() {
			//q v0.11.2 does not return Temporary error !
		}`
