### ISSUE TITLE
Reopening: Expose underlying UDP socket #1719

### ISSUE THREAD

**Issue by paaguti** [lucas-clemente/quic-go#1726]
OK, I tried to use Listen and Dial... I'm able to set the TOS/Traffic class in the server side, where I use ListenUDP("udp", serveraddr).

I can also set IPv6 Traffic class on the client side where I use ListenUDP("udp", UDPAddr("[::]:0"))
However I'm not able to set IPv4 TOS on the client side when I use ListenUDP("udp",UPDAddr("0.0.0.0:0")

For my tests, I need both client and server side to set the TOS/TrafficClass 
I'm not using golang/x/net But wrote the setTos() function myself and it works for TCP and 'normal' UDP flawlessly

Scratching my head...

Thanks for any help /PA

**Comment by marten-seemann** [comment]
It doesn't sound like this is a QUIC-related issue. Sounds like you'll need to figure out how to use the Go standard library to set these flags.
