### ISSUE TITLE
Parallel downloads stalling until the first request is complete

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#173]

**Comment by marten-seemann** [comment]
@lucas-clemente: Didn't we conclude that is an issue with Chrome? So this is a *wontfix*, isn't it?

**Comment by lucas-clemente** [comment]
Yep, there's nothing we can do. It seems that, when downloading many files at once (e.g. via command line), Chrome waits until the first download completes and only then sends the request for the other downloads. This is identical for HTTPS or QUIC, but interestingly not for HTTP.
