### ISSUE TITLE
Tried to delete unknown stream

### ISSUE THREAD

**Issue by sintanial** [lucas-clemente/quic-go#1742]
After update to recent master, I rarely receive error like this "InternalError: Tried to delete unknown stream 689".

I updated from commit 34dd046cb6ceb362917d2124bd7e9ebef6ed7ed0 to current master, and after that receiving this error.

**Comment by marten-seemann** [comment]
Thanks for the bug report. This definitely should not happen.

Could you post a minimum working example that shows this behavior? That would make searching for the bug a lot easier?

Alternatively, or maybe even better, could you [git bisect](https://git-scm.com/docs/git-bisect) to find out which commit introduced the issue?

**Comment by marten-seemann** [comment]
Closing due to age. Please let me know if this ever occurs again - it's definitely a bug, and something that should be fixed asap.
