### ISSUE TITLE
Use public variable for "server closed" error when Listener is closed

### ISSUE THREAD

**Issue by swdee** [lucas-clemente/quic-go#1778]
Given the following code the Listener is closed and Accept() returns errors.New("server closed") at https://github.com/lucas-clemente/quic-go/blob/707e9f7b79d12a3aeee7db60ce7793ebc99be736/server.go#L298

```
ln, err := quic.ListenAddr(addr, tslCfg, nil)

go func() {
    time.Sleep(5*time.Second)
    ln.Close()
}

for {
    sess, err := ln.Accept()

    if err != nil {
        if err.Error() == "server closed" {
            break
        }
    }

    go handleSession(sess)
}
```

Rather than matching on the error string value "server closed", which is susceptible to changing in future versions, instead the code should define a public error variable for matching on, as is done in the standard lib net/http package, eg: https://github.com/golang/go/blob/ccd9d9d4cef16618d84bae9cba9f1b264278c8ab/src/net/http/server.go#L2826

Enabling something like;
```
sess, err := ln.Accept()

if err != nil {
    if err == quic.ErrServerClosed {
        break
    }
}
```

**Comment by marten-seemann** [comment]
I'm not opposed to this idea, but I'm not sure if HTTP is the right comparison here, since it's an application protocol.
Looking at TCP, Go doesn't return any specific error code, and you have to do a partial string match on "use of closed network connection", if I remember the error correctly. Any idea why this is?

**Comment by swdee** [comment]
Not sure on the TCP specifics on returned error code, however my thoughts on opening the issue were more idiomatic with packages defining public vars for error handling which can be picked up in an IDE so typing "quic.Err" quickly reveals the available error codes, versus having to grep through the code base to find out what the returned errors are.

**Comment by marten-seemann** [comment]
@swdee I was wondering about your code
```go
for {
    sess, err := ln.Accept()

    if err != nil {
        if err.Error() == "server closed" {
            break
        }
    }

    go handleSession(sess)
}
```

Why would you only break the loop in case the server is closed. `Accept` never returns an error, unless something has gone wrong - you definitely shouldn't handle the session in that case (it might be `nil` anyway), and for sure further class to `Accept` will also fail.
The following code should be safe:
```go
for {
    sess, err := ln.Accept()
    if err != nil {
       break
    }

    go handleSession(sess)
}
```

**Comment by mholt** [comment]
Is this something that Go 1.13's error wrapping can address?

**Comment by marten-seemann** [comment]
I'm not very familiar (yet) with the error wrapping in Go 1.13. How would that work?

**Comment by mholt** [comment]
It's pretty simple, basically you can wrap errors with `%w` formatting directive, then use errors.Is/As to inspect if they have the specific type you're looking for: https://golang.org/pkg/errors/#pkg-overview

**Comment by marten-seemann** [comment]
Yeah, but how would you use it in this case? I'm wary of extending the quic-go API here.

**Comment by mholt** [comment]
I'm not too familiar with it yet (I need to use it more) -- but one option that doesn't require Go 1.13 would be to return an error value that implements an interface, but you don't need to declare that in your package. @swdee could define that interface then do a type assertion on the error to see if it implements it. Just a possibility.

**Comment by marten-seemann** [comment]
I still don’t see why this error is needed anyway. We need the return *something* (that’s not nil), but that’s it.
I’m happy to reconsider once a compelling use case is presented.

**Comment by mholt** [comment]
That's fine, I don't really have a stake in this issue -- I'll let you know if I have a use case. Was just putting out a couple of ideas.
