### ISSUE TITLE
Allow injection of the internal buffer pool

### ISSUE THREAD

**Issue by VictoriaRaymond** [lucas-clemente/quic-go#1787]
It would be nice that caller can inject into the [internal buffer pool](https://github.com/lucas-clemente/quic-go/blob/master/buffer_pool.go). The buffer pool basically manages a pool of byte slices. The slices can be reused for other purposes. 

At the moment, we maintain a vendored copy of quic-go in [our codebase](https://github.com/v2ray/v2ray-core/blob/master/external/github.com/lucas-clemente/quic-go/buffer_pool.go#L55) to share the buffers. This is the only customization that blocks us to use the mainstream version.

Golang has [some similar design](https://golang.org/pkg/net/http/httputil/#ReverseProxy) for this kind of reuse.

**Comment by marten-seemann** [comment]
The problem here is that slices need to have a minimum capacity of `protocol.MaxReceivePacketSize`. Any idea for a nice API that fulfills that requirement?

**Comment by VictoriaRaymond** [comment]
I can't come up with a quick solution on this,  other than putting it in comment. It is mainly a responsibility of the caller to provide valid buffers. This API will surely cause some debugging nightmare, such as double releasing buffers to the pool. It is reasonable that quic-go panics in such cases.

**Comment by marten-seemann** [comment]
Hello @VictoriaRaymond, I talked about this with @lucas-clemente, and we're skeptical if it's wise to expose an internally used buffer in the API.
Furthermore, I believe the performance benefit you can achieve by merging an application's buffer pool with quic-go's buffer pool would be negligible.
