### ISSUE TITLE
vendor.json references inexistent commit in marten-seemann/qtls

### ISSUE THREAD

**Issue by raulk** [lucas-clemente/quic-go#1788]
from trying to generate a `go.mod` file:

```
→ go mod init
go: creating new go.mod: module github.com/lucas-clemente/quic-go
go: copying requirements from vendor/vendor.json
go: converting vendor/vendor.json: stat github.com/marten-seemann/qtls@591c71538704125b0b189f4cd3c0e61485dd6ef7: unknown revision 591c71538704125b0b189f4cd3c0e61485dd6ef7
```

Indeed the commit does not exist in that repo. It seems the entire repo was rebased or recreated, as `vendor.json` states this dep was added on `2019-01-10T16:28:36Z`, but the earliest commit is in February.

**Comment by raulk** [comment]
@marten-seemann maybe you can check if you still have this commit in your reflog and push it to a branch on GitHub? Then the `go mod` tool should be able to find it.

**Comment by anacrolix** [comment]
```
# github.com/lucas-clemente/quic-go/internal/handshake [github.com/lucas-clemente/quic-go/internal/handshake.test]
internal/handshake/initial_aead.go:27:15: undefined: qtls.AEADAESGCM13
internal/handshake/initial_aead.go:32:15: undefined: qtls.AEADAESGCM13
internal/handshake/qtls.go:47:3: cannot use c.Renegotiation (type tls.RenegotiationSupport) as type qtls.RenegotiationSupport in field value
```

**Comment by marten-seemann** [comment]
I moved the repository (which was based on tls-tris) and replaced it by code based on the standard library implementation.
#1780 will use the new repository. However, that won’t help for old releases. I guess we won’t be able to use go mod for them.

**Comment by anacrolix** [comment]
It is possible to replace references to the old repo with the new deprecated one. I had a go but still got the same errors.
```
module github.com/lucas-clemente/quic-go

require (
	github.com/cheekybits/genny v1.0.0
	github.com/cloudflare/sidh v0.0.0-20181111220428-fc8e6378752b
	github.com/golang/mock v1.2.0
	github.com/marten-seemann/qtls v0.0.0-20190208043938-9320dc76eab2
	github.com/onsi/ginkgo v1.7.0
	github.com/onsi/gomega v1.4.3
	golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
	golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
	golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4 // indirect
	golang.org/x/sys v0.0.0-20190213121743-983097b1a8a3
	gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
	gopkg.in/yaml.v2 v2.2.2 // indirect
)

replace github.com/marten-seeman/qtls => github.com/marten-seemann/qtls-deprecated v0.0.0-20190207043627-591c71538704
```
It may be due to https://github.com/golang/go/issues/24110.
```
$ go list -m all
github.com/lucas-clemente/quic-go
github.com/cheekybits/genny v1.0.0
github.com/cloudflare/sidh v0.0.0-20181111220428-fc8e6378752b
github.com/fsnotify/fsnotify v1.4.7
github.com/golang/mock v1.2.0
github.com/golang/protobuf v1.2.0
github.com/hpcloud/tail v1.0.0
github.com/marten-seemann/qtls v0.0.0-20190208043938-9320dc76eab2
github.com/onsi/ginkgo v1.7.0
github.com/onsi/gomega v1.4.3
golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
golang.org/x/sys v0.0.0-20190213121743-983097b1a8a3
golang.org/x/text v0.3.0
gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
gopkg.in/fsnotify.v1 v1.4.7
gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
gopkg.in/yaml.v2 v2.2.2
```

**Comment by marten-seemann** [comment]
I suggest we wait until quic-go has go-mod support and a new version is released.

**Comment by anacrolix** [comment]
I thought this was quic-go, or do you mean qtls?

**Comment by marten-seemann** [comment]
I’ll add go mod for both at the same time.

**Comment by apmattil** [comment]
looks like also mint version fails update 
go get -u github.com/lucas-clemente/quic-go
# github.com/lucas-clemente/quic-go/internal/crypto
../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.10.1/internal/crypto/key_derivation.go:46:37: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.10.1/internal/crypto/key_derivation.go:47:35: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)

**Comment by apmattil** [comment]
update gets version
github.com/bifurcation/mint v0.0.0-20190129141059-83ba9bc2ead9
reverting back to 
github.com/bifurcation/mint v0.0.0-20180715133206-93c51c6ce115
gets update to work again.

**Comment by anacrolix** [comment]
See #1789, which works with master.

**Comment by anacrolix** [comment]
The error above with replace was due to a typo. The PR is the correct solution.

**Comment by marten-seemann** [comment]
I pushed the old qtls back to the qtls repo into the [deprecated branch](https://github.com/marten-seemann/qtls/tree/deprecated), so this commit should be available now.
