### ISSUE TITLE
Unable to connect to quic-server

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1813]
Hi administrator,

I follow the instructions from https://github.com/lucas-clemente/quic-go/tree/gquic. However, I got the error when I implement the example server:

_server Serving new connection: 0xfa30f504a3a7892c, version gQUIC 43 from x.x.x.x:44955
server Closing session with error: ProofInvalid: Proof invalid: Failed to verify certificate chain: net::ERR_CERT_DATE_INVALID._

Do you know why? How can I resolve this issue?
Thank you in advance.

**Comment by marten-seemann** [comment]
@lucas-clemente Can you please update the certificate in the gquic branch?

@shinichikudo987 You can use your own certificate.

**Comment by shinichikudo987** [comment]
Hi,
I updated the certificate, but I got the error. 
Could you show me how to generate the certificate?
Thank you.

**Comment by marten-seemann** [comment]
Please use your favorite search engine to find out how to generate a certificate. This is not related to quic-go.
