### ISSUE TITLE
Interop of quic-go

### ISSUE THREAD

**Issue by klaasel** [lucas-clemente/quic-go#1827]
At [https://docs.google.com/spreadsheets/d/1D0tW89vOoaScs3IY9RGC0UesWGAwE6xyLk0l4JtvTVg](url) the interopability status between various implementations of QUIC is being kept track of. The row and column of quic-go is very empty. Is there any known interoperability?

**Comment by marten-seemann** [comment]
We didn’t participate in the remote interop. quic-Go should have basic interoperability based on the latest draft.
