### ISSUE TITLE
The tls  certificate has expired 

### ISSUE THREAD

**Issue by wangjianyayaya** [lucas-clemente/quic-go#1835]
because of this(quic.clemente.io，Valid until 2  Mar 2019), between the  chrome  and  server , we  can not use QUIC to transport, please  help  me, thanks a lot.

**Comment by wangjianyayaya** [comment]
@lucas-clemente

**Comment by wangjianyayaya** [comment]
@marten-seemann

**Comment by marten-seemann** [comment]
Please use your own cert.
