### ISSUE TITLE
../../marten-seemann/qtls/common.go:1062:20: undefined: cpu.ARM64

### ISSUE THREAD

**Issue by wimgithub** [lucas-clemente/quic-go#1839]
# github.com/marten-seemann/qtls
../../marten-seemann/qtls/common.go:1062:20: undefined: cpu.ARM64

**Comment by wimgithub** [comment]
I am using the latest golang version 1.12.1

**Comment by marten-seemann** [comment]
You need to use go mod.

**Comment by wimgithub** [comment]
> You need to use go mod.

Thank you！
