### ISSUE TITLE
figure out when to send StopWaitingFrames in QUIC 34

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#185]

**Comment by marten-seemann** [comment]
We definitely need to send a `StopWaiting` with every ACK: `QuicConnection::SendAck()` calls `QuicPacketGenerator::SetShouldSendAck(bool also_send_stop_waiting)` with `also_send_stop_waiting = true.

**Comment by lucas-clemente** [comment]
See the discussion in https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/5XgGkb2P58Y
