### ISSUE TITLE
Path Migration

### ISSUE THREAD

**Issue by dmat93** [lucas-clemente/quic-go#1851]
Working with the quic-go v0.6.0 I saw this behavior:
 - QUIC-client (c_IP) and QUIC-server (s_IP)
 - NAT on QUIC-client
 - two different paths available with two different IP addresses (c_IP1, c_IP2, s_IP)

At certain time, with routing operation, I order to QUIC-client 

*"OK, to reach QUIC-server don't use anymore IP1 through path 1 but use IP2 on path2"*

**Time 0**
c_IP1 -------------> s_IP
c_IP1 <------------- s_IP

**Time t0**
c_IP2 -------------> s_IP
c_IP2 <------------- s_IP

In version 0.10.1 I saw that this behavior disappeared:
when I change path I saw that

**Time 0**
c_IP1 -------------> s_IP
c_IP1 <------------- s_IP

**Time t0**
c_IP2 -------------> s_IP
**c_IP1** <------------- s_IP [responses uses old path]

**I use only NAT on QUIC-client in order to reach internet and/or local web-server**
**No SNAT/DNAT/REDIRECTION**

The old behavior was intentional or it was only a lucky shot?

**Comment by marten-seemann** [comment]
Connection migration (#234) is not yet supported. The behavior in 0.6.0 was insecure and should not be relied on under any circumstances.
