### ISSUE TITLE
panic calling LocalAddr

### ISSUE THREAD

**Issue by whyrusleeping** [lucas-clemente/quic-go#1880]
Including some extra logs as they may be insightful:

```
10:00:44.492 ERROR        dht: Got error retrieving record with key /F5YGWLYSEA5Z2Z4V2BOXPCQI73DIUOTCRFE4X4VUI646EXVW4FTWGLGR5RTN6 from datastore: open /home/whyrusleeping/.ipfs/datastore/1304092.ldb: too many open files handlers.go:215
10:00:46.334 ERROR        dht: Got error retrieving record with key /F5YGWLYSECBTCRLNSEFB73MRVNZF7N6KSEPPJPVFJ7EM7Y6ZZ6LF5WN7LJZ72 from datastore: open /home/whyrusleeping/.ipfs/datastore/1304082.ldb: too many open files handlers.go:215
10:00:46.342 ERROR        dht: Got error retrieving record with key /F5YGWLYSEBGF3Q23SBRYL5SFH354L3G24WTQ77VWO2OGEPPMUN532MUTU5HUQ from datastore: open /home/whyrusleeping/.ipfs/datastore/1304075.ldb: too many open files handlers.go:215
10:00:46.578 ERROR blockstore: blockstore.AllKeysChan got err: walk failed: open /home/whyrusleeping/.ipfs/blocks: too many open files blockstore.go:222
10:00:46.711 ERROR        dht: Got error retrieving record with key /F5UXA3TTF4JCATC5YNNZAY4F6ZCT566F5TNOLJYP723HNHDCHXWKG655GKJ2OT2I from datastore: open /home/whyrusleeping/.ipfs/datastore/1304151.ldb: too many open files handlers.go:215
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xadd0e5]

goroutine 225359 [running]:
net.(*UDPConn).LocalAddr(0x0, 0xc00b7720f0, 0x0)
        <autogenerated>:1 +0x5
github.com/lucas-clemente/quic-go.(*conn).LocalAddr(0xc0018f3200, 0x0, 0x4)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/conn.go:42 +0x34
github.com/lucas-clemente/quic-go.(*client).dial(0xc006a29860, 0x1a0e760, 0xc00b1d96e0, 0xc00bb5bfb0, 0xc0088f9280)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/client.go:248 +0x49
github.com/lucas-clemente/quic-go.dialContext(0x1a0e760, 0xc00b1d96e0, 0x1a19400, 0x0, 0x19f6220, 0xc00bb5bfb0, 0xc00b6ebc80, 0x11, 0xc00fc1f080, 0xc0088f9280, ...)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/client.go:132 +0x1aa
github.com/lucas-clemente/quic-go.DialContext(...)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/client.go:110
github.com/libp2p/go-libp2p-quic-transport.(*transport).Dial(0xc000181cb0, 0x1a0e760, 0xc00b1d96e0, 0x1a18fe0, 0xc008b94740, 0xc00e06a1e0, 0x22, 0x3, 0xc000054f70, 0xc000054f00, ...)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/libp2p/go-libp2p-quic-transport@v0.0.2/transport.go:135 +0x255
github.com/libp2p/go-libp2p-swarm.(*Swarm).dialAddr(0xc00041a280, 0x1a0e760, 0xc00b1d96e0, 0xc00e06a1e0, 0x22, 0x1a18fe0, 0xc008b94740, 0x0, 0xc0001eeb70, 0xc00b1d96e0, ...)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.0.1/swarm_dial.go:440 +0x21f
github.com/libp2p/go-libp2p-swarm.(*dialLimiter).executeDial(0xc0001bbf40, 0xc0018f3140)
        /home/whyrusleeping/gopkg/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.0.1/limiter.go:217 +0x17f
created by github.com/libp2p/go-libp2p-swarm.(*dialLimiter).addCheckFdLimit
        /home/whyrusleeping/gopkg/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.0.1/limiter.go:167 +0x606
```

Looks like we fail to open a socket because of too many open files, and then that causes us to have a nil underlying UDP socket.

**Comment by marten-seemann** [comment]
This is weird.
First of all, we're reusing the socket for QUIC dials (and let QUIC handle the demultiplexing of multiple QUIC connections on the same conn): https://github.com/libp2p/go-libp2p-quic-transport/blob/fbfc45cf44a6a8669362d97f6668e5da937ecca6/transport.go#L41-L66. So we shouldn't run out of file descriptors no matter how many QUIC connection we open.
Furthermore, in the code linked above we're handling the errors correctly, so I don't see how we could possible end up with a `nil` value for the `pconn`.

Can you help me reproduce this somehow?

**Comment by whyrusleeping** [comment]
Yeah, my machine is crashing with this every 20 minutes or so. What do you
need?

**Comment by marten-seemann** [comment]
Is this your local machine or one of the bootstrappers? Are you running anything special on there, or just an idle IPFS node?

**Comment by marten-seemann** [comment]
My node has been running for 2 hours now and nothing is happening...

**Comment by whyrusleeping** [comment]
its one of the bootstrappers, I'm running the new peerstore code which is causing a ton of file descriptors to be opened, leading lots of random things to get panics due to having too many file descriptors being open.

**Comment by marten-seemann** [comment]
The thing is, it shouldn't panic. If we run out of file descriptors, https://github.com/libp2p/go-libp2p-quic-transport/blob/fbfc45cf44a6a8669362d97f6668e5da937ecca6/transport.go#L60-L66 would return an error, and we'd abort the `Dial` in https://github.com/libp2p/go-libp2p-quic-transport/blob/fbfc45cf44a6a8669362d97f6668e5da937ecca6/transport.go#L103-L106.

Could you maybe put a log statement for both `pconn` and `err` before that line? I'm sorry that I don't have any better fix, this looks really mysterious to me.

**Comment by whyrusleeping** [comment]
@marten-seemann i think i found it. The once.Do in GetConnForAddr fails, and correctly returns an error,  but the next caller for that won't call the function in the once.Do closure, because its already been done. so that second call here will get nil,nil returned (since the conn is nil already, and the error is defined locally and nil).

**Comment by marten-seemann** [comment]
@whyrusleeping You're right. How could I miss that 🤦‍♂?

I'll transfer this issue to https://github.com/libp2p/go-libp2p-quic-transport/issues/58, since it's a bug there.
