### ISSUE TITLE
How install MPQuic with quic-go?

### ISSUE THREAD

**Issue by thomaswpp** [lucas-clemente/quic-go#1883]
I tried different ways to install MPQuic, but were not successful. How can I install MPQuic? and what version of quic-go is compatible?

I tried this tutorial
https://multipath-quic.org/2017/12/09/artifacts-available.html
but when I try "go get -t -u ./..."
I get error

``
package golang.org/x/net/lex/httplex: cannot find package "golang.org/x/net/lex/httplex" in any of:
	/usr/local/go/src/golang.org/x/net/lex/httplex (from $GOROOT)
	/home/thomas/go/src/golang.org/x/net/lex/httplex (from $GOPATH)
``
So, I change this files request_writer.go and roundtrip.go
"golang.org/x/net/lex/httplex" ==> "golang.org/x/net/http/httpguts"

And when I try again "go get -t -u ./..."
I got this error:

``
github.com/lucas-clemente/quic-go/internal/crypto
internal/crypto/key_derivation.go:47:60: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
internal/crypto/key_derivation.go:48:58: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)
``

**Comment by marten-seemann** [comment]
Please ask the authors of MPQuic.

**Comment by Heath68** [comment]
Hello，
 Did you fixed this problem？I have the same problem as you did.
