### ISSUE TITLE
cantfind package what happen

### ISSUE THREAD

**Issue by 344524488** [lucas-clemente/quic-go#1885]
go get -d -u -t github.com/caddyserver/forwardproxy/... github.com/mholt/caddy/...
package github.com/caddyserver/forwardproxy
imports github.com/lucas-clemente/quic-go/h2quic: cannot find package "github.com/lucas-clemente/quic-go/h2quic" in any of:
/usr/local/go/src/github.com/lucas-clemente/quic-go/h2quic (from $GOROOT)
/home/gopath/src/github.com/lucas-clemente/quic-go/h2quic (from $GOPATH)

**Comment by marten-seemann** [comment]
This looks like a Caddy issue, not a quic-go issue.
