### ISSUE TITLE
Error run quic-go

### ISSUE THREAD

**Issue by vanvantong** [lucas-clemente/quic-go#1889]
Hi,
I follow the instruction from github, however I got the errors:

# github.com/lucas-clemente/quic-go/internal/crypto
github.com/lucas-clemente/quic-go/internal/crypto/aesgcm12_aead.go:32:20: undefined: cipher.NewGCMWithTagSize
github.com/lucas-clemente/quic-go/internal/crypto/aesgcm12_aead.go:40:20: undefined: cipher.NewGCMWithTagSize
github.com/lucas-clemente/quic-go/internal/crypto/key_derivation.go:46:37: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
github.com/lucas-clemente/quic-go/internal/crypto/key_derivation.go:47:35: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)

Any body knows why? How can I resolve this issue?
Thank you in advance.

**Comment by marten-seemann** [comment]
Please use a current Go version with Go mod enabled.

**Comment by misterch0c** [comment]
I'm having the same issue with latest Go version and go mod enabled.
Using quick-go v10.2 which is a requirement for the project I'm trying to run
