### ISSUE TITLE
Supporting gQUIC39 now?

### ISSUE THREAD

**Issue by vanvantong** [lucas-clemente/quic-go#1890]
Hi all,

Is there any branch of quic-go on github supporting the older version of gQUIC (e.g. 39) now?
Thank you in advance!

**Comment by marten-seemann** [comment]
The gquic branch.

**Comment by vanvantong** [comment]
Hi Marten,

When I start quic-go as the server (gQUIC 45), and the quic_client (gQUIC39) as the client (https://www.chromium.org/quic/playing-with-quic), I got this error (server):

server Serving new connection: 0x21e52571a171f5b3, version gQUIC 39 from 127.0.0.1:53537
server Closing session with error: HandshakeTimeout: Crypto handshake did not complete in time.
server Connection 0x21e52571a171f5b3 closed

Do you know why?

**Comment by marten-seemann** [comment]
We don’t support gQUIC 45.
