### ISSUE TITLE
Session.Close hangs if the PacketConn is closed

### ISSUE THREAD

**Issue by Eudi4H** [lucas-clemente/quic-go#1894]
I'm using quic-go v0.11.1 with go1.12.5.

This program sets up a simulated in-memory `PacketConn`, opens a stream, then closes the `PacketConn` before tearing down the session. `Session.Close` then hangs instead of returning with an error.

<details>
<summary>test.go</summary>

<pre>
// Demonstrates a hang in quic.Session.Close when the underlying PacketConn's
// WriteTo method starts returning errors. quic-go v0.11.1.

package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"os"
	"time"

	"github.com/lucas-clemente/quic-go"
)

type StringAddr string

func (addr StringAddr) Network() string { return "local" }
func (addr StringAddr) String() string  { return string(addr) }

// Simulated PacketConn between two peers that use opposite ends of a pair of
// channels. Calling Close on either end closes the other end too.
type localPacketConn struct {
	peer   *localPacketConn
	addr   net.Addr
	closed chan struct{}
	rChan  <-chan []byte
	wChan  chan<- []byte
}

func (c *localPacketConn) ReadFrom(p []byte) (int, net.Addr, error) {
	select {
	case data := <-c.rChan:
		n := copy(p, data)
		return n, c.peer.addr, nil
	case <-c.closed:
		fmt.Fprintf(os.Stderr, "%s<-%s: ReadFrom on closed PacketConn\n", c.addr, c.peer.addr)
		return 0, nil, errors.New("ReadFrom on closed")
	}
}

func (c *localPacketConn) WriteTo(p []byte, addr net.Addr) (int, error) {
	select {
	case c.wChan <- p:
		return len(p), nil
	case <-c.closed:
		fmt.Fprintf(os.Stderr, "%s->%s: WriteTo on closed PacketConn\n", c.addr, c.peer.addr)
		return 0, errors.New("WriteTo on closed")
	}
}

func (c *localPacketConn) Close() error {
	select {
	case <-c.closed:
	default:
		close(c.closed)
	}
	return nil
}

func (c *localPacketConn) LocalAddr() net.Addr {
	return c.addr
}

func (c *localPacketConn) SetDeadline(t time.Time) error      { return nil }
func (c *localPacketConn) SetReadDeadline(t time.Time) error  { return nil }
func (c *localPacketConn) SetWriteDeadline(t time.Time) error { return nil }

// Create a pair of localPacketConns that are connected to each other.
func NewLocalPacketConnPair(aAddr, bAddr net.Addr) (*localPacketConn, *localPacketConn) {
	// Each side gets half of both of these channels.
	a2bChan := make(chan []byte, 100)
	b2aChan := make(chan []byte, 100)
	// Both sides share the "closed" channel.
	closed := make(chan struct{})
	a := localPacketConn{
		addr:   aAddr,
		closed: closed,
		rChan:  b2aChan,
		wChan:  a2bChan,
	}
	b := localPacketConn{
		addr:   bAddr,
		closed: closed,
		rChan:  a2bChan,
		wChan:  b2aChan,
	}
	a.peer = &b
	b.peer = &a
	return &a, &b
}

func run() error {
	// The simulated network connection that carries the QUIC session.
	clientConn, serverConn := NewLocalPacketConnPair(StringAddr("client"), StringAddr("server"))

	// Start the QUIC server.
	cert, err := generateTLSCertificate()
	if err != nil {
		return err
	}
	serverTLSConfig := &tls.Config{
		Certificates: []tls.Certificate{*cert},
	}
	ln, err := quic.Listen(serverConn, serverTLSConfig, nil)
	if err != nil {
		return err
	}

	// Start the QUIC client and dial the server.
	var clientSession quic.Session
	var dialErr error
	dialCh := make(chan struct{})
	go func() {
		clientTLSConfig := &tls.Config{
			InsecureSkipVerify: true,
		}
		clientSession, dialErr = quic.Dial(clientConn, nil, "dummy:dummy", clientTLSConfig, nil)
		close(dialCh)
	}()

	// Accept the client's session.
	serverSession, err := ln.Accept()
	if err != nil {
		return err
	}

	// Block until the client has finished dialing.
	<-dialCh
	if dialErr != nil {
		return dialErr
	}

	// Open a bidirectional stream. We must send something on it for the
	// server to actually accept it.
	var clientStream quic.Stream
	var streamErr error
	streamCh := make(chan struct{})
	go func() {
		clientStream, streamErr = clientSession.OpenStream()
		if streamErr == nil {
			_, streamErr = clientStream.Write([]byte("hello"))
		}
		close(streamCh)
	}()

	// Accept the client's bidirectional stream.
	serverStream, err := serverSession.AcceptStream()
	if err != nil {
		return err
	}

	// Block until the client has established the stream.
	<-streamCh
	if streamErr != nil {
		return streamErr
	}

	time.Sleep(500 * time.Millisecond)

	// Receive the client's message (this step is not necessary).
	var buf [128]byte
	fmt.Fprintf(os.Stderr, "serverStream.Read\n")
	n, err := serverStream.Read(buf[:])
	fmt.Fprintf(os.Stderr, "serverStream.Read -> %+q %v\n", buf[:n], err)
	if err != nil {
		return err
	}

	time.Sleep(500 * time.Millisecond)

	// Close the simulated network connection. After this point, all
	// ReadFrom and WriteTo calls will produce errors.
	fmt.Fprintf(os.Stderr, "clientConn.Close\n")
	err = clientConn.Close()
	fmt.Fprintf(os.Stderr, "clientConn.Close -> %v\n", err)
	if err != nil {
		return err
	}

	time.Sleep(500 * time.Millisecond)

	// Attempt to close the session from the server's side. This step hangs
	// because of the previous clientConn.Close.
	fmt.Fprintf(os.Stderr, "serverSession.Close\n")
	err = serverSession.Close()
	fmt.Fprintf(os.Stderr, "serverSession.Close -> %v\n", err)
	if err != nil {
		return err
	}

	return nil
}

func main() {
	err := run()
	fmt.Fprintf(os.Stderr, "program finished: %v\n", err)
}

func generateTLSCertificate() (*tls.Certificate, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, err
	}

	template := x509.Certificate{
		SerialNumber: big.NewInt(1),
	}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		return nil, err
	}
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, err
	}

	cert, err := tls.X509KeyPair(
		pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER}),
		pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}),
	)
	return &cert, err
}
</pre>
</details>

The program produces output like this (may vary slightly) before hanging indefinitely:
```
serverStream.Read
serverStream.Read -> "hello" <nil>
clientConn.Close
clientConn.Close -> <nil>
server<-client: ReadFrom on closed PacketConn
client<-server: ReadFrom on closed PacketConn
serverSession.Close
```

I expected to see something like this instead, and for the program to terminate:
```
serverStream.Read
serverStream.Read -> "hello" <nil>
clientConn.Close
clientConn.Close -> <nil>
server<-client: ReadFrom on closed PacketConn
client<-server: ReadFrom on closed PacketConn
serverSession.Close
serverSession.Close -> <some error>
program finished: <some error>
```

I tried to minimize the code for the sake of making a report, which is the reason for the in-memory `PacketConn` with both ends in a single process. When I encountered the problem, it was in a larger program, using a `PacketConn` built on top of a TCP connection, and separate client and server processes.

**Comment by marten-seemann** [comment]
Thanks for the detailed bug report @Eudi4H!
I could reproduce the problem, and I'm working on a fix.
