### ISSUE TITLE
No way to set a timeout/deadline for Listener.Accept()

### ISSUE THREAD

**Issue by AudriusButkevicius** [lucas-clemente/quic-go#1915]
Other than closing a connection, which makes it tricky to handle shutdowns.
Ideally Accept/Listen should take a context.

**Comment by marten-seemann** [comment]
This is analogous to the `net.Listener.Accept`, which also doesn't take a context.

**Comment by AudriusButkevicius** [comment]
But it does: https://golang.org/pkg/net/#ListenConfig.Listen

**Comment by AudriusButkevicius** [comment]
Or perhaps I am wrong, but let me check.

**Comment by AudriusButkevicius** [comment]
You can set the deadline for the listener, before calling accept:

```
		listener.SetDeadline(time.Now().Add(time.Second))
		conn, err := listener.Accept()
```

**Comment by AudriusButkevicius** [comment]
The listener interface is yours, so the world is your oyster as in how you expose this.

**Comment by AudriusButkevicius** [comment]
Same goes for stream acceptance.

**Comment by marten-seemann** [comment]
Can you describe your use case for this?

**Comment by AudriusButkevicius** [comment]
Usecase is not to block forever, and have a clean way of timing out and tearing down.

Sure I can hack it like I do now:
```
        // Accept is forever, so handle stops externally.
	go func() {
		select {
		case <-t.stop:
			_ = listener.Close()
		}
	}()

	for {
		// Blocks forever, see https://github.com/lucas-clemente/quic-go/issues/1915
		session, err := listener.Accept()

		select {
		case <-t.stop:
			if err == nil {
				_ = session.Close()
			}
			return
		default:
		}

		// Accept blocks forever, give it 10s to do it's thing.
		ok := make(chan struct{})
		go func() {
			select {
			case <-ok:
				return
			case <-time.After(10 * time.Second):
				l.Debugln("timed out waiting for stream on", session.RemoteAddr())
				_ = session.Close()
			}
		}()

		stream, err := session.AcceptStream()
		if err != nil {
			l.Debugln("failed to accept stream from", session.RemoteAddr(), err.Error())
			_ = session.Close()
			continue
		}
	}
```

But this spins up there random routines which just yank the carpet from underneath the feet after some time which is not a nice "API" to do fairly normal things.


Part of the same problem being solved using TCPListener:
```
	for {
		listener.SetDeadline(time.Now().Add(time.Second))
		conn, err := listener.Accept()
		select {
		case <-t.stop:
			if err == nil {
				conn.Close()
			}
			return
		default:
		}
	}
```

It's even worse with quic, as I have two of these "yank the carpet", once for the session, once for the stream.

**Comment by marten-seemann** [comment]
I'm aware of how you can hack this, but I still don't understand the use case. Why would you send a deadline for `Listener.Accept`? In reality, I assume that this code would always be called in a loop, in order to accept whichever connection is coming in.

**Comment by AudriusButkevicius** [comment]
My specific case is my listener is a service that a user can enable and disable, hence I want to periodically check if I should stop my accept loop which happens to do a bunch of other things other than accept. Killing the connection is a super crude way to do this, so doing an accept requires doing a listen again etc.

I think net.Listener does not guarantee for Accept to return on Close (atleast I have something like that in memory of being an issue).

Also the signalling of when I should accept something and when not might be signalled by an external mechanism, so for that external mechanism to be able to control how long we wait for an accept to happen seems normal. Imagine STUN where the timeframes when you need to do something if well defined.

As for streams, you definitely want a timeout there as the remote client might be misbehaving, or the connection goes away before a stream is accepted and you don't want to block by more than N seconds.

TCPListener has it, so clearly there were other sensible reasons to expose this.
What are the downsides of exposing this?
