### ISSUE TITLE
GQUIC: can only serve 30M/s bandwidth output

### ISSUE THREAD

**Issue by cnkedao** [lucas-clemente/quic-go#1923]
config:
wellcdn.com:4433 {
root /data
tls /data/fullchain.pem /data/privkey.pem
}

/etc/hosts:
127.0.0.1 wellcdn.com

testing:
./quicbench -rt quic -c 100 -d 10 -u https://wellcdn.com:4433/10m
./quicbench -rt quic -c 100 -d 10 -u https://wellcdn.com:4433/5m
./quicbench -rt quic -c 1000 -d 10 -u https://wellcdn.com:4433/2m
……

bandwidth:
dstat -nf -N bond0
-net/bond0-
recv send
1260k 34M
1291k 33M
1279k 32M
1265k 32M
1259k 32M
1242k 32M
1234k 32M
1298k 32M
1335k 32M
1275k 32M
1305k 32M

**Comment by marten-seemann** [comment]
I don’t see how this is an actionable issue.
