### ISSUE TITLE
The log should be correct by type.

### ISSUE THREAD

**Issue by jinleileiking** [lucas-clemente/quic-go#1947]
for example, the CHLO log, all the info :
```

        MIDS: "d\x00\x00\x00"
      
```

the MIDS should be printed like this:
`MIDS: "\x(hex of d)\x00\x00\x00"`

**Comment by marten-seemann** [comment]
I‘m not sure why we should change the logging format here. Furthermore, I’m not planning to invest a lot more effort into gQUIC.

**Comment by jinleileiking** [comment]
Did you mean you will do more about ietf quic and less about gquic?

**Comment by marten-seemann** [comment]
Yes, the master branch has been IETF QUIC for months now.

**Comment by marten-seemann** [comment]
Yes, the master branch has been IETF QUIC for months now.
