### ISSUE TITLE
Best practice to authenticate SessionOpen

### ISSUE THREAD

**Issue by richp10** [lucas-clemente/quic-go#1949]
Ideally I would like the client to pass a JWT through the Quic.Dial and evaluate that on the server before deciding whether to open the session. 

I tried adding this to context like this: 

```
ctx := context.WithValue(context.Background(), "values", common.ContextVars{Jwt: "This IS JWT"})
s, err := quic.DialAddrContext(ctx,addr, &tls.Config{InsecureSkipVerify: qd.skipCertVerify}, nil)
```

And on the server OnSessionOpen

```
j := session.Context().Value("values").(common.ContextVars).Jwt
log.Infof("Incoming JWT = %v", j)
```

But the struct containing the token does not come through - j is nil

There might be a simpler way (that actually works!). How do others do session authentication?

**Comment by marten-seemann** [comment]
Client authentication is provided by the TLS handshake.
