### ISSUE TITLE
does not implement qtls.RecordLayer (wrong type for SetReadKey method)

### ISSUE THREAD

**Issue by Evan-5210** [lucas-clemente/quic-go#1960]
hi 
**1. I downloaded the package v0.11.2 and extracted all files. 
2. run  "go build", the error ocurred as below:**

   _# github.com/lucas-clemente/quic-go/internal/handshake
internal/handshake/crypto_setup.go:115:5: cannot use &cryptoSetup literal (type *cryptoSetup) as type qtls.RecordLayer in assignment:
	*cryptoSetup does not implement qtls.RecordLayer (wrong type for SetReadKey method)
		have SetReadKey(*qtls.CipherSuite, []byte)
		want SetReadKey(qtls.EncryptionLevel, *qtls.CipherSuite, []byte)
internal/handshake/crypto_setup.go:216:35: cannot use cs (type *cryptoSetup) as type qtls.RecordLayer in argument to tlsConfigToQtlsConfig:
	*cryptoSetup does not implement qtls.RecordLayer (wrong type for SetReadKey method)
		have SetReadKey(*qtls.CipherSuite, []byte)
		want SetReadKey(qtls.EncryptionLevel, *qtls.CipherSuite, []byte)_

**3. go version;  go1.12.4 linux/amd64
4. What should I do?**

**Comment by marten-seemann** [comment]
You need to use to go mod.

**Comment by Dispelk9** [comment]
what does go mod do then? can you give me an example of syntax? thanks
