### ISSUE TITLE
why quic-go is slower than websocet?

### ISSUE THREAD

**Issue by vklonghml** [lucas-clemente/quic-go#1963]
hi, all, when i using the latest release code to test, creating 10 streams in one session, and each sending 10MB file, is slower than 10 websocket connection. And the pseudo code as follows:

quic client;
session := quic.DialAddr()
startTime := time.Now()
var wg sync.WaitGroup
wg.Add(10)
for i :=0; i<10; i++{
    go func(){
         stream, := session.OpenStream()
         stream.Write([]byte{10MB})
         wg.Done()
    }()
}
wg.Wait()
endTime := time.Now()
diff := endTime.Sub(startTime0

And the websocket client:
startTime := time.Now()
var wg sync.WaitGroup
wg.Add(10)
for i :=0; i<10; i++{
    go func() {
        lock.lock()
        c := websocket.DIal()
        c.WriteMessage(c, []byte{10MB})
       lock.Unlock()
        wg.Done()
    }()
}
wg.Wait()
endTime := time.Now()
diff := endTime.Sub(startTime0

through the code, i found all stream write will through the session.run(), so the packet will send  in order, not really concurrently writing, while we can run many thread, and write the packet without lock in c and the UDP socket. can anybody know that how can we increase the performance.

**Comment by marten-seemann** [comment]
QUIC is not expected to be faster on local transfers. Why would it be?
