### ISSUE TITLE
use-cases

### ISSUE THREAD

**Issue by vtolstov** [lucas-clemente/quic-go#1967]
does this package suitable for such things:
i have 3 data centers with 20 microservices on each. i need to communicate sometimes from one dc to another.
sometimes between this locations packets can be lost or latency increased, now i'm use tcp as transport, and i can lower some tcp params via sysctl, but i want to avoid such thing for end-user cases.
Each message not more then 1-2K of data.
I'm use protobuf coded messages.

**Comment by marten-seemann** [comment]
That sounds like QUIC could be used in that case. Note that compared to a stream multiplexer running on top of TCP, QUIC benefits because there's no head-of-line blocking between streams.
