### ISSUE TITLE
build main: cannot load github.com/lucas-clemente/quic-go/http3: cannot find module providing package github.com/lucas-clemente/quic-go/http3

### ISSUE THREAD

**Issue by Dispelk9** [lucas-clemente/quic-go#1968]
when I go build main.go in example folder it shows this error:

Dispelk9@server:~/go/quic-go/example$ go build main.go
go: finding github.com/lucas-clemente/quic-go/http3 latest
go: finding github.com/lucas-clemente/quic-go/quictrace latest
build main: cannot load github.com/lucas-clemente/quic-go/http3: cannot find module providing package github.com/lucas-clemente/quic-go/http3

How can I solve this?
thanks

**Comment by marten-seemann** [comment]
You need to use Go 1.12 with Go mod enabled.

**Comment by ArthurCChen** [comment]
@free1139 Thanks! I've done as you said, but still some packets missed:

example.com/m/v2 imports
	github.com/lucas-clemente/quic-go/ackhandler: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/ackhandler
example.com/m/v2 imports
	github.com/lucas-clemente/quic-go/congestion: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/congestion
example.com/m/v2 imports
	github.com/lucas-clemente/quic-go/internal/crypto: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/crypto
example.com/m/v2 imports
	github.com/lucas-clemente/quic-go/qerr: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/qerr
example.com/m/v2/example imports
	github.com/lucas-clemente/quic-go/h2quic: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/h2quic
example.com/m/v2 tested by
	example.com/m/v2.test imports
	github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc
example.com/m/v2/benchmark tested by
	example.com/m/v2/benchmark.test imports
	github.com/lucas-clemente/quic-go/integrationtests/tools/testlog: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testlog
example.com/m/v2/integrationtests/chrome tested by
	example.com/m/v2/integrationtests/chrome.test imports
	github.com/lucas-clemente/quic-go/integrationtests/tools/testserver: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testserver

Is there any other solutions?

**Comment by free1139** [comment]
> @free1139 Thanks! I've done as you said, but still some packets missed:
> 
> example.com/m/v2 imports github.com/lucas-clemente/quic-go/ackhandler: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/ackhandler example.com/m/v2 imports github.com/lucas-clemente/quic-go/congestion: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/congestion example.com/m/v2 imports github.com/lucas-clemente/quic-go/internal/crypto: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/crypto example.com/m/v2 imports github.com/lucas-clemente/quic-go/qerr: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/qerr example.com/m/v2/example imports github.com/lucas-clemente/quic-go/h2quic: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/h2quic example.com/m/v2 tested by example.com/m/v2.test imports github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc example.com/m/v2/benchmark tested by example.com/m/v2/benchmark.test imports github.com/lucas-clemente/quic-go/integrationtests/tools/testlog: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testlog example.com/m/v2/integrationtests/chrome tested by example.com/m/v2/integrationtests/chrome.test imports github.com/lucas-clemente/quic-go/integrationtests/tools/testserver: module github.com/lucas-clemente/quic-go@latest found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testserver
> 
> Is there any other solutions?

I haven't used quic-go for a long time. I don't know your specific compilation environment, and go mod has changed a lot.

I tried to compile the master branch one minute ago, it could build. I suggest you upgrade the go version. If it still can't work, you can learn more about go mod or follow the readme of official.

go version
```
go version go1.16.4 linux/amd64
```

git log -n 1
```
commit 1f3350557e2a195d22619091a5d001b371bf068f (HEAD -> master, origin/master, origin/HEAD)
Merge: b935a54c ba4d0201
Author: Marten Seemann <martenseemann@gmail.com>
Date:   Thu Dec 16 10:40:23 2021 +0400

    Merge pull request #3298 from lucas-clemente/go118
    
    add support for Go 1.18
```

```
shu@iZwz9as52j0wtijnk9v0ucZ:~/go/src/github.com/lucas-clemente/quic-go/example$ go build
shu@iZwz9as52j0wtijnk9v0ucZ:~/go/src/github.com/lucas-clemente/quic-go/example$ ls
client  Dockerfile  echo  example  main.go
```

**Comment by free1139** [comment]
Rename your repo and download a clean source code do a try again? Looks like your go mod has changed. Try to see these two `git status` or `go mod help` `go help get`, I can't reproduce your issue now.



At 2021-12-27 14:40:02, "Yuning Chen" ***@***.***> wrote:

@free1139 Thanks! I've done as you said, but still some packets missed:

example.com/m/v2 imports
github.com/lucas-clemente/quic-go/ackhandler: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/ackhandler
example.com/m/v2 imports
github.com/lucas-clemente/quic-go/congestion: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/congestion
example.com/m/v2 imports
github.com/lucas-clemente/quic-go/internal/crypto: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/crypto
example.com/m/v2 imports
github.com/lucas-clemente/quic-go/qerr: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/qerr
example.com/m/v2/example imports
github.com/lucas-clemente/quic-go/h2quic: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/h2quic
example.com/m/v2 tested by
example.com/m/v2.test imports
github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/internal/mocks/mocks_fc
example.com/m/v2/benchmark tested by
example.com/m/v2/benchmark.test imports
github.com/lucas-clemente/quic-go/integrationtests/tools/testlog: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testlog
example.com/m/v2/integrationtests/chrome tested by
example.com/m/v2/integrationtests/chrome.test imports
github.com/lucas-clemente/quic-go/integrationtests/tools/testserver: module ***@***.*** found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/integrationtests/tools/testserver

Is there any other solutions?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
