### ISSUE TITLE
# github.com/lucas-clemente/quic-go/internal/handshake build failed

### ISSUE THREAD

**Issue by Dispelk9** [lucas-clemente/quic-go#1975]
I'm using go 1.12.6 and Ubuntu 16.04.3 LTS. I have 'export GO111MODULE=on' in bashrc. Still, I have this error when try go test ./... in folder quic-go.

internal/handshake/crypto_setup.go:110:5: cannot use &cryptoSetup literal (type *cryptoSetup) as type qtls.RecordLayer in assignment:
	*cryptoSetup does not implement qtls.RecordLayer (wrong type for SetReadKey method)
		have SetReadKey(*qtls.CipherSuite, []byte)
		want SetReadKey(qtls.EncryptionLevel, *qtls.CipherSuite, []byte)
internal/handshake/crypto_setup.go:211:35: cannot use cs (type *cryptoSetup) as type qtls.RecordLayer in argument to tlsConfigToQtlsConfig:
	*cryptoSetup does not implement qtls.RecordLayer (wrong type for SetReadKey method)
		have SetReadKey(*qtls.CipherSuite, []byte)
		want SetReadKey(qtls.EncryptionLevel, *qtls.CipherSuite, []byte)
FAIL	github.com/lucas-clemente/quic-go [build failed]
FAIL	github.com/lucas-clemente/quic-go/benchmark [build failed]
FAIL	github.com/lucas-clemente/quic-go/http3 [build failed]
FAIL	github.com/lucas-clemente/quic-go/integrationtests/self [build failed]

**Comment by marten-seemann** [comment]
Again, this seems like a problem with your Go environment.

Please understand that we cannot provide any support with your local Go installation, there are plenty of tutorials for that on the internet. Please use your favorite search engine to find them.

**Comment by helllyf** [comment]
consider using a tagged release

**Comment by phuslu** [comment]
also meet this a week ago.
we always follow go tip and quic-go (and other libs, qtls) master to build our application for performance measure.

Hope it could be cured. (Yes, use go mod could avoid it, but we still want stay tip/master)

**Comment by marten-seemann** [comment]
@phuslu You can, please have a look at our CI setup, which does exactly that.
