### ISSUE TITLE
performance comparision tests with websocket and quic

### ISSUE THREAD

**Issue by edisonxiang** [lucas-clemente/quic-go#1985]
Hey team,

Absolutely quic-go is the first class go project for quic.
Currently I am trying to replace websocket with quic in my project.
I made some performance comparision tests with websocket and quic.
but the test data shows the websocket is better than quic as following.
![comparison](https://user-images.githubusercontent.com/28946359/60493523-8dabd700-9cdf-11e9-9f45-b5d4f2473f00.PNG)
Actually the test data exceeds our expectations,
since the websocket is based on tcp and the quic is based on udp.
I am using quic-go v0.10.1, but I tried quic-go v0.11.2.
The test result is the same like v0.10.1.

Could someone give some suggestions about this?
Thanks very much.

Attachment: [The Performance Test Data](https://github.com/lucas-clemente/quic-go/files/3348832/Performance.Data.xlsx)

**Comment by edisonxiang** [comment]
@marten-seemann @lucas-clemente Thanks:)

**Comment by marten-seemann** [comment]
What's your test setup (RTT, bandwidth, loss rate)?

**Comment by edisonxiang** [comment]
@marten-seemann Thanks your reply.
The graph shown in the issue is for RTT.
Actually we make a test with bandwidth, the result is the same.
Does the quic-go client write packets concurrently?

**Comment by marten-seemann** [comment]
The graph shows the total response time, not the RTT. At least according to the labeling of the axes.
So I'm asking again: What are the network conditions you're using for the test?

**Comment by edisonxiang** [comment]
Hey @marten-seemann 
The attachment in this issue includes the data comparision 
`Latency 50%	Latency 90%	Latency 99%	Latency 100%`
Please feel free to take a look at it.

I tested it in the opentelekom public cloud.
and the servers and the clients are in the same vpc.
the bandwidth is 50Mb/s.

**Comment by edisonxiang** [comment]
![quic-client](https://user-images.githubusercontent.com/28946359/60792290-01465c00-a198-11e9-92fd-130ba312a33a.PNG)

Hi @marten-seemann I am not sure if we understand corrently.
Does the quic-go client write packets concurrently or sequentially?
From this graph, it seems like the quic-go client is working sequentially.
Looking forward to your suggestions. Thanks.

**Comment by marten-seemann** [comment]
That’s correct.

**Comment by edisonxiang** [comment]
Thanks @marten-seemann 
If we change the working way of quic-go client into `concurrently',
Will it promote the permance?

**Comment by marten-seemann** [comment]
Do you have any measurement that shows that packing packets is the bottleneck?

**Comment by edisonxiang** [comment]
Not yet. I just tested the whole quic-go server and client.
Actually I am not familiar enough with quic-go like you guys.
So the working way of client is just the possible doubtful point.

**Comment by marten-seemann** [comment]
The problem is most likely somewhere in loss recovery or congestion control. We’re working on a benchmarking suite, so you should see some improvements there in coming months.

**Comment by edisonxiang** [comment]
@marten-seemann Thanks.
Feel free to ping me if I can do something:)
