### ISSUE TITLE
how to set meta data in stream?

### ISSUE THREAD

**Issue by Ice-Storm** [lucas-clemente/quic-go#1988]
grpc like:
`md, ok := metadata.FromIncomingContext(ccServer.Context())`
I'm confused that how to set and get metadata in quic-go?

**Comment by marten-seemann** [comment]
I don't know what metadata package you're referring to.
A stream is just an ordered byte-stream.

**Comment by Ice-Storm** [comment]
I mean set the header information.

**Comment by marten-seemann** [comment]
A stream doesn't have a header.
