### ISSUE TITLE
data send overload causes new streams to fail to send

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#1990]
I have tcp to quic proxy using v0.11.2
when I use fast.com to test speed new streams fail to send (receive works).

I debugged this as far:

- base framer send window gets full
- stream send window gets full (can be before base framer send window)
- framer.go: AppendStreamFrames() will not get frames because popStreamFrame() fails due send window is full.
- new streams will just cumulate and can not send due (s *session) sendPacket() will return packet not sent and sendPackets() will break out.
- As I understand acks are handled as special case so stream will appear to be open.

I do not know what we can do about this but perhaps AppendStreamFrames() should consider if it can not get frame what is the send window state and is the deadline exceeded and just fail the write.

In my case other timers expire before sends all sends fail and whole session is closed before send window is open enough to send anything.

**Comment by marten-seemann** [comment]
The way we’re handling writes on streams is analogous to how Go implements the TCP connection: when there’s no available flow control window, Write blocks until new data can be sent. If the connection stalls and no flow control credit becomes available, the session might run into the idle timeout.
Note that you can use the write deadline on the stream to unblock a Write call earlier.

**Comment by apmattil** [comment]
yes setting write deadline small and at timeout closing stream earlier works in my case to get space to base send window.
Sorry about making ticket about not really a bug.

BTW: I wish errors were public (as they were qerr) so I would not need to parse error strings.

**Comment by apmattil** [comment]
net.Error only gives Temporary() or Timeout() it is not enough info.
my code against version 0.10.x was like this 
if err.(*qerr.QuicError).ErrorCode == qerr.NetworkIdleTimeout {
now against 0.11.2 
if err.(net.Error).Temporary() {
				if strings.Contains(err.Error(), "No recent network activity") || strings.Contains(err.Error(), "too many open streams") {

and this error handling was is for OpenStream(), I guess it will eventually return 'NO ERROR' but too late.

**Comment by marten-seemann** [comment]
The idle timeout is not a temporary error, but a timeout error.
The error for opening streams is a temporary error, not a timeout error.

So you should get all the information you need from the `net.Error` interface.

**Comment by apmattil** [comment]
problem is that I can not separate does error apply to stream or session.
net.Error can give true from Temporary() e.g tcp write, this temporary problem could go away.
for opening quic stream  e.g "too many open streams" does not go away.. it implies problem of the session.
I can just continue to parse error string and check how they are changed per release.. but I would like to have specific error codes... so if they change I get compiler error.

**Comment by marten-seemann** [comment]
As I described in https://github.com/lucas-clemente/quic-go/issues/1990#issuecomment-508438150, you actually can, because one of them is a temporary and the other a timeout error.
