### ISSUE TITLE
quic-go client example shows nothing when running

### ISSUE THREAD

**Issue by Dispelk9** [lucas-clemente/quic-go#1994]
Hi,
I have a question about main.go of the client. I have successfully build both main.go of server and client. When I run main on the node server, which I created using a computer with Linux 16.04.3 LTS it shows: 

`Dispelk9@server:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example$ ./main -v
listen tcp 127.0.0.1:6060: bind: address already in use
listen udp 127.0.0.1:6121: bind: address already in use`

but when I run main of client on client node, it shows nothing. 

`Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ls
cover.out  main  main.go
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ./main
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ps -a
  PID TTY          TIME CMD
 3150 pts/0    00:00:00 bash
 3215 pts/0    00:00:00 ps
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ `

thanks for your help, I hope we get some kind of tutorial soon.

**Comment by marten-seemann** [comment]
> Dispelk9@server:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example$ ./main -v listen tcp 127.0.0.1:6060: bind: address already in use listen udp 127.0.0.1:6121: bind: address already in use

The error message says it all. You can't bind more than one process to one port.

**Comment by Dispelk9** [comment]
Thanks for your help, so I have binded one one process to one port.
```
Dispelk9@server:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example$ ./main -v
server Listening for udp connections on 127.0.0.1:6121
```

However I found nothing on client side.

**Comment by marten-seemann** [comment]
What do you mean, you don't find anything on the client side?

**Comment by Dispelk9** [comment]
```
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ls
cover.out  main  main.go
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ./cover.out
bash: ./cover.out: Permission denied
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ls
cover.out  main  main.go
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ./main
Dispelk9@client:~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/example/client$ ps -a
  PID TTY          TIME CMD
 3150 pts/0    00:00:00 bash
 3215 pts/0    00:00:00 ps

```

I used another computer with main.go in client example. Both machines are in same network. But when I run the built file. It shown nothing, so I check the processes, and task main is running.
