### ISSUE TITLE
request cancelations for H3 request in the client

### ISSUE THREAD

**Issue by spacewander** [lucas-clemente/quic-go#1998]
With the `RoundTripper` provided in this library, `http.Client`'s `Timeout` field doesn't take effect by default.
After reading https://github.com/lucas-clemente/quic-go/pull/1172, I figured out that we need to manually assign a context to the request, for example:

```go
        hclient := &http.Client{
                Transport: roundTripper,
        }

        req, err := http.NewRequest("GET", address, nil)
        if timeout > 0 {
                ctx, cancel := context.WithTimeout(context.Background(), timeout)
                defer cancel()
                req = req.WithContext(ctx)
        }

        resp, err := hclient.Do(req)
```

Although this trick works with release 0.11.2, it doesn't work with the code from the master branch. The `http3` package is quite different from the `h2quic` package in the latest release.

**Comment by spacewander** [comment]
It seems that #1172 doesn't fully support `Client.Timeout` field. That implementation doesn't take the response body reading time into account.

**Comment by marten-seemann** [comment]
It looks like we haven't implemented request cancelations yet in http3, in fact, we already have a TODO in the code: https://github.com/lucas-clemente/quic-go/blob/d42c954c816ca4325a9b0a4148a2aaa8af26348e/http3/client.go#L125-L126

I'm currently busy with other stuff, but I'd appreciate a PR, if you want to contribute some code for this.

**Comment by spacewander** [comment]
@marten-seemann 
Currently, I am busy with my work, too. I will dive into the internal and maybe find a solution once I have enough spare time.
