### ISSUE TITLE
values of server_parameters.go should can pass from config

### ISSUE THREAD

**Issue by jinleileiking** [lucas-clemente/quic-go#1999]
like `ReceiveStreamFlowControlWindow` is hardcoded? 

What about passed by config?

**Comment by marten-seemann** [comment]
You can set maximum flow control windows via the `quic.Config`, see https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L175.
quic-go automatically tunes the actual flow control window based on the BDP of the connection.

Is this sufficient for your use case?

**Comment by jinleileiking** [comment]
But consts in server_parameters.go cannot change by config.
