### ISSUE TITLE
Are the client applications which use quic-go?

### ISSUE THREAD

**Issue by halbaka** [lucas-clemente/quic-go#2005]
Hi, 
sorry for misusing the issue functionality, but I don't know any other place for asking questions about quic-go.

My question is:
I know that for server applications there is caddy which implements quic-go.
But are there client applications which already make use of quic-go (beside of the applications in the  example folder)? 

Thanks

**Comment by marten-seemann** [comment]
quic-go is used by a quite a few projects, but since it's open-source software, I don't have a comprehensive list.
For example, it is powering QUIC support in [libp2p](https://libp2p.io/).
