### ISSUE TITLE
Decrypt payload in WireShark using KeyLogWriter

### ISSUE THREAD

**Issue by klaasel** [lucas-clemente/quic-go#2011]
When inspecting quic-go traffic with WireShark between my client (Go client bridged in a React Native Android app) and a quic-go http3 server (Windows VM, Azure), I see Initial, handshake and protected payload packets captured with their CID's, but a lot of header information (Version a.o.) and payload is unknown and/or encrypted. I would like to decrypt the payload, to see what is actually sent.

I was wondering if there is an option in quic-go to export session keys like done [here](https://golang.org/pkg/crypto/tls/#example_Config_keyLogWriter) with TLS, but then with QUIC. That is, assuming the KeyLogWriter in the tlsConfig of the transport is only suited for TLS.

![Screenshot 2019-07-20 at 13 23 26](https://user-images.githubusercontent.com/23315758/61578099-b90d2f00-aaf1-11e9-9857-2372338234a5.png)

**Comment by marten-seemann** [comment]
I just merged #2003. Can you please check again?

**Comment by Lekensteyn** [comment]
Even though quic-go uses its own qtls library, it is based on crypto/tls and configuring the KeyLogWriter callback should work. quic-go seems to use an "AlternativeRecordLayer" option to receive keys, but in handshake_client_tls13.go, the original keys are still written to the KeyLogWriter callback.

**Comment by klaasel** [comment]
@marten-seemann thanks, there is now more information about headers and handshake protocol. @Lekensteyn thanks for checking that out, I'll go try implement the KeyLogWriter callback

**Comment by marten-seemann** [comment]
@klaasel Did you succeed using the KeyLogWriter or do we have an actual bug here?

**Comment by marten-seemann** [comment]
I believe this should work, feel free to reopen if it doesn't.

**Comment by klaasel** [comment]
I successfully used the KeylogWriter to write secrets, but still I can't decrypt the payload. There is some more information, especially at the start of the connection. Attached are the .pcapng and the client secrets for your information. I'm using Wireshark 3.1.1rc0-215-gbb7b35963508

[Master secret log.txt](https://github.com/lucas-clemente/quic-go/files/3547830/Master.secret.log.txt)

[19 aug 2019 - 001.pcapng.zip](https://github.com/lucas-clemente/quic-go/files/3547836/19.aug.2019.-.001.pcapng.zip)

**Comment by Lekensteyn** [comment]
I found a bug in Wireshark with respect to handling initial packets after retry packets. There is no need to reopen this quic-go bug as quic-go is working normally. I'll get back to you later when I have more details.

**Comment by klaasel** [comment]
FYI, I successfully got this working with (a lot of) help of @Lekensteyn . Take care you might need to ignore some packets in the capture, in my case there were 3 initial packets and corresponding retries, where 2 were redundant.

**Comment by cmgl** [comment]
@klaasel Could you please post your solution? Thank you.

**Comment by Lekensteyn** [comment]
@cmgl What exactly are you looking for? Obtaining a packet capture and decryption secrets? See https://github.com/lucas-clemente/quic-go/issues/2123

**Comment by klaasel** [comment]
@cmgl take a look at https://github.com/klaasel/irmago/commit/1796d86aee31d225391cb6e1aae6328724b1c3e7 for my implementation in our research project, which is almost a 1:1 copy of the Golang documentation. This will generate a txt file with the TLS 1.3 secrets. Get a recent version of Wireshark on https://www.wireshark.org/download/automated/ and startup Wireshark with the following command:

wireshark -otls.keylog_file:"<name of txt file>" -r "<name of pcapng file>" -Y udp -dudp.port==<port of your QUIC server>,quic -Y quic

credits to @Lekensteyn
