### ISSUE TITLE
add function to get destination connection id to session

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#2014]
To debug application using quic-go you really need to know the dstID. 
Other use case is comparing are two sessions the same.
One way is log it with %v or use reflect to get it.

btw: what is the purpose of config.ConnectionIDLength ?

**Comment by marten-seemann** [comment]
What would you use that debugging information for?
Why would you want to compare if two sessions are the same? Since destination connection IDs can change, using DCID for that purpose would be inherently racy.

**Comment by apmattil** [comment]
e.g I need to check when I can close the session (after all streams are closed) and no new streams are created e.g 1 min. To debug this I need to log what session was in question when stream was closed.

DCID change is not a problem, If I compare array of sessions against one session, ID just needs to be same.

using quic-go env variable logging is really not option, they log too much and not to my logger.

**Comment by marten-seemann** [comment]
I'm not sure I understand how the DCID would help you here. It should be easy to track which stream belongs to which session. Exposing protocol internals doesn't seem to be the right way to go.

**Comment by apmattil** [comment]
my use case:

1. one go routine is handling one stream
2. this go routine gets Timeout() error, "deadline exceeded" or "no recent network activity"
3. this go routine asks 'session-handler'-goroutine to remake the session and get's new connection that uses newly created session
4. for debug which goroutines are using old session-connection and which already got the new session-connection I would like log DCID
5. when all go routines using old-session are updated I can stop the old session-handler  

at point 4 in case of some other error (non quic-go) or signal occured, I need to know was the go routine using old or new session, so I know can it decrement correct stream ref-count. I know ..I could do this with 'renewed-session counter' etc.

for point 5 the uni/bi-streammaps hold the information already how many sessions are at any given time, so I would not need my own stream-ref counter.. e.g session.ActiveBiStreams()

Why I do not just start new go routine with with new-session+stream and let the old routine just exit ?
I need to keep the other end (tcp) connection open.
(yes, I could store it at session handler.)

**Comment by marten-seemann** [comment]
There should never be a situation where you need to keep track of streams belonging to two different connections to the same server:
- When you get a "deadline exceeded" error from the stream, you can just set a new deadline. Deadlines are purely local operations, and expiration doesn't prevent you from using the stream, if you reset the deadline appropriately.
- "No recent network activity" means that the *connection* timed out, so all streams belonging to this connection will experience this error at the same time.

On a higher level, I don't think it's the role of an API to expose protocol internals such as connection IDs. Furthermore, as I mentioned before, since connection IDs change frequently over the lifetime of a connection (although quic-go only partly implements that currently), they are a very poor fit for uniquely identifying a session.

**Comment by apmattil** [comment]
well I actually need keep track of go routines using the session.

Ok, I will implement some other means to track the sessions.

about  "deadline exceeded" / "No recent network activity" 
pseudo code:
```
if err.Timeout() {
  if err.Error() == "deadline exceeded" {
    // set new deadline
  } else if err.Error() == "No recent network activity"  {
    // session broken, 'session-handler ' needs to wait all stream handling go routines to exit
    return
} else if err.Error() == "NO_ERROR" {
   // stream closed, return
} else if err != io.EOF{
   // session broken, 'session-handler ' needs to wait all stream handling go routines to exit
   return
}
```
other timeout is recoverable error other is not.. yes they are both timeout errors at API respect, but it means app needs to parse error string.
how about making const errors for the timeout case ?

**Comment by marten-seemann** [comment]
Error codes are not guaranteed to be stable, and we won’t make them part of our API.

Your code is incorrect, a stream that is closed returns io.EOF, not NO_ERROR. 
 
==================
WARNING: DATA RACE
Read at 0x00c0001d0000 by goroutine 25:
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*baseFlowController).sendWindowSize()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/internal/flowcontrol/base_flow_controller.go:60 +0x51
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*connectionFlowController).SendWindowSize()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/internal/flowcontrol/connection_flow_controller.go:42 +0x4d
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*streamFlowController).SendWindowSize()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/internal/flowcontrol/stream_flow_controller.go:110 +0x96
  github.com/lucas-clemente/quic-go.(*sendStream).Write()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/send_stream.go:98 +0x588
  github.com/lucas-clemente/quic-go.(*stream).Write()
      <autogenerated>:1 +0xcf
  NGN/common/sm-quic-conn.(*Conn).Write()
      /home/go/src/NGN/common/sm-quic-conn/conn.go:311 +0x101
  NGN/common/sm-conn.SendSMHeader()
      /home/go/src/NGN/common/sm-conn/sm-conn.go:165 +0x55a
  NGN/common/sm-conn.SMhandshake()
      /home/go/src/NGN/common/sm-conn/sm-conn.go:224 +0x1a1
  main.forwardConnection()
      /home/go/src/NGN/cmd/client/client.go:319 +0xbd2

Previous write at 0x00c0001d0000 by goroutine 15:
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*baseFlowController).AddBytesSent()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/internal/flowcontrol/base_flow_controller.go:46 +0x79
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*connectionFlowController).AddBytesSent()
      <autogenerated>:1 +0x61
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*streamFlowController).AddBytesSent()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/internal/flowcontrol/stream_flow_controller.go:106 +0xa6
  github.com/lucas-clemente/quic-go.(*sendStream).getDataForWriting()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/send_stream.go:232 +0x55e
  github.com/lucas-clemente/quic-go.(*sendStream).popStreamFrameImpl()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/send_stream.go:178 +0x366
  github.com/lucas-clemente/quic-go.(*sendStream).popStreamFrame()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/send_stream.go:155 +0xa9                                                                     
  github.com/lucas-clemente/quic-go.(*stream).popStreamFrame()                                                                                                   
      <autogenerated>:1 +0x86
  github.com/lucas-clemente/quic-go.(*framerI).AppendStreamFrames()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/framer.go:95 +0x44d
  github.com/lucas-clemente/quic-go.(*packetPacker).composeNextPacket()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/packet_packer.go:349 +0x5b3
  github.com/lucas-clemente/quic-go.(*packetPacker).PackPacket()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/packet_packer.go:264 +0x3cd
  github.com/lucas-clemente/quic-go.(*session).sendPacket()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/session.go:1105 +0x22b
  github.com/lucas-clemente/quic-go.(*session).sendPackets()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/session.go:1013 +0x6f4
  github.com/lucas-clemente/quic-go.(*session).run()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/session.go:426 +0x1688
  github.com/lucas-clemente/quic-go.(*client).establishSecureConnection.func1()
      /home/go/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.2/client.go:269 +0x85

Goroutine 25 (running) created at:
  main.XXX()
      XXX/client.go:250 +0x79f
  main.clientMain()
      XXX/client.go:168 +0x6a8
  main.(*program).Run()
      XXX/client.go:569 +0x139

**Comment by apmattil** [comment]
How can I filter out deadline without parsing error message ?

I understand you do not wanto fix the error codes to have flexibility to change them later, but users do need to take different actions based on the error.
other example: server responses "max streams", client could  close not so important streams and retry.

**Comment by marten-seemann** [comment]
> How can I filter out deadline without parsing error message ?

```go
if err == context.DeadlineExceeded {
   ...
} 
```

**Comment by apmattil** [comment]
my version (go go1.12.6 ) of context deadline is :
func (deadlineExceededError) Error() string   { return "context deadline
exceeded" }
quic-go returns 0.11.2 :
func (deadlineError) Error() string   { return "deadline exceeded" }

**Comment by marten-seemann** [comment]
You're right, https://github.com/lucas-clemente/quic-go/issues/2014#issuecomment-515830697 is wrong. This is not a context deadline, so comparing against `context.DeadlineExceeded` won't work.

**Comment by apmattil** [comment]
I'm trying to be constructive, just telling my view how to improve the quic-go, not to annoy you about minor issues.

I'm trying to recover from different kind of errors, when you try to recover from errors you need to know the reason, then you can decide can you do anything about it.

correct if I'm wrong but e.g net API's read/write/accept(/dial) have SetDeadline() when that triggers we get Timeout(), and only then.

The case is as with EOF, we do not get "End Of FIle", since it is not real error we have io.EOF (what should be const not variable).
In my opinion the same case is when read-deadline expires.. it is not really error.

As for "max streams" error, that could be temporary.. but only that or have a const error.

error documentation could be better, like I did not know the "no recent network activity" applies to the whole session.. some separation between stream and session errors.. if there is any.
