### ISSUE TITLE
examples should not use internal packages

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#2015]
as title says examples should not use internal packages.

or should we use vendoring at go.mod ?

**Comment by marten-seemann** [comment]
It's just using the internal package for logging and for getting a certificate. I don't see a problem here.

**Comment by apmattil** [comment]
as I pointed out at issue #2014, debug logging is important.
This just points it out.

**Comment by jinleileiking** [comment]
See my example.

**Comment by jinleileiking** [comment]
https://github.com/jinleileiking/quic-go-example

**Comment by jinleileiking** [comment]
@apmattil

**Comment by apmattil** [comment]
great, now we just need to get it to quic-go as example..it is the first place first timer will look at.

This example shows one of my problem, how do you know was the network problem with a stream or whole session ! 
should we have external counter how many active streams and when all of them get 'no network activity' we know whole session is broken ?
(old version had 'peer going away' error)

please add deadline to sever read and then you see you need to parse error cause.

**Comment by marten-seemann** [comment]
As described in #2014, you never need to parse error codes. They *only* exist for logging purposes.
