### ISSUE TITLE
[question] Why does gquic stream id 3 does not contributes to flow control?

### ISSUE THREAD

**Issue by jinleileiking** [lucas-clemente/quic-go#2016]
In gquic branch:

```
  // StreamContributesToConnectionFlowControl says if a stream contributes to connection-level flow control
  func (vn VersionNumber) StreamContributesToConnectionFlowControl(id StreamID) bool {
      if id == vn.CryptoStreamID() {
          return false
      }
      if vn.isGQUIC() && id == 3 {
          return false
      }
      return true
  }
```

I do not why stream id 3 is so extraordinary? Could you guru give me a quick answer ? Thanks a lot

**Comment by jinleileiking** [comment]
https://github.com/lucas-clemente/quic-go/issues/923

**Comment by jinleileiking** [comment]
https://github.com/lucas-clemente/quic-go/pull/928/commits/1f644debd4b26bd812b83838e6d1b24ac083f2d1

**Comment by marten-seemann** [comment]
Please have a look at the Google QUIC specification.

**Comment by jinleileiking** [comment]
When using HTTP/2 over QUIC, Stream 3 is reserved for transmitting compressed headers for all other streams, ensuring reliable in-order delivery and processing of headers.

**Comment by jinleileiking** [comment]
If it is not HTTP/2 over Quic, should 3 contributes to connection flow control?

**Comment by jinleileiking** [comment]
@marten-seemann

**Comment by dista** [comment]
we use lsquic as client(not http/2 over quic), client stucks because of this
