### ISSUE TITLE
sender sending wire.StopWaitingFrame with wrong LeastUnacked number

### ISSUE THREAD

**Issue by youjujun** [lucas-clemente/quic-go#2019]
I found that the Sender's StopWaiting Frame is Not follow the document in 
https://tools.ietf.org/html/draft-tsvwg-quic-protocol-02, which wrote in page25:
```
The resulting least unacked is the
      smallest packet number of any packet for which the sender is still
      awaiting an ack.  If the receiver is missing any packets smaller
      than this value, the receiver should consider those packets to be
      irrecoverably lost.
```
I think the StopWaitingFrame 's unacked number means that the receiver should take certain measures for all unreceived packets smaller than this value.  
So that the StopWaitingFrame's unacked number should be the value that the sender has not been confirmed for a long time.
but in quic-go v0.10.2, I found that the least unacked number is too big. even bigger than the largeset ACK number! there are logs:
```
### quic.txt is what quic-go logged.
grep -rn "<- &wire.AckFrame\|StopWaitingFrame" quic.txt > tmp.txt

cat tmp.txt

quic.txt:195017:2019/7/22 18:46:19 server   <- &wire.AckFrame{LargestAcked: 0xe6c, LowestAcked: 0xe69, DelayTime: 6.32ms}
quic.txt:195039:2019/7/22 18:46:19 server   -> &wire.StopWaitingFrame{LeastUnacked: 0xe6d, PacketNumberLen: 0x2}

I see that StopWaitingFrame LeastUnacked is too big
```

In fact, I found the code in quic-go/internal/ackhandler/stop_waiting_manager.go:
```
func (s *stopWaitingManager) GetStopWaitingFrame(force bool) *wire.StopWaitingFrame {
	if s.nextLeastUnacked <= s.largestLeastUnackedSent {
		if force {
			return s.lastStopWaitingFrame
		}
		return nil
	}

	s.largestLeastUnackedSent = s.nextLeastUnacked
	swf := &wire.StopWaitingFrame{
		LeastUnacked: s.nextLeastUnacked,
	}
	s.lastStopWaitingFrame = swf
	return swf
}

func (s *stopWaitingManager) ReceivedAck(ack *wire.AckFrame) {
	largestAcked := ack.LargestAcked()
	if largestAcked >= s.nextLeastUnacked {
		s.nextLeastUnacked = largestAcked + 1// this will lead StopWaitingFrame's LeastUnacked too big.
	}
}
```

**Comment by marten-seemann** [comment]
If all packets up to `n` are acknowledged, then the smallest packet number we're expecting an acknowledgement for is `n+1`, so I believe that the code is exactly doing what it should.

Please also note that https://tools.ietf.org/html/draft-tsvwg-quic-protocol-02 is not the right specification to refer to. The wire spec for gQUIC can be found here: https://docs.google.com/document/d/1WJvyZflAO2pq77yOLbp9NsGjC1CHetAXV8I0fQe-B_U/edit.
