### ISSUE TITLE
[question or bug] blocked by flow control if sending massive data using stream 3 bidirectional.

### ISSUE THREAD

**Issue by jinleileiking** [lucas-clemente/quic-go#2025]
Using `https://github.com/jinleileiking/quic-go-example` for test

Server: `./quic-go-example` (enable echo)

Client: ` ./quic-go-example -t client -r -rlen 70000  -c 1`  (Sending 70k bytes, and echo)

System will hang, the logs were:

```
 ``

**Comment by jinleileiking** [comment]
@marten-seemann I did  paste the log. Any ideas?

**Comment by jinleileiking** [comment]
[server.log](https://github.com/lucas-clemente/quic-go/files/3441618/server.log)
[client.log](https://github.com/lucas-clemente/quic-go/files/3441619/client.log)

**Comment by jinleileiking** [comment]
@tandf Could  you give a glance ?Thanks

**Comment by tandf** [comment]
It seems the stream is blocked, and the server doesn't send MAX_STREAM_DATA to offer more space after ByteOffset 0xf2d4. I'm not very familiar with go and therefore can't offer any help with your code.

There is something I don't understand. In the log you offered, the stream on which you send data has an ID of 0x3. However that indicates the stream is a server-Initiated unidirectional one (see the [draft](https://tools.ietf.org/html/draft-ietf-quic-transport-22#section-2.1)), and the client shouldn't be allowed to send data on it. Is there anything I missed?

**Comment by jinleileiking** [comment]
@tandf  Thanks. This problem is solved. See https://github.com/lucas-clemente/quic-go/issues/2031. 
For the 0x3 problem, I am using gquic. What you said is ietf quic 😄
