### ISSUE TITLE
Slow upload speed

### ISSUE THREAD

**Issue by cgCodeLife** [lucas-clemente/quic-go#2027]
When I upload 11 MB file found in the network good quic upload half is more time-consuming than HTTPS / 1.1, if the control packet loss rate of not less than 10% of the time quic performance will be better than HTTPS / 1.1 nearly half, another scene, I download quic time-consuming when network is good or bad are better than HTTPS / 1.1 want to ask is why

**Comment by marten-seemann** [comment]
The performance depends on the network conditions. We're currently benchmarking quic-go, so you can expect performance improvements in the future.
