### ISSUE TITLE
Handle WINDOW_UPDATEs for unknown streams properly

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#203]
We should decide whether we want to support WINDOWS_UPDATEs on unknown streams, which might e.g. appear when a client sends a WINDOW_UPDATE immediately after opening a stream and packets get reordered.

**Comment by marten-seemann** [comment]
@lucas-clemente: I think we discussed this before.

As far as I remember, we agreed to just open the new stream in that case, didn't we?

**Comment by lucas-clemente** [comment]
Yep, iirc.
