### ISSUE TITLE
If io read and write is synchronize, the program will block

### ISSUE THREAD

**Issue by jinleileiking** [lucas-clemente/quic-go#2031]
The test program is: https://github.com/jinleileiking/quic-go-example

commit : 69ae1404b151667da940242a818f55b39765e266

The key code are:
```
n, err = io.Copy(loggingWriter{stream}, stream)¬
```

Or using read, write:

```
| ! 120 ▸   ▸   ▸   ▸   for {¬
| + 121 ▸   ▸   ▸   ▸   ▸   log.Error("-----------------------------Read-------------------\n")¬
| + 122 ▸   ▸   ▸   ▸   ▸   if n, err = io.ReadFull(stream, buf); err != nil {¬
| + 123 ▸   ▸   ▸   ▸   ▸   ▸   log.Errorf("io.Read error %s\n", err.Error())¬
| + 124 ▸   ▸   ▸   ▸   ▸   }¬
| + 125 ▸   ▸   ▸   ▸   ▸   log.Errorf("-----------------------------Read %d bytes------done\n", n)¬
| + 126 ▸   ▸   ▸   ▸   ▸   var writeBytes int¬
| + 127 ▸   ▸   ▸   ▸   ▸   log.Error("-----------------------------Write-------------------\n")¬
| + 128 ▸   ▸   ▸   ▸   ▸   writeBytes, err = stream.Write(buf)¬
| + 129 ▸   ▸   ▸   ▸   ▸   if err != nil {¬
| + 130 ▸   ▸   ▸   ▸   ▸   ▸   log.Error("stream.Write failed")¬
| + 131 ▸   ▸   ▸   ▸   ▸   }¬
| + 132 ▸   ▸   ▸   ▸   ▸   log.Error("-------------------------write Done, bytes:", writeBytes)¬
|   133 ▸   ▸   ▸   ▸   }¬
```

The problem is:

Prerequisite:  echo lots of data(70000). 

In some case, The sending window will full, but the code is hang at `write` call. But adding the sending window is depend on call `read`. 

When this case came out, the sender will hang.

So, if you are using quic-go(gquic), it will be dangerous using `io.Copy` or `io.Read` and `io.Write`  synchronize. The better solution is using two goroutine, one for read, one for write.

OR:

When receive stream frame, updating the window which is not depending on calling `read`?

The ok version is uploaded: c7ac43e255d003660c0545b56429f7abe5e8aa02

**Comment by marten-seemann** [comment]
> So, if you are using quic-go(gquic), it will be dangerous using io.Copy or io.Read and io.Write synchronize. The better solution is using two goroutine, one for read, one for write.

That's essentially correct, if your copy buffer is roughly the same size as the flow control window. Using separate go routines for reading and writing or modifying the buffer size are both solutions that should work.

**Comment by jinleileiking** [comment]
Should this case  be optimized?
