### ISSUE TITLE
[Feature Request] Provide an asynchronous way to indicate the stream is deleted

### ISSUE THREAD

**Issue by spacewander** [lucas-clemente/quic-go#2048]
When I tried to add request cancellation for H3 request(https://github.com/lucas-clemente/quic-go/issues/1998), it seems that there is no way to know if a stream is deleted asynchronously.
The `Stream.Context().Done()` doesn't work because it is triggered when the write side is closed. However, the read side may keep opening.

An alternative is to signal the read side is closed when read `responseBody` failed or it is closed. However, if the caller ignore the body, the signal will not be delivered. Therefore I think it would be better to solve the problem in the low level.

Maybe we can provide a new method in the `Stream` interface, which works like `Context().Done` but only called when the stream is deleted from the session?

**Comment by marten-seemann** [comment]
Why is this needed for #1998? Request canceling deals with the cancellation  of *the request's context*, doesn't it?

**Comment by spacewander** [comment]
In my plan to support request canceling, I need a goroutine waiting on either `request's context is canceled` or `request stream is done`. If the context is canceled, the goroutine cancels the request stream. If the stream is done before the context is canceled, the goroutine does nothing but exit.

It seems that currently there is no way to know if a stream is done (deleted from the stream map). If we don't have a way to signal the goroutine to leave, there will be goroutine leaked.

**Comment by marten-seemann** [comment]
Why can't you hook into the `request.Body.Read` method?

**Comment by spacewander** [comment]
If the caller doesn't read the `request.Body`, the signal will not be triggered and delivered, which will cause the goroutine to leak.

**Comment by marten-seemann** [comment]
Right. 

> When I tried to add request cancellation for H3 request(#1998), it seems that there is no way to know if a stream is deleted asynchronously.

Streams are not deleted before they haven't completely been read from (or canceled).

**Comment by spacewander** [comment]
> Streams are not deleted before they haven't completely been read from (or canceled).

I agree with you.
But a stream is read by the library is sometimes different from is read by the caller.

For example, assumed the request stream receives a RST frame from the remote, it will be deleted if the write side is already closed. However, until the caller calls `Read` or `Close` on the `request.Body`, she doesn't know if the underlying stream is already deleted or not.

The observation (caller calls `Read` or `Close`) is always happened after the fact (the read side of the request stream is closed). And sometimes the observation doesn't happen at all. If the code can act according to the fact instead of the observation, it can be more precise.

Providing a signal when the stream is deleted also have another benefit: now we only need to signal the event in one single place (maybe need some extra forwarding) instead of `Read`, `Close` and other methods which might be added in the future.

**Comment by spacewander** [comment]
An alternative way to implement request cancellation without leaking goroutine is only check the cancellation in the `responseBody.Read` method. Because it doesn't create a separate goroutine, there is not risk to leak any goroutine. As a downside, the cancellation will be delayed until `responseBody.Read` is called. However, I think this solution can cover the majority cases.
