### ISSUE TITLE
panic: qtls.ConnectionState not compatible with tls.ConnectionState

### ISSUE THREAD

**Issue by smtlzh1017** [lucas-clemente/quic-go#2060]
Look forward to your reply。when i start a program, it shows:
panic: qtls.ConnectionState not compatible with tls.ConnectionState
goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.0()
        /home/lizh/go/src/github.com/lucas-clemente/quic-go/internal/handshake/unsafe.go:17 +0x12f

**Comment by marten-seemann** [comment]
Which Go version are you using?

**Comment by smtlzh1017** [comment]
> Which Go version are you using?

1.10.4

**Comment by marten-seemann** [comment]
As the [README](https://github.com/lucas-clemente/quic-go/blob/master/README.md) says:

> We currently support Go 1.12+, with Go modules support enabled.

**Comment by smtlzh1017** [comment]
> As the [README](https://github.com/lucas-clemente/quic-go/blob/master/README.md) says:
> 
> > We currently support Go 1.12+, with Go modules support enabled.

ok，i'll try it. thank you
