### ISSUE TITLE
get pkg error:key_schedule.go:40:9: undefined: hkdf.Extract

### ISSUE THREAD

**Issue by blusewang** [lucas-clemente/quic-go#2063]
```
go get github.com/lucas-clemente/quic-go
# github.com/marten-seemann/qtls
.go/src/github.com/marten-seemann/qtls/key_schedule.go:40:9: undefined: hkdf.Extract
.go/src/github.com/marten-seemann/qtls/key_schedule.go:59:12: undefined: hkdf.Expand
```
what's going on?

**Comment by marten-seemann** [comment]
As the readme says:
> We currently support Go 1.12+, with Go modules support enabled.

**Comment by blusewang** [comment]
```
go version
go version go1.12.6 darwin/amd64
```

**Comment by coral** [comment]
@marten-seemann Having the same issue, the Readme now says "We currently support Go 1.13+"

I'm running go version go1.13.1 darwin/amd64

Getting

`
go get
# github.com/marten-seemann/qtls
../../marten-seemann/qtls/key_schedule.go:41:9: undefined: hkdf.Extract
../../marten-seemann/qtls/key_schedule.go:60:12: undefined: hkdf.Expand
`

**Comment by coral** [comment]
# NEVER MIND

if anyone else runs into this
just refresh your golang.org crypto package

i'm stupid
sorry @marten-seemann
