### ISSUE TITLE
Handshake did not complete in time

### ISSUE THREAD

**Issue by linyongzuo** [lucas-clemente/quic-go#2093]
`for i := 0; i < 10000; i++ {
_, err := quic.DialAddr(global.Config.ServerAddress, &tls.Config{
			InsecureSkipVerify: true, NextProtos: []string{"quic"}}, nil)
		if err != nil {
			continue
		}
}`
i run a text compare to tcp net.Dial and found some problems. quic.DialAddr cost much more time than tcp net.Dial, and quic.DialAddr often failed with error Handshake did not complete in time

**Comment by linyongzuo** [comment]
i run the test On the same machine

**Comment by marten-seemann** [comment]
Of course it takes more time. You’re comparing an unencrypted TCP connections with a fully encrypted QUIC connection.

**Comment by manjiewang** [comment]
quic.DialAddr often failed with error Handshake did not complete in time
