### ISSUE TITLE
Use quic-go with a Golang ReverseProxy

### ISSUE THREAD

**Issue by klaasel** [lucas-clemente/quic-go#2110]
As described in #1996 , I'm unsuccessfully trying to connect to a non-QUIC server with a Java application on Tomcat on a Linux VM with an Android app client using quic-go's http3.RoundTripper as transport. 

As a workaround, I'm investigating the possibility to implement a Golang reverse proxy on that VM, which passes the messages on to the Java application, see [https://golang.org/pkg/net/http/httputil/#ReverseProxy](url)

Do you think this can be pulled off at all currently? My guess would be to spin up a server http3.ListenAndServe() with a proxy as a handler (?)

Would one need to assign the http3.RoundTripper to the ReverseProxy's Transport? I don't think so, as that would be the transport from ReverseProxy to the Java application I guess. If it behaves like the http3.RoundTripper in the client, it would be unable to connect with the local Java application, so in essence moving the problem from the Android app client to the ReverseProxy.

**Comment by ironsteel** [comment]
Yup that's what I've also done but using the old gquic branch of quic-go. 
See this project for a kickstart: https://github.com/fholzer/go-quic-reverse-proxy

I've basically set the ReverseProxy as the handler to the h2quic.Server.

**Comment by marten-seemann** [comment]
@klaasel Did @ironsteel's answer resolve your issue?

**Comment by klaasel** [comment]
@marten-seemann I didn't look at the implementation yet, but this seems like a good pointer. I'll close the issue. Thanks for the heads up.
