### ISSUE TITLE
HTTP/3 server fails to connect with http3check.net

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#2131]
I stood up a public HTTP/3 endpoint just to see how it works, but i can't get it to negotiate a successful connection with http3check.net.

Do you know why this might be failing? https://www.http3check.net/?host=matt.life

You can click that link, but here's the qlog output anyway:

```
{
  "qlog_version": "0.1",
  "connections": [
    {
      "events": [
        [
          0,
          "CONNECTIVITY",
          "NEW_CONNECTION",
          "LINE",
          {
            "dstip": "138.68.63.103",
            "ip_version": "4",
            "srcport": "41086",
            "dstport": "443",
            "srcip": "0.0.0.0"
          }
        ],
        [
          430,
          "CONNECTIVITY",
          "VERNEG",
          "LINE",
          {
            "proposed_version": "FAFAFAFA"
          }
        ]
      ],
      "connectionid": "8B2A6FEE4625202E",
      "qlog_version": "0.1",
      "vantagepoint": "NETWORK",
      "starttime": 30190842806221,
      "fields": [
        "time",
        "category",
        "type",
        "trigger",
        "data"
      ]
    }
  ],
  "description": "matt.life"
}
```

It looks like it tried to negotiate version 1363628031.

Using the example client built into this library works:

```
$ go run main.go --insecure https://matt.life
```

But I need to specify `--insecure`, even though I'm using a publicly-trusted Let's Encrypt cert.

Thanks for any help!

**Comment by marten-seemann** [comment]
It looks like version negotiation failed. I guess that's because you didn't include one of the tagged versions.
In the master branch, we're using an experimental version number, since we don't want to guarantee any interoperability as new features and wire changes are added. Only the tagged releases use the official draft version numbers.
We'll release draft-23 soon-ish (I definitely want to get #2045 into that release), if you want, I can create a PR for Caddy then.

**Comment by mholt** [comment]
Ah, you're right, I had forgotten that about the tagged releases. Thanks, sorry about that!

> if you want, I can create a PR for Caddy then.

I would love that! I imagine it'd just be an update to go.mod and go.sum right? Either way, please do!

**Comment by marten-seemann** [comment]
> I would love that! I imagine it'd just be an update to go.mod and go.sum right? Either way, please do!

That's right, there weren't any API changes for HTTP/3. The next release will contain a bunch of HTTP/3 improvements, and the next version would be the first one I would feel comfortable deploying publicly (as an experiment).

**Comment by mholt** [comment]
After deploying caddy 2 with the latest tagged version of quic-go, I'm still experiencing problems unfortunately. This is in my go.mod when I built Caddy:

```
github.com/lucas-clemente/quic-go v0.13.0
```

https://www.http3check.net/?host=matt.life is no longer able to connect at all: 

But I do see the HTTP request from that site come in at my access logs. The response header seems correct (`h3-23=":443"; ma=2592000`).

You can test it out with https://matt.life.

The example client in this repo, also checked out at v0.13.0, is able to connect, but only if I use `--insecure`, like before. (The site does have a valid certificate.)

Incidentally, the site no longer serves HTTP/2 after serving a successful HTTP/3 response to the quic-go client. In other words, starting the server, then loading the site in my browser (loads over HTTP/2 just fine), then use the example client in this repo to do a successful HTTP/3 request and response, then close the browser profile (to clear cache and close connections) and open a new one and load the site again, uses HTTP/1.1. (Curl exhibits the same behavior as the browser here.) Any ideas why that might be happening?

**Comment by marten-seemann** [comment]
> * HTTP3Check can't connect to my site when it's serving HTTP/3, but the example client can

I wouldn't trust HTTP3Check too much here. It's powered by LiteSpeed, and who knows what's going wrong on their side. Let's stick to testing with Chrome, since it's currently the only client we care about.

> * Example client only connects when using --insecure, despite being built at the same tag

That was a bug in the example client (I forgot to add the system certs to the CA pool), which should be fixed in #2207. Nothing to worry about here, just continue using `--insecure` for now.

> * Site stops serving HTTP/2 after HTTP/3 is successfully served to a client

That's a very good question. How does Caddy do the upgrade to HTTP/2. Is it using Alt-Svc for that? Maybe quic-go is overwriting the Alt-Svc H2 upgrade header, so that the only options left are HTTP/1.1 and H3 then.

**Comment by mholt** [comment]
> I wouldn't trust HTTP3Check too much here. It's powered by LiteSpeed, and who knows what's going wrong on their side. Let's stick to testing with Chrome, since it's currently the only client we care about.

I was thinking it but didn't want to say it. :smile: Sounds good to me!

> That was a bug in the example client (I forgot to add the system certs to the CA pool), which should be fixed in #2207. Nothing to worry about here, just continue using --insecure for now.

Oh! Awesome, okay then. :)

> That's a very good question. How does Caddy do the upgrade to HTTP/2. Is it using Alt-Svc for that? Maybe quic-go is overwriting the Alt-Svc H2 upgrade header, so that the only options left are HTTP/1.1 and H3 then.

The standard lib does it for us. I believe `NextProtos` on the TLS config has "h2" which tells the client to start using HTTP/2 after the TLS handshake.

**Comment by marten-seemann** [comment]
> The standard lib does it for us. I believe NextProtos on the TLS config has "h2" which tells the client to start using HTTP/2 after the TLS handshake.

Right, it's not Alt-Svc. Apparently I forgot about ALPN for a moment.
quic-go is replacing the ALPN with H3:
https://github.com/lucas-clemente/quic-go/blob/914193cc9de381ed286b4938f9ebaa2f61edcaa1/http3/server.go#L107-L108
The reasoning behind this is that in the http3 package, it won't make any sense to negotiate anything other than H3. However, it seems (?) like clients are caching the ALPNs and using this to determine which protocol to use on subsequent connections. @mholt Does that make sense to you?

**Comment by mholt** [comment]
> However, it seems (?) like clients are caching the ALPNs and using this to determine which protocol to use on subsequent connections. @mholt Does that make sense to you?

Hmm, seems _unlikely_, since I'm using private browsing tabs to test. Private browsing / incognito doesn't use the cache and discards its cache when closed... or at least, it's supposed to. Oh, and it happens in curl too.

@marten-seemann I just restarted my server on matt.life, if you want to try it again. It's serving HTTP/2 currently.

**Comment by marten-seemann** [comment]
@mholt #2215 should fix the problem. Turns out that quic-go was replacing the ALPN tokens in the `tls.Config` returned by `GetConfigForClient`.

**Comment by mholt** [comment]
Nice!! Sure enough, it no longer drops to HTTP/1.1 after a successful HTTP/3 request. Thank you very much!
