### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by nullchinchilla** [lucas-clemente/quic-go#2135]
Right now `quic-go` consumes quite a lot of CPU when transferring data: my laptop cannot even saturate a 100 Mbps link. It seems like it consumes roughly 10x the CPU as [kcp-go](https://github.com/xtaci/kcp-go), another userspace reliable transport on top of UDP.

Why is this so? Is there some sort of huge performance bottleneck that needs to be fixed, or is it inherent to the design of QUIC?

**Comment by chengxuncc** [comment]
[pprof.samples.cpu.003.pb.gz](https://github.com/lucas-clemente/quic-go/files/3639025/pprof.samples.cpu.003.pb.gz)
```
Ping statistics for ...:
    Packets: Sent = 20, Received = 20, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 243ms, Maximum = 251ms, Average = 244ms
```

**Comment by marten-seemann** [comment]
Closing due to age.
