### ISSUE TITLE
Chrome Canary now supports HTTP/3

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#2146]
You probably know this already, but: https://twitter.com/programmingart/status/1174775953316294658

> Google Chrome Canary just became the first (available) browser to integrate (very) experimental #QUIC and HTTP/3 support! 
> 
> Add flags "--enable-quic --quic-version=h3-23" and you should see "http/2+quic/99" show up in the devtools, which is actually http3 in disguise!

I am looking forward to shipping this in one of the next Caddy 2 beta releases! 😃

**Comment by joeblew99** [comment]
so thats what the HTTP3 directory in this lib represents now ?
I thought  IQUIC was still very unstable ?

**Comment by marten-seemann** [comment]
@mholt That's great! We'll add draft-23 support with the next quic-go release soon.

**Comment by Henrocker** [comment]
I think this issue can now be closed :-)

![image](https://user-images.githubusercontent.com/15855905/68534360-fb25df00-0333-11ea-800d-0e95640623ef.png)

**Comment by mholt** [comment]
Thanks for testing it @Henrocker !
