### ISSUE TITLE
QUIC: can only serve 30M/s bandwidth output

### ISSUE THREAD

**Issue by xdown-org** [lucas-clemente/quic-go#2152]
```
config:
wellcdn.com:4433 {
root /data
tls /data/fullchain.pem /data/privkey.pem
}

testing:
./quicbench -rt quic -c 100 -d 10 -u https://wellcdn.com:4433/10m

bandwidth:
dstat -nf -N bond0
-net/bond0-
recv send
1260k 34M
1291k 33M
1279k 32M
1265k 32M
1259k 32M
1242k 32M
1234k 32M
1298k 32M
1335k 32M
1275k 32M
1305k 32M
```

Use the latest gquic branch.

Both server and client use Centos7. Two client machine and one server machine. 32G MEM,24 cores CPU, 1000Mbps bandwidth.

Yes,various parameters have been tested many times.

quicbench: https://github.com/cnkedao/quicbench

Testing Caddy's http2, the bandwidth result is 960 Mbps.

The maximum bandwidth of both machines is 1000Mbps.

**Comment by marten-seemann** [comment]
This issue is way too unspecific. This could be an issue with quicbench, the network conditions, or anything else.
