### ISSUE TITLE
Server-side call AcceptStream with context.Background() return NoError Immediate

### ISSUE THREAD

**Issue by bokuore** [lucas-clemente/quic-go#2153]
Thanks for this great project

I have a server-side QUIC session listening on UDP port with multiple streams.

Sometimes, when accepting stream after closing another, will immediately return a NO_ERROR

codes like this
```
		stream, err := tunnel.Session.AcceptStream(context.Background())
		if err != nil{
			log.Printf("[%s] tunnel closed for %s",  tunnel.ID, err.Error())
			service.notifyTunnelClose(tunnel.ID)
			return
		}

```
the client-side using OpenStream not OpenStreamSync

I think the err is set only when some errors occur, what causing this behavior or what should I do in this case, thank you.

**Comment by marten-seemann** [comment]
NO_ERROR is a connection-level error, which occurs when one of the peers closes the connection.

**Comment by bokuore** [comment]
> NO_ERROR is a connection-level error, which occurs when one of the peers closes the connection.

Thanks for reply

I've checked my codes, this is no explicit closing to the session or packetconn.

furthermore, the session is listening on UDP packet conn, and the UDP has no connection, maybe something about the QUIC session?

Is there some method could check whether the connection is closed by the client or server-side?

**Comment by bokuore** [comment]
Hi
I think the problem is solved
It is nothing to do with the Session and the stack, but I close a stream too earlier to cause this.
Is it safe to leave stream objects without explicit close?  (the underly connection already closed by a remote peer)
