### ISSUE TITLE
add network name to multiplexer's index

### ISSUE THREAD

**Issue by chengxuncc** [lucas-clemente/quic-go#2154]
When I use different datagram-based protocols at the same time, quic-go server will not response. It takes me long time to figure it out why, because I am using same listening address and port.
https://github.com/lucas-clemente/quic-go/blob/03ab56330b3e06c8a68f2576822d711d8dc1252e/multiplexer.go#L61
https://github.com/lucas-clemente/quic-go/blob/03ab56330b3e06c8a68f2576822d711d8dc1252e/multiplexer.go#L69
https://github.com/lucas-clemente/quic-go/blob/03ab56330b3e06c8a68f2576822d711d8dc1252e/multiplexer.go#L85
https://github.com/lucas-clemente/quic-go/blob/03ab56330b3e06c8a68f2576822d711d8dc1252e/multiplexer.go#L89

**Comment by marten-seemann** [comment]
There's no way to get the network name from a generic `net.PacketConn`.
Is that something you can solve by wrapping the `LocalAddr()` function to add the network name in your application?

**Comment by chengxuncc** [comment]
Sorry for misunderstanding code snippets, `laddr` is a string from `net.Addr.String()`.
```
	laddr := c.LocalAddr().String()
	p, ok := m.conns[laddr]
```
I did a modification:
```
	network := c.LocalAddr().Network()
	laddr := c.LocalAddr().String()
	connIndex := network + " " + laddr
	p, ok := m.conns[connIndex]
```

**Comment by marten-seemann** [comment]
You're right, `LocalAddr` returns a `net.Addr`, so you can't reasonably wrap this function to achieve this.

Your solution looks good to me. Would you mind sending us a PR?
