### ISSUE TITLE
Low bandwidth over high latency links

### ISSUE THREAD

**Issue by vincent-163** [lucas-clemente/quic-go#2155]
I used the following code snippet to simulate high latency (200ms):
```go
package qproxy

import (
        "net"
        "time"
)

type slowPacketConn struct {
        net.PacketConn
}

func (s slowPacketConn) WriteTo(p []byte, addr net.Addr) (int, error) {
        time.AfterFunc(time.Millisecond * 200, func() {
                s.PacketConn.WriteTo(p, addr)
        })
        return len(p), nil
}
```
I created a client and a server on localhost. The client makes a single QUIC session to the server, accepts TCP connections and forwards them as QUIC streams to the server. The server accepts streams, makes a TCP connection for each stream and forwards them to an upstream HTTP server. The HTTP server is an nginx instance on localhost too and hosts a file. So essentially the client/server pair proxies TCP connections and multiplex them in QUIC streams.

Then I used the browser to connect to the client (and thus to the nginx instance) and download a file. Without slowPacketConn on the client side, the speed stabilized around 9MB/s. When I used slowPacketConn on the client side, however, the speed slowly increased from 200KB/s to 700KB/s and stabilized. This represents a 13x drop.

I'm sure there are no bottlenecks elsewhere, like CPU or disk I/O.  Both MaxReceiveStreamFlowControlWindow and MaxReceiveConnectionFlowControlWindow has been raised to 64MB. While the experiment is done on localhost, the behavior is alike when the file is hosted on a server on the Internet, or when the client and the server are really 200ms away (i.e. the three components are not on localhost but actually separate computers on the Internet).

The test program is at https://github.com/vincent-163/quic-throughput. The results are (at 200ms latency):
<details>

```
starting client
0 bytes per second
0 bytes per second
46221 bytes per second
93412 bytes per second
451414 bytes per second
589824 bytes per second
131072 bytes per second
524288 bytes per second
945633 bytes per second
365087 bytes per second
1074259 bytes per second
1157634 bytes per second
1206554 bytes per second
755857 bytes per second
1426146 bytes per second
671006 bytes per second
1678506 bytes per second
1992733 bytes per second
524288 bytes per second
1426146 bytes per second
2243870 bytes per second
1426146 bytes per second
1717136 bytes per second
2099598 bytes per second
1426146 bytes per second
470982 bytes per second
2381057 bytes per second
964695 bytes per second
1048576 bytes per second
```
</details>

at 0ms latency:
<details>

```
starting client
120147056 bytes per second
120206224 bytes per second
119365516 bytes per second
120186909 bytes per second
119798585 bytes per second
118093426 bytes per second
119097004 bytes per second
116627427 bytes per second
116905470 bytes per second
110250819 bytes per second
114736615 bytes per second
112928135 bytes per second
115349455 bytes per second
109724330 bytes per second
115719510 bytes per second
108507038 bytes per second
115170987 bytes per second
114001091 bytes per second
112212115 bytes per second
116671146 bytes per second
115304497 bytes per second
110946353 bytes per second
114853059 bytes per second
105270320 bytes per second
102618405 bytes per second
111975570 bytes per second
112360253 bytes per second
115028944 bytes per second
114843452 bytes per second
```
</details>

**Comment by marten-seemann** [comment]
`time.AfterFunc` doesn't guarantee the ordering of events, so you're introducing massive amounts of packet reordering. Please use an actual network simulator for experiments like these, for example the [quic-network-simulator](https://github.com/marten-seemann/quic-network-simulator/).
