### ISSUE TITLE
Supporting multiple versions of Go

### ISSUE THREAD

**Issue by asim** [lucas-clemente/quic-go#2158]
Hi. Is it possible to support multiple versions of Go with this library? Our experience has been that it moved in lock step with certain versions of Go and even becomes protocol incompatible if not built with identical versions of dependencies. 

What's the best way to incrementally upgrade and make use of this library so we're protocol compatible on the wire and build compatible across dependencies and versions of Go?

**Comment by asim** [comment]
So people are forced into using the exact same version of dependencies and Go despite this being a network protocol? Does that not seem a bit strange?

**Comment by marten-seemann** [comment]
There's nothing strange here.
The wire protocol and the implementation are two completely separate things.
And specifying dependencies using `go.mod` ensure predictable and reproducible builds
