### ISSUE TITLE
Tag v0.12.0 was moved and became unusable with Go 1.13

### ISSUE THREAD

**Issue by zserge** [lucas-clemente/quic-go#2163]
I left a comment in the original issue #2129 but will also open a new one, so that it would get noticed.

Briefly: tag v0.12.0 was most likely moved from one commit to another, and official Go proxy has cached the old version, which now fails all checksum verifications.

**Comment by marten-seemann** [comment]
Thanks for researching this. I re-tagged the v0.12.0 release as v0.12.1.
