### ISSUE TITLE
GQUIC Q39 StreamContributesToConnectionFlowControl

### ISSUE THREAD

**Issue by everett1224** [lucas-clemente/quic-go#2198]
Hi. Resently I build my quic client with quic lib which cames from chromium 63.0.3239.150 and I also build a quic server with  lucas-clemente/quic-go gquic branch. The negotiation is version Q39 and client transmit data with stream id 3, but in file _gquic/internal/protocol/version.go_ we found that stream id 3 is not contribute to the connection flowcontrol,  after some time the client will send BLOCKED_FRAME becasue of the connection send_window has been consumed.

I check the Google QUIC specification (https://docs.google.com/document/d/1WJvyZflAO2pq77yOLbp9NsGjC1CHetAXV8I0fQe-B_U/edit). It said _When using HTTP/2 over QUIC, Stream 3 is reserved for transmitting compressed headers for all other streams, ensuring reliable in-order delivery and processing of headers._ . It seems like gquic/internal/protocol/version.go follows the protocol which chromium 63.0.3239.150 doesn't. 

I am confused. Should I modify the protocol/version.go to make the stream 3 contributes to the connection flowcontrol or something I misunderstood about the QUIC Protocol

**Comment by marten-seemann** [comment]
We're not implementing Google QUIC (any more), quic-go now only support IETF QUIC.
