### ISSUE TITLE
QUIC without tls semantics

### ISSUE THREAD

**Issue by Sakuralala** [lucas-clemente/quic-go#2201]
Is there anyway to use quic-go without tls?

**Comment by marten-seemann** [comment]
No, QUIC uses TLS 1.3 for securing the connection, see https://tools.ietf.org/html/draft-ietf-quic-transport-24.

**Comment by Dreamacro** [comment]
Is there any way to replace TLS with other Transport like noise protocol?

**Comment by timkuijsten** [comment]
> Is there any way to replace TLS with other Transport like noise protocol?

From [nQUIC: Noise-Based QUIC Packet Protection (2019)](https://eprint.iacr.org/2019/028):
> Similarly, we have a Go implementation (nquic-go), based on (quic-go) which has an experimental library targeting IETF draft-11 as well. Reworking the extended draft-11 version of quic-go to support nQUIC required the addition of under 1000 lines of code.
