### ISSUE TITLE
don't retire a connection ID if the peer provides too many

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#2204]

**Comment by aki237** [comment]
Hey @marten-seemann 
Can you explain this issue?
I think i might be having this problem. If lots of streams are open the connection blanks out in every stream.

**Comment by marten-seemann** [comment]
According to draft-24, an endpoint should just ignore connection IDs that exceed the limit. If the two peers have a mismatch in how they count the number of connection IDs, they'd keep retiring and reissuing connection IDs all the time (once per RTT, that is).
Note that this was recently changed in the spec: https://github.com/quicwg/base-drafts/pull/3201.

Since this can only happen once per RTT, this is probably not the reason your connection stalls. It would be helpful if you could [get a log](https://github.com/lucas-clemente/quic-go/wiki/Logging) to see what's going on. Please open a new issue once you figure out the reason and you think it might be a bug in quic-go.

**Comment by aki237** [comment]
Thanks for the explanation

**Comment by marten-seemann** [comment]
Fixed by #2252.
