### ISSUE TITLE
about performance 

### ISSUE THREAD

**Issue by xubobbs** [lucas-clemente/quic-go#2214]
I test this protocol,and make tx and rx do loop test , then I found the test packet performance seems not very good. it only got near 28000 packets send in each second on a udp port.  It seesm the max packet processed on a server can't reach 30000 . Is there any performance report about this ?

**Comment by marten-seemann** [comment]
That doesn't seem like a very meaningful benchmark.

**Comment by xubobbs** [comment]
I write a server with this quic go implement on udp port. and I test the performance  .I test two scenes case .  One is only one quic client and another is  many quic client.   I found the max performance kept same ,it always only got near 28000 on 40 core cpu.   what is the problem ?   and Is there any performance test report about this ?  thanks !
