### ISSUE TITLE
Recurring QUIC packets

### ISSUE THREAD

**Issue by klaasel** [lucas-clemente/quic-go#2217]
When I setup a successful connection with QUIC, after a while there are still some QUIC data packets sent as this screenshot of a Wireshark capture shows.

In this case the initial session successfully ends at 15 seconds, but at 53, 68 and 83 seconds still there are 2 packets sent. I'm at commit 03ab56330b3e06c8a68f2576822d711d8dc1252e though, but updating to the latest master is currently not an option because of research reasons, I have to stick to this version for now.

I was just wondering, is this by design? I can provide the pcapng if needed.

![Stray_packets_QUIC](https://user-images.githubusercontent.com/23315758/68621106-34468680-04cf-11ea-9b5f-bc4542f93991.png)

**Comment by marten-seemann** [comment]
Are you using keep alives? That would send a PING frame every half the idle timeout (note that we're introducing a maximum value for this in #2216) to keep the connection open.

**Comment by klaasel** [comment]
yes, we are, for our sessions. That explains it, thanks!
