### ISSUE TITLE
Unable to build caddy against 1.6.3

### ISSUE THREAD

**Issue by konobi** [lucas-clemente/quic-go#222]
I'm trying to build caddy, but am getting the following:

```
go build -v
github.com/lucas-clemente/quic-go/h2quic
# github.com/lucas-clemente/quic-go/h2quic
../../../lucas-clemente/quic-go/h2quic/request.go:24: h.IsPseudo undefined (type "golang.org/x/net/http2/hpack".HeaderField has no field or method IsPseudo)
```

is there a branch where this version works?

**Comment by lucas-clemente** [comment]
Thanks for the report! I'm afraid I can't reproduce this issue. Maybe your version of the hpack package is outdated, could you try running `go get -u` in the caddy (or quic-go) directory?

**Comment by konobi** [comment]
i think it was trying do build under the vendor experiments env var.

**Comment by lucas-clemente** [comment]
We used vendored dependencies in the past, but don't anymore, so that shouldn't change anything. Have you tried `go get -u`?

**Comment by konobi** [comment]
I haven't been able to try `go get -u`, as I was attempting to use git-subrepo to do some dependency management. I unfortunately had to give up and move onto nginx. Unable to reproduce... womp womp.
