### ISSUE TITLE
decryption of packets fails if they don’t use the minimal varint encoding

### ISSUE THREAD

**Issue by Zeymo** [lucas-clemente/quic-go#2259]
https://github.com/lucas-clemente/quic-go/blob/9d6ae474d7b57d32f3fe85575242855a54bf3cf9/internal/utils/varint.go#L87-L106

it means length of 0-63 bytesCount is 1 ，64-16383 bytesCount is 2 and so on

but by daft-ietf-QUIC-transport 24 of section 16  

2Bit | Length | Usable Bits | Range
-- | -- | -- | --
00 | 1 | 6 | 0-63
01 | 2 | 14 | 0-16383
10 | 4 | 30 | 0-1073741823
11 | 8 | 62 | 0-4611686018427387903

it means length of 56 can presents by 1 byte or 2 decided by peer 

when peer use 2 bytes present 56 that is not using minimal encoding length , the code below occur decryption err 
https://github.com/lucas-clemente/quic-go/blob/9d6ae474d7b57d32f3fe85575242855a54bf3cf9/internal/wire/extended_header.go#L194

#2256

**Comment by Zeymo** [comment]
#2256

**Comment by marten-seemann** [comment]
`ExtendedHeader.GetLength` is only used for headers that we send. quic-go always uses the most efficient encoding for varints, so this is not a bug.

**Comment by initlifeinc** [comment]
it seems ExtendedHeader.GetLength will be used to recopy bytes back to payload. 
imagine if quic-go really receive data like this (assume some non quic-go client really will send unexpected data, it seems ietf draft allow to send this kind data):

**** SCID len,  SCID ,**length(64 56)**, packet number ****

use 2 bytes to indicate length 56.
what will happend of following code? decode payload data failed because of a wrong recopy operation?

unpackLongHeaderPacket -> unpack -> ExtendedHeader.GetLength->utils.VarIntLen

	// 4. if the packet number is shorter than 4 bytes, replace the remaining bytes with the copy we saved earlier
	if extHdr.PacketNumberLen != protocol.PacketNumberLen4 {
		copy(data[extHdr.GetLength(u.version):hdrLen+4], origPNBytes[int(extHdr.PacketNumberLen):])
	}

**Comment by Zeymo** [comment]
@marten-seemann I fix the issue above and handshake success. It's turelly because `VarIntLen` return length compatibility

```
type Header struct {
	......
	**lenByteCount int // len actual byte count refer to peer implement of Section 16**
}

func (h *Header) parseLongHeader(b *bytes.Reader) error {
        ......
        **firstByteIndex := b.Len()  // mark start**
	pl, err := utils.ReadVarInt(b)
	if err != nil {
		return err
	}
	h.Length = protocol.ByteCount(pl)
	**h.lenByteCount = firstByteIndex - b.Len() // actual length count bytes**
}

func (h *ExtendedHeader) GetLength(v protocol.VersionNumber) protocol.ByteCount {
	if h.IsLongHeader {
		length := 1 /* type byte */ + 4 /* version */ + 1 /* dest conn ID len */ + protocol.ByteCount(h.DestConnectionID.Len()) + 1 /* src conn ID len */ + protocol.ByteCount(h.SrcConnectionID.Len()) + protocol.ByteCount(h.PacketNumberLen) + **protocol.ByteCount(h.lenByteCount)**
```

and any use `VarIntLen` will occur error when length present multi-bytes for simply byte range

**Comment by Zeymo** [comment]
just fix above maybe cause other bad-side effect , sorry for PR is not enough test

**Comment by marten-seemann** [comment]
Thanks for digging into this. This looks like a bug, GetLength shouldn’t be used at all on the receiving side. I’ll prepare a fix.
