### ISSUE TITLE
Error when downloading large files: Least unacked too small

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#226]
When downloading a large file via the network, the download sometimes abort after ~1min with the following error:

```
Closing session with error: InvalidStopWaitingData: Least unacked too small.
```

**Comment by marten-seemann** [comment]
@lucas-clemente: Can you send me the debug output?

**Comment by lucas-clemente** [comment]
Can't reproduce it with the debug log on :/

The relevant Chrome code is (`quic_connection.cc QuicConnection::ValidateStopWaitingFrame`):

```c++
  if (stop_waiting.least_unacked <
      received_packet_manager_.peer_least_packet_awaiting_ack()) {
    DLOG(ERROR) << ENDPOINT << "Peer's sent low least_unacked: "
                << stop_waiting.least_unacked << " vs "
                << received_packet_manager_.peer_least_packet_awaiting_ack();
    // We never process old ack frames, so this number should only increase.
    return "Least unacked too small.";
  }
``` 

Does that help?

**Comment by marten-seemann** [comment]
I already found that, but I'd need to know what the exact numbers were (in the `StopWaitingFrame` that we sent and in the `ACK`s we received).

**Comment by lucas-clemente** [comment]
With all of the recent changes I was unable to reproduce this issue while downloading ~4GB of data via the internet.
