### ISSUE TITLE
latency spin bit support

### ISSUE THREAD

**Issue by MPK1** [lucas-clemente/quic-go#2263]
Hi, are you planning to implement the bit in the near future?
It's inside the IETF draft since draft20.
It's described in section 17.3.1 of the current draft24.

**Comment by marten-seemann** [comment]
The spin bit is optional:

> The spin bit is an OPTIONAL feature of QUIC.  A QUIC stack that chooses to support the spin bit MUST implement it as specified in this section.

We're not planning to implement it.
