### ISSUE TITLE
Is it a bug use VersionTLS as default SupportedVersions?

### ISSUE THREAD

**Issue by CodeLife2012** [lucas-clemente/quic-go#2269]
https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/version.go#L28

This will fail `handleVersionNegotiationPacket` when `ChooseSupportedVersion`.

**Comment by marten-seemann** [comment]
Please use a release, not the master branch.

**Comment by CodeLife2012** [comment]
@marten-seemann release v0.14.x also have this bug.

**Comment by marten-seemann** [comment]
Where do you see a bug?

**Comment by CodeLife2012** [comment]
VersionTLS is not a valid quic version.

@marten-seemann can you reopen this issue, let other one  confirm this.

**Comment by marten-seemann** [comment]
VersionTLS is only used for development. We're using draft versions in releases. Again, please use a release.

**Comment by CodeLife2012** [comment]
@marten-seemann You are right. Goland not reload when checkout, so I made a mistake.
