### ISSUE TITLE
Handling an existing session with http3?

### ISSUE THREAD

**Issue by jefferai** [lucas-clemente/quic-go#2272]
I've been playing around with quic-go (so far, it's great) and have a use-case I'm interested where I want to have two (or more) streams. On one stream I want to do something custom with binary data; on the other I want to use some kind of message-oriented communications and send messages back and forth. One obvious possibility here would be to simply make HTTP/3 calls since I already have the QUIC connection open; this would allow me to use normal HTTP semantics and save me from having to figure out framing.

I have two questions I haven't sorted yet:

1. I could possibly make a custom Dial function in an http3.RoundTripper to simply return the existing Session. Is this bad? Does HTTP/3 need to be the _only_ thing running over a given Session, or will it just open up new streams as needed alongside my custom streams?

2. Assuming the answer to question 1 is that it's okay to do this, how can I implement this on the Server? There is a Server.Serve function that takes in a PacketConn but that's already lower level than the Session I have. I could maybe take a server.Server and call SetQuicHeaders but then I still need a way to invoke a Handler from a given Session/Stream.

I don't think this is currently possible but would love some pointers if you have any; otherwise I will probably look into some custom framing or some kind of RPC system that can work on top of regular io.Reader/io.Writer implementations (like capnproto).

Thanks!

**Comment by marten-seemann** [comment]
Hello @jefferai, you can use quic-go without using the `http3` package. Just use `quic.Listen{Addr}` and `quic.Dial{Addr}`, and you'll get a `quic.Session` that doesn't impose any semantics on the kind of data you send on streams. Does that work for you?

If you want to use HTTP semantics on some streams, but not others, I'm afraid that the mapping of HTTP onto QUIC doesn't allow that: For example, HTTP/3 assumes that every client-initiated bidirectional stream is a new HTTP request. There might be ways around that if you're willing to define your own HTTP extension, but this is likely to get a bit complicated.

**Comment by jefferai** [comment]
Hi Martin,

Thanks for the quick reply!

I already have code using Listen and am using some custom streams; I was hoping on some streams to also use HTTP/3, especially if I set up my non-HTTP/3 streams first. But it seems you've verified it's not possible

Since Stream is close to the net.Conn interface it does seem like I could potentially use HTTP/1 or /2 over a Stream, if I decide to go that route.

**Comment by marten-seemann** [comment]
@jefferai I'm closing this issue for now. Feel free to open a new one if you have any further questions.

**Comment by jefferai** [comment]
Sounds good. Thanks for the help!
