### ISSUE TITLE
This always happens when you introduce your package,Why is that？

### ISSUE THREAD

**Issue by helloycboy** [lucas-clemente/quic-go#2278]
![image](https://user-images.githubusercontent.com/44854263/71705176-39fa8180-2e19-11ea-8828-ff260dfd8a30.png)

go get github.com/lucas-clemente/quic-go
# github.com/lucas-clemente/quic-go/internal/handshake
../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket
        have ()
        want ([]byte)

**Comment by kjozic** [comment]
Still not working
