### ISSUE TITLE
STREAM_STATE_ERROR error after a while

### ISSUE THREAD

**Issue by Marlinc** [lucas-clemente/quic-go#2286]
Hey there,

I've been working on a HTTP1 to HTTP3 proxy to transport allow NGINX to connect to a HTTP3 upstream. I have been testing this by connecting to both Cloudflare.com using HTTP3 and the Quiche based NGINX server patches.

After a while (few hundred requests) and sometimes even immediately I start to run into `STREAM_STATE_ERROR` errors. And the client won't be able to recover on its own without creating a new round tripper instance. This is when connecting to the same host. This is on quic-go version v0.14.1.

When it breaks while connecting to the NGINX based server it will for example still work to Cloudflare.com, so I assume something got stuck in the connection state and the client isn't cleaning up because of the error.

A code sample essentially boils down to this:

```go
package main

import (
	"github.com/lucas-clemente/quic-go/http3"
	"log"
	"net/http"
)

func main() {
	hclient := &http.Client{
		Transport: &http3.RoundTripper{},
	}

	http.HandleFunc("/", func(w http.ResponseWriter, request *http.Request) {
		request.RequestURI = ""
		request.URL.Host = request.Host
		request.URL.Scheme = "https"

		response, err := hclient.Do(request)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError) + ": "+ err.Error(), http.StatusInternalServerError)

			return
		}

		if err := response.Write(w); err != nil {
			log.Printf("Write error: %+v", err)

			http.Error(w, http.StatusText(http.StatusInternalServerError) + ": "+ err.Error(), http.StatusInternalServerError)

			return
		}
	})
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

**Comment by marten-seemann** [comment]
A STREAM_STATE_ERROR is a fatal (and connection-level) error generated on the transport layer. Since one of the peers detected a protocol violation, the connection is immediately closed.

Can you please enable logging and post a log here?

**Comment by marten-seemann** [comment]
This seems to be a bug in quiche, which is being reproduced by the interop runner, see https://interop.seemann.io/logs/quiche_quicgo/multiplexing/.
