### ISSUE TITLE
Application error 0x0 after 1000 requests

### ISSUE THREAD

**Issue by Marlinc** [lucas-clemente/quic-go#2287]
Hey there,

I've been working on a HTTP1 to HTTP3 proxy to transport allow NGINX to connect to a HTTP3 upstream. I have been testing this by connecting to both Cloudflare.com using HTTP3 and the Quiche based NGINX server patches.

The client library starts to throw `Application error 0x0` errors after 1000 successful requests to the same host (with Quiche based NGINX).

A code sample essentially boils down to this:

```go
package main

import (
	"github.com/lucas-clemente/quic-go/http3"
	"log"
	"net/http"
)

func main() {
	hclient := &http.Client{
		Transport: &http3.RoundTripper{},
	}

	http.HandleFunc("/", func(w http.ResponseWriter, request *http.Request) {
		request.RequestURI = ""
		request.URL.Host = request.Host
		request.URL.Scheme = "https"

		response, err := hclient.Do(request)
		if err != nil {
			http.Error(w, http.StatusText(http.StatusInternalServerError) + ": "+ err.Error(), http.StatusInternalServerError)

			return
		}

		if err := response.Write(w); err != nil {
			log.Printf("Write error: %+v", err)

			http.Error(w, http.StatusText(http.StatusInternalServerError) + ": "+ err.Error(), http.StatusInternalServerError)

			return
		}
	})
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

**Comment by marten-seemann** [comment]
As far as I know, nginx only allows 1000 request per connection.

**Comment by Marlinc** [comment]
Thanks for looking into this issue, I will verify whether this is a limit in NGINX.

But any case,  as a user for in this the HTTP3 round tripper I would expect the round tripper to cleanup in this case or have the ability to close the particular QUIC connection myself.

Currently this causes unexpected behaviour, I would expect to always have the ability to send requests into the round tripper and that the round tripper will make sure it works.

I'm not sure where in the protocol stack (before the HTTP3 request gets send handled) NGINX blocks the request. If it happens before the handling (if the client has knowledge of that somehow) that I would expect the client (or round tripper by creating a new client) to handle that gracefully.

**Comment by marten-seemann** [comment]
> Currently this causes unexpected behaviour, I would expect to always have the ability to send requests into the round tripper and that the round tripper will make sure it works.

That's probably #765 then.

**Comment by Marlinc** [comment]
Ah okay, nice thanks!
