### ISSUE TITLE
http.Request.RemoteAddr is empty

### ISSUE THREAD

**Issue by heisedebaise** [lucas-clemente/quic-go#2296]
request.RemoteAddr is empty, how to get the remote address?

thank you

**Comment by marten-seemann** [comment]
A PR with a fix would be very much appreciated.

**Comment by marten-seemann** [comment]
The fix should be straightforward. As a pointer, here's how it was fixed for the h2quic package a while ago: https://github.com/lucas-clemente/quic-go/commit/8c5a3dabd6428102a8e51ec233ace5cf09bf78a3.
