### ISSUE TITLE
check that the client doesn't send a DiversificationNonce

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#232]
According to the Spec, with QUIC >= 33 the `Public Flag` 0x04 indicates if the `PublicHeader` contains a Diversification Nonce. However, Chrome intentionally doesn't set this bit correctly, apparently because of middleboxes (see `QuicFramer::AppendPacketHeader`).

What we can do for now is just leaving the 0x04 bit unchecked. This is not a big problem, since we just assume that the packet does not include a Diversification Nonce (the client is supposed to _never_ send one).
Once Chrome finally sets this bit correctly (hopefully in one of the future QUIC versions), we can enable this check when parsing the `PublicHeader`.

**Comment by lucas-clemente** [comment]
There's already a pending test for that.

**Comment by marten-seemann** [comment]
It's exactly this test that we **must not** enable yet, since Chrome doesn't comply with the Spec.

**Comment by lucas-clemente** [comment]
Sure. That's why it's pending ;)

I'm not sure what you mean by this issue then. What else do we need to change?

**Comment by marten-seemann** [comment]
Read the issue.
I noticed this after dropping support for QUIC 32 (in the *drop-32* branch).
