### ISSUE TITLE
panic: qtls.ConnectionState not compatible with tls.ConnectionState

### ISSUE THREAD

**Issue by fugolmere** [lucas-clemente/quic-go#2324]
I am getting the same error as mentioned in #2060. Although, I don't believe its cause is the same mentioned in the previous issue.
```
$ go version
go version go1.13.6 linux/amd64

$ go run example/echo/echo.go 
panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	<redacted>/github.com/lucas-clemente/quic-go/internal/handshake/unsafe.go:17 +0x1aa
exit status 2

```
The problem appears to be raised from a mismatch in the number of fields between the two structs. The check is performed here:
https://github.com/lucas-clemente/quic-go/blob/6407f5bf680283bf7e3755976306767da2c55e66/internal/handshake/unsafe.go#L30

I believe the latest commit on the qtls package (dependency) broke this code. It adds a new field (i.e. Used0RTT) which causes failure of the NumField check mentioned in the aforementioned file.
https://github.com/marten-seemann/qtls/commit/03df35d729e1dbe8dbb00066b3cc62d72b28fe43

**Comment by marten-seemann** [comment]
As written in the README, please use Go mod.

**Comment by fugolmere** [comment]
I am using Go modules. The problemactually arose from updating the dependencies, as shown in the README, just prior to running the tests:
```
go get -u ./...
go test ./...
```
This upgrades qtls package in go.mod to version 0.6.0 and breaks the test.

**Comment by marten-seemann** [comment]
I guess we don't need the first command at all, right? `go test` should download all the dependencies that are needed, now that we use Go modules.

Would you mind sending us a PR that fixes this?
