### ISSUE TITLE
Panic related to ChaCha20-based header protection

### ISSUE THREAD

**Issue by rod-hynes** [lucas-clemente/quic-go#2326]
We're running v0.14.0 (fork with minor changes) in production and we encounter the following panic from time to time.

```
panic: chacha20: counter overflow

goroutine 53078166 [running]:
.../vendor/github.com/marten-seemann/chacha20.(*Cipher).XORKeyStream(0xc0031697d8, 0xc00d4d2dc0, 0x5, 0x5, 0xc00d4d2dc0, 0x5, 0x5)
	/go/src/.../vendor/github.com/marten-seemann/chacha20/chacha_generic.go:167 +0xc3b
.../vendor/github.com/marten-seemann/chacha20.XORKeyStream(0xc00d4d2dc0, 0x5, 0x5, 0xc00d4d2dc0, 0x5, 0x5, 0xc00d4d2de5, 0xc00d4d2dc5)
	/go/src/.../vendor/github.com/marten-seemann/chacha20/chacha_generic.go:237 +0x12d
.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake.(*chachaHeaderProtector).apply(0xc00d4d2dc0, 0xc00e208009, 0x10, 0x5a3, 0xc00e208000, 0xc00e208005, 0x2, 0x5a7)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake/header_protector.go:109 +0xa9
.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake.(*chachaHeaderProtector).EncryptHeader(0xc00d4d2dc0, 0xc00e208009, 0x10, 0x5a3, 0xc00e208000, 0xc00e208005, 0x2, 0x5a7)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake/header_protector.go:98 +0x77
.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake.(*updatableAEAD).EncryptHeader(0xc0054fab40, 0xc00e208009, 0x10, 0x5a3, 0xc00e208000, 0xc00e208005, 0x2, 0x5a7)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/internal/handshake/updatable_aead.go:246 +0x8a
.../vendor/github.com/Psiphon-Labs/quic-go.(*packetPacker).writeAndSealPacketWithPadding(0xc00cd6aa90, 0xc0044ec5a0, 0xc00aa7f5e0, 0x1, 0x1, 0x0, 0x4cd, 0x0, 0x3, 0x7f9a46a5acd8, ...)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/packet_packer.go:579 +0x456
.../vendor/github.com/Psiphon-Labs/quic-go.(*packetPacker).writeAndSealPacket(0xc00cd6aa90, 0xc0044ec5a0, 0xc00aa7f5e0, 0x1, 0x1, 0x0, 0x4cd, 0x3, 0x7f9a46a5acd8, 0xc0054fab40, ...)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/packet_packer.go:534 +0x114
.../vendor/github.com/Psiphon-Labs/quic-go.(*packetPacker).maybePackAppDataPacket(0xc00cd6aa90, 0x0, 0x0, 0x0)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/packet_packer.go:401 +0x26a
.../vendor/github.com/Psiphon-Labs/quic-go.(*packetPacker).PackPacket(0xc00cd6aa90, 0xc003169c00, 0x0, 0xc0058630a0)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/packet_packer.go:274 +0x41
.../vendor/github.com/Psiphon-Labs/quic-go.(*session).sendPacket(0xc0027faa00, 0x1, 0xc003169f18, 0xc011d9eae0)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/session.go:1272 +0x80
.../vendor/github.com/Psiphon-Labs/quic-go.(*session).sendPackets(0xc0027faa00, 0x10a164e8d5836, 0x12cbc40)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/session.go:1187 +0x270
.../vendor/github.com/Psiphon-Labs/quic-go.(*session).run(0xc0027faa00, 0x0, 0x0)
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/session.go:541 +0x5af
created by .../vendor/github.com/Psiphon-Labs/quic-go.(*baseServer).createNewSession
	/go/src/.../vendor/github.com/Psiphon-Labs/quic-go/server.go:461 +0x3dd
```

While ChaCha20 allows 2^32 blocks (https://tools.ietf.org/html/rfc7539#section-2.3.2), we observe that the `chacha20` code will panic when the counter is at 2^32-1 and processing just 1 block, even though that should be a valid case: https://github.com/marten-seemann/chacha20/blob/36564989294fee5f3957d3e3fbfc655e10786ec0/chacha_generic.go#L165-L16.

Since QUIC ChaCha20-based header protection (https://tools.ietf.org/html/draft-ietf-quic-tls-24#section-5.4.4) initializes the counter with "4 bytes of [...] sampled ciphertext", it appears that it's possible that a counter value of 2^32-1 (0xffffffff) is selected and then `chacha20` will panic.

We note that the upstream `x/crypto/chacha20` has the same panic bahavior, and a number of other Go ChaCha20 implementations also panic when the counter is 2^32-1 and there's only 1 block to process. But it appears that OpenSSL allows a full 2^32 blocks to be processed before entering its overflow logic: https://github.com/openssl/openssl/blob/706457b7bda7fdbab426b8dce83b318908339da4/crypto/evp/e_chacha20_poly1305.c#L94-L104.

So, we believe that the correct fix is to allow the counter value 2^31-1 and only panic if more than 1 block is processed beyond that point.

We have implemented a proposed fix: https://github.com/Psiphon-Labs/chacha20/commit/899a4be528633ecf678f45e4f6b177d0f89b9e7c.

**Comment by marten-seemann** [comment]
Hello @rod-hynes, thank you for digging into this. What you're writing makes sense to me. However, as I don't have any in-depth knowledge of ChaCha20, I'm a bit hesitant to merge a PR at this point.

https://github.com/marten-seemann/chacha20/ is just a copy of the *x/crypto* package (which appears to have been removed by now, maybe related to https://github.com/golang/go/issues/24485?). This means that I can probably remove this repository and switch to using the standard library code once Go 1.14 is released.
Have you checked if the code in the standard library exhibits the same crash that you discovered. If so, it might be worth reporting this issue and your fix in the Go bug tracker.

**Comment by marten-seemann** [comment]
Update: The code still lives in *x/crypto*, so it's independent of Go's release cycle. As it turns out, the Go team made some ChaCha20 API available a few months ago, but didn't add the `SetCounter` method that we'd need in QUIC. So for now, we'll have to stick with my forked repository.

I opened https://github.com/golang/go/issues/36862, and hope that we'll get the required API sooner than later. In any case, I think the Go team would appreciate your fix, @rod-hynes.

**Comment by rod-hynes** [comment]
Thanks for the the quick follow up. Following your links I found this open issue: https://github.com/golang/go/issues/35506, "x/crypto/chacha20: add Cipher.SetCounter". And related pull request: https://github.com/golang/crypto/pull/108. I pulled that PR and added a test case for a counter value of 0xffffffff and 1 block and it panics. I will post a comment to that PR.

**Comment by rod-hynes** [comment]
It appears that a counter overflow fix will accompany the upcoming Advance (SetCounter) API enhancement to `x/crypto/chacha20`. See discussion starting here: https://github.com/golang/crypto/pull/108#issuecomment-579802871.

**Comment by marten-seemann** [comment]
Great, thank you! I really hope things will move any time soon, this PR has been lying around for almost 3 months already...

**Comment by marten-seemann** [comment]
@rod-hynes Can you give me an update on the status of the fix? It seems like I can't find the corresponding CL that you prepared.

The `SetCounter()` method was merged a few days ago, but it looks like the overflow bug is still there.

**Comment by rod-hynes** [comment]
As requested (https://github.com/golang/crypto/pull/108#issuecomment-583527753) I opened an issue: https://github.com/golang/go/issues/37157.

I don't think @lukechampine has created a CL yet?

**Comment by lukechampine** [comment]
Oops, slipped my mind, sorry -- will open a CL today!

**Comment by marten-seemann** [comment]
Thank you @rod-hynes and @lukechampine! Already looking forward to dropping the awkward workaround I had to implement in quic-go to prevent this crash (#2331).

**Comment by marten-seemann** [comment]
For future reference, this is the CL: https://go-review.googlesource.com/c/crypto/+/220591/.

**Comment by marten-seemann** [comment]
@lukechampine Any progresss on this issue?

**Comment by marten-seemann** [comment]
And another CL mentioning this issue: https://go-review.googlesource.com/c/crypto/+/224279/
