### ISSUE TITLE
Fix DOS in new AckHandler

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#236]
See this profile: https://dl.dropboxusercontent.com/u/1428776/dtrace_236.svg

Will push the test shortly.

**Comment by lucas-clemente** [comment]
See the branch [benchmark-test](https://github.com/lucas-clemente/quic-go/tree/benchmark-test).

**Comment by marten-seemann** [comment]
@lucas-clemente: I don't get any transfer rate values from the benchmark-test. I hope that #239 fixed this. Can you please check?

**Comment by lucas-clemente** [comment]
Don't think so. I've rebased and pushed to the branch. The test still hangs and consumes a lot of CPU.

**Comment by marten-seemann** [comment]
The test hangs (probably due to the ACK cascade), but doesn't consume any CPU.
@lucas-clemente: Please confirm and close this issue.

**Comment by lucas-clemente** [comment]
The DOS is indeed gone, but we now hang on #248.
