### ISSUE TITLE
Chacha20 is public now

### ISSUE THREAD

**Issue by QuLogic** [lucas-clemente/quic-go#2363]
Chacha20 is no longer internal: https://github.com/golang/crypto/commit/e0829623afd464429396234eeac9277b0135e15f

Does it make sense to move off the forked one now, and to normal golang.org/x/crypto?

**Comment by marten-seemann** [comment]
It doesn't provide the API necessary for QUIC, see https://github.com/lucas-clemente/quic-go/issues/2326#issuecomment-579698019.

**Comment by QuLogic** [comment]
Ah, sorry for the noise then.
