### ISSUE TITLE
API for delivered bytes

### ISSUE THREAD

**Issue by svenschwermer** [lucas-clemente/quic-go#2390]
I'm wondering if there's a way to write to a stream and have that function only return once the written bytes are actually acknowledged, i.e. it returns the number of actually delivered bytes?

Here's my use case: I have an intermittent connection and need reliable data delivery. The connection breaks and I write some data to a stream. This write will succeed. However, the bytes will never be delivered and I need to redial the connection. In such a situation, do I need to add my own higher layer acknowledgements, or does quic-go allow me to use the QUIC ACK mechanism somehow?

**Comment by marten-seemann** [comment]
> I'm wondering if there's a way to write to a stream and have that function only return once the written bytes are actually acknowledged

That would prevent you from continuously sending. You'd send the contents of the first `Write` call, wait for one round-trip for the acknowledgement (which would make `Write` return), and only could send the next batch of data afterwards.

> Here's my use case: I have an intermittent connection and need reliable data delivery. The connection breaks and I write some data to a stream. This write will succeed. However, the bytes will never be delivered and I need to redial the connection

Isn't this the classical case of the 2-generals problem? For example, your connection might break after the data has been delivered, but before the acknowledgement has been delivered.

**Comment by svenschwermer** [comment]
> > I'm wondering if there's a way to write to a stream and have that function only return once the written bytes are actually acknowledged
> 
> That would prevent you from continuously sending. You'd send the contents of the first `Write` call, wait for one round-trip for the acknowledgement (which would make `Write` return), and only could send the next batch of data afterwards.

Yes, I understand why this isn't the default API behaviour.

> > Here's my use case: I have an intermittent connection and need reliable data delivery. The connection breaks and I write some data to a stream. This write will succeed. However, the bytes will never be delivered and I need to redial the connection
> 
> Isn't this the classical case of the 2-generals problem? For example, your connection might break after the data has been delivered, but before the acknowledgement has been delivered.

Sure. An at-least-once delivery guarantee would be fine for me, i.e. if I retransmitted a message whose ACK got lost, that would be tolerable.

But it sounds like what I have in mind is not possible out-of-the-box as of now?

**Comment by marten-seemann** [comment]
It seems like this could be easily implemented using a (unidirectional?) acknowledgement-stream on the application layer, and there would be no benefits of using this to the transport layer.

**Comment by svenschwermer** [comment]
> It seems like this could be easily implemented using a (unidirectional?) acknowledgement-stream on the application layer, and there would be no benefits of using this to the transport layer.

Agreed. Functionally, this is simple. However, I'm trying to keep the network overhead at a minimum. Unfortunately, (this implementation of) QUIC sends the QUIC ACK and the application-level ACK in separate UDP packets which increases the overhead quite significantly.

**Comment by marten-seemann** [comment]
> Unfortunately, (this implementation of) QUIC sends the QUIC ACK and the application-level ACK in separate UDP packets which increases the overhead quite significantly.

That's not entirely correct. When receiving a packet, we queue an ACK frame, but we don't send it out until 25 ms (max_ack_delay) after receiving the packet. We need to acknowledge the packet in a timely manner to prevent the peer's loss recovery kicking in and retransmitting it.
If another packet is packed before that deadline (e.g. because you write on a stream), the ACK will get bundled with that packet.

**Comment by svenschwermer** [comment]
Thanks for the clarification!

**Comment by svenschwermer** [comment]
I have a practical question: How do I best change quic-go's parameters to tune the following 2 aspects?

* Wait with sending the ACK (up to a maximum duration) until application data is sent, i.e. don't send datagrams that only contains ACKs.
* Bundle stream data that is written in rapid succession in very few datagrams. I'm aware that this would delay stream data.

In my application, I control both clients and the server.

**Comment by marten-seemann** [comment]
quic-go currently doesn't provide any API to tune these aspects.
