### ISSUE TITLE
fix DOS against ReceivedPacketHandler

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#240]
A client that omits all `StopWaitingFrames` can cause the `receivedTimes` map to grow indefinitely.

Once we properly implement #10, entries in the map should be cleaned when sending ACK frames that contain timestamps, but until then, we have to delete the values earlier to avoid this obvious DOS vulnerability.

**Comment by marten-seemann** [comment]
Maybe it's a good idea to implement this as a linked list, too.

**Comment by marten-seemann** [comment]
See https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/3ZU-LRc5qFs

**Comment by lucas-clemente** [comment]
Is this issue resolved? I see a check for `len(h.receivedTimes)` [here](https://github.com/lucas-clemente/quic-go/blob/master/ackhandler/received_packet_handler.go#L78).

**Comment by marten-seemann** [comment]
I think so. I'll do some major rewrites in the `ReceivedPacketHandler` soon, so even if there's still an issue, it will likely disappear.

Closing this for now.
