### ISSUE TITLE
How the client should deal with a server restart

### ISSUE THREAD

**Issue by fabioyy** [lucas-clemente/quic-go#2414]
Hi

How should i deal on the client, when the servers restart?

On regular TCP there is RST/FIN packet type, telling all clientes to close the connection

How should i know that the server has been restarted and processed to reconnect?

**Comment by marten-seemann** [comment]
In case of a restart, the server will send a CONNECTION_CLOSE. It then depends on the client's policy how it handles this.

Alternatively, your application protocol can define a specific error code for server restarts, and condition client behavior on that.
