### ISSUE TITLE
duplicate method StreamID version 0.15.2

### ISSUE THREAD

**Issue by bonedaddy** [lucas-clemente/quic-go#2456]
Updating to the latest libp2p quic release is causing CI to fail for the following error:

```
../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.15.2/interface.go:54:2: duplicate method StreamID
../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.15.2/stream.go:44:2: duplicate method StreamID
```

**Comment by marten-seemann** [comment]
You need Go 1.14.

**Comment by bonedaddy** [comment]
Yea that would be it. What exactly does go 1.14 do to alleviate this? I don't recall anything in the release notes about ignoring duplicate methods

**Comment by marten-seemann** [comment]
That was one of the new features of this release.
