### ISSUE TITLE
How to dial different server

### ISSUE THREAD

**Issue by joyhope** [lucas-clemente/quic-go#2463]
I tried to DialAddr for some different servers, but the dial success for the first server connection. The next dial will failure because of the certification verification. It is always using first server certification.  

How could solve the problem?

**Comment by marten-seemann** [comment]
Can you post the code, so I can reproduce the problem?

**Comment by joyhope** [comment]
for _, proxy := range cfg.Proxies {
		s, err := quic.DialAddr(proxy, tlsconfig, nil)
		if err == nil {
			log.Println("quic proxy:", proxy, " success")
			s.CloseWithError(0, "")
		} else {
			log.Println("quic proxy:", proxy, "timeout err:", err)
		}
	}

**Comment by marten-seemann** [comment]
This code doesn't help, I cannot run it without your configuration.

Can you please post a minimal working example?

**Comment by joyhope** [comment]
The problem is certificate pair.  I could email you my certificate file.

**Comment by marten-seemann** [comment]
If this only occurs with your certificate, then your certificate is the problem, not quic-go.

**Comment by joyhope** [comment]
Only dial one server is no problem. The problem is I dial the 3 at the same time. The quic-go will use the wrong certificate (or cached.)  I read the code, but has not find any clue.

**Comment by joyhope** [comment]
If possible, you provide email address, I construct the test environment for your checking.

**Comment by marten-seemann** [comment]
We don't cache any certificates. You can set up a public server that uses your certificate, then I can try dialing that server.

**Comment by joyhope** [comment]
The client verification is configured. So client dial has to have the certificate.  Or could you show how to dial multi servers at the same time?  Thank you in advance.  (I am struggling for the problem for days. )

**Comment by marten-seemann** [comment]
```
Error information
2020/04/05 12:52:16 quic proxy: xxx1 success
2020/04/05 12:52:16 quic proxy: xxx2 timeout err: CRYPTO_ERROR: x509: certificate is valid for 127.0.0.1, xxx2 address, not xxx1 address
2020/04/05 12:52:17 quic proxy: xxx3 timeout err: CRYPTO_ERROR: x509: certificate is valid for 127.0.0.1, xxx3, not xxx3 address
```

How can I help you if you blank out the most relevant information? It looks the certificate is not valid for the address you're dialing, but there's no way of telling if you hide it.

**Comment by joyhope** [comment]
I could not find your email address.  I could prepare for the test environment. The server won't accept the no authorized connection.  The key is not the server certificate,  I provide the logical mismatched.  The certificate verification is keeping using first server certificate information.  Even I changed the dial target.

**Comment by marten-seemann** [comment]
From the limited information you're provided, this seems to be a problem with your certificate, not with quic-go. I'm afraid I can't provide support for your internal systems.

**Comment by joyhope** [comment]
I fond the problem. 

for _, proxy := range cfg.Proxies {
	s, err := quic.DialAddr(proxy, ##tlsconfig.Clone()###, nil)
	if err == nil {
		log.Println("quic proxy:", proxy, " success")
		s.CloseWithError(0, "")
	} else {
		log.Println("quic proxy:", proxy, "timeout err:", err)
	}
}
