### ISSUE TITLE
Connecting to localhost QUIC server

### ISSUE THREAD

**Issue by 0xVikas** [lucas-clemente/quic-go#2499]
I am trying to connect to the example server running on localhost with the example client. I replaced the existing certificates with the ones I generated. But it says "certificate is valid for localhost, not quic.clemente.io". How can I solve this?
```
$ go run example/client/main.go https://localhost:6121
GET https://localhost:6121
Starting new connection to localhost ([::]:56484 -> 127.0.0.1:6121), connectionID 79b6bee48fbfff47, version 512
Certificate validation failed: x509: certificate is valid for localhost, not quic.clemente.io
Closing session with error: ProofInvalid
Connection 79b6bee48fbfff47 closed.
panic: Get https://localhost:6121: ProofInvalid
```

**Comment by marten-seemann** [comment]
This is not QUIC specific. Please refer to the countless TLS tutorial on the internet.

**Comment by baiyehuahuo** [comment]
edit example/client/main.go

replace 
`
hclient := &http.Client{
	Transport: &h2quic.RoundTripper{QuicConfig: quicConfig},
}
`
with 

`
hclient := &http.Client{
	Transport: &h2quic.RoundTripper{QuicConfig: quicConfig, TLSClientConfig: &tls.Config{InsecureSkipVerify: true}},
}

`
