### ISSUE TITLE
making partially reliable or unreliable data stream

### ISSUE THREAD

**Issue by mayankmclaren** [lucas-clemente/quic-go#2503]
I have been trying to create a partially reliable data stream but i'm unable to do so. can you please help me with that.

**Comment by marten-seemann** [comment]
QUIC doesn't support partial reliability.

**Comment by mayankmclaren** [comment]
QUIC offers a good starting point for redesigning video transport. QUIC supports multiple streams within a single association
and decouples congestion control from retransmission. In particular, QUIC’s congestion control and acknowledgments operate on a
per-packet basis while retransmissions are realized on a per-stream
basis. This feature enables the sender to selectively retransmit or to
introduce FEC on a per-stream basis, and, thus, allows, in principle,
reliable and unreliable streams within the same association. Extending QUIC to support such selective delivery of the video frames
over either reliable or unreliable streams, as required based on the
frame type, introduces several non-trivial challenges
[](https://arxiv.org/pdf/1809.10270.pdf)


**Is there any way that i can stop retransmission of data?**

**Comment by marten-seemann** [comment]
Please direct your question to the IETF QUIC working group. quic-go is an implementation of the QUIC protocol, and not the place to suggest changes to the core protocol.
