### ISSUE TITLE
Don't discard version negotiation packets before successfully processing any other packet

### ISSUE THREAD

**Issue by rip-create-your-account** [lucas-clemente/quic-go#2510]
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-6.2 mentions that "A client MUST discard any Version Negotiation packet if it has received and successfully processed any other packet"

[Currently](https://github.com/lucas-clemente/quic-go/blob/81daa8afd3d90fca847f582f2c51e145b694d602/client.go#L321) the other packets don't need to be "successfully processed" for the client to start discarding version negotiation packets. Now it would be enough for the client to receive a packet for active source connection ID where the packet can otherwise be garbage.

**Comment by marten-seemann** [comment]
This is a bit complicated to implement. Maybe we should pass Version Negotiation packets to the session directly. But then the session has to close itself and somehow tell the client to create a new session with a specific version.

**Comment by rip-create-your-account** [comment]
The session processing the packets seems to work. To create a new session it could close itself with `errCloseForRecreating` that carries the selected version and new initial packet number. Something like the following

``` diff
diff --git a/session.go b/session.go
index e738865e..f2e98653 100644
--- a/session.go
+++ b/session.go
@@ -104,7 +104,14 @@ type closeError struct {
        immediate bool
 }
 
-var errCloseForRecreating = errors.New("closing session in order to recreate it")
+type closeForRecreatingError struct {
+       selectedVersion protocol.VersionNumber
+       nextPN          protocol.PacketNumber
+}
+
+func (e *closeForRecreatingError) Error() string {
+       return "closing session in order to recreate it"
+}
```

session processes the version negotiation packet
``` golang
selectedVersion, _ := protocol.ChooseSupportedVersion(s.config.Versions, hdr.SupportedVersions)
nextPN, _ := s.sentPacketHandler.PeekPacketNumber(protocol.EncryptionInitial)
s.closeLocal(&closeForRecreatingError{
	selectedVersion: selectedVersion,
	nextPN:          nextPN,
})
```

and then client extracts the values after the run loop returns the error
``` diff
diff --git a/client.go b/client.go
index ee46c454..b3701540 100644
--- a/client.go
+++ b/client.go
@@ -296,7 +296,11 @@ func (c *client) dial(ctx context.Context) error {
                c.session.shutdown()
                return ctx.Err()
        case err := <-errorChan:
-               if err == errCloseForRecreating {
+               var recreatingErr *closeForRecreatingError
+               if errors.As(err, &recreatingErr) {
+                       c.initialVersion = c.version
+                       c.version = recreatingErr.selectedVersion
+                       c.initialPacketNumber = recreatingErr.nextPN
                        return c.dial(ctx)
                }
                return err
```

**Comment by marten-seemann** [comment]
LGTM. Would you mind sending us a PR?
