### ISSUE TITLE
Set MTU on Session

### ISSUE THREAD

**Issue by MagicalTux** [lucas-clemente/quic-go#2511]
A way to alter the MTU for a given session would be nice, and should be easy enough to implement.

```go
// (this should also be added to the Session interface)
func (s *Session) SetMaxPacketSize(packetSize uint64) {
  s.packer.maxPacketSize = protocol.ByteCount(packetSize)
}
```

This allows people who perform PMTU to update the MTU once result comes in (If #94 is resolved manually setting MTU wouldn't be required anymore but it's still nice to have).

**Comment by marten-seemann** [comment]
How would you perform PMTU yourself?

**Comment by MagicalTux** [comment]
In my case when the client performs server discovery it'll send a number of UDP packets (with DF flag set) to various servers in order to measure latency, MTU and packet loss, so I already know the path MTU when I connect. In some cases MTU may change after the connection is established, so an API that can update it could be nice.

**Comment by marten-seemann** [comment]
I don't really think the performance benefits outweigh the cost in complexity here. PMTUD is a nice optimization, but there are many more low-hanging fruits at this time. Setting an MTU that's already known seems to be even more of a corner case.
