### ISSUE TITLE
stop the timer when the session is closed

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#2515]

**Comment by Stebalien** [comment]
We also need to tear down the timer here: https://github.com/lucas-clemente/quic-go/blob/6d66eac1b9a9264d539931f4178c1969693a73ed/server.go#L452-L454

**Comment by marten-seemann** [comment]
Right, fixed in 286dcf555f9b175186a7e809ead909815d5b140d.
