### ISSUE TITLE
add integration tests with long RTTs

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#253]
RTTs of ~500ms would be an interesting case.

Aus gegebenem Anlass.

**Comment by marten-seemann** [comment]
Maybe we should postpone this until we eliminated all flaky tests.

**Comment by marten-seemann** [comment]
I implemented a test with 500 ms RTT and a 10 MB download takes more than 2 minutes (using Chrome). I suspect this has something to do with congestion, so we might want to fix #302 first.

**Comment by lucas-clemente** [comment]
Fixed by #679.
