### ISSUE TITLE
Reduce memory usage from inbound packet queue

### ISSUE THREAD

**Issue by Stebalien** [lucas-clemente/quic-go#2532]
Currently, the `receivedPacket` queue has room for 10K packets. That means every connection takes 10K pointers worth of memory (usually 78KiB), even when idle.

It would be _really_ nice if this queue were variable length (or possibly just smaller).

**Comment by Stebalien** [comment]
For context on why I care about 78KiB of memory: if all 3K+ connections held by my go-ipfs daemon right now used QUIC, I'd be using 50% more memory (+225MiB).

**Comment by marten-seemann** [comment]
Yes, that queue is overly large. We once set it equal to the congestion window, and then increased the congestion window by 10x. We can probably get away with a value of 128 or 256 here.

**Comment by Stebalien** [comment]
256 or even 1024 is reasonable.
