### ISSUE TITLE
Facing problem while sending an image.

### ISSUE THREAD

**Issue by mayankmclaren** [lucas-clemente/quic-go#2540]
I made my own webpage and added a picture to it. I tried to send that HTML file using these instructions
 [https://www.uio.no/studier/emner/matnat/ifi/INF5072/v18/quicgo.txt](url) 

I am getting the output given below. Please help me with sending a picture using quic-go

GET https://localhost:6121/
client Starting new connection to localhost ([::]:60654 -> 127.0.0.1:6121), source connection ID (empty), destination connection ID 0xd9ef4b4e010bd366d1605ffeff36, version QUIC WG draft-27
Got response for https://localhost:6121/: &http.Response{Status:"200 OK", StatusCode:200, Proto:"HTTP/3", ProtoMajor:3, ProtoMinor:0, Header:http.Header{"Accept-Ranges":[]string{"bytes"}, "Content-Length":[]string{"114"}, "Content-Type":[]string{"text/html; charset=utf-8"}, "Last-Modified":[]string{"Tue, 12 May 2020 11:49:23 GMT"}}, Body:(*http3.body)(0xc00020ebc0), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(nil), TLS:(*tls.ConnectionState)(nil)}
Request Body:
<html>
<head>
    <title>PICTURE</title>
</head>
<body>
    <img src="image.png" alt="image test">
</body>
</html>
client Closing session with error: Application error 0x100
client Connection 0xd9ef4b4e010bd366d1605ffeff36 closed.

![Screenshot from 2020-05-12 17-48-05](https://user-images.githubusercontent.com/42915416/81691282-2ec7fa00-947a-11ea-9f78-caa364d6ea80.png)

**Comment by marten-seemann** [comment]
I don't see any problem here.
