### ISSUE TITLE
Extra round-trip at connect?

### ISSUE THREAD

**Issue by jeremywohl** [lucas-clemente/quic-go#2549]
Using the echo example code, I'm seeing an extra round-trip in connection setup.  That is, 2 RTTs, where I expect 1 RTT.

See [qlog viz here](https://qvis.edm.uhasselt.be/#/sequence?file=https://jeremywohl.com/assets/faraday_run_2.qlog.txt?ext=.qlog).

Am I confused?  Thoughts on debugging this further?

Thanks.

**Comment by marten-seemann** [comment]
Looks like the server is performing a Retry. qvis doesn’t draw it, see https://github.com/quiclog/qvis/issues/7.

**Comment by jeremywohl** [comment]
I see.  So why is there a Retry response?  Address validation?  And under what circumstances can I get it down to 1 RTT?

(Note this is quic-go on both client and server.)

**Comment by marten-seemann** [comment]
That's what we have the `AcceptToken` callback for.
