### ISSUE TITLE
example echo.go problem

### ISSUE THREAD

**Issue by hesen2006cn** [lucas-clemente/quic-go#2550]
quic-go/example/echo/
server:  stream, err := sess.AcceptStream(context.Background())
              _, err = io.Copy(loggingWriter{stream}, stream)

client:   _, err = stream.Write([]byte(message))
             I'm add stream.Close()

When the client stream is closed, the server is still blocked.
Is there any way to deal with this problem？

**Comment by marten-seemann** [comment]
I can’t see any problem here.
