### ISSUE TITLE
head-of-line blocking  across multiple streams

### ISSUE THREAD

**Issue by FangJianHust** [lucas-clemente/quic-go#2566]
quic rfc says "Note  that when data from multiple streams is bundled into a single QUIC packet, loss of that packet blocks all those streams from making progress.  Implementations are advised to bundle as few streams as necessary in outgoing packets without losing transmission efficiency to underfilled packets."

But in quic-go,we pick a frame from every stream in streamQueue, this may be against the rfc ?

**Comment by marten-seemann** [comment]
Not at all. We bundle stream data from as few streams as possible in a single packet, by dequeueing a maximum size STREAM frame from every stream. So if a stream has enough data to send, the packet will only contain a single STREAM frame.

Only if a stream doesn't have enough data to send, we'll ask the next stream for data to send. This makes sense as it reduces the number of packets sent out.
