### ISSUE TITLE
client Closing session with error: Application error 0x100

### ISSUE THREAD

**Issue by xowns4817** [lucas-clemente/quic-go#2577]
Hello, I ran the example code of quic-go. I turned on the server with main.go (/example/main.go) and sent a request to the server turned on with main.go (/example/client/main.go).

The request was received to the server, and the result was returned, but the result is returned and the following error occurs: "server Peer closed session with error: Application error 0x100" The following error occurs and the server is disconnected. ??

[client log]
server Peer closed session with error: Applicaiotn error 0x100
server Connection 0x....... closed.

thank you.

**Comment by marten-seemann** [comment]
Not sure why you think this is a bug. This is the NO_ERROR code:
https://github.com/lucas-clemente/quic-go/blob/85c19fbb5ae34fd81238c424fe1e11cd30646f72/http3/error_codes.go#L12

**Comment by JcdeA** [comment]
Wouldn't it make more sense if the message was more descriptive?
Saying that "peer closed session with error" could make people assume that there was an error.
