### ISSUE TITLE
HTTP/3 request timeout with io.PipeReader body

### ISSUE THREAD

**Issue by l2dy** [lucas-clemente/quic-go#2620]
With an `http.Request` like this:

```go
pipeR, pipeW := io.Pipe()
relayReq, err := http.NewRequestWithContext(ctx, "POST", "https://127.0.0.1:8888/v1", pipeR)
resp, err := rt.RoundTrip(relayReq)
[...]
io.Copy(pipeW, os.Stdin)
```

The request fails with the following error.

```
$ echo TEST | go run .
2020/06/21 xx:xx:xx Read on stream 0 canceled with error code 268
```

But if the body in `http.NewRequestWithContext` is a `strings.Reader` or `nil`, the request would successfully complete.

The request body seems to be [sent asynchronously](https://github.com/lucas-clemente/quic-go/blob/c956ca4447b3945920219db6dc79cbc613761970/http3/request_writer.go#L57). Why would the RoundTrip call get blocked and eventually time out?

Example code:

```go
package main

import (
	"context"
	"crypto/tls"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/lucas-clemente/quic-go/http3"
)

func main() {
	if err := dial(); err != nil {
		log.Fatal(err)
	}
}

func dial() error {
	http.Handle("/", http.NotFoundHandler())

	server := http3.Server{
		Server: &http.Server{
			Addr: "127.0.0.1:8888",
		},
	}
	go server.ListenAndServeTLS("c", "k")

	rt := http3.RoundTripper{
		DisableCompression: true,
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}

	pipeR, pipeW := io.Pipe()

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	relayReq, err := http.NewRequestWithContext(ctx, "POST", "https://127.0.0.1:8888/v1", pipeR)
	if err != nil {
		return err
	}

	resp, err := rt.RoundTrip(relayReq)
	if err != nil {
		return err
	}

	errCh := make(chan error)
	go func() {
		io.Copy(pipeW, os.Stdin)
		pipeW.Close()
		errCh <- nil
	}()
	go func() {
		io.Copy(os.Stdout, resp.Body)
		resp.Body.Close()
		errCh <- nil
	}()
	<-errCh
	return nil
}
```

**Comment by l2dy** [comment]
For use with bidirectional HTTP streams like WebSocket. Alternative way to support this is to make resp.Body an io.ReadWriteCloser, see https://github.com/nhooyr/websocket/blob/v1.8.6/dial.go#L119.

**Comment by l2dy** [comment]
According to [RFC 8441](https://tools.ietf.org/html/rfc8441), WebSockets over HTTP/2 can be bootstrapped using an extended CONNECT method to create a tunnel over a single HTTP/2 stream. HTTP/3 explicitly supports the CONNECT method, and

> The request stream remains open at the end of the request to carry the data to be transferred.

So I think eventually our http3 package should support an open request stream (body) after the RoundTrip call.

**Comment by marten-seemann** [comment]
Does the websocket connection use HTTP framing?

**Comment by l2dy** [comment]
> Does the websocket connection use HTTP framing?

Yes, it should.

> https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-the-connect-method
> All DATA frames on the stream correspond to data sent or received on the TCP connection. Any DATA frame sent by the client is transmitted by the proxy to the TCP server; data received from the TCP server is packaged into DATA frames by the proxy. Note that the size and number of TCP segments is not guaranteed to map predictably to the size and number of HTTP DATA or QUIC STREAM frames.

**Comment by l2dy** [comment]
Oops, looks like RFC 8441 uses the raw stream. I'll do more resarch on this.

    After successfully processing the opening handshake, the peers should
    proceed with the WebSocket Protocol [RFC6455] using the HTTP/2 stream
    from the CONNECT transaction as if it were the TCP connection
    referred to in [RFC6455].

**Comment by l2dy** [comment]
> Oops, looks like RFC 8441 uses the raw stream. I'll do more resarch on this.

Well, stream in HTTP/2 is a bidirectional sequence of frames, so of course it uses HTTP framing.

**Comment by marten-seemann** [comment]
> stream in HTTP/2 is a bidirectional sequence of frames, so of course it uses HTTP framing.

Right. If you were to layer websockets on top of HTTP/3, you could get rid of HTTP framing, since QUIC already provides native streams. However, I'm not sure if that's even properly specified anywhere.

The IETF recently formed a new working group for WebTransport, which will address exactly this issue: https://tools.ietf.org/html/draft-vvv-webtransport-overview-01.

**Comment by l2dy** [comment]
Yes, how WebSocket would work with HTTP/3 is not specified yet.

Back to the CONNECT method itself (primarily used with HTTP proxies), there is still need for bidirectional data stream after the HEADERS exchange, which is not supported in quic-go yet as I have demonstrated.

**Comment by marten-seemann** [comment]
> Back to the CONNECT method itself (primarily used with HTTP proxies), there is still need for bidirectional data stream after the HEADERS exchange, which is not supported in quic-go yet as I have demonstrated.

How does this work in HTTP/2? Can you point me to the corresponding Go standard library code?

**Comment by l2dy** [comment]
> How does this work in HTTP/2? Can you point me to the corresponding Go standard library code?

See https://github.com/golang/go/issues/13717 and https://golang.org/cl/18266.

**Comment by marten-seemann** [comment]
Not sure if I understand https://golang.org/cl/18266 correctly, but all it's doing is setting the `URL` and `RequestURI` of the `http.Request`, right? That should be easy enough to mimic in the http3 package.

**Comment by l2dy** [comment]
https://github.com/golang/go/issues/13717 references https://github.com/golang/go/issues/13444#issuecomment-161115822, which is an `io.Pipe()` demo that works in x/net/http2 but not in quic-go. I think quic-go is lacking a more fundamental capability here.

**Comment by l2dy** [comment]
I'll modify my example to fit his demo, wait a sec.

**Comment by l2dy** [comment]
> I'll modify my example to fit his demo, wait a sec.

quic-go's RoundTrip() blocks and times out, as expected from the top comment demo.

<details><summary>Example 2</summary>

```go
[...]
	pipeR, pipeW := io.Pipe()

	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()

	relayReq, err := http.NewRequestWithContext(ctx, "PUT", "https://127.0.0.1:8888/v1", pipeR)
	if err != nil {
		return err
	}

	errCh := make(chan error)
	go func() {
		for {
			time.Sleep(1 * time.Second)
			fmt.Fprintf(pipeW, "It is now %v\n", time.Now())
		}
	}()

	go func() {
		resp, err := rt.RoundTrip(relayReq)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Got: %#v", resp)
		io.Copy(os.Stdout, resp.Body)
		resp.Body.Close()
		errCh <- nil
	}()

	<-errCh
	return nil
}
```

</details>

**Comment by l2dy** [comment]
Interestingly, in my second example, if I remove the context with timeout (turn http.NewRequestWithContext into http.NewRequest), it would eventually return 404 in a minute and a few seconds.

**Comment by marten-seemann** [comment]
The reason this is timing out is that we're using a buffered writer for requests (as introduced in #2443).
It looks like that change was ok for the the `http.ResponseWriter`, as it implements the `http.Flusher` interface, but apparently that doesn't apply to requests.
Does that make sense to you?

**Comment by l2dy** [comment]
> Does that make sense to you?

Yes, indeed. The more frequent data is written to pipe in Example 2 without context, the faster it receives the response and exits. Looks like buffering.
