### ISSUE TITLE
padding frame not seal

### ISSUE THREAD

**Issue by FangJianHust** [lucas-clemente/quic-go#2625]
if endport send packet or coalescedPacket with padding frame, it is not seal, but peer will try to open it, and we got payload_decrypt_error

**Comment by marten-seemann** [comment]
I don't understand what you're saying. Can you please give some more details?

**Comment by FangJianHust** [comment]
this [padPacket](https://github.com/lucas-clemente/quic-go/blob/master/packet_packer.go#L315) function are not encryption

**Comment by marten-seemann** [comment]
That's intentional. We're applying padding outside of the QUIC packet.

**Comment by FangJianHust** [comment]
but，if you add padding after 1-RTT，you try to decrypt it by receiver

**Comment by marten-seemann** [comment]
That's why we don't do that.

**Comment by FangJianHust** [comment]
I don‘t understand what you mean，you can try your echo example，and you will find an payload_decrypt_error for receive an coalescedPacket
