### ISSUE TITLE
Server receives 0-RTT packets, but does not deliver them to QUIC session.

### ISSUE THREAD

**Issue by zverevm** [lucas-clemente/quic-go#2629]
If 0-RTT packet arrives after an Inital packet, it is buffered in zeroRTTQueue and never recovered. 0-RTT packets cannot be sent before Initial in a new connection.

Initial and 0-RTT packets are handled with [baseServer.handlePacketImpl(*receivedPacket)](https://github.com/lucas-clemente/quic-go/blob/master/server.go#L315) method. If the packet is Inital, [another method](https://github.com/lucas-clemente/quic-go/blob/master/server.go#L359) is called which starts the session, [checks](https://github.com/lucas-clemente/quic-go/blob/master/server.go#L429) if there are any 0-RTT packets in the buffer, and passes them to the new session. When 0-RTT packet arrives (after the Initial one), it will be handled by the new session if it is ready. If the 0-RTT is sent right after the Initial, the session is not ready yet, and the packet is handled by baseServer.handlePacketImpl, which [buffers it](https://github.com/lucas-clemente/quic-go/blob/master/server.go#L338). Once the session is created, new packets are handled with session.handlePacketImpl, and baseServer.handlePacketImpl, which triggers 0-RTT packets transfer to the session, is never called again. 

My team has discovered this issue with an experiment based on the code in quic-go/integrationtest/self/zero_rtt_test.go . The test does not fail, because it check if the client has sent the 0-RTT packet, not if the other endpoint has received it ([line 104](https://github.com/lucas-clemente/quic-go/blob/master/integrationtests/self/zero_rtt_test.go#L104)).

A possible solution is to pass *zeroRTTQueue to the session, and recover 0-RTT packets there.

**Comment by marten-seemann** [comment]
I'm not sure I understand the problem. `handlePacketImpl` doesn't create a new go routine, except in cases where it needs to send either a Retry or a CONNECTION_CLOSE. That means there can't be a race condition between receiving an Initial (that creates a new session) and receiving a 0-RTT packet. Or am I missing something?

**Comment by zverevm** [comment]
It's not a race condition. The part of the code that is meant to dequeue 0-RTT packets and pass them to the new session is not executed, and the client ends up resending 0-RTT data in 1-RTT packets.

The issue is hard to see, I will try to give a graphical description

```
Client                  Server
  |       Initial         |
  | --------------------> | packetHandlerMap.handlePacket(...)
  |                       |    no session found, sending new packet to baseServer
  |        0-RTT          |    baseServer.receivedPackets <- p // [ 1 ]
  | --------------------> | packetHandlerMap.handlePacket(...)
  |                       |    no session found, sending new packet to baseServer
  | /* session ready! */  |    baseServer.receivedPackets <- p // [ 2 ]
  |      Any packet       |
  | --------------------> | packetHandlerMap.handlePacket(...)
  |                       |    found session for this CID
  |      Any packet       |    session.receivedPackets <- p    // [ 3 ]
  | --------------------> | packetHandlerMap.handlePacket(...)
  |                       |    found session for this CID
  |                       |    session.receivedPackets <- p    // [ 4 ]


// [ 1 ]
baseServer.handlePacketImpl(p)
  Not 0-RTT && Valid Initial
  baseServer.handleInitialImpl(p, hdr)
    Check token and other things
    sess := s.createNewSession(...)
    sess.handlePacket(p)
    for {
      p := s.zeroRTTQueue.Dequeue(hdr.DestConnectionID)
      if p == nil {
          // No 0-RTT packets at this point
          break
      }
      sess.handlePacket(p)
    }

// [ 2 ]
baseServer.handlePacketImpl(p)
  p is 0-RTT
    s.zeroRTTQueue.Enqueue(hdr.DestConnectionID, p)

// [ ? ] HERE IS THE PROBLEM
// Once the session is created, the method that would
// trigger 0-RTT packets dequeuing is not called.
baseServer.handlePacketImpl(p)
  Not 0-RTT && Valid Initial
  baseServer.handleInitialImpl(p, hdr)
    Check token and other things
    sess := s.createNewSession(...)
    sess.handlePacket(p)
    for {
      p := s.zeroRTTQueue.Dequeue(hdr.DestConnectionID)
      if p == nil {
          break
      }
      // There are 0-RTT packets, but this code is not executed
      sess.handlePacket(p)
    }

// [ 3 ]
session.handlePacketImpl(p)

// [ 4 ]
session.handlePacketImpl(p)
```

**Comment by marten-seemann** [comment]
Which packets in your example are correctly processed, and which ones aren't?

**Comment by zverevm** [comment]
All packets are correctly processed except the 0-RTT one. The server buffers it, which is correct, but then does not pass it to the session.

**Comment by marten-seemann** [comment]
Ok, now I understand. This actually is a race condition here. The 0-RTT packet is passed to the `baseServer` before the Initial packet was processed. At the time the Initial is processed and the new session is created, the 0-RTT packet is still sitting in the `receivedPackets` channel.
When the 0-RTT packet is then processed, the session has already been created and all 0-RTT packets have been dequeued.

**Comment by q191201771** [comment]
hi, I'm learning QUIC and quic-go.
Is this bug should be fixed?
I came up with three solutions:

1. all packet goes into `baseServer` first, then check if the session exists at the beginning of `baseServer.handlePacket`
2. check if the session exists before `zeroRTTQueue.Enqueue`
3. check if the session exists before `zeroRTTQueue.deleteQueue` in timer

I could send a PR if you like.
