### ISSUE TITLE
wireshark decrypt failed

### ISSUE THREAD

**Issue by yangjinecho** [lucas-clemente/quic-go#2653]
v0.17.2

I create a KeyLogWriter file ,then

wireshark -otls.keylog_file:echo.txt -r xxx.pcapng -Y udp -dudp.port==4242,quic -Y quic
<img width="1059" alt="截屏2020-07-06 下午10 50 01" src="https://user-images.githubusercontent.com/28773685/86606882-2653f180-bfdb-11ea-8353-d2dc45e98ef8.png">

**Comment by marten-seemann** [comment]
This is probably padding applied outside of the QUIC packet.
