### ISSUE TITLE
Deadlock in session shutdown / sendQueue.Send()

### ISSUE THREAD

**Issue by ltucker** [lucas-clemente/quic-go#2655]
It appears possible to wind up stuck in sendQueue.Send() after sendQueue.Run() has exited, preventing Session shutdown from exiting. 

Here is a boiled-down test case from the situation I saw it in (a failed handshake). 
https://gist.github.com/ltucker/0b433b775982176de4cfd8a540984d16

**Comment by marten-seemann** [comment]
Thank you for the bug report! As always, the example was super helpful in understanding what's going on here.
