### ISSUE TITLE
RemoteAddr field of http.Request is empty when using QUIC

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#266]
Is it expected that, when using quic-go, the RemoteAddr field of the http.Request is empty? I know that UDP doesn't really have the concept of a "connection" in the TCP sense, but I don't know enough about QUIC to be sure. Is it possible/supposed to fill the RemoteAddr field of the http.Request using QUIC?

**Comment by lucas-clemente** [comment]
It is absolutely possible to set RemoteAddr properly, I will fix this shortly.

In principle, there's not such a big difference between remote addresses in TCP and QUIC. Two major points come to mind:

With UDP you don't know whether the remote address is correct or the sender of the packet is spoofing it, so one needs mechanisms to detect that. Currently, we assign a token consisting of the (encrypted) IP address + timestamp to each client and require the client to "proof" ownership of the IP (= one RTT) before we formally accept the connection. This mitigates traffic amplification attacks. So, once we pass a RemoteAddr up in an HTTP request, we know the address is correct.

Secondly, QUIC allows for the remote address to change. This is a really cool feature – think switching from WiFi to cellular on your phone without interrupting connections. We currently don't support this yet, but even once we do (#234), the HTTP server should not notice anything. New requests will simply have a new RemoteAddr, while old ones continue normally.

**Comment by mholt** [comment]
Thanks Lucas! This is great, and wow, you're fast. :smile: Keep up the great work with this lib. It's generated a lot of interest.

**Comment by heisedebaise** [comment]
The latest version is still empty ?
