### ISSUE TITLE
handcraft congestion control

### ISSUE THREAD

**Issue by Leo-rojo** [lucas-clemente/quic-go#2695]
Hi,
I'm currently working with the gquic branch of the protocol (because I need to use the browser as a client). 
I'm able to set up the connection and serve the various files.
I would like to play with the congestion control, more specifically I would like to change the congestion window based on a parameter that I update regularly in the server main.go file. 
For what I have understood in order to do that I need to change the interface, the cubic related files (cubic and cubic, cubic_sender and others) and expose to session set and get methods related (I need also to measure congestion control metrics. I have seen the new qlog module in the master branch but it's not present into gquic branch).
My problem is that I don't know how to retrieve and set (once I have exposed the right methods) the congestion control parameters from the session in the main.go file. I think I should do something inside my http handler, could you please give me a hint? Moreover, the workflow I exposed is correct?
Best regards

**Comment by marten-seemann** [comment]
The gquic branch has been unmaintained for a long time. Chrome speaks IETF QUIC, if you start it with the right command line flags.
We don't support modification of Cubic constants from an HTTP handler, that's something that you'd need to add yourself.
