### ISSUE TITLE
Library 

### ISSUE THREAD

**Issue by akay777** [lucas-clemente/quic-go#2706]
Is there any library that can be directly imported for coding (i.e. Visual studio Code)?

**Comment by marten-seemann** [comment]
You can use any editor you like.

**Comment by akay777** [comment]
I used require(‘net’) and for that I installed browserify which is working fine but fs.readFileSync is giving error as “it is not a function “.
Any help would be appreciated.
Regards,

**Comment by SuneethaYamani** [comment]
@akay777  please follow steps from below doc you can run in vs code.
[node quic experimental build.docx](https://github.com/lucas-clemente/quic-go/files/5303649/node.quic.experimental.build.docx)
