### ISSUE TITLE
Confusing (incorrect?) behavior when both peers close a stream

### ISSUE THREAD

**Issue by arashpayan** [lucas-clemente/quic-go#2709]
Firstly, thank you @lucas-clemente for creating such a useful library and sharing it with the world.

I'm new to quic, and have stumbled upon something that may or may not be a bug. It might just need more documentation.

In short, if both peers `Close()` a stream, after the second or third stream they `Close()`, the client will receive the error:
```
FRAME_ENCODING_ERROR: 1152921504606846977 exceeds the maximum stream count
```
from the goroutine that is calling `AcceptStream()` on the `quic.Session`.

I've written a minimal program demonstrating the issue: https://gist.github.com/arashpayan/7c25dc8c26d3c0ea6ea43ace273fc09c

I've tested this issue against 0.17.3 and the HEAD of master as of this writing (https://github.com/lucas-clemente/quic-go/commit/d7c2169c55bd0ab0ce4724bcab270a6ec902534f). Simply run the sample with `go run main.go` and then tap 'enter' to make the "server" send a message to the "client". You'll notice the above error after the 4th stream/message is sent. To avoid the error, you can comment out the line where the client is closing the stream (`main.go:92`).

The number of successful streams before receiving this error is a function of the `MaxIncomingStreams` value passed in the `quic.Config` struct to `quic.DialAddr()`. In my program, I've been passing 2^60 for the maximum number streams, which lets me get away with 1 successful stream before receiving the above error. If I set the max to 2^60-1, I can get away with 2 streams. 2^60-2 gets me 3 streams and so on.

Anyway, I'm not sure if this is expected behavior, a bug, or something else.

Thanks.

**Comment by marten-seemann** [comment]
That makes sense as you're setting the stream limit to 2^60-3: https://gist.github.com/arashpayan/7c25dc8c26d3c0ea6ea43ace273fc09c#file-main-go-L73.
Every time a stream is closed, we grant the peer a new stream, so after closing 3 streams, we hit the highest number that can be encoded.

So technically, this is probably a bug, as we shouldn't send a value that can't be encoded here. In practice though, setting a stream limit anywhere close to 2^60 wouldn't be a very wise thing to do, as you open yourself up to a trivial DoS attack (the peer can now open that many streams and you have to keep state for each and every one of them).

**Comment by arashpayan** [comment]
Thanks for the reply.

> Every time a stream is closed, we grant the peer a new stream

Interesting. Why is that done? Is it something that I should be managing at the application level?

> In practice though, setting a stream limit anywhere close to 2^60 wouldn't be a very wise thing to do, as you open yourself up to a trivial DoS attack (the peer can now open that many streams and you have to keep state for each and every one of them).

That makes sense. Thanks for the tip.

**Comment by marten-seemann** [comment]
> Interesting. Why is that done? Is it something that I should be managing at the application level?

Your application configures how many concurrent streams it allows, and quic-go will take care of the rest (i.e. granting the peer credit as old streams are closed). Do you have a use case where this level of control is not fine-grained enough?

**Comment by arashpayan** [comment]
> Do you have a use case where this level of control is not fine-grained enough?

No, I was just wondering why the library would open a stream when I had not requested it. I still have a lot to learn about QUIC. :-)

**Comment by marten-seemann** [comment]
> No, I was just wondering why the library would open a stream when I had not requested it. 

It is not.
During the QUIC handshake, endpoints use their transport parameters to tell their peer: "You're allowed to open streams up to stream ID X.". At any point later in the connection, an endpoint can send a MAX_STREAMS frame to tell the peer "Now you're allowed to open streams up to stream ID Y". That's what I mean by "granting the peer stream credit".

**Comment by arashpayan** [comment]
Oh, that makes sense. Thank you for the clarification.

**Comment by kokes** [comment]
Hey @marten-seemann,
I've actually run into a tangentially related issue that I've been able to reproduce using the gist included above. If I remove the reading/writing bits and just close the stream (from both sides), the MAX_STREAMS update doesn't seem to be communicated, I'm not able to create any new streams and it blocks.

In this edited gist I've removed the binary.{Read,Write} and just closed the stream from both sides and added a bit of logging. I set `MaxIncomingStreams` to 2 and after two initiated (and closed) streams... it just gets stuck.

https://gist.github.com/kokes/15324dce93a41fff61cbbf101bc45590

```
$ go run repro2.go
10:03:16 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT

10:03:17 repro2.go:62: closed a stream from the server side
10:03:17 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT
10:03:17 repro2.go:94: closed a stream from the client side

10:03:17 repro2.go:62: closed a stream from the server side
10:03:17 repro2.go:42: TAP ENTER TO SEND THE NEXT NUMBER TO THE CLIENT
10:03:17 repro2.go:94: closed a stream from the client side

10:03:51 repro2.go:50: timeout: no recent network activity
exit status 1
```

Am I using it wrong or does the information not get through over the wire?

Thanks!
