### ISSUE TITLE
A possible deadlock: conflicting lock order between packetHandlerMap and baseServer

### ISSUE THREAD

**Issue by BurtonQin** [lucas-clemente/quic-go#2716]
Lock1: [packetHandlerMap](https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/packet_handler_map.go#L31-L32)
Lock2: [baseServer](https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/server.go#L55-L56)

**Lock1->Lock2**
In `packetHandlerMap.close()`: Lock1 `h.mutex.Lock()` is called before `h.server.setCloseError(e)`
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/packet_handler_map.go#L228-L245
`h.server` is an interface `unknownPacketHandler` which is implemented by `baseServer`
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/server.go#L106
In `baseServer.setCloseError()`: Lock2 `s.mutex.Lock()` is called
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/server.go#L290-L292

**Lock2->Lock1**
In `baseServer.Close()`: Lock2 `s.mutex.Lock()` is called before `s.sessionHandler.CloseServer()`
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/server.go#L268-L274
`s.sessionHandler` is `packetHandlerMap`
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/server.go#L71
In `packetHandlerMap.CloseServer()`: Lock1 `h.mutex.Lock()` is called
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/packet_handler_map.go#L200-L201

I found this conflicting lock order through static analysis. Not sure if it can actually happen in production.

**Comment by marten-seemann** [comment]
It actually can, if you close the connection and the server at the same time. Thanks for uncovering this!

Fixes in #2849.
