### ISSUE TITLE
evaluate Azure Pipelines

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#2722]
Looks like Microsoft built a quite CI. Maybe we can finally replace AppVeyor (and run our integration tests on Windows as well).

To do so, we need to add Azure Pipelines to this repository. @lucas-clemente, can you please it from the MarketPlace https://github.com/marketplace/azure-pipelines?

**Comment by lucas-clemente** [comment]
The setup process keeps failing with a 403…

**Comment by marten-seemann** [comment]
After my failed attempt to migrate the QUIC Interop Runner to Azure, I've gotten the impression that Microsoft still has **a lot** of development work ahead of them to make this useful. I think we're good with GitHub Actions for now.
