### ISSUE TITLE
how to know quic session is closed

### ISSUE THREAD

**Issue by 0990** [lucas-clemente/quic-go#2735]
I search quic session api and not found IsClosed() method,I wonder how to know session is closed

**Comment by marten-seemann** [comment]
`Session.Context()` is what you're looking for:
https://github.com/lucas-clemente/quic-go/blob/7c204d4d9e070263c5bb718b32366669dc7ff28f/interface.go#L180-L182

**Comment by 0990** [comment]
thank you
