### ISSUE TITLE
Long security handshake/leaked goroutine

### ISSUE THREAD

**Issue by aschmahmann** [lucas-clemente/quic-go#2737]
I noticed this goroutine on a go-ipfs node, it seems suspicious to me that after 29 minutes there's a handshake still going on but I also am not familiar with the quic-go internals.

@marten-seemann does this look like a bug, or is it potentially valid behavior?  

```
goroutine 66760407 [chan send, 29m0s]:
github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).SendAlert [0xc105b86780, 0xc057f36f2a]
	pkg/mod/github.com/lucas-clemente/quic-go@v0.16.2/internal/handshake/crypto_setup.go:689
github.com/marten-seemann/qtls.(*Conn).sendAlert [0xc02220b880, 0x2a, 0x0, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/conn.go:838
github.com/marten-seemann/qtls.(*Conn).verifyServerCertificate [0xc02220b880, 0xc0415cedc0, 0x1, 0x1, 0x35d, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/handshake_client.go:877
github.com/marten-seemann/qtls.(*clientHandshakeStateTLS13).readServerCertificate [0xc015a19e20, 0x0, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/handshake_client_tls13.go:464
github.com/marten-seemann/qtls.(*clientHandshakeStateTLS13).handshake [0xc015a19e20, 0xc03a782700, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/handshake_client_tls13.go:89
github.com/marten-seemann/qtls.(*Conn).clientHandshake [0xc02220b880, 0x0, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/handshake_client.go:240
github.com/marten-seemann/qtls.(*Conn).Handshake [0xc02220b880, 0x0, 0x0]
	pkg/mod/github.com/marten-seemann/qtls@v0.9.1/conn.go:1395
github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetup).RunHandshake.func1 [0xc105b86780, 0xc063a3cfc0, 0xc113900a20]
	pkg/mod/github.com/lucas-clemente/quic-go@v0.16.2/internal/handshake/crypto_setup.go:266
created by github.com/lucas-clemente/quic-go/internal/handshake. [*cryptoSetup).RunHandshak]
	pkg/mod/github.com/lucas-clemente/quic-go@v0.16.2/internal/handshake/crypto_setup.go:264
```

**Comment by marten-seemann** [comment]
In #2744, I made the existing timeout integration test a lot stricter: We now test that both peers time out if one of them encounters an error writing to / reading from its packet conn. Additionally, this test now also tests t the hat`RunHandshake` go routine has gone away. Apparently, this doesn't lead to test failures, so a peer going away at a random point in time is probably not the cause of this failure.

We also recently added a [handshake fuzzing test case](https://github.com/lucas-clemente/quic-go/blob/master/fuzzing/handshake/fuzz.go), which replaces handshake messages with random data, thereby testing that a malicious peer can't crash (or time out) the handshake by sending unexpected data in CRYPTO frames. So far, this test hasn't yielded any bugs in quic-go (only in the fuzzing code itself).

**Comment by marten-seemann** [comment]
#2773 theoretically *could* be the fix for this, although that would imply this hang was caused by a maliciously crafted TLS ClientHello.

**Comment by marten-seemann** [comment]
Update: I confirmed that this can't be caused by #2773. While the bug fixed in this PR can lead to the handshake getting stuck in case the client sends a ClientHello with an unsupported TLS version (i.e. the handshake would fail, but no connection error would be send), the regular handshake timeout still works, and would kill the session after 10 seconds.

**Comment by VinozzZ** [comment]
Hi there, is it possible that the code got stuck at `SendAlert()` after the handshake timeout has triggered? Then the `handshakeDone` channel never got closed but there's also no one is receiving from the alertChan

**Comment by marten-seemann** [comment]
Is it? After the handshake timeout has triggered, we wouldn't process any more packets, so there shouldn't be anything that would trigger a TLS alert.

**Comment by egonelbre** [comment]
After inspecting the code a bit, my best guesses how this could happen are:

A: `SendAlert` gets called twice for some reason, however I wasn't able to find a code-path where it would happen.

B: Concurrent `Close` with `SendAlert`. Potential scenario, the connection gets terminated together with an external timeout calling `Close`. The connection termination causes an invalid server certificate - this calls `SendAlert`. Calling `Close` causes it to start waiting for `handshakeDone`. `SendAlert` cannot finish due to nothing waiting for the message.

@aschmahmann does go-ipfs call `Close` when there's some sort of timeout?

**Comment by aschmahmann** [comment]
> @aschmahmann does go-ipfs call Close when there's some sort of timeout?

@marten-seemann may know more, but it might. Once we get a connection object after getting the QUIC session from `quic.DialContext` https://github.com/libp2p/go-libp2p-quic-transport/blob/cb94d99b111b50490a2713972693be7c3036a157/transport.go#L159 then the application could close that connection at any time.

go-ipfs opens connections in a lot of places, so it's a bit difficult to say how the application layer deals with every connection. However, normally we leave connections open and then periodically prune connections that are deemed less useful. There's some leeway time (20 seconds by default) that keeps new connections alive even if they're not super useful.
