### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by wangwanchao** [lucas-clemente/quic-go#2745]
when  I execute `go run example/client/main.go localhost:6121`, I have this problem: 
```
go: finding module for package github.com/lucas-clemente/quic-go/h2quic
example\client\main.go:11:2: no matching versions for query "latest"

```

how can I solve it?

By the way, I want to know where can I get more detail doc about the quic-go?

**Comment by marten-seemann** [comment]
h2quic has not been in use for at least a year, maybe even two.

**Comment by wangwanchao** [comment]
> h2quic has not been in use for at least a year, maybe even two.

There is lib `h2quic` in release-0.10. why dont you have a more detail description? It is beyond my apprehension.
