### ISSUE TITLE
Support CONNECT method

### ISSUE THREAD

**Issue by klzgrad** [lucas-clemente/quic-go#2748]
CONNECT method has no :path. 

The current implementation requires a non-empty path somehow:

https://github.com/lucas-clemente/quic-go/blob/bed802aee5732c8fe373bf4f71e789bea2f7f11f/http3/request.go#L40-L47

Also url.ParseRequestURI will return an error on empty path.

**Comment by marten-seemann** [comment]
If I remember correctly, we took this from the HTTP/2 implementation in the standard library.
Could you point me to how it's handled there?

**Comment by klzgrad** [comment]
I don't know where you took it from but this is the what I can find:

https://github.com/golang/net/blob/62affa334b73ec65ed44a326519ac12c421905e3/http2/server.go#L1984

**Comment by marten-seemann** [comment]
Looks like we only implemented the `else if` branch... Do you want to send us a PR to add CONNECT support?

There's some text about CONNECT in the HTTP/3 spec: https://tools.ietf.org/id/draft-ietf-quic-http-29.html#name-the-connect-method
