### ISSUE TITLE
return tls.ConnectionState from quic.Session.ConnectionState()

### ISSUE THREAD

**Issue by VinozzZ** [lucas-clemente/quic-go#2772]
Hi team, I have found that in v0.11.0 release, we added the change, `Return a tls.ConnectionState from quic.Session.ConnectionState().`
However, it has been changed back to returning `qtls.ConnectionState`. Is it expected to have the application to handle the conversion?
Thank you for all your awesome work!

**Comment by marten-seemann** [comment]
That's correct.

Note that the `qtls.ConnectionState` gives you access to all fields of the `tls.ConnectionState`, plus a field to check if 0-RTT was used: https://github.com/marten-seemann/qtls-go1-15/blob/e2848f7418080d3f0e81e80909a25b5e6a23c388/common.go#L297-L301
