### ISSUE TITLE
any possibilities of automatic ssl letsencrypt, and used as a reverse proxy to customized address and port e.g.127.0.0.1:8081 etc?

### ISSUE THREAD

**Issue by gitmko0** [lucas-clemente/quic-go#2795]
any possibilities of automatic ssl letsencrypt, and used as a reverse proxy to customized address and port e.g.127.0.0.1:8081 etc?

**Comment by marten-seemann** [comment]
You can use any tls.Config you like. Generating this config is none of quic-go’s responsibilities though. I believe there are implementations of the ACME protocol in Go, so this probably won’t be more than a few lines of code.
