### ISSUE TITLE
possible to have an example code that's more real world practical?

### ISSUE THREAD

**Issue by gitmko0** [lucas-clemente/quic-go#2796]
would like to use quic-go as a reverse proxy to web server.
e.g. (this is in fasthttp)
https://play.golang.org/p/aPLj8KF5FtU

possible to give an example like the code i've generated? it'll be a great no brainer quic-letsencrypt code for the masses for huge adoption

**Comment by marten-seemann** [comment]
Building a reverse proxy really isn't in the scope of a QUIC or HTTP/3 implementation. I'm sure you can find plenty of examples how to do so on the internet.
