### ISSUE TITLE
qtls.ClientSessionState not compatible with tls.ClientSessionState or running clang failed

### ISSUE THREAD

**Issue by fsyyft** [lucas-clemente/quic-go#2801]
Go Version: 1.15.2

When require 0.14.4, build success, bus can not run application.

`panic: qtls.ClientSessionState not compatible with tls.ClientSessionState`

When require  0.15.x or 0.16.x or 0.17.x or 0.18.0, build fail.

```
/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: sectionForAddress(0x74465E) address not in any section file '/var/folders/qj/4y8pczjj6v5828wk6twsj4100000gn/T/go-link-796586071/go.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

build with `-ldflags="-w"`, it is ok , why ?

**Comment by marten-seemann** [comment]
That’s expected. If you build an old version, you’ll need an old Go version. Not sure why you’d want to build an old version in the first place though...

**Comment by fsyyft** [comment]
Well, at the beginning, I used version `0.18.0`, but when I compiled without `-LDflags ="-w"`, there would be an error, so I used a different version to try, generally try backwards, try to version `0.14.4`, the compilation was passed, but there was a panic.

Now the question is, is this also expected if the compilation fails without `-LDflags ="-w"?` @marten-seemann 

thank you!

**Comment by fsyyft** [comment]
Go version 1.15.2
quic-go version 0.18.0

Successful sample

```
 go build -ldflags="-w" -o ./bin/example example/cmd/example
```

Failure sample

```
go build -o ./bin/example example/cmd/example   
# example/cmd/example
/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: sectionForAddress(0x74483E) address not in any section file '/var/folders/qj/4y8pczjj6v5828wk6twsj4100000gn/T/go-link-636049088/go.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by marten-seemann** [comment]
I see, so this is not related to qtls.
What exactly is `-ldflags="-w"` supposed to do? I don't think I've ever used it. 
This error doesn't look like a quic-go issue to me, maybe related to https://github.com/golang/go/issues/40974?

**Comment by fsyyft** [comment]
I think it's probably also a go problem;

I'm still wondering why I don't have this problem with `quic-Go` version `0.14` or less.

Well, that goes beyond the quic-Go question, thank you very much!

**Comment by fsyyft** [comment]
I don't know what happened, but according to your thinking, so far my problem has been solved. @marten-seemann 

In my project, I have a piece of code that I put in the init method, and when I modify it, I'm done.

Old

```
func init() {
	sentinelCommand := newSentinelCommand()
	quicCommand := newQUICCommand()

	newbieRootCommand.Command().AddCommand(
		sentinelCommand.Command(),
		quicCommand.Command(),
	)
}

func Run() {
	newbieRootCommand.Run()
}
```

New

```
func preRun() {
	sentinelCommand := newSentinelCommand()
	quicCommand := newQUICCommand()

	newbieRootCommand.Command().AddCommand(
		sentinelCommand.Command(),
		quicCommand.Command(),
	)
}

func Run() {
	preRun()
	newbieRootCommand.Run()
}
```

**Comment by marten-seemann** [comment]
That means you can't use `init` any more?

**Comment by fsyyft** [comment]
> That means you can't use `init` any more?

I don't know what's going on, but I guess you're right, maybe there's a little loop in init itself that's causing the compilation to go wrong.



What I don't understand is why adding -LDflags ="-w" should be ok.
