### ISSUE TITLE
Quic versions draft-ietf-quic-transport-xx unofficial supported?

### ISSUE THREAD

**Issue by BitFis** [lucas-clemente/quic-go#2808]
Hey guys

I have some short questions. I have issues to communicate with other quic clients (aka. [aioquic](https://github.com/aiortc/aioquic) / [picoquic](https://github.com/private-octopus/picoquic)).
It seemed to be connected to the version, it seems that quic-go only supports [Google Quic versions](https://github.com/quicwg/base-drafts/wiki/QUIC-Versions). Does that mean the draft-ietf-quic-transport-xx are not supported at all?

To test if communication is at all possible, I changed following lines, which enabled seemingly successful communication;

```diff
--- c/internal/protocol/version.go
+++ i/internal/protocol/version.go
@@ -18,8 +18,9 @@ const ( 
 // The version numbers, making grepping easier
 const (
-   VersionTLS      VersionNumber = 0x51474fff
-   VersionWhatever VersionNumber = 1 // for when the version doesn't matter
+   //VersionTLS VersionNumber = 0x51474fff
+   VersionTLS      VersionNumber = 0xff00001d // change TMP to offical IETF Version
+   VersionWhatever VersionNumber = 1          // for when the version doesn't matter
    VersionUnknown  VersionNumber = math.MaxUint32
 )
```

Is it possible to set the supported version outside
the library? Is there a cleaner way to achievethis without changing
internal code? Is this the goal of Expose version information #1271?

I might be having the a wrong understanding of how the different [quic versions](https://github.com/quicwg/base-drafts/wiki/QUIC-Versions) are connected or are not connected.
Thank you for the help,
cheers

**Comment by marten-seemann** [comment]
It’s the other way round: we only support IETF QUIC version.

Please use a tagged release, not the master branch.
