### ISSUE TITLE
Allow passing in context when using 0RTT

### ISSUE THREAD

**Issue by VinozzZ** [lucas-clemente/quic-go#2812]
Hi there,

My team is trying to utilize the 0RTT feature from QUIC.  We use context cancellation in our code. However, I have noticed that `quic-go` provides `DialAddrContext` but no `DialAddrEarlyContext`. Is it possible that we can add another method for `DialAddrEarly` that can take in a context?

**Comment by marten-seemann** [comment]
That seems consistent with what we have now. Want to send us a PR that adds those two methods?

**Comment by VinozzZ** [comment]
Great! Yes, I will put up a PR for adding `DialAddrEarlyContext`

**Comment by marten-seemann** [comment]
Would be great if you could also add a `DialEarlyContext`, so we context for all variants of dial functions.
