### ISSUE TITLE
Receiving closed error on the server stream when client close its session

### ISSUE THREAD

**Issue by VinozzZ** [lucas-clemente/quic-go#2819]
Hi there, 

Periodically, I would get `Application error: 0x100` from `AcceptStream()` after client side called `session.CloseWithError(0x100, "")`. Then my server would exit due to such error. 
I see that in the `http3` package, we are only logging out the error from `AcceptStream` and return nil. Is that the correct way to handle errors from `AcceptStream` method? If so, do you mind to explain to me why that's the case?

Thanks!

**Comment by marten-seemann** [comment]
That's expected. `AcceptStream` will return the error that the session was closed with.

**Comment by VinozzZ** [comment]
I see. Is there a way to close a connection without an error? I can only find `CloseWithError` API

**Comment by marten-seemann** [comment]
Applications are to free to define their own error codes.
