### ISSUE TITLE
Is there a way to set a handler which is used to handle non-quic packets?

### ISSUE THREAD

**Issue by go101** [lucas-clemente/quic-go#2823]
Some apps might need handle both quic and non-quic packets for a session.

**Comment by marten-seemann** [comment]
There's no API, but you can wrap the packet conn.

**Comment by go101** [comment]
How to? My current understanding is that a custom function calling another ReadFrom is needed. How to prevent this ReadFrom and the one in quic-go internal from mutual interference?
