### ISSUE TITLE
how do i use quic-go? hving the problem below

### ISSUE THREAD

**Issue by gitmko0** [lucas-clemente/quic-go#2829]
go get github.com/lucas-clemente/quic-go    
# github.com/lucas-clemente/quic-go/internal/qtls
/go/src/github.com/lucas-clemente/quic-go/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate

**Comment by eoeac** [comment]
How is this problem solved?

**Comment by luyuming** [comment]
it happens again，the console give a prompt -- require go 1.14。

# github.com/lucas-clemente/quic-go/internal/qtls
../goProject/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.2/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate
note: module requires Go 1.14


I use go 1.13.8 version，does any older quic-go version support  go 1.13.x version or I have to update my go version to  1.14?
