### ISSUE TITLE
Can't connect quictransport via Chrome.

### ISSUE THREAD

**Issue by okgame** [lucas-clemente/quic-go#2832]
Hello,

I can't connect quictransport via Chrome.
This issue look like https://github.com/lucas-clemente/quic-go/issues/2696 , but i use newest Chrome.

**Golang version**: 1.14
**Client 1**: Google Chrome verison 86.0.4240.75 + https://googlechrome.github.io/samples/quictransport/client.html
**Client 2**: Google Chrome Canary verison 88.0.4301.0 + https://googlechrome.github.io/samples/quictransport/client.html
**Code server**: https://gist.github.com/FZambia/07dca3a7a75a264746101cd5657f1150
**SSL Key:** Let's Encrypt
**Enable Quic**: Yes (chrome.exe --enable-quic --quic-version=h3-29)
**Quic H3-29 work:** Yes (https://i.imgur.com/kenufKX.png)
Register Origin-trial key for domaintest: Yes

Test with Chrome.
Error show in Console.
_Failed to establish a connection to quic-transport://domaintest:4433/: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_INVALID_VERSION (Client may support one of the versions in the server's list, but it's going to close the connection anyway. Supported versions: {draft29,draft27}, peer supported versions: {})._

Edit code echo.go of quic-go for connect to server: https://github.com/lucas-clemente/quic-go/blob/master/example/echo/echo.go
It work: https://i.imgur.com/DdAtO0J.png

I am newbie, sorry for basic question.

Please give me some advice.

Thank you.

**Comment by marten-seemann** [comment]
Please use a released version of quic-go.
