### ISSUE TITLE
When will the next new stable release be published?

### ISSUE THREAD

**Issue by VinozzZ** [lucas-clemente/quic-go#2834]
Hi there,

I'm hoping to utilize the change that reduce dependencies when one imports `quic-go`.
Do you know when that change will be published into a stable release?

thank you in advance

**Comment by marten-seemann** [comment]
Soon(-ish).

**Comment by marten-seemann** [comment]
Targeting a new release by middle / end of the week. If you want to get any changes in, now would be a good time to send the PR.
