### ISSUE TITLE
Use Google Chrome to visit Http3 Server

### ISSUE THREAD

**Issue by DEVINccp** [lucas-clemente/quic-go#2842]
I run the example in /quic-go/example folder, my command is: 
go run main.go -v -trace -qlog -tcp -bind=127.0.0.1:6121
When I use google chrome to visit https://127.0.0.1:6121/demo/echo, there is an error in chrome: certificate invalid; 
quic server also has an error: http: TLS handshake error from 127.0.0.1:50788: remote error: tls: unknow certificate.

I just want to use chrome to visit quic server.
Can anyone help me? thx

**Comment by marten-seemann** [comment]
As the error message says, the certificate you're using is invalid.

**Comment by DEVINccp** [comment]
ok, thx,I have solved this problem.
