### ISSUE TITLE
Large number of packets during initial handshake

### ISSUE THREAD

**Issue by folbricht** [lucas-clemente/quic-go#2852]
I'm using QUIC for DNS which is of course sensitive to latency and noticed that the initial handshake is rather slow (slower than regular TLS over TCP). Looking at the PCAP, there seems to be a large number of packets exchanged between client and server before the connection is up. I don't know enough about QUIC to tell why that's happening. Perhaps I'm using it wrong?

This is with 0.18.1, and it seems to happen in all combinations, quic-go to external services, between quic-go client/server, http3 or not. Here's a very basic example:

Server
```go
func main() {
	panic(http3.ListenAndServeQUIC("127.0.0.2:4242", "server.crt", "server.key", nil))
}
```

Client
```go
func main() {
	client := http.Client{
		Transport: &http3.RoundTripper{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}},
	}
	resp, err := client.Get("https://127.0.0.2:4242/")
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
}
```

![Screenshot from 2020-11-01 09-23-37](https://user-images.githubusercontent.com/3505107/97808782-1618ef80-1c26-11eb-8fd8-686dce8c2b8b.png)

Is this expected? If not, any pointers as to why this might be?

**Comment by marten-seemann** [comment]
You might want to disable retries (conditionally?), otherwise your QUIC handshake will always take 2 round trips.
Other than that, the trace is distorted by the fact that you're running on localhost with a negligible RTT, which makes the retransmission timer fire very early.
