### ISSUE TITLE
A Simple issue

### ISSUE THREAD

**Issue by DEVINccp** [lucas-clemente/quic-go#2860]
I use the official version of Google Chrome to visit the example in release 0.18.1; I use QUIC Indicator can not find the symbol (HTTP/3) when I use chrome to visit the server in /example/main.go;

I also know that chrome support Google QUIC, But I also find chrome will support IETF QUIC[This Link](https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html). 

Now, Can we now use the official version of Google Chrome to access the quic0.18.1 server？
or, we must use chrome Beta?

**Comment by marten-seemann** [comment]
Probably you need to set some command line flags to make it work. As this is an issue with Chrome and not with quic-go, I'll close it.
