### ISSUE TITLE
Add support for draft-banks-quic-disable-encryption-00

### ISSUE THREAD

**Issue by emersion** [lucas-clemente/quic-go#2868]
https://datatracker.ietf.org/doc/draft-banks-quic-disable-encryption/

This extension allows clients and servers to opt-out of encryption. My use-case is setting up a reverse proxy:

```
[public internet] <----- secure QUIC -----> [reverse proxy] <----- QUIC without TLS -----> [backend]
```

**Comment by marten-seemann** [comment]
I don't think this extension is a good idea. quic-go won't support any unencrypted QUIC.

**Comment by emersion** [comment]
Can you elaborate? Is the use-case unappealing? Are you concerned about people enabling it for the public Internet?

If you're concerned about the latter:

- The RFC says it MUST NOT be used on the public Internet
- Both sides need to opt out, meaning a server or a client can't disable encryption on its own
- Would you be more comfortable with this RFC if it could only be enabled by importing a different package?

**Comment by marten-seemann** [comment]
1. It's not an RFC. It's an individual draft that has not been adopted by the QUIC working group, and in fact **cannot** be adopted by the QUIC working group, as the group chartered to deliver an always-encrypted transport protocol.
2. I don't think there's a clear definition of what constitutes "the public internet". In times of cloud computing and multi-tenant architectures, one could argue that there's no such thing. We've all learned this lesson the hard way (Thank you Snowden!)
![image](https://user-images.githubusercontent.com/1478487/98459764-5bae5d00-21d0-11eb-9c3e-f76a027621e4.png)
3. On a more technical level, I haven't seen any convincing use case where the cost of encryption would be prohibitively high.

**Comment by emersion** [comment]
All right, I'll just wait for this to become an RFC and bump this again when that happens.

**Comment by someview** [comment]
We also need this.
