### ISSUE TITLE
error "conn_helper_generic.go:10:60: undefined: syscall.IP_RECVTOS" in DragonFly BSD

### ISSUE THREAD

**Issue by kslr** [lucas-clemente/quic-go#2880]
```bash
GOOS=dragonfly GOARCH=amd64 

../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.1/conn_helper_generic.go:10:60: undefined: syscall.IP_RECVTOS
```

**Comment by marten-seemann** [comment]
Not sure of Dragonfly is used enough to warrant fixing this. I’d be willing to review a PR though, if you want to contribute a fix.

**Comment by kslr** [comment]
> Not sure of Dragonfly is used enough to warrant fixing this. I’d be willing to review a PR though, if you want to contribute a fix.

I think it might be 68

https://gitweb.dragonflybsd.org/freebsd.git/blob/32041f44edbadf78cfaf57b4d6a30f5c41b4732d:/sys/netinet/in.h#l465

**Comment by marten-seemann** [comment]
@kslr Thank you for the PR. Have you tested it locally? Is there any way to test it on CI, so we don't break it accidentally in the future?
