### ISSUE TITLE
Fails to compile with gccgo

### ISSUE THREAD

**Issue by Splizard** [lucas-clemente/quic-go#2883]
Compiling the package with gccgo (GCC10) on Ubuntu results in:

```
/usr/bin/ld: ~/.cache/go-build/23/2336227077038d68f137aff2289715ee27beab225944a06e6152d2153d25eaf7-d(_go_.o): 
in function `github.x2ecom..z2flucas..z2dclemente..z2fquic..z2dgo..z2finternal..z2fqtls.CipherSuiteTLS13ByID':
~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.0/internal/qtls/go114.go:177: 
undefined reference to `github.com..z2fmarten..z2dseemann..z2fqtls.cipherSuiteTLS13ByID'
```

Exporting cipherSuiteTLS13ByID to CipherSuiteTLS13ByID allows the package to compile.
This may be a gccgo bug?

**Comment by marten-seemann** [comment]
I guess it doesn't like `go:linkname` then? Afaik this is valid Go code though. Maybe it's worth opening an issue with gccgo?

https://github.com/lucas-clemente/quic-go/blob/287a324acff8762e664998313ff8412e449010c6/internal/qtls/go115.go#L101-L102

**Comment by marten-seemann** [comment]
@Splizard I'm closing this issue for now. I'd appreciate if you could update this issue when you have any news from gccgo though.
