### ISSUE TITLE
Chrome 87 fails on key updates

### ISSUE THREAD

**Issue by klzgrad** [lucas-clemente/quic-go#2901]
Chrome 87 with `--enable-quic --quic-version=h3-29` downloads a large file from quic-go's example server on localhost (`sudo ./main -bind 127.0.0.1:443 -www /tmp -qlog` with some certificate and /etc/hosts setup).

After the first several megabytes the connection stalls and the server reports:
```
server Peer closed session with error: NO_ERROR: 85:Network blackhole detected
server could not flush to stream: NO_ERROR: 85:Network blackhole detected
```

The qlog is quite large so I won't attach it. I believe this is now easy to reproduce.

**Comment by marten-seemann** [comment]
As I’ve asked before, please attach a log or a qlog.

**Comment by klzgrad** [comment]
[server_56c0d949cba8b5bc.qlog.zip](https://github.com/lucas-clemente/quic-go/files/5582714/server_56c0d949cba8b5bc.qlog.zip)

**Comment by marten-seemann** [comment]
Looks like Chrome is not properly responding to the key update and fails to decrypt any packet sent under the new keys.

**Comment by klzgrad** [comment]
What are the next steps? Is this a bug of either side or is it a generic interop issue which fixes itself over time? Should I try older versions of quic-go?

**Comment by marten-seemann** [comment]
This is a bug in Chrome.

**Comment by klzgrad** [comment]
Thanks for the pointer.

I looked for QUIC Key Update support and it was added in Chrome v88. I tested it with Chrome dev channel and this issue is no more.
