### ISSUE TITLE
Error when upgrade from v0.18.1 > v0.19.2

### ISSUE THREAD

**Issue by okgame** [lucas-clemente/quic-go#2919]
Hello,
I got this error when upgrade from v0.18.1 > v0.19.2

> Failed to sufficiently increase receive buffer size. Was: 208 kiB, wanted: 2048 kiB,                                                                                                                         got: 416 kiB.

Server Centos 7.
Golang 1.14 + v0.18.1: No error.
Golang 1.15 + v0.18.1: No error
Golang 1.14 + v0.19.2: Show Error
Golang 1.15 + v0.19.2: Show Error

Run with quic run: Show error log one time and work well.
Run with pm2: Show error log many time + reload app every few seconds.

Please give me some advice.

**Comment by marten-seemann** [comment]
You should consider increasing the kernel UDP receive buffer size. Performance will suffer if you don't.
