### ISSUE TITLE
Quictransport not work when embed from site use http

### ISSUE THREAD

**Issue by okgame** [lucas-clemente/quic-go#2920]
Hello,

Quictransport not work in case below.

domain.A: quictransport + statics file
domain.B: https + html site + load resource from domain.A + registed quic trial key.
domain.C: embed iframe to domain.B.

When domain.C use https: resource from domain.A can load via quictransport.
When domain.C use http: resource from domain.A can't load via quictransport.

But when i test with youtube embed withh case domain.C use http.
It work well, youtube can load resource from H3-Q50.
Are my test is wrong or quictransport diffrent quic http3?

**Comment by marten-seemann** [comment]
I don't know what you mean by "quictransport". This repository contains the code quic-go, and since you're doing H3 I doubt you're referring to [go-libp2p-quic-transport](https://github.com/libp2p/go-libp2p-quic-transport/).
