### ISSUE TITLE
Is Mutual TLS authentication supported?

### ISSUE THREAD

**Issue by liuzhiyi1993** [lucas-clemente/quic-go#2938]
Both quic and http3 examples given by quic-go use  one-way tls auth, is mutual tls auth also supported?

**Comment by marten-seemann** [comment]
What do you mean by mutual auth? You can use client certificates, please refer to the documentation of `crypto/tls` for the details.

**Comment by liuzhiyi1993** [comment]
Ah, was just wondering if I could use client certificates. Thx:)
