### ISSUE TITLE
Get "https://google.com": No compatible QUIC version found.

### ISSUE THREAD

**Issue by aep** [lucas-clemente/quic-go#2943]
the error message is a bit confusing, since it claims 

> server offered [draft-29 0x8a4a1a1a 0x54303531 0x51303530 gQUIC 46 gQUIC 43]

but draft-29 should be supported according to README.md

instead the output 

> We support [TLS dev version (WIP)],

doesnt indicate which versions are actually supported by quic-go

this appears to be intentional according to https://github.com/lucas-clemente/quic-go/blob/9693a46d31c6a699b22bc24e94797f8e582525d3/internal/protocol/version.go#L38

but how do you test current master then during development?

**Comment by marten-seemann** [comment]
This is correct. Please don’t use the current master, use a release.
