### ISSUE TITLE
How to use bbr-quic for congestion control algorithm? (Novice asks)

### ISSUE THREAD

**Issue by Fhokud** [lucas-clemente/quic-go#2957]
How should I use it?

  - For QUIC BBR:
 https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr_sender.cc
      https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr_sender.h

**Comment by marten-seemann** [comment]
You don't. This is a Go project, you don't just run C++ code from a third party project.
