### ISSUE TITLE
Example Server "/demo/upload" endpoint not working

### ISSUE THREAD

**Issue by saptarsi96** [lucas-clemente/quic-go#2959]
When I am trying to upload some files in this endpoint from the example client I am not getting the required response.
![Screenshot from 2020-12-28 00-06-58](https://user-images.githubusercontent.com/29809001/103177481-e2161f80-48a0-11eb-8774-1021de1200b9.png)

**Comment by saptarsi96** [comment]
How to use the example server to upload files? Any help will be appreciated. I am using the client to upload files to the server.
 @0xVikas?

**Comment by marten-seemann** [comment]
You can use your web browser. If you want to drive this using Go, have a look at the documentation for the http.Client.

**Comment by saptarsi96** [comment]
Sorry to disturb you again but when I am trying to access this endpoint using a web browser it's not working. Can you please suggest something or guide me in the right direction. 
![Screenshot from 2020-12-28 17-48-10](https://user-images.githubusercontent.com/29809001/103213899-176c4d00-4935-11eb-8b50-7e196e8a8334.png)

**Comment by 0xVikas** [comment]
Try using https

**Comment by saptarsi96** [comment]
I am using https only.Still not getting the response in the web [browser.]
I am using the following example codes. [Server](https://github.com/lucas-clemente/quic-go/blob/master/example/main.go) & [Client](https://github.com/lucas-clemente/quic-go/blob/master/example/client/main.go)
![Screenshot from 2020-12-28 18-21-06](https://user-images.githubusercontent.com/29809001/103215495-8481e180-4939-11eb-9c36-55474e4bd020.png)
![Screenshot from 2020-12-28 18-20-53](https://user-images.githubusercontent.com/29809001/103215498-88156880-4939-11eb-808b-e211ec3f1032.png)

**Comment by 0xVikas** [comment]
Maybe the browser doesn't support quic(or supports a different version of quic). There aren't many clients that you can use with quic protocol.

**Comment by saptarsi96** [comment]
For this project which web-browser/client were you using?

**Comment by 0xVikas** [comment]
I couldn't find any working client for my project. So I used the same [Client](https://github.com/lucas-clemente/quic-go/blob/master/example/client/main.go) and forwarded the data to a local proxy running at the client side. Refer to [client.go](https://github.com/0xVikas/mpquic-demo/blob/master/client.go)

**Comment by saptarsi96** [comment]
h2quic module has been updated to "github.com/ipsn/go-ipfs/gxlibs/github.com/lucas-clemente/quic-go/h2quic".
Your client function fails with the following errors. Can you please update those.
![Screenshot from 2020-12-28 18-49-46](https://user-images.githubusercontent.com/29809001/103217002-85b50d80-493d-11eb-8e6a-a0581a9b0f2d.png)

**Comment by 0xVikas** [comment]
Refer to the setup instructions provided. Move further discussions regarding this to the [mpquic-demo](https://github.com/0xVikas/mpquic-demo) repo issues.
