### ISSUE TITLE
Session interface methods and blocking API to accept streams and receive datagrams

### ISSUE THREAD

**Issue by FZambia** [lucas-clemente/quic-go#2960]
Hello.

First of all thanks a lot to all the contributors for work on the package.

I have a question regarding the current API of `Session`. At this moment it has the following blocking methods: `AcceptStream`, `AcceptUniStream`, `ReceiveMessage`.

This means that an application that processes different types of streams from a client including UDP receiving should use at least 3 goroutines just to accept streams and receive UDP:

```go
sess, _ := listener.Accept(context.Background())
go acceptBidiStreams(sess)
go acceptUniStreams(sess)
receiveUDP(sess)
```

For servers that work with many clients this can be rather expensive (in terms of memory consumption since every goroutine adds about 2.6kb of memory). I am mostly thinking about WebSocket-like servers that work with many simultaneous connections from different clients.

I looked at other QUIC implementations, for example Python Quic on top of asyncio:

```python
class CounterHandler:

    def __init__(self, connection) -> None:
        self.connection = connection
        self.counters = defaultdict(int)

    def quic_event_received(self, event: QuicEvent) -> None:
        if isinstance(event, DatagramFrameReceived):
            payload = str(len(event.data)).encode('ascii')
            self.connection.send_datagram_frame(payload)

        if isinstance(event, StreamDataReceived):
            self.counters[event.stream_id] += len(event.data)
            if event.end_stream:
                if is_client_bidi_stream(event.stream_id):
                    response_id = event.stream_id
                else:
                    response_id = self.connection.get_next_available_stream_id(
                        is_unidirectional=True)
                payload = str(self.counters[event.stream_id]).encode('ascii')
                self.connection.send_stream_data(response_id, payload, True)
                del self.counters[event.stream_id]
```

Also NodeJS has event-driven approach (obviously):

```javascript
socket.on('session', async (session) => {
  // A new server side session has been created!

  // The peer opened a new stream!
  session.on('stream', (stream) => {
    // Let's say hello
    stream.end('Hello World');

    // Let's see what the peer has to say...
    stream.setEncoding('utf8');
    stream.on('data', console.log);
    stream.on('end', () => console.log('stream ended'));
  });
```

The same for a client-side in browsers (WebTransport implementation): it's possible to run asynchronous functions to consume streams and read datagrams. [Example](https://googlechrome.github.io/samples/webtransport/client.js).

I suppose it's a legal case when a client sends UDP and opens various types of streams with a server in random moments inside one connection. So at first glance API where developers can use only one goroutine for accepting streams and reading UDP seems reasonable to have (maybe over channels, maybe functional). I.e. - do not consume several goroutines just for accepting things. Maybe not very idiomatic for Go – but practical.

Another thing that bothers me a bit is that each accepted stream should be also processed in a separate goroutine, I suppose this is very similar in its nature to my main question here.

What do you think?

**Comment by marten-seemann** [comment]
I'd be more worried about having one Go routine per stream than the one or two Go routines you need to serve a session. That said, Go routines are cheap, and even a consumer notebook is able to handle millions of them at a time.

The API you're suggesting is very different from every other API found in the Go ecosystem. Go is all about having blocking APIs and spawning Go routines to do so, not about juggling callbacks. I don't see any precedent for this in the standard library, in fact, it is encouraged to implement `io.Reader` and `io.Writer` as frequently as possible.

**Comment by FZambia** [comment]
Thanks for your response @marten-seemann. I understand your opinion and I think this is a right and idiomatic choice for most apps.

At the same time I am sure that it won't fit very well **some** servers with many concurrent connections since the question already araised ([one](https://www.freecodecamp.org/news/million-websockets-and-go-cc58418460bb/), [two](https://github.com/golang/go/issues/15735), [three](https://github.com/golang/go/issues/36973)) in Go community - and this can become even more relevant in context of QUIC where we need to have even more goroutines blocking for nothing. I have not suggested fully changing API here, but rather thinking about an alternative way to deal with things keeping existing package API.
