### ISSUE TITLE
How to upload a file using client in example

### ISSUE THREAD

**Issue by saptarsi96** [lucas-clemente/quic-go#2969]
When I am trying to run the example client[](https://github.com/lucas-clemente/quic-go/tree/master/example/client) and server[](https://github.com/lucas-clemente/quic-go/blob/master/example/main.go) I am getting the following output. The file is never uploaded. Can you please suggest how to use the upload endpoint to send a POST request to upload the file? 

![Screenshot from 2020-12-31 11-31-17](https://user-images.githubusercontent.com/29809001/103396909-cd18e500-4b5b-11eb-8282-f0aa31f38d80.png)

**Comment by marten-seemann** [comment]
Duplicate of #2959.
