### ISSUE TITLE
Quic-Go team, are you ok?

### ISSUE THREAD

**Issue by okgame** [lucas-clemente/quic-go#3000]
Hello,
I m big fan of quic-go.
I check project quic-go 2-3 times per day.
I saw quic-go have no new commit since 7 days ago.
Marten-seemann still work in Action and Pull Request review for lucas-clemente, but lucas-clemente no reply.

I have a bit worries. 
Is Quic-Go team/Mr.lucas-clemente ok?
I hope all you well.

**Comment by marten-seemann** [comment]
@okgame, I can assure you that both me and @lucas-clemente are fine. As you can see from the large number of open PRs, there will be a bunch of progress on this repository very soon.
