### ISSUE TITLE
SendStream doesn't complete if canceled when it has inflight frames or queued retransmissions

### ISSUE THREAD

**Issue by rip-create-your-account** [lucas-clemente/quic-go#3002]
`cancelWriteImpl` does not call `onStreamCompleted` if there is inflight frames for the stream. If any of those inflight frames is lost then `queueRetransmission` is called. It does not check for completion but queues the frame for retransmission. That retransmission never happens because `popStreamFrame` checks if `cancelWrite` flag has been set and returns early. `onStreamCompleted` is never called.

I think `queueRetransmission` should check `cancelWrite` flag and not add the frame to retransmission queue if set. Then it would check for completion. `cancelWriteImpl` should also clear the retransmission queue before checking for completion.

**Comment by marten-seemann** [comment]
Wow, good catch! Once again!

**Comment by marten-seemann** [comment]
> I think queueRetransmission should check cancelWrite flag and not add the frame to retransmission queue if set. 

Agreed.

> Then it would check for completion.

The stream should complete as soon as `CancelWrite` is called (or it is triggered by receiving a STOP_SENDING frame).
