### ISSUE TITLE
New session is left to linger if created while (*packetHandlerMap).CloseServer is executing

### ISSUE THREAD

**Issue by rip-create-your-account** [lucas-clemente/quic-go#3019]
This happens when `(*baseServer).Close` calls `(*packetHandlerMap).CloseServer` before `(*baseServer).createNewSession` calls `(*packetHandlerMap).AddWithConnID`.

`(*packetHandlerMap).CloseServer` will shutdown the active sessions while `(*packetHandlerMap).AddWithConnID` blocks on the mutex. Eventually `(*packetHandlerMap).AddWithConnID` runs and adds the Session successfully. The Session then ends in `(*baseServer).handleNewSession` where it waits until handshake/idle timeout. `(*baseServer).Close` does nothing additional that could cause this Session to close.

I didn't find easy way to write a test to validate this so this is only based on reading the code.

**Comment by marten-seemann** [comment]
Interesting. Good catch!

So it seems like an easy fix for this would be to make sure that `(*packetHandlerMap).CloseServer()` is called after the `*baseServer` has shut down in
https://github.com/lucas-clemente/quic-go/blob/53b1cbb5010c405497c90c85066e267f08135032/server.go#L276-L296

For example by using a `defer s.sessionHandler.CloseServer()`. That would solve the race condition you've discovered, wouldn't it?

**Comment by marten-seemann** [comment]
Or rather, by moving `s.sessionHandler.CloseServer()` to the end of `(*baseserver).Close()`.
