### ISSUE TITLE
Connection timedout due to lack of progress

### ISSUE THREAD

**Issue by TroyDota** [lucas-clemente/quic-go#3022]
```*qerr.QuicError=&{12 0 connection timed out due to lack of progress false false})```

Occasionally this error is thrown. Not sure why.

**Comment by TroyDota** [comment]
When trying to request the same file again it fails and does not work.

**Comment by marten-seemann** [comment]
That’s not a quic-go error.

**Comment by TroyDota** [comment]
@marten-seemann where is the error from then?

**Comment by marten-seemann** [comment]
Googling the error message, this seems to be an lsquic error.
