### ISSUE TITLE
Maintain client stream open

### ISSUE THREAD

**Issue by DouglasSL** [lucas-clemente/quic-go#3025]
Hello!
I've been trying to open a single client stream and use it to send multiple messages, but after completing the first request it stops, like the server is not available anymore. Is it possible to maintain it open?
[Here](https://play.golang.org/p/Q5qme2lDgzL) is the sample that I've made.
The particular problem that I have is keeping the session and stream out of the loop to avoid create them over and over:
```
func runClient() error {
	...
	session, err := quic.DialAddr(addr, tlsConf, nil)
	if err != nil {
		return err
	}

	stream, err := session.OpenStreamSync(context.Background())
	if err != nil {
		return err
	}

	for i := 0; i < 10; i++ {
		_, err = stream.Write([]byte(messageClient))
		if err != nil {
			return err
		}
                ...
	}
}
``` 
Thanks in advance.

**Comment by marten-seemann** [comment]
The stream is only closed when you call `stream.Close()`.

**Comment by deshmukhrajvardhan** [comment]
The problem is that on the Server you expect new connection and stream and block on it
```
	for {
		sess, err := listener.Accept(context.Background())
		if err != nil {
			return err
		}

		stream, err := sess.AcceptStream(context.Background())
		if err != nil {
			return err
		}
```
Get these out of the loop and your code will work @DouglasSL
