### ISSUE TITLE
add a quic.Config option for STK checks

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#303]
We currently require a STK on all connections, which requires 2 RTTs for the initial connection. We should think about relaxing this, or making it configurable.

**Comment by marten-seemann** [comment]
What do you think of adding a `func VerifySourceAddress() bool` to the `quic.Config`? As a default value, we could provide a function that always returns `true`.

A reasonable way to use that for an application would be to collect some statistics about the ratio of successful connection establishments using the `ConnStateCallback`, and dynamically decide whether to require an STK based on that.

**Comment by lucas-clemente** [comment]
What information would you pass to that function? Definitely the IP, but what else?

**Comment by marten-seemann** [comment]
That's a good question. Apart from the IP, at that moment in the handshake all we have is the CHLO, but I doubt that any value in there provides any useful information.

**Comment by marten-seemann** [comment]
I'd suggest implementing it with the remote `net.Addr` (instead of the IP) for now. We might revisit this when switching to TLS 1.3.

**Comment by lucas-clemente** [comment]
Please pass a struct to that function to make it easier to add more infos later without breaking the API. Also, I'd have the time of issuance of the token included.

**Comment by marten-seemann** [comment]
After offline discussion with @lucas-clemente, we agreed on the following:

The function signature will be: `func VerifySourceAddress(STKOptions) bool`.
With the `STKOptions` struct
```go
type STKOptions struct {
  remoteAddr net.Addr
  sentTime time.Time
}
```
(more fields might be added later)

`sentTime` is set iff the CHLO contains a `TagSTK` field and is the timestamp encoded in the STK.

The default value for the for `VerifySourceAddress` is the following:
```go
func VerifySourceAddress(opts STKOptions) bool {
  return opts.sentTime.IsZero() || 
    time.Now().After(opts.sentTime.Add(protocol.DefaultValidityPeriod))
}
```
i.e. we will send the client a new STK in these two cases:
1. he didn't send any STK in the CHLO or
2. he sent an STK but it already expired (in the default period)

**Comment by marten-seemann** [comment]
I have to say, I don't find this very intuitive anymore. `VerifySourceAddress` is called twice during the handshake:

1. when receiving the first (inchoate) CHLO. In that case only `STKOptions.remoteAddr` is set, `STKOptions.sentTime` is unset. `VerifySourceAddress` then decides, based on the IP address, if an STK should be sent.
2. when receiving a CHLO containing a `TagSTK`. In that case, `VerifySourceAddress` is called (but only if the STK provided matches the address). `VerifySourceAddress` then decides if it considers the STK as expired.

**Comment by marten-seemann** [comment]
Different proposal:

The `STKOptions` only contains the remote addr:
```go
type STKOptions struct {
  remoteAddr net.Addr
}
```

`VerifySourceAddress` is called only once during the handshake, when we receive the first CHLO. It has the following signature (and default value):
```go
func VerifySourceAddress(opts STKOptions) (bool, time.Time) {
  return true, time.Now().Add(protocol.DefaultValidityPeriod)
}
```

The `bool` return value determines whether a source address verification is performed, and the `time.Time` determines how long an STK is considered valid. The `cryptoSetupServer` would then save these values and perform the STK validation, if necessary.

**Comment by lucas-clemente** [comment]
As discussed OOB, we will try the following approach:

```go
type STK struct {
  remoteAddr net.Addr
  sentTime time.Time
}
```

The signature for `VerifySourceAddress` is the following:
```go
func VerifySourceAddress(clientAddr net.Addr, stk *STK) bool {}
```

**Comment by marten-seemann** [comment]
I'm afraid this too won't work. We're not saving a `net.Addr` in the STK.
If we're on a UDP connection, we're saving the IP address, otherwise we're saving `RemoteAddr().String()`.

**Comment by marten-seemann** [comment]
@lucas-clemente: Any ideas?

**Comment by marten-seemann** [comment]
As discussed OOB,

```go
type STK struct {
  remoteAddr string // IP if UDPConn, otherwise net.Addr.String()
  sentTime time.Time
}
```

**Comment by marten-seemann** [comment]
I made some progress implementing this. The default `VerifySourceAddress` callback now is:
```go
func(clientAddr net.Addr, stk *STK) bool {
	if time.Now().After(stk.sentTime.Add(protocol.STKExpiryTime)) {
		return false
	}
	var sourceAddr string
	if udpAddr, ok := clientAddr.(*net.UDPAddr); ok {
		sourceAddr = udpAddr.IP.String()
	} else {
		sourceAddr = clientAddr.String()
	}
	return (subtle.ConstantTimeCompare([]byte(sourceAddr), []byte(stk.remoteAddr)) != 1)
}
```
