### ISSUE TITLE
why sentPacketHistory cached skipped packet numbers

### ISSUE THREAD

**Issue by q191201771** [lucas-clemente/quic-go#3050]
`sentPacketHistory` cached `skipped packet numbers` when packet number skipping.
But it looks like haven't used them.
All `sentPacketHistory.Iterate` has just ignored `skipped packet numbers`.
Am I missing something?

**Comment by marten-seemann** [comment]
Did you see https://github.com/lucas-clemente/quic-go/blob/e3c1a677087dd88db476fdc77e8e1a5c2db44a46/internal/ackhandler/sent_packet_handler.go#L314-L317

**Comment by q191201771** [comment]
Without cache `skipped packet numbers`, `func detectAndRemoveAckedPackets` can also check if received an ACK for skipped packet number?

**Comment by marten-seemann** [comment]
I don't understand your question.

**Comment by q191201771** [comment]
Sorry for my poor English, and thank you for your time.

For instance, sent packet numbers are 1, 3, 5.
There are 2 ways to implement sentPacketHistory:

1. only cache [1, 3, 5]
2. cache [1, 2, 3, 4, 5], each item with a skipped flag, and item 2 and 4's flag is true

Both ways can detect the situation of receiving an ACK for skipped packet numbers:

1. not found in the container
2. found but skipped flag is true

The 1st way is much simpler.

**Comment by marten-seemann** [comment]
The problem with the 1st way is the following: 
1. We send packets `[ 1, 2, 3, 4 ]`.
2. We receive an ACK for packet 2, and delete packet 2 from the history. Now we have `[ 1, 3, 4 ]`.
3. Now we recieve an ACK for packet 1, 2 and 3.

We can't throw an error in this situation.

**Comment by q191201771** [comment]
oh, I see.
Maybe it's better to don't to remove the skipped number in `sentPacketHistory::Remove`.
But it's ok since we don't need to handle receiving two ACK for the same skipped number.

**Comment by marten-seemann** [comment]
Well, we need to remove them eventually to keep the state bounded. We just rely on QUIC loss recovery for this: Once a skipped packet number is declared "lost", we can just remove it.
