### ISSUE TITLE
Deadlock in datagramQueue

### ISSUE THREAD

**Issue by mengelbart** [lucas-clemente/quic-go#3075]
I am trying to send a lot of datagrams and I think there may be a deadlock in the datagram queue. After reading the code, my guess is, that after calling `SendMessage`, `AddAndWait` triggers `scheduleSending` and then blocks until the frame has been dequeued. But if the `runLoop` tries to empty the queue before the frame is actually enqueued, `AddAndWait` will block until the connection is closed.

I am not sure how to write a proper test case for this, so I used a variation of the echo example to reproduce it:
https://gist.github.com/mengelbart/cab8d851e6ad101b37a7db9f632292c6

After a few seconds, it blocks until the connection times out. If I try to delay the `hasData`/`scheduleSending` until the frame is enqueued it seems to work fine.

**Comment by marten-seemann** [comment]
Good catch! Looks like we need another internal channel in the `datagramQueue` to signal when `Get` has actually dequeued the DATAGRAM frame.
Do you want to send us a PR?

**Comment by mengelbart** [comment]
Thanks! Yes, I'll send a PR later today.
