### ISSUE TITLE
go1.16 build failure

### ISSUE THREAD

**Issue by vyzo** [lucas-clemente/quic-go#3077]
While trying to run tests in an upstream package, I get this:
```
/home/vyzo/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/streams_map_generic_helper.go:4:2: missing go.sum entry for module providing package github.com/cheekybits/genny/generic (imported by github.com/lucas-clemente/quic-go)
```

**Comment by marten-seemann** [comment]
v0.19.3 doesn't support Go 1.16 yet. I'm planning to cut a new release this week.

**Comment by vyzo** [comment]
Solution seems to be `go test -v -mod=mod ./...`

**Comment by marten-seemann** [comment]
Will this go away once I release a version that builds with Go 1.16?

**Comment by vyzo** [comment]
I sure hope so :)

**Comment by okgame** [comment]
Big fan of quic-go. Waiting for new release.

**Comment by marten-seemann** [comment]
> v0.19.3 doesn't support Go 1.16 yet. I'm planning to cut a new release this week.

Typical case of being way too optimistic. This will take another week or so, I have a bunch of fixes that need to go into the next release.

**Comment by okgame** [comment]
> > v0.19.3 doesn't support Go 1.16 yet. I'm planning to cut a new release this week.
> 
> Typical case of being way too optimistic. This will take another week or so, I have a bunch of fixes that need to go into the next release.

We will wait, still love you and quic-go team.

**Comment by okgame** [comment]
![image](https://user-images.githubusercontent.com/22207363/111771458-4f54b200-88de-11eb-9342-bb5e6f742ae1.png)
Yessss!!!
