### ISSUE TITLE
(m *incomingBidiStreamsMap) GetOrOpenStream(num protocol.StreamNum) returns nil / empty stream if it to be deleted

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#3084]
```// if the num is smaller than the highest we accepted
	// * this stream exists in the map, and we can return it, or
	// * this stream was already closed, then we can return the nil
	if num < m.nextStreamToOpen {
		var s streamI
		// If the stream was already queued for deletion, and is just waiting to be accepted, don't return it.
		if entry, ok := m.streams[num]; ok && !entry.shouldDelete {
			s = entry.stream
		}
		m.mutex.RUnlock()
		return s, nil
	}
```
should it pick new stream if num found at map is to be deleted ? 
at least that was comment is indicating.

**Comment by marten-seemann** [comment]
I don't understand. Can you elaborate? What is the problem?

**Comment by apmattil** [comment]
returned s is empty when it is returned in case entry.shouldDelete is true
is this the intention ?
I was debugging same place and noticed now this code has changed from 19.3 release.
I get 'too many open streams' under heavy load.
And I only got like 20/40 streams.. limit at config is 2000.
looks like the next/maxStream id is not yet and checks fall to 'too many open'

**Comment by marten-seemann** [comment]
Could you please describe what you’re doing to cause this error? A minimal example reproducing the but would be helpful.

**Comment by apmattil** [comment]
I have proxy using quic-go.
when I run fast.com from browser at phone something gets stuck (rx-window ?) and fast.com generates new streams at upload test.
next stream id keeps increasing at client side, only some streams get to server side.
finally client side exceeds max limit that server has sent sometime ago.
since next stream id is never decreased closing streams at client side does not help.
finally I get 'too many stream' what seems to be permanent.

but the issue was not at the code above, so I'll close this one.
