### ISSUE TITLE
occasional "authentication failed" errors

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#31]
Sample output:

    <- Reading packet 6 for connection 3793658948447668933
    Closing session with error: authentication failed
    invalid http2 frame: authentication failed

**Comment by lucas-clemente** [comment]
We now treat these packets as lost packets, c.f. #38.

**Comment by lucas-clemente** [comment]
I'm closing this, since I think it was due to Chrome using version 30, which still had FEC stuff. If this pops up again, just reopen the issue.
