### ISSUE TITLE
Can't really get the new release update

### ISSUE THREAD

**Issue by galpt** [lucas-clemente/quic-go#3101]
I believe this is a new issue because the latest tagged release (v0.20.0) was just released 10 hours ago.
This happens when I tried to do `go get -u` command and it happens on Windows and Linux (Debian).
These messages will appear if I want to update **quic-go** to the latest release
```
go get all: module github.com/lucas-clemente/quic-go@upgrade found (v0.20.0), but does not contain package github.com/lucas-clemente/quic-go/quictrace
go get all: module github.com/lucas-clemente/quic-go@upgrade found (v0.20.0), but does not contain package github.com/lucas-clemente/quic-go/quictrace/pb
```

**Comment by marten-seemann** [comment]
Not sure about the error message here. Support for quic-trace was removed in https://github.com/lucas-clemente/quic-go/pull/2913.

**Comment by galpt** [comment]
I did `go clean -cache`, `go clean -testcache`, `go clean -modcache` just to make sure and then `go mod tidy`, it downloaded the **quic-go v0.19.3** just fine — but after that, I did a `go get -u all` and the same message appeared.
```
go get all: module github.com/lucas-clemente/quic-go@upgrade found (v0.20.0), but does not contain package github.com/lucas-clemente/quic-go/quictrace
go get all: module github.com/lucas-clemente/quic-go@upgrade found (v0.20.0), but does not contain package github.com/lucas-clemente/quic-go/quictrace/pb
```

It's the same when I tried to `go get -u` **quic-go v0.20.0** on a fresh vps server.
Not sure either if I'm missing something here.

**Comment by marten-seemann** [comment]
That shouldn't happen. `quictrace` was completely removed from quic-go in the commit I mentioned above.
You can try replacing the version number in `go.mod` manually, and then running `go mod tidy`.
