### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [lucas-clemente/quic-go#3111]
## Description 

Hi 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/quic-go/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Function literal can be simplified [here](https://deepsource.io/gh/HarshCasper/quic-go/issue/CRT-A0018/occurrences)
- Empty fallthrough can be avoided [here](https://deepsource.io/gh/HarshCasper/quic-go/issue/CRT-A0003/occurrences)
- Empty String Test can be improved [here](https://deepsource.io/gh/HarshCasper/quic-go/issue/CRT-A0004/occurrences)
- Calls to exit/fatal made in function using defer [here](https://deepsource.io/gh/HarshCasper/quic-go/issue/CRT-D0011/occurrences)
- Shadow of builtin detected [here](https://deepsource.io/gh/HarshCasper/quic-go/issue/CRT-A0004/occurrences)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by marten-seemann** [comment]
I didn’t know about DeepSource before, but from the “issues” it seems to be another linter, right?
I’m not really sure if these are worth fixing tbh. I wouldn’t be opposed either, but some of these suggestions seem to be more a matter of taste than anything else (for example, the empty string comparison).
