### ISSUE TITLE
keepaliveinterval divided twice, correct ?

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#3117]
at release 0.19.3
keepAliveInterval is first calculated at processTransportParametersImpl()
s.keepAliveInterval = utils.MinDuration(s.idleTimeout/2, protocol.MaxKeepAliveInterval)

where with max 30sec max idle time is divided by 2. Making it 15 sec

then again at nextKeepAliveTime()
s.lastPacketReceivedTime.Add(s.keepAliveInterval / 2)
making it 7.5 sec

was this intention ?

**Comment by marten-seemann** [comment]
Good catch! There should not be a `/ 2` in https://github.com/lucas-clemente/quic-go/blob/81d16a99035a48b33cfdfdb16567da73c79c7a35/session.go#L741

I confirmed that we're sending keep-alives to frequently (every 7.5s instead of every 15s).

Would you mind sending us a PR?

**Comment by apmattil** [comment]
I can do the PR.

**Comment by apmattil** [comment]
PR 3127 will fix this issue.
