### ISSUE TITLE
Response code and http method supported.

### ISSUE THREAD

**Issue by haoguo** [lucas-clemente/quic-go#3125]
1. Wired response status code.
When the status code has been set to 500 in the server.  The client would get 200.

2. When using method POST
After intercept, find the :method: send is GET

Both cases are using quic-go http3.ListenAndServeQUIC and client with http3.RoundTripper.

**Comment by marten-seemann** [comment]
I can't reproduce this.
If you still think this is a bug, please post a minimal example here.

**Comment by haoguo** [comment]
Hi marten-seemann,
I found what cause these issues.
About 1. It is my fault.
About 2. I found that if the my handler serves at https://domain.com/health, but I called https://domain.com//health. one more slash added，it would really hit the handler, but with method=get. this is ok in http2. I don't know should this align to http2 or not.
Thx for your help.
