### ISSUE TITLE
The problem of read method of quic.stream

### ISSUE THREAD

**Issue by Darrenjava** [lucas-clemente/quic-go#3131]
`	var SendDate = make([]byte, 52396, 52396)
	acceptStream, err := sess.AcceptStream(context.Background())
	if err != nil {
		log.Println(err)
		return
	}
	_, err = acceptStream.Read(SendDate)`
issue: **### The data is read correctly when the size of the array is equal to the value of the data to be read**

When I need to read data from the **quic.stream** into a byte array, the byte array needs to be given the size of the data to be read in order to read the data correctly. An EOF error is returned when the byte array is too large. But When the size of the array is too small, the data cannot be read correctly.

Given the size of the array in advance is very inconvenient. Is there another way available ?

**Comment by Darrenjava** [comment]
> `	var SendDate = make([]byte, 52396, 52396) acceptStream, err := sess.AcceptStream(context.Background()) if err != nil { log.Println(err) return } _, err = acceptStream.Read(SendDate)`
> issue: **### The data is read correctly when the size of the array is equal to the value of the data to be read**
> 
> When I need to read data from the **quic.stream** into a byte array, the byte array needs to be given the size of the data to be read in order to read the data correctly. An EOF error is returned when the byte array is too large. But When the size of the array is too small, the data cannot be read correctly.
> 
> Given the size of the array in advance is very inconvenient. Is there another way available ?

**Comment by marten-seemann** [comment]
Sounds like any `io.Reader` would behave. Where do you see the problem here?
