### ISSUE TITLE
How to use with chrome?

### ISSUE THREAD

**Issue by watjurk** [lucas-clemente/quic-go#3141]
I'm trying to use this library in web server, chrome keeps throwing `ERR_QUIC_PROTOCOL_ERROR `, I'm using chrome flag `--origin-to-force-quic-on`. After further inspection I've got some logs and exact error message:
```
t=7591 [st=14]    QUIC_SESSION_VERSION_NEGOTIATION_PACKET_RECEIVED
                  --> versions = ["draft29"]
t=7591 [st=14]    QUIC_SESSION_CLOSED
                  --> details = "Client may support one of the versions in the server's list, but it's going to close the connection anyway. Supported versions: {Q050}, peer supported versions: {draft29}"
                  --> from_peer = false
                  --> quic_error = 20 (QUIC_INVALID_VERSION)
t=7591 [st=14]    QUIC_SESSION_CLOSED
                  --> details = "Client may support one of the versions in the server's list, but it's going to close the connection anyway. Supported versions: {Q050}, peer supported versions: {draft29}"
                  --> from_peer = false
                  --> quic_error = 20 (QUIC_INVALID_VERSION)
t=7591 [st=14] -QUIC_SESSION
```

From my reaserch on quic versions (I might be mistaken):
`Q050` - one version before `draft29`
`Q051` - `draft29`

The question is: how to get this library working with chrome? Or maybe better question: is it possible to get list library working witch chrome?

Thanks!

**Comment by marten-seemann** [comment]
We send Alt-Svc. That should be sufficient in practice to make Chrome dial using the right version.

**Comment by watjurk** [comment]
Sorry but I can't understand how this should help me getting QUIC working with chrome. Could you provide siple working example?

**Comment by runner365** [comment]
I write code like this:
`
func main() {
	addr := ":4242"
	handler := setupHandler()

	//certFile, keyFile := testdata.GetCertificatePaths()
	certFile := "new.pem"
	keyFile := "new.pem"
	err := http3.ListenAndServe(addr, certFile, keyFile, handler)
	if err != nil {
		fmt.Println("http3 ListenAndServe error:", err)
		return
	}
	fmt.Println("http3 ListenAndServe done....")
}
`

I access the demo server by https://172.29.66.121:4242/demo/tiles in chrome.

It can show a picture in chrome but the protocal is still http1.1.

`
Request information:
Request URL: https://172.29.66.121:4242/demo/tiles
Request Method: GET
Status Code: 200 OK
Remote Address: 172.29.66.121:4242
Referrer Policy: strict-origin-when-cross-origin

Response information:
Alt-Svc: h3-29=":4242"; ma=2592000
Content-Type: text/html; charset=utf-8
Date: Mon, 10 May 2021 12:50:49 GMT
Transfer-Encoding: chunked
`
This 'Alt-Svc: h3-29=":4242"; ma=2592000' doen't contain quic.
