### ISSUE TITLE
A few issues I had with the samples

### ISSUE THREAD

**Issue by fagnercarvalho** [lucas-clemente/quic-go#3151]
Hello!

I'm trying to learn more about the QUIC protocol and this Go implementation and I encountered a few issues in the [main sample](https://github.com/lucas-clemente/quic-go/tree/master/example).

First, I get `use of internal package` for the `"github.com/lucas-clemente/quic-go/internal/testdata"` and `"github.com/lucas-clemente/quic-go/internal/utils"` packages.

After I remove the references for these packages (just so I can run the sample) I get this runtime error when running the client:

```
crypto/x509: system root pool is not available on Windows
```

Yes, I'm running this on Windows.

After removing the reference for the cert pool both the client and the server are running but the client is not able to connect to the server because it was only accepting HTTPS but the server is not configured for HTTPS because it relies on the `testdata.GetCertificatePaths()`: and `testdata` is internal.

https://github.com/lucas-clemente/quic-go/blob/d9c7467b569526b3e4d9df2e2bd4d8e9805fd82e/http3/roundtrip.go#L105

Is `RoundTripOpt.SkipSchemeCheck` exposed for clients or is QUIC only supposed to work under TLS?

Also, if you don't mind me asking, what is the difference between:

https://github.com/lucas-clemente/quic-go/blob/b8358dc2bb979d3638fbaf9eda3cd74573289e4b/http3/server.go#L118

https://github.com/lucas-clemente/quic-go/blob/b8358dc2bb979d3638fbaf9eda3cd74573289e4b/http3/server.go#L495

**Comment by fagnercarvalho** [comment]
After creating a self signed certificate:

```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
```

And getting the certificate like this in the server:

```go
func getCerts() (string, string){
	return path.Join("C:/github/", "cert.pem"), path.Join("C:/github/", "key.pem")
}
```

And creating a cert pool like this in the client:

```go
pool := x509.NewCertPool()
caCertPath := path.Join("C:/github/", "cert.pem")
caCertRaw, err := ioutil.ReadFile(caCertPath)
if err != nil {
	panic(err)
}
if ok := pool.AppendCertsFromPEM(caCertRaw); !ok {
	panic("Could not add root certificate to pool.")
}
```

I was able to run the client but got a 400 response from the server if connecting to the root path. If connecting to `/demo/tile` I finally get a 200 and a PNG file.

```go
&{Status:200 OK StatusCode:200 Proto:HTTP/3 ProtoMajor:3 ProtoMinor:0 Header:map[] Body:0xc00028c030 ContentLength:-1 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:<nil> TLS:0xc000288000}
```

Would you accept a PR to improve the docs around the sample and to allow Windows support?

**Comment by fagnercarvalho** [comment]
The echo sample looks more straightforward but it is using a 3rd method for creating the QUIC server and now I'm not sure how it differs from the other 2 methods I mentioned in my first message in this issue:

https://github.com/lucas-clemente/quic-go/blob/f51eff48e95502cdb4268600e80a8af1e9260937/server.go#L121

**Comment by fagnercarvalho** [comment]
There is also a flag in the server for enabling TCP that would use `ListenAndServeTLS`. I sniffed the traffic in Wireshark and I'm seeing that if I connect using Chrome (even with QUIC enabled in chrome://flags) this only works if the TCP flag is enabled and I connect over TCP and TLSv1.2. What would be the meaning of using QUIC in TCP if the idea would be to use UDP? Fallback method?

**Comment by marten-seemann** [comment]
Hello @fagnercarvalho, thank you for taking this on. I admit the examples haven't received the attention they deserve. It would be great if you could help out here!

> First, I get use of internal package for the "github.com/lucas-clemente/quic-go/internal/testdata" and "github.com/lucas-clemente/quic-go/internal/utils" packages.

Good point. I agree it would be nice to have a way to write this without using internal.

Regarding windows support, how would you make it possible that the client can connect both to the example server as well as to external hosts? Not sure how cert pool handling is supposed to work in Go on Windows.

**Comment by fagnercarvalho** [comment]
> Hello @fagnercarvalho, thank you for taking this on. I admit the examples haven't received the attention they deserve. It would be great if you could help out here!
> 
> > First, I get use of internal package for the "github.com/lucas-clemente/quic-go/internal/testdata" and "github.com/lucas-clemente/quic-go/internal/utils" packages.
> 
> Good point. I agree it would be nice to have a way to write this without using internal.

Happy to help and thank you for the fast reply!

I will work on improving these samples during the upcoming weeks.
 
> Regarding windows support, how would you make it possible that the client can connect both to the example server as well as to external hosts? Not sure how cert pool handling is supposed to work in Go on Windows.

This would not be possible if we use `NewCertPool`. Since this client only connects to the sample server I don't believe this would be a problem. In any case, an alternative would be to implement a solution similar to what someone in Red Hat did [by using build tags to use `NewCertPool` for Windows and `SystemCertPool` for everything else](https://github.com/openshift-online/ocm-sdk-go/pull/333/files). [Here is the discussion about this issue](https://github.com/golang/go/issues/16736).

**Comment by marten-seemann** [comment]
> Since this client only connects to the sample server I don't believe this would be a problem. 

You can use the example client to connect to any QUIC server on the internet.
Now I don't really care about offering reduced functionality for Windows users (it's not my fault that they chose a subpar OS... 😛). If we decide to do this we should add a warning though ("Connecting to server other than the example server doesn't work on Windows.", or something along those lines).

**Comment by fagnercarvalho** [comment]
> > Since this client only connects to the sample server I don't believe this would be a problem.
> 
> You can use the example client to connect to any QUIC server on the internet.

Definitely, I understand.

> Now I don't really care about offering reduced functionality for Windows users (it's not my fault that they chose a subpar OS... 😛). If we decide to do this we should add a warning though ("Connecting to server other than the example server doesn't work on Windows.", or something along those lines).

Haha, sure, I will do this and add this note to the README, thank you!

**Comment by gavan1** [comment]
I may also be missing a few steps on getting the example file running.
As an initial test running 

`go run main.go`

and pointing the browser to localhost:6060 does give me or "/demo/tiles" gets me a 404.

**Comment by marten-seemann** [comment]
@fagnercarvalho Are still planning to fix this?

**Comment by marten-seemann** [comment]
Closing due to age.
