### ISSUE TITLE
Enabling qlog when using http3.ListenAndServe() at server

### ISSUE THREAD

**Issue by chanh1964** [lucas-clemente/quic-go#3156]
Hi all,

So I wanted to set a server that listens to both TLS and QUIC connections by using `func ListenAndServe(addr, certFile, keyFile string, handler http.Handler)`. 

https://github.com/lucas-clemente/quic-go/blob/0a063966a770e9cde186b2aab8ef5c97363872cd/http3/server.go#L495-L568

But using this function, I couldn't create the qlog files. Therefore, I decided to look into the source code and added the `quic.Config` to the parameters:

- Line 495
```golang
func ListenAndServe(addr, certFile, keyFile string, handler http.Handler, quicConf *quic.Config) error {
```
- Line 539-541
```golang
quicServer := &Server{
   Server:     httpServer,
   QuicConfig: quicConf,
}
```

Example code:
```golang
quicConf := &quic.Config{}
quicConf.Tracer = qlog.NewTracer(func(_ logging.Perspective, connID []byte) io.WriteCloser {
  filename := fmt.Sprintf("server_%x.qlog", connID)
  f, err := os.Create(filename)
  if err != nil {Is
    log.Fatal(err)
  }
  log.Printf("Creating qlog file %s.\n", filename)
  return utils.NewBufferedWriteCloser(bufio.NewWriter(f), f)
})

if err := http3.ListenAndServe(":8888", cert, key, nil, quicConf); err != nil {
  log.Fatal(err)
}
```

Is there any proper way to do it rather than modifying the source?

**Comment by marten-seemann** [comment]
Yes, you just can't use `ListenAndServe`. As `http.ListenAndServer`, `http3.ListenAndServe` is just a shortcut for getting a server up and running with a single line of code.

If you want do something more complex, you need to create a [`http3.Server`](https://pkg.go.dev/github.com/lucas-clemente/quic-go/http3#Server). You can set a `quic.Config` there. Then you call `http3.Server.ListenAndServe` to start listening.

Does that work for you?

**Comment by chanh1964** [comment]
Hi, thank you very much for your reply and I'm sorry for the delay.

I've been trying to set up a webserver `http3.Server.ListenAndServeTLS` but it seems the server only listens to QUIC/UDP so I cannot open the webpage with the browser (no `Alt-Svc` headers, I guess). The same problem happens when running `/example/main.go` without `-tcp` as the code I'm using is similar.

https://github.com/lucas-clemente/quic-go/blob/84e03e59760ceee37359688871bb0688fcc4e98f/example/main.go#L185-L194

Perhaps I should look into the code in `http3.ListenAndServe` for details about setting up TCP and QUIC in parallel?

**Comment by marten-seemann** [comment]
Yes, `http3.ListenAndServe` is the function you need to call to listen on both TCP and QUIC.
