### ISSUE TITLE
read me instruction insufficient

### ISSUE THREAD

**Issue by govwin** [lucas-clemente/quic-go#3169]
1. where to run test?
`go test ./...` from where?

Below is what I did.
```
a@a:~/quic-go$ go test .
ok      github.com/lucas-clemente/quic-go       (cached)
```
2. how to remove cached test and rerun?

**Comment by marten-seemann** [comment]
> where to run test?
> go test ./... from where?

From the base directory.

>     how to remove cached test and rerun?

Please consult the Go man page.
