### ISSUE TITLE
proposal : do not close idle session

### ISSUE THREAD

**Issue by apmattil** [lucas-clemente/quic-go#3170]
I'm making proxy and have tcp connections that are just opened but no data is sent.
If I enable keepalive, session is closed after 30 sec.

Could you add option not to close session if it has streams open ? not just data passed.
I do like to detect if connection is broken when keepalive's do not get reply.

I know this could be done at my proxy as well but implementing it to quic-go would make things much simpler.

**Comment by marten-seemann** [comment]
> I'm making proxy and have tcp connections that are just opened but no data is sent.
> If I enable keepalive, session is closed after 30 sec.

That's not what keep-alive does. Keep-alive just sends a PING after half the `MaxIdleTimeout`. The connection is only closed if there's no reply from the peer. This is independent from actual application data being exchanged.

**Comment by apmattil** [comment]
here a diff:
`diff --git a/example/echo/echo.go b/example/echo/echo.go
index 7c1ae280..06a24d9a 100644
--- a/example/echo/echo.go
+++ b/example/echo/echo.go
@@ -11,6 +11,7 @@ import (
        "io"
        "log"
        "math/big"
+       "time"
 
        quic "github.com/lucas-clemente/quic-go"
 )
@@ -44,8 +45,13 @@ func echoServer() error {
        if err != nil {
                panic(err)
        }
+
        // Echo through the loggingWriter
        _, err = io.Copy(loggingWriter{stream}, stream)
+       _, err = stream.Read(make([]byte, 10))
+       if err != nil {
+               fmt.Printf("server err: %s", err.Error())
+       }
        return err
 }
 
@@ -76,6 +82,7 @@ func clientMain() error {
                return err
        }
        fmt.Printf("Client: Got '%s'\n", buf)
+       time.Sleep(100 * time.Second)
 
        return nil
 }`

output:
`apmattil@penguin:~/src/quic/example/echo$ go run echo.go 
2021/05/18 23:02:27 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Client: Sending 'foobar'
Server: Got 'foobar'
Client: Got 'foobar'
server err: timeout: no recent network activity2021/05/18 23:02:57 timeout: no recent network activity
exit status 1`

**Comment by marten-seemann** [comment]
The echo example doesn't use keep alives, so this is expected.

**Comment by apmattil** [comment]
aa..ok.
I'll close this one.
