### ISSUE TITLE
Sending data CPU usage is too high

### ISSUE THREAD

**Issue by SkyWalkerFrom2018** [lucas-clemente/quic-go#3179]
I have a file server and my program send data by stream.Write(buf)。
I found the following problem：
1. CPU usage is tooo high.
2. stream.Write() failed and the error is **Timeout: No recent network activity.**
3. This phenomenon is prone to occur when the number of connections reaches 30, but it does not necessarily occur.

**Comment by marten-seemann** [comment]
Can you export a pprof?

**Comment by SkyWalkerFrom2018** [comment]
[Exported pprof files of svg](http://abc.cxrender.com/profile001.svg)
Not happend always, so I exported it this morning.
I read this file and found maybe the problem is **Lock**.

**Comment by SkyWalkerFrom2018** [comment]
> Can you export a pprof?

Exported pprof files of svg
Not happend always, so I exported it this morning.
I read this file and found maybe the problem is Lock.

SVG:  http://abc.cxrender.com/profile001.svg

**Comment by marten-seemann** [comment]
Looks like most of the time is spent selecting go routines. Which version are you running?

**Comment by SkyWalkerFrom2018** [comment]
> Looks like most of the time is spent selecting go routines. Which version are you running?

Go 1.16.4  quic-go  The new version from github

**Comment by marten-seemann** [comment]
This is / was probably the consequence of busy looping. #3570 will fix that. #3526 is the tracking issue to reduce allocations, which will further bring down CPU load by triggering GC less frequently.

**Comment by zengxiaobai** [comment]
> > Can you export a pprof?
> 
> Exported pprof files of svg Not happend always, so I exported it this morning. I read this file and found maybe the problem is Lock.
> 
> SVG: http://abc.cxrender.com/profile001.svg

excuse me,does this merge solved your problem?
