### ISSUE TITLE
How to use 0-RTT consistently?

### ISSUE THREAD

**Issue by springself** [lucas-clemente/quic-go#3187]
I am doing a test using quic, but I found that for every two dial-connections only one used 0-RTT. Why? wrong config? Please HELP!

**Client Code**
```go
tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"quic-echo-example"},
	}

	gets := make(chan string, 100)
	puts := make(chan string, 100)
	tlsConf.ClientSessionCache = newClientSessionCache(gets,puts)
	tlsConf.ServerName = "localhost:4242"

	qconfig := getQuicConfig(&quic.Config{})
	qconfig.TokenStore = quic.NewLRUTokenStore(100, 100)
	qconfig.Versions = []protocol.VersionNumber{protocol.VersionDraft29}

	for i := 0;;i++{
		tStart := time.Now()
		fmt.Println(fmt.Sprintf("Running Now %d", tStart))
		s1,err := quic.DialAddrEarly(addr,tlsConf,qconfig)
		if err !=nil{
			return err
		}

		msg := fmt.Sprintf("msg [%d]", i)

		if err = handle(s1, &msg);err !=nil{
			fmt.Println("s1 fail to handle,err:",err.Error())
		}
		s1.CloseWithError(0,"")
		fmt.Printf("[4242 same]i:%d ,cost %d,used0RTT:%v\n",i, time.Now().Sub(tStart),s1.ConnectionState().TLS.Used0RTT)

		time.Sleep(time.Millisecond * 5000)
	}
```

**Server Code**
```go
     listener, err := quic.ListenAddrEarly(addr, generateTLSConfig(), nil)
	if err != nil {
		return err
	}
	for {
		sess, err := listener.Accept(context.Background())
		if err != nil {
			return err
		}
		stream, err := sess.AcceptStream(context.Background())
		if err != nil {
			panic(err)
		}
		_, err = io.Copy(loggingWriter{stream}, stream)  //echo back
	}
	return err
```

**Log Result**

> Running Now {13844735111062025452 2051201 13116576}
handshake_client.go/clientHandshake
Client: Sending 'msg [0]'
Server: Got 'msg [0]'
Client: Got 'msg [0]'
[4242 same]i:0 ,cost 211056800,used0RTT:false
Running Now {13844735116642499072 5213815701 13116576}
handshake_client.go/clientHandshake
Client: Sending 'msg [1]'
Server: Got 'msg [1]'
Client: Got 'msg [1]'
[4242 same]i:1 ,cost 1629200,used0RTT:true
Running Now {13844735122014062292 10216669801 13116576}
handshake_client.go/clientHandshake
Client: Sending 'msg [2]'
Server: Got 'msg [2]'
Client: Got 'msg [2]'
[4242 same]i:2 ,cost 2600400,used0RTT:false
Running Now {13844735127386204312 15220102701 13116576}
handshake_client.go/clientHandshake
Client: Sending 'msg [3]'
Server: Got 'msg [3]'
Client: Got 'msg [3]'
[4242 same]i:3 ,cost 1002800,used0RTT:true

**Comment by marten-seemann** [comment]
I'd suspect that you're not keeping the connection alive for long enough to receive the session ticket from the server (which is required to be able to resume the connection).
