### ISSUE TITLE
Changing congestion control algorithm in quic-go and Ubuntu

### ISSUE THREAD

**Issue by chanh1964** [lucas-clemente/quic-go#3189]
Hello everyone.

I’m currently using the latest release of quic-go.

For experimental purpose, I need to configure quic-go’s congestion control algorithm (CCA) to match with one Ubuntu 20.04 is using. I have some questions about this.

**1. Changing Ubuntu’s CCA**
Ubuntu runs CUBIC as its default CCA. After running `sysctl net.ipv4.tcp_available_congestion_control`, I found that there is a `reno` entry. I wonder if this `reno` is the New Reno currently implemented in quic-go?

I tried to search about enabling New Reno on Ubuntu but so far the answer in this [link](https://stackoverflow.com/a/33075156) is the only source I could find that says `reno`  is New Reno. So I’m not so sure about it. Do you have any idea?

**2. Changing quic-go’s CCA to CUBIC**
Going through the issues and commits, I found out that quic-go used CUBIC before changing to New Reno (fccdb1c558ec7643ab44877e568ca3d2e2226cc6). Based on this, I tried to set the parameter at line 116 in [/internal/ackhandler/send_packet_handler.go](https://github.com/lucas-clemente/quic-go/blob/bd9b085c7405f3aa2ddf42854bc965c3f6aa75d5/internal/ackhandler/sent_packet_handler.go#L112-L118) to `false`, expecting it would go back to use CUBIC.
https://github.com/lucas-clemente/quic-go/blob/bd9b085c7405f3aa2ddf42854bc965c3f6aa75d5/internal/ackhandler/sent_packet_handler.go#L112-L118

I wonder if it is possible to do so? Will it influence other components?

Thank you very much.

**Comment by chanh1964** [comment]
After changing [/internal/ackhandler/sent_packet_handler.go](https://github.com/lucas-clemente/quic-go/blob/bd9b085c7405f3aa2ddf42854bc965c3f6aa75d5/internal/ackhandler/sent_packet_handler.go#L112-L118) and checking the congestion windows, it think that it definitely is not a good option at all.

So, what is left is whether `reno` in linux is the New Reno algorithm.

**Comment by marten-seemann** [comment]
We only implement New Reno. If there are references to Cubic in the code, it's because we took Chromium's CC implementation a few years ago, but there hasn't been any work on maintaining, updating or benchmarking it, and we also might have removed bits and pieces from it since.
