### ISSUE TITLE
WebTransport Support

### ISSUE THREAD

**Issue by runner365** [lucas-clemente/quic-go#3191]
Hi, I try to connect http3 server writed by quic-go.
And I setup https by tls certification files.
When I try to use WebTransport in web:
```
let trans = new WebTransport('https://rtc1.live.corp.xxxx.com:443/live/2000.flv');
```

But it fail and console log is:
```
Failed to establish a connection to https://rtc1.live.corp.xxxx.com/live/2000.flv: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_TLS_CERTIFICATE_UNKNOWN (TLS handshake failure (ENCRYPTION_HANDSHAKE) 46: certificate unknown).
```

but I write http3 client by quicgo and use the http3 client to connect http3 server by quic-go, It work fine.

My chrome version is  91.0.4472.77.

Please help.

**Comment by marten-seemann** [comment]
quic-go implements the QUIC protocol, but not WebTransport.
Not sure why you're getting a TLS certificate error though.

**Comment by okgame** [comment]
Maybe you should add Webtransport?
I use quic-go for connect Quictransport > Google Chrome since draft-27 until Quictransport trial end.

Quictransport is removed and i can't use quic-go for connect Webtransport > Google Chrome.

Now I'm using Websocket for alternative.
I have no choice.
Sad :'(

**Comment by marten-seemann** [comment]
Afaik, Chrome's QuicTransport implementation is not up to date with the current IETF draft.
We might add a QuicTransport implementation here (or in a separate repo, building on top of quic-go), once the specification has become more stable.

**Comment by ydnar** [comment]
I’ve made some progress adding WebTransport support to quic-go:

https://github.com/lucas-clemente/quic-go/compare/master...alta:webtransport?expand=1

Progress so far:

- Added support for `WEBTRANSPORT_ENABLED` H3 setting in client and server.
- Defined WebTransport stream types.
- Exposed a new `WebTransport bool` flag in `http3.Server` and `settingsFrame`.
- Rudimentary (read: hacked-in) support for the draft WebTransport ALPN `wq-vvv-01`.

I also added a slight optimization to `parseSettingsFrame` to skip the required-but-ignored `0x1f * N + 0x21` settings. I could cherry-pick that into a separate PR if you think it’d be useful.

**Comment by marten-seemann** [comment]
@ydnar Is this implementing the current draft of the WebTransport spec?
That's super exciting. Are you planning to send us a PR with your changes?

> I also added a slight optimization to parseSettingsFrame to skip the required-but-ignored 0x1f * N + 0x21 settings. I could cherry-pick that into a separate PR if you think it’d be useful.

That defeats the purpose of greasing. A receiver must not create any special cases for greased values.

**Comment by ydnar** [comment]
> @ydnar Is this implementing the current draft of the WebTransport spec?
> That's super exciting. Are you planning to send us a PR with your changes?

Yep! I’m working against the [current draft](https://tools.ietf.org/id/draft-vvv-webtransport-http3-03.html), and will submit a PR in draft form for feedback when it’s working at minimum with the current Chromium demo. I’d love your guidance on how best to test this.

> > I also added a slight optimization to parseSettingsFrame to skip the required-but-ignored 0x1f * N + 0x21 settings. I could cherry-pick that into a separate PR if you think it’d be useful.
> 
> That defeats the purpose of greasing. A receiver must not create any special cases for greased values.

Greasing? What’s this?

**Comment by marten-seemann** [comment]
> current Chromium demo. I’d love your guidance on how best to test this.

That might be a bit tricky. The ideal test would be running a headless Chromium and establishing a WebTransport connection. I have a Docker setup that runs headless Chromium and downloads a file via HTTP/3 in https://github.com/marten-seemann/chrome-quic-interop-runner, maybe it’s possible to modify that and build an integration test for quic-go?

> Greasing? What’s this?

The spec says that unknown frame types have to be ignored when receiving them. In the past (with other protocols), many implementations ignored that, and got away with it because nobody ever sent new frame types. As soon as you try to extend the protocol, things start to fall apart…
That’s why recently, protocols like TLS 1.3 and QUIC have started to grease these mechanisms. Implementations occasionally send a “reserved” frame (i.e. a frame that will never be used by an actual extension) with random data, just to make sure that everyone in the ecosystem properly implements the skipping of unknown frames.

**Comment by ydnar** [comment]
> > current Chromium demo. I’d love your guidance on how best to test this.
> 
> That might be a bit tricky. The ideal test would be running a headless Chromium and establishing a WebTransport connection. I have a Docker setup that runs headless Chromium and downloads a file via HTTP/3 in https://github.com/marten-seemann/chrome-quic-interop-runner, maybe it’s possible to modify that and build an integration test for quic-go?

I have some experience running headless Chromium in CI. To validate WebTransport I’m using a test server that uses [alta/insecure](https://github.com/alta/insecure) certs signed by [mkcert](https://github.com/FiloSottile/mkcert) to get around a weird issue where Chrome will happily use a self-signed TLS cert for HTTP/1.1 but not QUIC.

Any objection to using Puppeteer in an integration test in this repo?

> > Greasing? What’s this?
> 
> The spec says that unknown frame types have to be ignored when receiving them. In the past (with other protocols), many implementations ignored that, and got away with it because nobody ever sent new frame types. As soon as you try to extend the protocol, things start to fall apart…
> That’s why recently, protocols like TLS 1.3 and QUIC have started to grease these mechanisms. Implementations occasionally send a “reserved” frame (i.e. a frame that will never be used by an actual extension) with random data, just to make sure that everyone in the ecosystem properly implements the skipping of unknown frames.

Ah, interesting. So you’re saying that implicitly ignoring these settings identifiers rather than [explicitly ignoring them](https://github.com/alta/quic-go/commit/7c4ed91cfab5e8665fd736c1ae48adce2f9a05110) is closer to the [spec](https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-7.2.4.1)?

```
   Setting identifiers of the format "0x1f * N + 0x21" for non-negative
   integer values of N are reserved to exercise the requirement that
   unknown identifiers be ignored.  Such settings have no defined
   meaning.  Endpoints SHOULD include at least one such setting in their
   SETTINGS frame.  Endpoints MUST NOT consider such settings to have
   any meaning upon receipt.
```

**Comment by marten-seemann** [comment]
> Any objection to using Puppeteer in an integration test in this repo?

Whatever works, as long as we can run it in GitHub Actions.

**Comment by ydnar** [comment]
Got first bytes echoed over a bidi WebTransport stream using Chrome:

<img src="https://user-images.githubusercontent.com/34146/124701655-cf118700-dea3-11eb-853d-2ea04b3ec219.png" width="300" />

The handler looks like this:

```go
func handleCounter(rw http.ResponseWriter, req *http.Request) {
	// TODO: check Origin header and ensure req.Method == http.MethodConnect
	// TODO: wrap this up into webtransport.Accept(rw, req)
	rw.WriteHeader(http.StatusOK)
	if flusher, ok := rw.(http.Flusher); ok {
		flusher.Flush() // Required to send headers
	}

	// http3.Session exposes a subset of the quic.Session API with HTTP/3 and WebTransport flow identifiers.
	sess := rw.(http3.Session)
	for {
		str, err := sess.AcceptStream(req.Context())
		if err != nil {
			return
		}
		log.Printf("webtransport stream %d", str.StreamID())

		go func(str quic.Stream) {
			defer str.Close()
			buf := make([]byte, 4096)
			n, err := str.Read(buf)
			if err != nil {
				log.Printf("error reading from stream %d: %v", str.StreamID(), err)
				return
			}

			log.Printf("webtransport message: %v", string(buf))

			s := strings.ToUpper(string(buf[:n]))

			_, err = str.Write([]byte(s))
			if err != nil {
				log.Printf("error writing to stream %d: %v", str.StreamID(), err)
				return
			}
		}(str)
	}
}
```

**Comment by ydnar** [comment]
This is the commit that glues it together, if you want to comment on the direction:

https://github.com/alta/quic-go/commit/49a00924274133808524ee1d9edd560f942df719

**Comment by runner365** [comment]
> This is the commit that glues it together, if you want to comment on the direction:
> 
> [alta@49a0092](https://github.com/alta/quic-go/commit/49a00924274133808524ee1d9edd560f942df719)

Thanks!!
The PR is niubility(chinglish).

**Comment by guest271314** [comment]
> Got first bytes echoed over a bidi WebTransport stream using Chrome:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/34146/124701655-cf118700-dea3-11eb-853d-2ea04b3ec219.png">
> 
> The handler looks like this:
> 
> ```go
> func handleCounter(rw http.ResponseWriter, req *http.Request) {
> 	// TODO: check Origin header and ensure req.Method == http.MethodConnect
> 	// TODO: wrap this up into webtransport.Accept(rw, req)
> 	rw.WriteHeader(http.StatusOK)
> 	if flusher, ok := rw.(http.Flusher); ok {
> 		flusher.Flush() // Required to send headers
> 	}
> 
> 	// http3.Session exposes a subset of the quic.Session API with HTTP/3 and WebTransport flow identifiers.
> 	sess := rw.(http3.Session)
> 	for {
> 		str, err := sess.AcceptStream(req.Context())
> 		if err != nil {
> 			return
> 		}
> 		log.Printf("webtransport stream %d", str.StreamID())
> 
> 		go func(str quic.Stream) {
> 			defer str.Close()
> 			buf := make([]byte, 4096)
> 			n, err := str.Read(buf)
> 			if err != nil {
> 				log.Printf("error reading from stream %d: %v", str.StreamID(), err)
> 				return
> 			}
> 
> 			log.Printf("webtransport message: %v", string(buf))
> 
> 			s := strings.ToUpper(string(buf[:n]))
> 
> 			_, err = str.Write([]byte(s))
> 			if err != nil {
> 				log.Printf("error writing to stream %d: %v", str.StreamID(), err)
> 				return
> 			}
> 		}(str)
> 	}
> }
> ```

Interesting that the image you posted includes the `TypeError: Connection lost.` message. The same error is occurring with Python aioquic implementation of WebTransport https://bugs.chromium.org/p/chromium/issues/detail?id=1237781.

I arrived here researching that error and `ERR_QUIC_PROTOCOL_ERROR.QUIC NETWORK IDLE TIMEOUT`.

**Comment by ydnar** [comment]
I need to verify this but I suspect it's because quic-go closes the write side of a request stream upon sending the (empty) response body.

The proper behavior for a CONNECT / WebTransport session is to only close the write side when the session is complete.

**Comment by guest271314** [comment]
I do not know what the ultimate source of the `Connection lost.` error is. I am currently reading Chromium source code https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webtransport/web_transport_test.cc to try to isolate the cause.

I commented here because I find it interesting that the same error is being thrown using different code than aioquic.

I have observed different behaviour with regard to Chromium implementation of `TransformStream` in general https://bugs.chromium.org/p/chromium/issues/detail?id=1237799

```
var {readable, writable} = new TransformStream();
var writer = writable.getWriter();
console.log(writer.desiredSize);
await writer.ready;
await writer.write(new Uint8Array([1]));
console.log(writer.desiredSize);
await writer.ready;
await writer.write(new Uint8Array([2]));
await writer.close();
var reader = readable.getReader();
while (true) {
  let {value, done} = reader.read();
  console.log(value, done);
  if (done) {break}
}
console.log('Never reached!');
```

which might also be a contributing factor.

Perhaps you will be able to isolate and eliminate the error in Go.

**Comment by ydnar** [comment]
@guest271314 could you try with my new branch? ^^

**Comment by ydnar** [comment]
Got datagrams working this morning:

<img width="434" alt="quic-go-webtransport-datagrams-2" src="https://user-images.githubusercontent.com/34146/129953420-68ac2821-37e5-4915-b439-747bdca9e3e9.png">

**Comment by guest271314** [comment]
Does go require the 129MB for *nix? Is there a minimal go installation I can use to test this?

**Comment by ydnar** [comment]
> Does go require the 129MB for *nix? Is there a minimal go installation I can use to test this?

I’m not sure what you mean. Do you have a question about Go the language, or are you asking for a minimal WebTransport example?

**Comment by guest271314** [comment]
This repository is titled quic-go. I do not have go installed. I am testing `WebTransport`. I noticed the error at aioquic repository and researched other implementations to determine if the error(s) are unique to Python aioquic implementation. You appear to have solved the `Connection lost.` `TypeError` that aioquic exhibits. The golang-go download is 129MB on Linux https://golang.org/dl/go1.17.linux-amd64.tar.gz. I am on a *nix machine with limited disk space. I would prefer to, if possible, install the minimal requirement to run `WebTransport` that you have implemented.

**Comment by ydnar** [comment]
> This repository is titled quic-go. I do not have go installed. I am testing `WebTransport`. I noticed the error at aioquic repository and researched other implementations to determine if the error(s) are unique to Python aioquic implementation. You appear to have solved the `Connection lost.` `TypeError` that aioquic exhibits. The golang-go download is 129MB on Linux https://golang.org/dl/go1.17.linux-amd64.tar.gz. I am on a *nix machine with limited disk space. I would prefer to, if possible, install the minimal requirement to run `WebTransport` that you have implemented.

The official Go distribution is as about small as you’re going to get. I’d recommend getting started with examples here: https://go.dev/learn/

The #3226 branch, while functional, is still very much a work in progress. Currently the WebTransport functionality it exposes isn’t documented, and assumes a certain fluency with Go and building HTTP/3 and HTTP servers.

**Comment by guest271314** [comment]
I tested the Python aioquic implementation of `WebTransport` support on Chromium 95.0.4613.0 (Developer Build) (64-bit)
Revision bc3004dc4c9d5f668f02734dc51a66526609d256-refs/heads/master@{#913061} today 100 times without a `TypeError: Connection lost.` error. I am not sure what changed. The last two `Webtransport` commits are https://source.chromium.org/chromium/chromium/src/+/a00975321a56921658a94f4d8ab5f03067ad41bd, https://source.chromium.org/chromium/chromium/src/+/a1eb58b0a454baa5496b6a1ec12761628ba56b86.

I will find a way to try Go and test implementation of WebTransport.

**Comment by guest271314** [comment]
@ydnar After several updates to Chromium implementation of `WebTransport` the basic server is now working.

What I have not been able to achieve is streaming to the browser https://github.com/GoogleChrome/samples/pull/749#issuecomment-960433712.

Have you tested serving an infinite stream to the browser in go?

**Comment by ydnar** [comment]
I haven't updated this branch to the current working version of the WebTransport draft. 

I'm waiting to merge the related PR as foundation before continuing to implement WT.

**Comment by guest271314** [comment]
I suggest thoroughly testing streaming (an infinite data stream from server to client) which WPT does not do.

If you have any experinece with Python this is the code I used to test, e.g., streaming captured system audio ("What-U-Hear") to the browser with random numbers https://gist.github.com/guest271314/5f567517f94572e84026e76ec6e7cd89.

We can do this with `fetch()` and minimal PHP code using `passthru()` - not with aioquic implmentation.

I am currently just trying to gather why that is the case. So far I have not located any code in the wild that achieves that requirement.

**Comment by marten-seemann** [comment]
WebTransport support is now available via https://github.com/marten-seemann/webtransport-go (under development), using APIs added to the `http3` package.
