### ISSUE TITLE
go mod vendor fails with quic-go v0.21.0

### ISSUE THREAD

**Issue by ShangguanHong** [lucas-clemente/quic-go#3194]
Using v0.21.0 of quic-go, the following error occurs when executing the **go mod vendor** command
"github.com\lucas-clemente\quic-go@v0.21.0\internal\qtls\go118.go:3:1: expected 'package', found "quic-go doesn't build on Go 1.18 yet."
It works the same in both windows and linux environments.
Check out the "github.com\lucas-clemente\quic-go@v0.21.0\internal\qtls\go118.go" file with the following code
![image](https://user-images.githubusercontent.com/37330396/120570336-771dd580-c44a-11eb-970f-c1f389cd3d5a.png)
Is this some new way of writing?

**Comment by marten-seemann** [comment]
This prevents quic-go from being built with Go 1.18, as we don't support that version yet.
I'm a bit surprised that `go mod vendor` tries to compile that file, but I guess it's trying to vendor dependencies regardless of the build flags.

@mvdan, do you have any idea?

**Comment by ameshkov** [comment]
Same issue here. Probably, it'd be better to replace it with something like `function init() { panic('xxx') }` to avoid breaking mod vendor.

**Comment by mvdan** [comment]
Ah, commands `go mod vendor` will need to parse import statements from all Go files to tell what packages need to be vendored. This will ignore build tags by definition, because one wants to vendor all dependencies across all build configurations.

@marten-seemann I think you need to provide valid syntax, then, but pulling imports doesn't require typechecking, so you can still use a typechecking error rather than a syntax error:

```
$ cat f.go
package p

var _ int = "quic-go doesn't build on Go 1.18 yet."
$ go build f.go
# command-line-arguments
./f.go:3:5: cannot use "quic-go doesn't build on Go 1.18 yet." (type untyped string) as type int in assignment
$ go mod vendor
go: no dependencies to vendor
$ gofmt f.go
package p

var _ int = "quic-go doesn't build on Go 1.18 yet."
```

**Comment by marten-seemann** [comment]
```go
// +build go1.18

package qtls

"quic-go doesn't build on Go 1.18 yet."
```

should be good enough. `go mod vendor` only seems to care about the `package` (and the `import`) part of the file.

**Comment by mvdan** [comment]
I don't think that prints the string when building, though. I arrived at my example above with that objective :)

**Comment by marten-seemann** [comment]
You're right. 
```go
var "quic-go doesn't build on Go 1.18 yet."
```
is an even shorter version to achieve the same.

**Comment by mvdan** [comment]
I'd try to stay in the realm of valid syntax, though, because there are plenty of tools that parse all Go files. `gofmt -l -w .`, for example.

**Comment by howardjohn** [comment]
Thanks! would it be possible to add a new tag for the fix?

**Comment by marten-seemann** [comment]
Will do so shortly, but I want to get the qtls update for Go 1.17beta1 in first.

**Comment by howardjohn** [comment]
Great, thanks!

**Comment by hktalent** [comment]
@ShangguanHong
go get -u github.com/lucas-clemente/quic-go
now me is ok
