### ISSUE TITLE
http3.RoundTripper.Dial signature

### ISSUE THREAD

**Issue by folbricht** [lucas-clemente/quic-go#3197]
The signature for the dialer is `Dial func(network, addr string, tlsCfg *tls.Config, cfg *quic.Config) (quic.EarlySession, error)` while the docs state that it will use `quic.DialAddr` by default (https://pkg.go.dev/github.com/lucas-clemente/quic-go@v0.21.0/http3#RoundTripper)

There's a couple of issues with this:
- `quic.DialAddr` has a different signature, not returning an `EarlySession`. Perhaps this is meant to be `quic.DialAddrEarly`?
- Even the signature of `quic.DialAddrEarly` doesn't quite match what the RoundTripper expects (extra network parameter), so basically there are no functions in the library that can be used directly.

I could make a PR but wanted to check first if you had any suggestions which way to address this. Could just fix the doc string, or come up with another dialer that can be plugged into the RoundTripper directly.

**Comment by marten-seemann** [comment]
This is the logic behind it:
https://github.com/lucas-clemente/quic-go/blob/af3e1008ad94c64d5a60d1d7b2ddc579bca4ca79/http3/client.go#L107-L111

So yes, it does use `DialAddrEarly`, not `DialAddr`.
