### ISSUE TITLE
Accessing the streamsMap from the Session Interface

### ISSUE THREAD

**Issue by nodughere** [lucas-clemente/quic-go#3200]
I see that streamsMap is available for the trace debugging, but I don't see it in the documentation.
Since a listener takes a config that specifies maxIncoming streams, it would be nice to be able to check how many streams are in use and available from within a program.

If I'm missing this in the documentation please point me in the right direction.  Otherwise please consider this as an enhancement.

**Comment by marten-seemann** [comment]
Can’t you just count how many streams you opened / accepted (subtracting the ones that were closed)?

**Comment by nodughere** [comment]
Sure.  That will work, I'll do that for now.
