### ISSUE TITLE
What are the plans for connection migration

### ISSUE THREAD

**Issue by zxfrocky** [lucas-clemente/quic-go#3209]
User always change their network from WIFI to 4G , this may cause quic connection would be reconnect，maybe connection migration is the best way，so when does the  connection migration to be implemented ？

**Comment by marten-seemann** [comment]
How do you run quic-go on a mobile phone?

**Comment by zxfrocky** [comment]
> How do you run quic-go on a mobile phone?

my server run quic-go ,  and the mobile client use google chrome's quic lib, it support connection migration, but quic-go do not support .

**Comment by marten-seemann** [comment]
Makes sense.
Then this is a duplicate of #234.

**Comment by ydnar** [comment]
> How do you run quic-go on a mobile phone?

Soon, hopefully: https://github.com/golang/mobile/pull/65
