### ISSUE TITLE
packet lost forever in loss scene

### ISSUE THREAD

**Issue by adwpc** [lucas-clemente/quic-go#3220]
I found the packet(280) lost forever under when capture with wireshark
My scene is loss-20% and latency 20ms
(comcast --device=lo0 --packet-loss=10% --latency=10)

![image](https://user-images.githubusercontent.com/12995347/123792591-5e9ebf00-d913-11eb-969b-37cd5be65887.png)

**Comment by adwpc** [comment]
Scene: send 5KB and recv 500KB (loss-20% and latency 20ms)
Latency=sendTime + recvTime
The latency of quic is 1896.757ms
The latency of tcp is 304.527ms

**Comment by marten-seemann** [comment]
What makes you think that packet 280 was lost? Most likely, it was never sent in the first place.

**Comment by adwpc** [comment]
> What makes you think that packet 280 was lost? Most likely, it was never sent in the first place.


I test again, capture the packet by wireshark.
I found 171 lost after I filtered the packet by PKN=171. 
Please tell me where i was wrong.
![image](https://user-images.githubusercontent.com/12995347/123893593-48cedf80-d98f-11eb-8149-cdd6d5bc5a21.png)
There isn't a packet(PKN=171) which was send from client.
![image](https://user-images.githubusercontent.com/12995347/123893785-a06d4b00-d98f-11eb-8c9b-625926519042.png)
You can see the different between 171 and 172
![image](https://user-images.githubusercontent.com/12995347/123893937-e62a1380-d98f-11eb-8dd4-8aa140cac594.png)

**Comment by adwpc** [comment]
Oh. i see . the PKN(resended) is not N
quic will use a new PKN(N+M) to resend

**Comment by marten-seemann** [comment]
That’s correct. Every packet number is only ever used once.

Also note that we’re occasionally skipping packet numbers to defend against Optimistic ACK attacks.
