### ISSUE TITLE
TCP/KCP/QUIC latency test

### ISSUE THREAD

**Issue by adwpc** [lucas-clemente/quic-go#3221]
Scene：

#### 1 set loss 10% and delay 10ms by: 
`comcast --device=lo0 --packet-loss=5% --latency=5`

#### 2 client use tcp/kcp/quic and send 5KB and recv 100KB, loop 100 times and get a result
```
client-----5KB------>server
client<----100KB--------|
```
for example:
```
./ethr -c 127.0.0.1 -port 443 -d 30s -t l -i 100 --debug -ls 5000 -lr 100000 -p quic
-----------------------------------------------------------------------------------------
Avg	Min	10%	20%	30%	40%	50%	60%	70%	80%	90%	95%	99%	99.9%	99.99%	Max
150.654	37.641	94.565	104.039	120.916	126.627	144.059	159.636	168.557	190.859	208.191	240.972	309.006	309.006	309.006	356.66
```
#### 3 make a scatter diagram with tcp/kcp/quic results
![image](https://user-images.githubusercontent.com/12995347/123935477-da0d7880-d9c6-11eb-8575-07096df5fc82.png)
seems: 
kcp and tcp latency is better than quic
80% tcp/kcp points latency < 50ms
80% quic points latency < 190ms

Any suggestions are welcome

**Comment by marten-seemann** [comment]
10% random loss? That seems like a very unrealistic scenario to test.

**Comment by ldmid666** [comment]
@adwpc 可以发一下测试代码，参考一下吗

**Comment by ldmid666** [comment]
> 10% random loss? That seems like a very unrealistic scenario to test.
Why is this an unrealistic test？
