### ISSUE TITLE
quic-go locks up

### ISSUE THREAD

**Issue by arashpayan** [lucas-clemente/quic-go#3225]
Hi there! Sorry for the generic sounding title. Hopefully someone who can diagnose the issue can also improve the title.

**OVERVIEW**
I've written a service made up of a 'director' (server) and a 'worker' (client) that communicate through the network using a long lasting quic session. Once the worker connects to the director, the director sends various commands to the worker for it to execute and then respond with a result. Each command uses a new bidirectional stream. The commands come in two forms:
* Short commands where the command is executed by the worker and the response is returned.
* Long (streaming) commands where the worker sends many updates/responses back to the director over the single stream for the duration of the execution of the command.

**BUG**
I found a scenario in the service where quic communication is effectively locked up.
* The session never times out,
* `Write()`s to the long running streams are blocked indefinitely
* New commands from (streams opened by) the director are able to send data, the worker receives the data, sends its response, but the director never receives the response from the stream. It also never errors out, despite the worker thinking it has finished writing and successfully closed the quic stream.

I know this all sounds crazy, and unbelievable, so I wrote a server and client that reproduces the issue:
https://github.com/arashpayan/reproquicblock

To reproduce it:
* Check out the code
* Run the director in one shell: `cd director` then `go run *.go`
* Run the worker in another shell: `cd worker` then `go run *.go`

**EXPECTED**
* The worker should continuously be printing `OnList in=...` as it receives commands from the director.
* The director should continuously be printing `Walk received response=...` as it receives results from the worker.
* The director should be able to send new commands to the worker at any time.

**ACTUAL**
Shortly after the second job is sent to the worker (https://github.com/arashpayan/reproquicblock/blob/main/director/main.go#L38), the director no longer receives responses from the long running command it issued to the worker. Additionally, the goroutine that starts here will never receive a response to its `List` command though the worker will log that it received it: https://github.com/arashpayan/reproquicblock/blob/main/director/main.go#L45

Also, if you comment out the sending of the second job, the director and worker will operate just fine. Weird.

**COMMENTS**
For convenience, the director serves `/debug/pprof` on port 8498 and the worker serves it on port 8499. The director listens for connections from the worker on port 7498.

After the lock up, if you look at the worker's goroutines, you'll see the writing ones stuck here: https://github.com/lucas-clemente/quic-go/blob/29452277517826b3c0c450dc8bd0a351edc9e8d9/send_stream.go#L167

I wish I was more fluent in the quic protocol and quic-go to help out, but hopefully the provided code will be sufficient. Thanks. :-)

**Comment by marten-seemann** [comment]
Not sure how I can help here. I don't have the bandwidth to do an in-depth review of your code.

In general, blocking on `Stream.Write` can occur when the other side is not reading from the stream, and the flow control budget is eventually used up.

**Comment by arashpayan** [comment]
The linked code isn't the whole project I was describing. It's a barebones client and server that I wrote just for this issue to demonstrate the problem.

> In general, blocking on Stream.Write can occur when the other side is not reading from the stream, and the flow control budget is eventually used up.

The director peer is reading and blocked in `receive_stream.go:148` waiting for data, but it never receives anything from the worker. Both processes are idle; one waiting for data to be read, and the other waiting for its write of the data to finish. If it was a flow control budget being used up would it not eventually push *some* data through?

**Comment by marten-seemann** [comment]
One you can debug this is to record qlogs and inspect them with https://qvis.quictools.info/.

**Comment by arashpayan** [comment]
I think I've cracked the issue. Am I correct in assuming that the amount of data that can be buffered (window size?) is limited per connection/session and *not* per stream? So if there is a peer that has been writing to a stream that is not being read from by the remote peer and the window fills up, any new streams that the remote peer tries to open will not receive data until some space opens up in the window. Is that correct?

**Comment by arashpayan** [comment]
Section 4 of the QUIC spec clears it all up for me.
> To enable a receiver to limit memory commitments for a connection, streams are flow controlled both individually and across a connection as a whole.

https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport-34#section-4
Thanks for the tip and thank you for quic-go!
