### ISSUE TITLE
Loss detection alarm for 1-RTT fired on MaxStreamsFrame

### ISSUE THREAD

**Issue by ydnar** [lucas-clemente/quic-go#3227]
I have a quic-go/http3 server which, when connected to via Chrome, consistently reports loss detection alarms for the `wire.MaxStreamsFrame` packets being sent back to the client.

Both the browser and server are on the same host, and the requests hit 127.0.0.1. An identical request using Safari or curl reports no lost packets.

```
2021/07/08 14:25:36 server Loss detection alarm for 1-RTT fired in PTO mode. PTO count: 1
2021/07/08 14:25:36 server -> Sending packet 26 (22 bytes) for connection e178715c41f043d6, 1-RTT
2021/07/08 14:25:36 server 	Short Header{DestConnectionID: (empty), PacketNumber: 26, PacketNumberLen: 2, KeyPhase: 0}
2021/07/08 14:25:36 server 	-> &wire.MaxStreamsFrame{Type: bidi, MaxStreamNum: 102}
```

Second, Chrome’s net-export logs show 6x retransmission of an H3 request packet to the same server:

```
t= 390 [st=29275]  QUIC_SESSION_PACKET_SENT
                   --> encryption_level = "ENCRYPTION_FORWARD_SECURE"
                   --> packet_number = 16
                   --> sent_time_us = 352797914314
                   --> size = 481
                   --> transmission_type = "NOT_RETRANSMISSION"
t= 553 [st=29438]  QUIC_SESSION_STREAM_FRAME_SENT
                   --> fin = false
                   --> length = 9
                   --> offset = 68
                   --> stream_id = 2
t= 553 [st=29438]  QUIC_SESSION_STREAM_FRAME_SENT
                   --> fin = true
                   --> length = 443
                   --> offset = 0
                   --> stream_id = 12
t= 553 [st=29438]  QUIC_SESSION_PACKET_SENT
                   --> encryption_level = "ENCRYPTION_FORWARD_SECURE"
                   --> packet_number = 18
                   --> sent_time_us = 352798077395
                   --> size = 481
                   --> transmission_type = "PTO_RETRANSMISSION"
t= 644 [st=29529]  QUIC_SESSION_STREAM_FRAME_SENT
                   --> fin = false
                   --> length = 9
                   --> offset = 68
                   --> stream_id = 2
t= 644 [st=29529]  QUIC_SESSION_STREAM_FRAME_SENT
                   --> fin = true
                   --> length = 443
                   --> offset = 0
                   --> stream_id = 12
t= 644 [st=29529]  QUIC_SESSION_PACKET_SENT
                   --> encryption_level = "ENCRYPTION_FORWARD_SECURE"
                   --> packet_number = 20
                   --> sent_time_us = 352798168799
                   --> size = 481
                   --> transmission_type = "PTO_RETRANSMISSION"
etc...
```

**Comment by marten-seemann** [comment]
If you enable qlog and load the file into qvis, you’ll see why the packet is being considered lost.

**Comment by ydnar** [comment]
Hah. The time scale between Chrome netlog and qlog is quite extreme.

**Comment by ydnar** [comment]
@marten-seemann it looks like the server-sent packets containing `wire.MaxStreamsFrame` frames are empty.

**Comment by ydnar** [comment]
It appears that:

- Whatever happens between quic-go and Chrome causes Chrome to mark the connection as bad, which chokes new WebTransport connections for 30s or a relaunch (or both).

- Forcing QUIC on localhost seems to enable QUIC/H3 for normal HTTP requests, even though the connection eventually fails 100% of the time.

- If I change quic-go to emit a PingFrame along with every MaxStreamsFrame, it reduces the ack alarm to 1x/session (Chrome will ack the combined Ping/MaxStream packets). Ultimately the session still fails.

- Neither curl or Safari seem to exhibit this problem. My best guess is there's some subtle incompatibility between quiche/Chrome and quic-go that manifests itself as missing acks and ultimately the connection being marked as broken.

**Comment by marten-seemann** [comment]
Great debugging!

This looks like a bug in Chrome. PING frames aren’t supposed to be treated any different from any other ack-eliciting frames.
Would you mind reporting this to the Chrome team?

**Comment by ydnar** [comment]
> Great debugging!
> 
> This looks like a bug in Chrome. PING frames aren’t supposed to be treated any different from any other ack-eliciting frames.
> Would you mind reporting this to the Chrome team?

PING frames elicit an ack from Chrome. It’s the MAX_STREAMS frames after a completed H3 request cycle that don’t seem to elicit an ack.

Bug filed here if you want to vote for it: https://bugs.chromium.org/p/chromium/issues/detail?id=1228086

**Comment by ydnar** [comment]
Here’s the relevant `UDP_SOCKET` section from the above Chrome netlog. As you can see, it sends out the its last `ACK` packet (number 17) with padding for packets 7-21, and then `go-quic` starts sending (and re-sending) the `MAX_STREAMS` packets (22 bytes each):

```
t= 4953 [st=   46]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 23
t= 4953 [st=   46]    UDP_BYTES_SENT
                      --> byte_count = 29
t= 4953 [st=   46]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 4987 [st=   80]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 4987 [st=   80]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5053 [st=  146]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5053 [st=  146]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5185 [st=  278]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5185 [st=  278]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5449 [st=  542]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5449 [st=  542]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5974 [st= 1067]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 5974 [st= 1067]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 7024 [st= 2117]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 7024 [st= 2117]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 9123 [st= 4216]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t= 9123 [st= 4216]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t=13319 [st= 8412]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t=13320 [st= 8413]    UDP_BYTES_RECEIVED
                      --> address = "127.0.0.1:4433"
                      --> byte_count = 22
t=20341 [st=15434] 
```

**Comment by ydnar** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1228086#c7

> Doh! That looks bad :( I think it's a really bug which is because QuicConnection::OnMaxStreamsFrame() does not appear to call   MaybeUpdateAckTimeout().

**Comment by ydnar** [comment]
Fix part 1: https://quiche.googlesource.com/quiche/+/fb75f7ecf567a9cecf9e0b89365b9e7d6c1268ad%5E%21/

Fix part 2: https://chromium-review.googlesource.com/c/chromium/src/+/3026853

Should land in Chrome Canary after ^ 3026853 is merged.

**Comment by ydnar** [comment]
Seems like it’s fixed in Chrome Canary as of yesterday.

https://chromium-review.googlesource.com/c/chromium/src/+/3035301

**Comment by marten-seemann** [comment]
Great news! Thanks for pushing this through @ydnar!

**Comment by ydnar** [comment]
> Great news! Thanks for pushing this through @ydnar!

Thanks for your help! Now if I could figure out what’s happening with these intermittent WebTransport connection failures, which fail with no connection attempts to the server:

```
Initiating connection...
Connection failed. TypeError: Connection lost.
```

**Comment by marten-seemann** [comment]
What does the qlog say?

**Comment by ydnar** [comment]
> What does the qlog say?

Nothing. It fails without any apparent connection attempt.
