### ISSUE TITLE
wrapConn called twice in server

### ISSUE THREAD

**Issue by ydnar** [lucas-clemente/quic-go#3228]
While debugging #3227, I noticed that the server wraps the `net.PacketConn` twice into a `connection` interface, once in `(multiplexer).AddConn` and immediately after in `listen` before instantiating the `baseServer`:

https://github.com/lucas-clemente/quic-go/blob/master/server.go#L190-L201

```go
	sessionHandler, err := getMultiplexer().AddConn(conn, config.ConnectionIDLength, config.StatelessResetKey, config.Tracer)
	if err != nil {
		return nil, err
	}
	tokenGenerator, err := handshake.NewTokenGenerator(rand.Reader)
	if err != nil {
		return nil, err
	}
	c, err := wrapConn(conn)
	if err != nil {
		return nil, err
	}
```

It looks like this change was introduced in #3067 (cc @rs).

I tried a small change to `listen` that extracts the `connection` from the `packetHandlerMap` and it seems to work (although it doesn’t fix my issue with Chrome):

```go
	var c connection
	if m, ok := sessionHandler.(*packetHandlerMap); ok {
		c = m.conn
		utils.DefaultLogger.Debugf("extracted wrapped connection: %v", m.conn)
	} else {
		c, err = wrapConn(conn)
		if err != nil {
			return nil, err
		}
	}
```

I can make a PR if that’d be helpful.

**Comment by marten-seemann** [comment]
I can't reproduce this. I added the following lines in `wrapConn` before the `return` statement:
```go
	if _, ok := pc.(connection); ok {
		panic("conn already wrapped")
	}
```

and I don't observe any panics when running the integration tests. Any ideas?

**Comment by ydnar** [comment]
It won't panic because the caller passes the udpconn to two things that wrap it.

Sorry on phone so I can't provide better context

**Comment by ydnar** [comment]
@marten-seemann here’s a commit that fixes the double `wrapConn` in my branch: https://github.com/alta/quic-go/commit/39ca6e6fcc4f41300ce0bb9cc1e71bf0508e98cb

There’s probably a better way to fix this. I observed the double `wrapConn` when enabling `QUIC_GO_LOG_LEVEL=debug`:

```shell
$ FS_LIVE=1 QUIC_GO_LOG_LEVEL=debug go run ./cmd/server -a 127.0.0.1:4433
2021/07/17 14:15:09 Server listening at: https://127.0.0.1:4433
2021/07/17 14:15:09 muxer Increased receive buffer size to 2048 kiB
2021/07/17 14:15:09 Activating reading of ECN bits for IPv4.
2021/07/17 14:15:09 Activating reading of ECN bits for IPv4.
2021/07/17 14:15:09 server Listening for udp connections on 127.0.0.1:4433
2021/07/17 14:15:11 muxer Tracking 0 connection IDs and 0 reset tokens.
``` 

The key line `Activating reading of ECN bits for IPv4.` indicated `wrapConn` was called twice from `listen`, once directly and once in `getMultiplexer().AddConn`.

**Comment by marten-seemann** [comment]
Indeed, adding some logging I get:
```
wrapConn from 127.0.0.1:6121 (&net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc000034a00)}})
wrapConn from 127.0.0.1:6121 (&net.UDPConn{conn:net.conn{fd:(*net.netFD)(0xc000034a00)}})
```
This means that we're wrapping the same `net.UDPConn` twice (but we're not double-wrapping it).

The server then only uses it to write Version Negotiation / Retry / SERVER_BUSY packets. So this is not actually a bug, but just a confusing way we do the wrapping.

**Comment by ydnar** [comment]
> This means that we're wrapping the same `net.UDPConn` twice (but we're not double-wrapping it).

Yes, correct.

> The server then only uses it to write Version Negotiation / Retry / SERVER_BUSY packets. So this is not actually a bug, but just a confusing way we do the wrapping.

I think the issue is that two separate `oobConn` structs get created, each with their own message buffers. Is that what you want?
