### ISSUE TITLE
loss package scene mismatch wireshark and qlog tracer

### ISSUE THREAD

**Issue by Zeymo** [lucas-clemente/quic-go#3234]
loss package scene : upstream 50% downstream 50%
client : lsquic
server：quic-go

server log
https://gist.github.com/Zeymo/cc3a4197d9e0eef27ed5dcda03fe3041

![image](https://user-images.githubusercontent.com/3691013/126274531-b3abeef5-e747-426b-bfa6-35e980beb0ca.png)

wireshark pcap
![image](https://user-images.githubusercontent.com/3691013/126272703-fcbddf25-99dd-440b-af78-16744aa33e9b.png)

I wondered why quic-go log and qlog shows send intial and handshake but wireshark shows nothing,that is,client send always package in 8732300f but quic-go send package in f7b99914. finnally client don't any handshake package

Is there any loss package here   

for another question,quic-go "Loss detection alarm for Initial fired in PTO mode" and send package with PTO(2,3) in 1s too frequantly, How can I delay this PTO delta

**Comment by marten-seemann** [comment]
The PTO timer is working as intended.
Wireshark won't be able to decrypt packet number from non-Initial packets unless you feed it the TLS keys, as the header is encrypted.
