### ISSUE TITLE
Document setting UDP buffer size on BSD-based platforms

### ISSUE THREAD

**Issue by gammazero** [lucas-clemente/quic-go#3246]
The wiki page [UDP Receive Buffer Size](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size) describes how to set the UDP receive buffer size and a recommended value, for Linux.  Since BSD-based platforms are popular networking platforms it would be useful to add instruction and recommended setting for this as well.

Taken from: https://medium.com/@CameronSparr/increase-os-udp-buffers-to-improve-performance-51d167bb1360

> On BSD/Darwin systems you need to add about a 15% padding to the kernel limit socket buffer. Meaning if you want a 25MB buffer (8388608 bytes) you need to set the kernel limit to 26214400*1.15 = 30146560. This is not documented anywhere but happens [in the kernel here](https://github.com/freebsd/freebsd-src/blob/master/sys/kern/uipc_sockbuf.c#L63-L64).

To update the value immediately to 2.5M, type the following commands as root:
```sh
sysctl -w kern.ipc.maxsockbuf=3014656
```
Add the following lines to the `/etc/sysctl.conf` file to keep this setting across reboots:
```
kern.ipc.maxsockbuf=3014656
```

**Comment by marten-seemann** [comment]
Thank you @gammazero! I copy-pasted your instructions to the wiki page.
