### ISSUE TITLE
Change UDP buffer size without sysctl on non-sysctl linux

### ISSUE THREAD

**Issue by brainos233** [lucas-clemente/quic-go#3250]
My router's kernel is 2.6.36.4 and there is no sysctl in it, so I suggest adding some ways to solve it.

After searching, I found that command is useful:

> echo 2500000 > /proc/sys/net/core/rmem_max

Please you put it to wiki.

**Comment by marten-seemann** [comment]
> My router's kernel is 2.6.36.4

That's more than 10 years old... https://lwn.net/Articles/428684/

**Comment by brainos233** [comment]
> > My router's kernel is 2.6.36.4
> 
> That's more than 10 years old... https://lwn.net/Articles/428684/

I am using asus RT-AC1900P, the firmware is merlin and only 2.6.36.4 is supported

**Comment by bt90** [comment]
Doesn't really change the fact that this is abandonware.

**Comment by marten-seemann** [comment]
Closing this issue, as we're not going to make any changes for ancient kernel versions.
