### ISSUE TITLE
Allow setting custom port in Alt-Svc header value

### ISSUE THREAD

**Issue by aaronriekenberg** [lucas-clemente/quic-go#3262]
I have an app using quic-go running as a non-privileged user process on port 8443.  A firewall redirects UDP and TCP traffic on port 443 to my app on port 8443.

I am finding I need to rewrite the Alt-Svc header value to replace ":8443" with ":443" to make this work: https://github.com/aaronriekenberg/pi-web/blob/master/pi-web.go#L24-L56

Is there any better way to do this?  Could it be possible to add some configuration to http3.ListenAndServe or quicServer.SetQuicHeaders to allow for a custom Alt-Svc port?  I suspect this is a fairly common use-case.

This is the form of ListenAndServe my app is calling: https://github.com/lucas-clemente/quic-go/blob/master/http3/server.go#L488

Thanks!

**Comment by marten-seemann** [comment]
> 2. In hopHeaders in reverse proxy. These seem to be used just to delete these headers from proxied requests and responses: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L902

That makes sense, doesn't it? Just because the backend server supports QUIC, that doesn't mean that the frontend server supports QUIC as well. This applies because Caddy acts as a HTTP proxy here.

Am I right to assume that your firewall just wants to forward UDP packets, without looking at the HTTP payload at all?

**Comment by aaronriekenberg** [comment]
> > 1. In hopHeaders in reverse proxy. These seem to be used just to delete these headers from proxied requests and responses: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L902
> 
> That makes sense, doesn't it? Just because the backend server supports QUIC, that doesn't mean that the frontend server supports QUIC as well. This applies because Caddy acts as a HTTP proxy here.

Yes agree 👍 

> Am I right to assume that your firewall just wants to forward UDP packets, without looking at the HTTP payload at all?

Yes correct - the firewall (OpenBSD PF) is using a "layer 4" redirect rule.  This redirects incoming TCP and UDP traffic from port 443 to port 8443.

The firewall is not aware of any application-level protocols (QUIC, HTTP).

This works perfectly with HTTP/1 and HTTP/2 using TCP connections.  But with HTTP/3 - my server using quic-go believes it is running on port 8443 and returns this in the Alt-Svc header.  In fact clients need to use UDP port 443 to connect to my server through the firewall.

**Comment by marten-seemann** [comment]
Thanks for confirming. What would you think of exposing the `port` in the `http3.Server`? That would solve your problem, wouldn't it?

**Comment by marten-seemann** [comment]
If so, I'd be happy to review a PR. Please make sure to add a comment explaining when a user might want to manually set this variable (i.e., when behind a layer 4 proxy).
