### ISSUE TITLE
timeout: no recent network activity

### ISSUE THREAD

**Issue by koalabearguo** [lucas-clemente/quic-go#3267]
```go
var qconf quic.Config
qconf.KeepAlive = true

tr := &http3.RoundTripper{TLSClientConfig: cli.tlsconfig, QuicConfig: &qconf}
//
qclient = &http.Client{
        Transport: tr,
}
resp,err = qclient.Post(url,"application/octet-stream",body1)

//err == nil

delay a few minutes

resp,err = qclient.Post(url,"application/octet-stream",body2) //same host url

//err != nil give timeout: no recent network activity
```
After i Post a data to url , wait a few minutes，then post another data to the same url，i get an err(timeout: no recent network activity)

I found i should call tr.Close() after Post a data,or next Post will fail!!!!

Is this expected behavior???

**Comment by marten-seemann** [comment]
I can't reproduce this. Please create a minimal working example (using the example server in `example/main.go` as the server endpoint), if you think there's a bug here.

**Comment by NitroCao** [comment]
Maybe duplicate of #765

**Comment by koalabearguo** [comment]
@NitroCao Yes,you are right.

**Comment by koalabearguo** [comment]
I found this duplicate of #3198
