### ISSUE TITLE
any event for new data coming for read without HTTP server

### ISSUE THREAD

**Issue by yifan513** [lucas-clemente/quic-go#3269]
Hi,
I am try to use your quic-go to my server to replace a UDP communication part. And I did some updating to test your echo server. It seems there is no event for new data coming for read. Correct?
As the below code in while loop
		
`		stream, err := session.AcceptStream(context.Background())
		if err != nil {
			fmt.Println("AcceptStream err", err)
			return
		}
		go func() {
			b := make([]byte, 1500)
			for {
				n, err := stream.Read(b)
				if err != nil {
					fmt.Println("Error in read", err)
				}

				fmt.Println("server Received ", string(b[:n]))
				stream.Write([]byte("quic-go server reply you:"))
				_, err = stream.Write(b[:n])
				if err != nil {
					log.Println("Stream write error: ", err)
				}
			}`

Thanks
David

**Comment by marten-seemann** [comment]
You probably want to have a Go routine that blocks on `Read`. I can't read your code, please familiarize with how to use Markdown before pasting code here.
