### ISSUE TITLE
 http3 client to access the http3 server using the get method, every 12 requests is extremely slow

### ISSUE THREAD

**Issue by RiseInRose** [lucas-clemente/quic-go#3274]
When I use the http3 client to access the http3 server using the get method, I found that one of every 12 requests is extremely slow. I used pprof and could not found  problems. also I used google to find any information but nothing helps. Can someone please check it out?
![image](https://user-images.githubusercontent.com/15624085/133230613-a152fb84-35d7-4d83-91d7-ef78fcf23002.png)

![image](https://user-images.githubusercontent.com/15624085/133232144-c11571a4-dff8-4320-964c-4dd8987abcb4.png)

**Comment by marten-seemann** [comment]
Have you tried turning on qlog and loading the trace into qvis?

**Comment by RiseInRose** [comment]
Sorry, This is my mistake. The quic client logic I wrote is very messy. After I refactored it, this situation did not happen.

The actual reason is probably that after I created a client connection, I closed it after the function ended, but I called the closed client in a later program, and it can be used. Then cause the above problem
