### ISSUE TITLE
Question about setting IP_PKTINFO for QUIC servers listening on wildcard (0.0.0.0). 

### ISSUE THREAD

**Issue by sudarshan-reddy** [lucas-clemente/quic-go#3275]
Hey guys. 

I'm trying to solve the problem raised in https://github.com/lucas-clemente/quic-go/issues/1736 by setting IP_PKTINFO on as sockopt but this doesn't seem to work. 

How can I tell: 

To reproduce this, I have a server behind anycast with a bunch of ips on a single NIC.

This is the server: https://pastebin.com/wJuVcWya (its the hello world example repurposed a bit). 

My expectation here when I run tcpdump is I should see communication flow the from the same ip both ways but this isn't the case.

```
sudo tcpdump -n -i eth0 port 4242 and udp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vlan100, link-type EN10MB (Ethernet), capture size 262144 bytes
14:44:27.742629 IP 17.24.60.44.50152 > 19.41.20.20.4242: UDP, length 1252
14:44:27.743298 IP 17.24.60.13.4242 > 17.24.60.44.50152: UDP, length 37
```

When running my server with `strace` I also  cannot see `ipi_addr` on `sendmsg()`. 

I'm using the latest revision of `quic-go` and running `go1.17`.

**Comment by marten-seemann** [comment]
#1736 should have been resolved. Have you looked at what packet info quic-go is passing around?

**Comment by sudarshan-reddy** [comment]
@marten-seemann is there a recommended way to do this?  I'm assuming setting logs to debug should do this.

**Comment by marten-seemann** [comment]
We don't have debug statements for that, so you'd have to add some to the code. https://github.com/lucas-clemente/quic-go/blob/ebcd98ed431baba6ab1c31e278fb80f23fdf1fd7/send_conn.go#L25-L32 and https://github.com/lucas-clemente/quic-go/blob/ebcd98ed431baba6ab1c31e278fb80f23fdf1fd7/conn_oob.go#L209-L215 would be probably be good starting points.

**Comment by sudarshan-reddy** [comment]
Okay they both get the correct source ips. Does my idea of setting the socket in the example I linked (    
    `if err := syscall.SetsockoptInt(int(fd), syscall.IPPROTO_IP, syscall.IP_PKTINFO, 1); err != nil {`
) look right?

**Comment by sudarshan-reddy** [comment]
Okay here is a better illustration of the problem. 

The OOB byte array [here](https://github.com/lucas-clemente/quic-go/blob/master/conn_oob.go#L227) has the destip but it is not set in `sendmsg`. 

From strace...
```
09:21:25.848522 write(1, "oob packet: [28 0 0 0 0 0 0 0 6 "..., 77oob packet: [28 0 0 0 0 0 0 0 6 0 0 0 8 0 0 0 4 0 0 0 172 16 60 198 0 0 0 0]
) = 77 <0.000009>
09:21:25.848563 sendmsg(3, {msg_name={sa_family=AF_INET6, sin6_port=htons(40056), inet_pton(AF_INET6, "::ffff:172.16.245.133", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, msg_namelen=28, msg_iov=[{iov_base="@\3\373\322\364\211\212\22\34\260\340\317aJ4\253\204G\354\10\31", iov_len=21}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_TCP, cmsg_type=0x8}], msg_controllen=28, msg_flags=0}, 0) = 21 <0.000027>
```

Notice `ipi_addr` is missing here. 

I can for example, see it on `recvmmsg`

```
09:20:55.140623 recvmmsg(3, [{msg_hdr={msg_name={sa_family=AF_INET6, sin6_port=htons(52706), inet_pton(AF_INET6, "::ffff:172.16.245.133", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, msg_namelen=28, msg_iov=[{iov_base="KC\275\204\233,\376\351>Ii\264\263zW\306\r\"\211{\343\363Va\34\35P\301", iov_len=1452}], msg_iovlen=1, msg_control=[{cmsg_len=36, cmsg_level=SOL_IPV6, cmsg_type=0x32}, {cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("eth0"), ipi_spec_dst=inet_addr("172.16.60.198"), ipi_addr=inet_addr("172.16.60.198")}}, {cmsg_len=17, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0]}], msg_controllen=96, msg_flags=0}, msg_len=28}], 8, 0, NULL) = 1 <0.000011>
```

**Comment by marten-seemann** [comment]
That's surprising. We're passing the OOB info to the `Write` call: https://github.com/lucas-clemente/quic-go/blob/ebcd98ed431baba6ab1c31e278fb80f23fdf1fd7/send_conn.go#L34-L37
Any idea why it doesn't work?

**Comment by sudarshan-reddy** [comment]
I tried using the ipv4 library instead and now I get

```
10:16:26.357833 sendmsg(3, {msg_name={sa_family=AF_INET6, sin6_port=htons(58388), inet_pton(AF_INET6, "::ffff:172.16.245.133", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, msg_namelen=28, msg_iov=[{iov_base="X\v\376s\363\240G\256\224_'\35P\247\230\323\241\22295\244\n6\242\360\36\205|\333\255i\247"..., iov_len=1277}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_IP, cmsg_type=IP_PKTINFO, cmsg_data={ipi_ifindex=if_nametoindex("eth0"), ipi_spec_dst=inet_addr("172.16.60.198"), ipi_addr=inet_addr("0.0.0.0")}}], msg_controllen=32, msg_flags=0}, 0) = 1277 <0.000040>
```

**Comment by marten-seemann** [comment]
Does that output show that it works now? Did you figure out what the problem with the current code is?

**Comment by sudarshan-reddy** [comment]
Correct. I also confirmed by running it in my test environment behind anycast.

My fix very roughly was to use `golang.org/x/net/ipv4` instead of unsafe cmsg control header.

```
func (info *packetInfo) OOB() []byte {
	if info == nil {
		return nil
	}
	if ip4 := info.addr.To4(); ip4 != nil {
		// struct in_pktinfo {
		// 	unsigned int   ipi_ifindex;  /* Interface index */
		// 	struct in_addr ipi_spec_dst; /* Local address */
		// 	struct in_addr ipi_addr;     /* Header Destination address */
		// };
		msgLen := 12
		if runtime.GOOS == "freebsd" {
			msgLen = 4
		}
		cmsglen := cmsgLen(msgLen)
		oob := make([]byte, cmsglen)
		cmsg := (*syscall.Cmsghdr)(unsafe.Pointer(&oob[0]))
		cmsg.Level = syscall.IPPROTO_TCP
		cmsg.Type = msgTypeIPv4PKTINFO
		cmsg.SetLen(cmsglen)
		off := cmsgLen(0)
		if runtime.GOOS != "freebsd" {
			// FreeBSD does not support in_pktinfo, just an in_addr is sent
			binary.LittleEndian.PutUint32(oob[off:], info.ifIndex)
			off += 4
		}
		copy(oob[off:], ip4)
		// this works for me
		cm := ipv4.ControlMessage{}
		cm.Src = ip4
		cm.IfIndex = int(info.ifIndex)
		return cm.Marshal()
		//return oob
	} else if len(info.addr) == 16 {
		// struct in6_pktinfo {
		// 	struct in6_addr ipi6_addr;    /* src/dst IPv6 address */
		// 	unsigned int    ipi6_ifindex; /* send/recv interface index */
		// };
		const msgLen = 20
		cmsglen := cmsgLen(msgLen)
		oob := make([]byte, cmsglen)
		cmsg := (*syscall.Cmsghdr)(unsafe.Pointer(&oob[0]))
		cmsg.Level = syscall.IPPROTO_IPV6
		cmsg.Type = msgTypeIPv6PKTINFO
		cmsg.SetLen(cmsglen)
		off := cmsgLen(0)
		off += copy(oob[off:], info.addr)
		binary.LittleEndian.PutUint32(oob[off:], info.ifIndex)
		// this works for me
		cm := ipv6.ControlMessage{}
		cm.IfIndex = int(info.ifIndex)
		cm.Src = info.addr
		return cm.Marshal()
		//return oob
	}
	return nil
}
```

Steps to reproduce:

1. Run the server I linked in pastebin with strace -ttT. (Make sure you run it with `dst` not set or false). 
2. Run this [client](https://pastebin.com/7LjEiLUT) to connect to it. 
3. You'll notice that `sendmsg` doesn't get populated with the needed fields.

**Comment by marten-seemann** [comment]
Using `golang.org/x/net/ipv4` definitely is cleaner than using `unsafe`. Would you be willing to contribute a PR?
Is there any way to make sure this also works on FreeBSD (not a priority, but would be nice to have)?

**Comment by sudarshan-reddy** [comment]
Absolutely. I'd love to. I'm on it now.

**Comment by sudarshan-reddy** [comment]
@marten-seemann I'm still trying to understand the testing framework. 

Running go test -v ./... as mentioned in the README.md gets me all green results but I can't seem to isolate or find tests from conn_oob_test.go there.

**Comment by marten-seemann** [comment]
We're using [ginkgo](https://github.com/onsi/ginkgo). Try `ginkgo -v`.

**Comment by sudarshan-reddy** [comment]
Awesome. 

I see them 

```
------------------------------
OOB Conn Test ECN conn
  reads ECN flags on IPv4
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:59
•
------------------------------
OOB Conn Test ECN conn
  reads ECN flags on IPv6
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:79
•
------------------------------
OOB Conn Test ECN conn
  reads ECN flags on a connection that supports both IPv4 and IPv6
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:99
•
------------------------------
OOB Conn Test Packet Info conn
  reads packet info on IPv4
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:142
•
------------------------------
OOB Conn Test Packet Info conn
  reads packet info on IPv6
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:160
•
------------------------------
OOB Conn Test Packet Info conn
  reads packet info on a connection that supports both IPv4 and IPv6
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:178
•
------------------------------
OOB Conn Test Batch Reading
  reads multiple messages in one batch
  /Users/sudarsanreddy/dev/quic-go/conn_oob_test.go:211
  ```

**Comment by sudarshan-reddy** [comment]
@marten-seemann : All green on CI and PR should be good to review.

**Comment by zllovesuki** [comment]
Side question: by the same logic, can we use the `x` package to Unmarshal OOB buffer?

**Comment by sudarshan-reddy** [comment]
Don't see why not. I'll try to make this change as well.

**Comment by zllovesuki** [comment]
It wasn't my intention to widen the scope of your PR 🙃

However, if you do have the time, thank you 👍

**Comment by sudarshan-reddy** [comment]
Actually, I think this should be a separate PR too. I just realised I did not do this because with the initial one because it breaks BSD and I need some time to understand how to handle that with the `x` package. I can create a separate issue to track my work if that is okay.
