### ISSUE TITLE
Test the bandwidth of a single Listener up to about 2000Mb, is there a problem with the configuration?

### ISSUE THREAD

**Issue by DoubleCircle-Salt** [lucas-clemente/quic-go#3279]
server

	tlsConfig := &tls.Config{
		Certificates:           []tls.Certificate{cert},
		NextProtos:             []string{"http3"},
	}

	quicConfig := &quic.Config{
		KeepAlive:      false,
		AcceptToken:    func(_ net.Addr, _ *quic.Token) bool { return true },
		Versions:       []quic.VersionNumber{quic.VersionDraft29},
		MaxIdleTimeout: 3 * time.Second,
	}

	quicListener, err := quic.ListenAddrEarly(fmt.Sprintf("0.0.0.0:%d", port), tlsConfig, quicConfig)
	if err != nil {
		println("listen failed:", err.Error())
		return
	}

**Comment by marten-seemann** [comment]
You probably don’t need to set NextProtos and Versions manually, but that’s not something that would affect your bandwidth.

**Comment by DoubleCircle-Salt** [comment]
Perform a stress test: The bandwidth of a single listener can be up to 2000Mb. When multiple listeners are turned on, the bandwidth can be hit more.The machine is 64-core, 10 Gigabit network card.When testing udp, a single listener can also hit more bandwidth

**Comment by marten-seemann** [comment]
Sorry, I can't help you debug your test setup. This doesn't sound like a quic-go bug.

**Comment by DoubleCircle-Salt** [comment]
Have you ever done a stress test? 
Can the input bandwidth of a single listener be more than 3000Mb? 
I tried a pressure test to 127.0.0.1, and the input bandwidth can only reach 2000+Mb at most.

**Comment by DoubleCircle-Salt** [comment]
Sorry, I want to make sure
