### ISSUE TITLE
PMTU Discovery causes IP fragmentation

### ISSUE THREAD

**Issue by VinozzZ** [lucas-clemente/quic-go#3285]
While running load test for our quic-go integration, we discovered that when PMTUD is enabled, there's IP fragmentation happening. Here's the pcap I capture
[ip-fragmentation.pcap.zip](https://github.com/lucas-clemente/quic-go/files/7289740/ip-fragmentation.pcap.zip)
d

**Comment by VinozzZ** [comment]
Just want to double check, are you using Wireshark to view the file? Have you turned off the automatic reassembling feature?

**Comment by marten-seemann** [comment]
I see that the DF bit is set, this is the only thing that's relevant from quic-go's perspective. If your host / network is fragmenting packets that have the DF bit set, this is a bug in your hosts / one of your network device's network stacks, not a bug in quic-go.

**Comment by VinozzZ** [comment]
<img width="1626" alt="Screen Shot 2021-10-06 at 12 02 15 PM" src="https://user-images.githubusercontent.com/22300958/136240986-47068084-2bbe-49ed-a65c-f4688b257713.png">
This is what I see from the capture in wireshark

**Comment by VinozzZ** [comment]
Thanks for jumping in! I will generate a new one and post it here

**Comment by VinozzZ** [comment]
[ip-fragment.pcap.zip](https://github.com/lucas-clemente/quic-go/files/7295843/ip-fragment.pcap.zip)
Here's the new capture. It should contain all packets from both side

**Comment by VinozzZ** [comment]
The quic packet is 1252(defined here: https://github.com/lucas-clemente/quic-go/blob/84e03e59760ceee37359688871bb0688fcc4e98f/internal/protocol/params.go#L9) + UDP header (8 bytes) + IP (20 bytes) + Ethernet (14 bytes) = 1294 bytes

**Comment by marten-seemann** [comment]
I assume this problem has been solved. Feel free to reopen if not.
