### ISSUE TITLE
Will streams block each other？

### ISSUE THREAD

**Issue by YUJIANHAO17** [lucas-clemente/quic-go#3294]
If I open two streams on the server, stream 1 and stream 2. Stream 1 circularly sends 1400 byte packets in goroutine1, and stream 2 circularly receives feedback from the client in goroutine2. When Stream2 waits for reception in gorountine2, will Stream1 in gorountine1 block? Or can I use two streams to send and receive simultaneously without affecting the throughput (under ideal link conditions)?

**Comment by marten-seemann** [comment]
Streams are independent of each other. Note though that there’s connection level flow control, so if there are many inactive streams, other streams might still block on that. For details please refer to the RFC.
