### ISSUE TITLE
How should I remove the retransmission module?

### ISSUE THREAD

**Issue by YUJIANHAO17** [lucas-clemente/quic-go#3296]
Hi
I want to remove the retransmission module, but after I annotate the queueretransmission (in send_stream. go), the client is blocked after a period of time. Why? Or how should I remove the retransmission module？

**Comment by marten-seemann** [comment]
> How should I remove the retransmission module?

You shouldn't 🤷‍♂️.
Retransmitting lost packets is required by RFC 9000.

**Comment by YUJIANHAO17** [comment]
Can the retransmission module be removed without considering reliability？

**Comment by marten-seemann** [comment]
A lot of things _can_ be done. I just don't understand how it makes sense.
