### ISSUE TITLE
tls: client requested unsupported application protocols ([hq-interop hq-29 hq-28 hq-27 http/0.9])

### ISSUE THREAD

**Issue by ketingNIS** [lucas-clemente/quic-go#3299]
quic client set version  hq-interop hq-29 hq-28 hq-27 http/0.9

**Comment by marten-seemann** [comment]
I don’t see any bug here.

**Comment by ketingNIS** [comment]
why not support hq-interop hq-29 hq-28 hq-27 http/0.9?
