### ISSUE TITLE
NullAuthError with old connections on new server

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#33]

**Comment by marten-seemann** [comment]
Not fixed.

**Comment by marten-seemann** [comment]
This output might be helpful.

    Serving new connection: 15554793836100592793 from 14.177.64.146:65443
    <- Reading packet 1 (1350 bytes) for connection 15554793836100592793
        <- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0}
    -> Sending packet 1 (44 bytes)
	    -> &frames.AckFrame{LargestObserved:0x1, Entropy:0x2, DelayTime:0, NackRanges:[]frames.NackRange(nil)}
    -> Sending packet 2 (1444 bytes)
	    -> &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0}
    -> Sending packet 3 (78 bytes)
	    -> &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 1409}
    <- Reading packet 2 (1350 bytes) for connection 15554793836100592793
	    <- &frames.AckFrame{LargestObserved:0x2, Entropy:0x0, DelayTime:1352000, NackRanges:[]frames.NackRange(nil)}
	    <- &frames.StopWaitingFrame{Entropy:0x2, LeastUnacked:0x2}
	    <- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 1024}
    <- Reading packet 3 (294 bytes) for connection 15554793836100592793
    Closing session with error: NullAEAD: failed to authenticate received data
    Sending public reset for connection 15554793836100592793, packet number 3

**Comment by marten-seemann** [comment]
And this probably even more helpful:

    Serving new connection: 3143566288782545330 from 42.115.215.194:35848
    <- Reading packet 1 (1350 bytes) for connection 3143566288782545330
      <- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0}
    -> Sending packet 1 (44 bytes)
      -> &frames.AckFrame{LargestObserved:0x1, Entropy:0x0, DelayTime:0, NackRanges:[]frames.NackRange(nil)}
    -> Sending packet 2 (1444 bytes)
      -> &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0}
    -> Sending packet 3 (78 bytes)
      -> &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 1409}
    <- Reading packet 2 (1350 bytes) for connection 3143566288782545330
      <- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0}
    -> Sending packet 4 (44 bytes)
      -> &frames.AckFrame{LargestObserved:0x2, Entropy:0x4, DelayTime:0, NackRanges:[]frames.NackRange(nil)}
    <- Reading packet 3 (43 bytes) for connection 3143566288782545330
      <- &frames.AckFrame{LargestObserved:0x3, Entropy:0x2, DelayTime:591000, NackRanges:[]frames.NackRange(nil)}
      Estimated RTT: 346ms
      <- &frames.StopWaitingFrame{Entropy:0x0, LeastUnacked:0x2}
    -> Sending packet 5 (44 bytes)
      -> &frames.AckFrame{LargestObserved:0x3, Entropy:0x4, DelayTime:0, NackRanges:[]frames.NackRange(nil)}
    <- Reading packet 4 (1350 bytes) for connection 3143566288782545330
      <- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 1300}
    <- Reading packet 5 (271 bytes) for connection 3143566288782545330
    Closing session with error: NullAEAD: failed to authenticate received data

**Comment by marten-seemann** [comment]
Error still occurs.
[output.txt](https://github.com/lucas-clemente/quic-go/files/245049/output.txt)
