### ISSUE TITLE
Implement a Flush() method on the response writer

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#330]
Motivated by [this issue on Caddy](https://github.com/mholt/caddy/issues/1083), it would be useful if the quic-go responseWriter had a [Flush()](https://golang.org/pkg/net/http/#Flusher) method. I'm not sure what that means semantically for a QUIC response (or if it's complicated), but even if the method is a no-op, it would make the response writer compatible with not only Caddy but pretty much any HTTP apps that is proxying or doing something fancy with the response body.

Thanks again for maintaining quic-go! And it was great to meet you and Marten this week at dotGo! :+1:

**Comment by lucas-clemente** [comment]
I've added `Flush` as a NOP for now. I don't really see any meaning that it has in our context (we don't currently buffer writes to the stream anyway), but we might change that later.

Just as a nitpick, the spec says "Handlers should always test for this ability at runtime." 😜 Was really cool meeting you too! :)

**Comment by mholt** [comment]
That was fast! You really get things done.

> Just as a nitpick, the spec says "Handlers should always test for this ability at runtime." 😜

We do test for it, but the question is what to do when it doesn't have the ability. Sometimes proxies or whatever just need to flush the response :P

Thank you! :star:
