### ISSUE TITLE
Accept failed: read udp [::]:25000: recvmsg: software caused connection abort

### ISSUE THREAD

**Issue by hjlp20150803** [lucas-clemente/quic-go#3304]
It report "Accept failed: read udp [::]:25000: recvmsg: software caused connection abort", and the source code like this:
sess, err := listener.Accept(context.Background())
if err != nil {
        fmt.Println(logger.INFO, "Accept failed:", err)
        continue
}

**Comment by marten-seemann** [comment]
Without any more details there's nothing we can do here. There was an error reading from the socket, and we stopped listening.

**Comment by hjlp20150803** [comment]
my code is too complicated, not easy too describe.It maybe caused by continuing flooding dial
