### ISSUE TITLE
"go get -t -u ./..." doesn't work well 

### ISSUE THREAD

**Issue by elhachi** [lucas-clemente/quic-go#3305]
Hello everyone, I have an issue when running the "go get -t -u ./..." command to download dependency packages for mpquic.
I flowed this tutorial " https://multipath-quic.org/2017/12/09/artifacts-available.html", using go1.17.5 instead of go1.9, and I got the following error:

github.com/lucas-clemente/quic-go/internal/crypto
internal/crypto/key_derivation.go:47:60: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
internal/crypto/key_derivation.go:48:58: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)

I tried to reset the mint repo, as it is mentioned in the tutorial, but it didn't solve the problem.

**Comment by marten-seemann** [comment]
This is not a quic-go issue. Please refer to the multipath QUIC implementation.
