### ISSUE TITLE
Question about lowestNotConfirmedAcked

### ISSUE THREAD

**Issue by crazypaul123** [lucas-clemente/quic-go#3307]
https://github.com/lucas-clemente/quic-go/blob/1f3350557e2a195d22619091a5d001b371bf068f/internal/ackhandler/sent_packet_handler.go#L409

Hi,
      I'm learning quic.I don't understand how to calculate sentPacketHandler.lowestNotConfirmedAcked. For example, if receive ack ranges [7,9],[2,5],  we miss ack 6. It seems we shouldn't make the lowestNotConfirmedAcked to be 10  in that case.

**Comment by marten-seemann** [comment]
It's explained in the same file: https://github.com/lucas-clemente/quic-go/blob/1f3350557e2a195d22619091a5d001b371bf068f/internal/ackhandler/sent_packet_handler.go#L70-L74

**Comment by crazypaul123** [comment]
I have read the notes  but I can't understand.  For example, we receive packets [80-88],[90-100], then we send ack for packets [80-88],[90-100] with packet number 20, once we receive an ACK from the peer for packet 20, the lowestNotConfirmedAcked is 101.  Is it correct? I think it is 89 now.

**Comment by crazypaul123** [comment]
> 

I have read the notes but I can't understand. For example, we receive packets [80-88],[90-100], then we send ack for packets [80-88],[90-100] with packet number 20, once we receive an ACK from the peer for packet 20, the lowestNotConfirmedAcked is 101. Is it correct? I think it is 89 now.

**Comment by marten-seemann** [comment]
This is implementing the logic described in https://datatracker.ietf.org/doc/html/rfc9000#section-13.2.4. Does this make sense to you, and do you agree that the implementation is correct?
I'd be happy for a suggestion for a better name (and / or adding a reference to that section of the RFC), if you want to open a PR.

**Comment by crazypaul123** [comment]
> This is implementing the logic described in https://datatracker.ietf.org/doc/html/rfc9000#section-13.2.4. Does this make sense to you, and do you agree that the implementation is correct? I'd be happy for a suggestion for a better name (and / or adding a reference to that section of the RFC), if you want to open a PR.

Many thanks for your kind reply. I have no doubt on the validity of rfc-9000 , but just haven’t catches on it completely. So I gave out an example based on personal understanding so far, which is may not correct. Appreciate your kind help to explain this question. I also would like to say sorry if my previous expression caused some misunderstanding. I have read the rfc-9000, and the Largest Acknowledged representing the largest packet number. Like the example that I said , we receive packets [80-88],[90-100] , the Largest Acknowledged is 100. then we send ack for packets [80-88],[90-100] with packet number 20, once we receive an ACK from the peer for packet 20, the lowestNotConfirmedAcked is 101. So we miss packet 89. Could you help me to explain that?

**Comment by marten-seemann** [comment]
`lowestNotConfirmedAcked` is _not_ determining which packets are retransmitted. Take a look at how this variable is used in `GetLowestPacketNotConfirmedAcked`.

**Comment by crazypaul123** [comment]
Thank you very much
