### ISSUE TITLE
go get an old version of the quic-go 

### ISSUE THREAD

**Issue by elhachi** [lucas-clemente/quic-go#3308]
Hello everyone,

I'm new to golang, and I want to use an old release (tag) of the Quic-go in my project, I tried the "go get" command as follow:

    go get github.com/lucas-clemente/quic-go/releases/tag/v0.X.X
    go get: module github.com/lucas-clemente/quic-go@upgrade found (v0.24.0), but does not contain package github.com/lucas-clemente/quic-go/releases/tag/v0.6.0

Please could you tell me what is the right way to get this tag and use it?

**Comment by ArthurCChen** [comment]
I've succeeded in getting old release by executing:
`go mod edit -replace github.com/lucas-clemente/quic-go=github.com/lucas-clemente/quic-go@v0.24.0`
the`0.24.0` could be defined as whatever you want as long as it exists.

But I tried all the versions of releases, still, there are some packages not found. I'm curious about your result! :)

Looking forward to your reply!
Happy new year!!

**Comment by marten-seemann** [comment]
Please refer to Go tutorials on the internet. This has **nothing** to do with quic-go.
