### ISSUE TITLE
Add cloudflared to 'Projects using quic-go' in the README

### ISSUE THREAD

**Issue by user8446** [lucas-clemente/quic-go#3311]
Not a bug but Cloudflare's [cloudflared](https://github.com/cloudflare/cloudflared) is using quic-go. You might want to add it to [Projects using quic-go](https://github.com/lucas-clemente/quic-go#projects-using-quic-go)

**Comment by marten-seemann** [comment]
Great. Can you open a PR?

**Comment by user8446** [comment]
https://github.com/lucas-clemente/quic-go/pull/3315/commits

**Comment by Akaame** [comment]
Hello,

The PR is already merged. @user8446 I think you have forgotten to close this issue.

Cheers for your contribution 🚀

**Comment by user8446** [comment]
Hi, thanks for the reminder
