### ISSUE TITLE
CRYPTO_ERROR: 0X178 ALPN negotiation failed. Server didn't offer any protocol

### ISSUE THREAD

**Issue by elhachi** [lucas-clemente/quic-go#3318]
Hello,
Please could you help me solve this error, I got it when I was trying to create a (server/client) network.
**error: CRYPTO_ERROR: 0X178 ALPN negotiation failed. Server didn't offer any protocol**
**server.go:**
      const addr = "0.0.0.0:" + PORT
      listener, err := quic.ListenAddr(addr, utils.GenerateTLSConfig(), nil)
      utils.HandleError(err)
      sess, err := listener.Accept(context.Background())
      utils.HandleError(err)
      stream, err := sess.AcceptStream(context.Background())
      utils.HandleError(err)
**client.go:**
      const addr = "10.1.1.10:"+PORT
      session, err := quic.DialAddr(addr, &tls.Config{InsecureSkipVerify: true}, nil)
      utils.HandleError(err)
      stream, err := session.OpenStream()
      utils.HandleError(err)
go version: 1.17
OS: linux (debian10)
Thank you for your help.

**Comment by marten-seemann** [comment]
You need to set an application protocol, in `tls.Config.NextProtos`.
