### ISSUE TITLE
sendStream.Write is NOT thread safe

### ISSUE THREAD

**Issue by wujunzhuo** [lucas-clemente/quic-go#3321]
version: 496fbe9fda4bb094b1cbdb162a52130b6beda6b1

file: send_stream.go

`s.mutex` is unlocked in the function (line 157), so `s.dataForWriting` might be assigned by other routines.

**Comment by Akaame** [comment]
https://github.com/lucas-clemente/quic-go/blob/master/stream.go#L74

This line states that multiple accesses to streams should be manually mutexed. I think the responsibility of managing multiple writers are delegated to the consumer of the code.

**Comment by marten-seemann** [comment]
Indeed, it doesn’t make sense to call in.Writer concurrently. Which one of the calls would you expect to be written first? If you do it concurrently, the ordering is undefined.
