### ISSUE TITLE
Churning through Streams over the same Session leaks memory

### ISSUE THREAD

**Issue by nmldiegues** [lucas-clemente/quic-go#3322]
Adapted an example from the repository to reproduce this easily:
```go
package main

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"io"
	"log"
	"math/big"
	"net/http"
	_ "net/http/pprof"

	quic "github.com/lucas-clemente/quic-go"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const addr = "localhost:4242"

const message = "foobar"

func main() {
	go func() {
		log.Println(http.ListenAndServe(":6060", nil))
	}()

	go func() {
		http.Handle("/metrics", promhttp.Handler())
		log.Println(http.ListenAndServe(":6061", nil))
	}()


	go func() { log.Fatal(echoServer()) }()

	err := clientMain()
	if err != nil {
		panic(err)
	}
}

// Start a server that echos all data on the first stream opened by the client
func echoServer() error {
	listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
	if err != nil {
		return fmt.Errorf("failed to listenAddr due to %v", err)
	}
	sess, err := listener.Accept(context.Background())
	if err != nil {
		return fmt.Errorf("failed to accept listener due to %v", err)
	}

	for {
		stream, err := sess.AcceptStream(context.Background())
		if err != nil {
			return fmt.Errorf("failed to accept stream due to %v", err)
		}

		_, err = io.Copy(loggingWriter{stream}, stream)
		if err != nil {
			return fmt.Errorf("failed to write response due to %v", err)
		}

		_ = stream.Close()
	}
}

func clientMain() error {
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"quic-echo-example"},
	}
	session, err := quic.DialAddr(addr, tlsConf, nil)
	if err != nil {
		return err
	}

	idx := 0
	for {
		stream, err := session.OpenStreamSync(context.Background())
		if err != nil {
			return fmt.Errorf("failed to open stream due to %v", err)
		}

		_, err = stream.Write([]byte(message))
		if err != nil {
			return fmt.Errorf("failed to write request due to %v", err)
		}

		buf := make([]byte, len(message))
		_, err = io.ReadFull(stream, buf)
		if err != nil {
			return fmt.Errorf("failed to read response due to %v", err)
		}

		idx = idx + 1
		if idx % 1000 == 0 {
			fmt.Printf("Request %d\n", idx)
		}

		// <--------------------------------------------------------------------------------->
		// If you uncomment the following line, memory is quite constant over time (and low).
		// <--------------------------------------------------------------------------------->
		// stream.CancelRead(0)
		// <--------------------------------------------------------------------------------->
		// If you uncomment the line above, memory is quite constant over time (and low).
		// <--------------------------------------------------------------------------------->

		if err := stream.Close(); err != nil {
			return fmt.Errorf("failed to close client stream due to %v", err)
		}
	}
}

// A wrapper for io.Writer that also logs the message.
type loggingWriter struct{ io.Writer }

func (w loggingWriter) Write(b []byte) (int, error) {
	return w.Writer.Write(b)
}

// Setup a bare-bones TLS config for the server
func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{
		Certificates: []tls.Certificate{tlsCert},
		NextProtos:   []string{"quic-echo-example"},
	}
}
```

By running this, you will observe memory growing quite fast.
You can monitor it with:
```
watch "curl -s 127.0.0.1:6061/metrics | grep mem | grep alloc | grep -v '#' | grep -v total"
```
And you can then collect a heap profile with:
```
go tool pprof http://localhost:6061/debug/pprof/heap
```

That will show the cause (collected once I had 1M streams churned, took just a couple mins or less):
![image](https://user-images.githubusercontent.com/889015/151393614-50a372a0-ccbc-46ea-b3fb-4211f462c0cc.png)

The root cause seems to be that `stream#receiveStreamCompleted` is never `true`, and so the `Session` piles up `Stream`s forever that the GC cannot collect: https://github.com/lucas-clemente/quic-go/blob/master/stream.go#L81

I can force that to happen with `stream.CancelRead(0)`, which if you uncomment (in the example above), it makes memory stable (and low).

Is there any way in which this behaviour is intended, or is this an actual bug?

**Comment by Akaame** [comment]
I think I might be reading the code wrong but `receiveStream.Close` is not implemented as receive stream itself is not embedded with `io.Closer` (unlike sendStream) so the only way to close an incoming stream gracefully is `CancelRead(0)`. From what I have read, 

```
if err := stream.Close(); err != nil {
	return fmt.Errorf("failed to close client stream due to %v", err)
}
```

this portion is dead code as far as reader/receiver portion of the connection is concerned. I would expect `SendStream` to be `WriteCloser` and `ReceiveStream` to be `ReadCloser`, WDYT?

**Comment by marten-seemann** [comment]
`Close` only closes the write side of the stream.

@nmldiegues's code has a race condition, in the sense that the `ReadFull` call might or might not read the `io.EOF`. If the FIN bit was bundled with the last STREAM frame, the EOF will be read, otherwise there's a chance it might not. The correct function to use here would be `io.ReadAll`, which would read from the stream until the EOF occurs.

That said, there's still a bug here. The code sample here _should_ just leave these streams open, which would at some point block the creation of new streams. Instead, it looks like streams are still opened, which leads to the memory leak.

**Comment by marten-seemann** [comment]
Actually, this is not a quic-go bug. I added some logging:
```
2022/01/28 10:09:34 Client num outgoing streams: 620756
2022/01/28 10:09:34 Client num incoming streams: 0
2022/01/28 10:09:35 Server num incoming streams: 2
2022/01/28 10:09:35 Server num outgoing streams: 0
```
The server is handling the streams correctly. It's the client that's keeping the streams open, due to the incorrect usage of `io.ReadFull` instead of `io.ReadAll`. It's basically the client DoSing itself ;)

**Comment by nmldiegues** [comment]
Thanks for the insights @marten-seemann 

Now that we're looking into this more in depth, we see that cleaning up the Streams requires more care than we thought. There seems to be a way to do it that works --- for e.g., the dummy example above can be solved as you suggest, I've confirmed it;  for our real scenario, we have a few more challenges, but I think we can nail them.

Looking back, we may have been overly optimistic in assuming that `Stream#Close` would close all associated resources.
I still think that is a fair assumption, and at the very best this warrants a docstring in `Stream` to warn about how to clean it up properly?
