### ISSUE TITLE
transfer files using quic protocol 

### ISSUE THREAD

**Issue by elhachi** [lucas-clemente/quic-go#3331]
Hello, 
I am trying to transfer files of different sizes (250Ko-9Mo) from a server to a client using QUIC protocol in mininet environment (client-router-server), so I opened a connection between them based on the echo example, and I used Write and ReadAll methods to send and receive data  as follow:
sender side: stream.Write(data) 
received side: data,err:=ioutil.ReadAll(stream)
 ioutil.WriteFile(my_file,data,0644)
The problem is sometimes the transfer success with small sizes and sometimes doesn't, and an error appeared:
NetworkIdleTimeout: No recent network activity
Could you please help me solve the problem?

**Comment by marten-seemann** [comment]
It's an idle timeout. See the RFC for the explanation. Most certainly this is not a quic-go problem.

**Comment by David-cyber123** [comment]
> 
I have encountered the same problem. Have you solved this problem yet? I hope you can share some solutions
