### ISSUE TITLE
failed to determine receive buffer size, for closed connections

### ISSUE THREAD

**Issue by brotaxt** [lucas-clemente/quic-go#3341]
UDP receive buffer size is set accordingly, but couldn't be recognized. 

I always get the mentioned error message after starting my Go application.

```
2022/03/07 09:05:32 failed to determine receive buffer size: raw-control udp [::]:60791: use of closed network connection. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

root@localhost:~# sysctl net.core.rmem_max
net.core.rmem_max = 2500000

OS-Version:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch

```

**Comment by brotaxt** [comment]
The warning message seems to be gone after raising `net.ipv4.udp_mem `

**Comment by marten-seemann** [comment]
> I always get the mentioned error

What do you mean by “always”? Does this happen on every connection, or just from time to time?

**Comment by brotaxt** [comment]
Oh sorry, I mean after starting my Go application (routedns). The message does only appear once.
 
After raising `net.ipv4.udp_mem` the message appears ~10 minutes after starting the routedns application.

**Comment by marten-seemann** [comment]
It would probably make sense to not print "use of closed network connection" errors. Want to send us a PR?

**Comment by brotaxt** [comment]
So you mean that error message is a false positive? Iam also seeing this variant since a few days: 
`failed to increase receive buffer size: set udp [::]:51914: use of closed network connection.`

I would be glad to help, but unfortunately I've no knowledge of go programming :(
