### ISSUE TITLE
http3.Server.SetQuicHeaders is slow

### ISSUE THREAD

**Issue by renbou** [lucas-clemente/quic-go#3350]
Web servers which want to serve http1/http2 and http3 using quic-go will need to use `http3.Server.SetQuicHeaders` in order for clients to discover http3 support. This pretty much means that `SetQuicHeaders` needs to be used on every request, and as such should be pretty fast. And it would be, however on each call it generates the headers again, even though there's no case where they might change in between the requests:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/30644072/159241186-fbbaad67-d093-4792-949b-164145096b23.png">

Is my understanding of this correct? I may be wrong about the fact that this header never changes, but currently I don't know why it would. I think it can be created during the `Serve*` methods, since it's pretty safe to assume that http3 will be used alongside http1/http2 and it would add increase the startup time by only a fraction.

**Comment by marten-seemann** [comment]
`http3.Port`, `http3.Server.Addr` shouldn't change once the listener has been started, and neither should the QUIC versions used.

What about using a `sync.Once` in `SetQuicHeaders` to generate the string the first time that function is called?

**Comment by renbou** [comment]
Makes sense as well, but is there a reason not to generate it during `serveImpl`, for example? Using `sync.Once` just seems like we'd still be leaving unneeded atomic operations there

**Comment by marten-seemann** [comment]
I would've argued that it's slightly cleaner to do it in `SetQuicHeaders`. The atomic operation should be free compared to the map insert that `http.Header.Add` performs. 
Or isn't it? I haven't benchmarked it.

**Comment by renbou** [comment]
Yeah, seems true
BenchmarkSetHeaderPrepared-8   	19700780	        58.53 ns/op
BenchmarkSetHeaderSyncOnce-8   	19443706	        60.93 ns/op

```go
type Server1 struct {
	quicHeader string
}

func (s *Server1) SetQuicHeaders(hdr http.Header) {
	hdr["Alt-Svc"] = append(hdr["Alt-Svc"], s.quicHeader)
}

type Server2 struct {
	onceHeader sync.Once
	quicHeader string
}

func (s *Server2) generateQuicHeaders() {
	s.quicHeader = `h3=":443"; ma=2592000`
}

func (s *Server2) SetQuicHeaders(hdr http.Header) {
	// allow inlining
	s.onceHeader.Do(s.generateQuicHeaders)
	hdr["Alt-Svc"] = append(hdr["Alt-Svc"], s.quicHeader)
}

func BenchmarkSetHeaderPrepared(b *testing.B) {
	s1 := Server1{
		quicHeader: `h3=":443"; ma=2592000`,
	}
	for i := 0; i < b.N; i++ {
		hdr := make(http.Header)
		s1.SetQuicHeaders(hdr)
	}
}

func BenchmarkSetHeaderSyncOnce(b *testing.B) {
	s2 := Server2{}
	for i := 0; i < b.N; i++ {
		hdr := make(http.Header)
		s2.SetQuicHeaders(hdr)
	}
}
```

**Comment by renbou** [comment]
> I would've argued that it's slightly cleaner to do it in `SetQuicHeaders`. The atomic operation should be free compared to the map insert that `http.Header.Add` performs. Or isn't it? I haven't benchmarked it.

Speaking of cleaner - it means that we need to add one more `sync.Once` field to the struct, even though we have `loggerOnce` which also does global initialization. I don't mind which way we it's done though, so if it's better to do it during `SetQuicHeaders` then sure. Tell me what you think and I'll make a PR @marten-seemann

**Comment by renbou** [comment]
Actually, I think something different needs to be done here. Since `http3.Server` can serve multiple listeners, we should advertise all of them in `Alt-Svc` for them to actually be used by clients. This means we should add the listener address to a map of some sort during `addListener` and update the generated header accordingly. An RWMutex could be used, it shouldn't impact the performance too much

**Comment by renbou** [comment]
I've run a benchmark and doing
```go
s.mutex.RLock()
hdr["Alt-Svc"] = append(hdr["Alt-Svc"], s.quicHeader)
s.mutex.RUnlock()
```
Doesn't impact the performance. I think we should just add a `Server.generateQuicHeaders()` which would use the `Server.listeners` map to add all of the necessary entries and save the string to some field which will be used by `SetQuicHeaders`. And if a user has set a different `Server.Port`, then we could just use that instead of generating them.

**Comment by francislavoie** [comment]
FWIW, as an aside, Caddy doesn't currently support changing `http3.Server.Port` but it probably should. We've had someone ask for that on the forums at some point, if you'd like to take a peek at that while you're at it @renbou

**Comment by renbou** [comment]
> FWIW, as an aside, Caddy doesn't currently support changing `http3.Server.Port` but it probably should. We've had someone ask for that on the forums at some point, if you'd like to take a peek at that while you're at it @renbou

Found the post you're talking about, I'll check out how to implement this sometime this week hopefully - definitely seems like it might be a common thing

**Comment by renbou** [comment]
@marten-seemann I've made a PR to resolve this - https://github.com/lucas-clemente/quic-go/pull/3352
