### ISSUE TITLE
how to get connid from server endpoint

### ISSUE THREAD

**Issue by fengyeall111** [lucas-clemente/quic-go#3365]
assume this case:
many client,one server.when they communicate  using quic-go without http3，server return result asynchronously 。we must impl
map like map[connId]result so we can dispatch results to client corrctly 。Is there some api to get connId on server side??????

**Comment by MonkeyBrothers** [comment]
Is there any way to solve the above problems？

**Comment by MonkeyBrothers** [comment]
@fengyeall111 @marten-seemann 
Is there any way to solve the above problems？
