### ISSUE TITLE
[Question] How can I get error when no ACK received?

### ISSUE THREAD

**Issue by StephanoGeorge** [lucas-clemente/quic-go#3366]
Here is my test code:

```go
func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	client(ctx)
	time.Sleep(time.Minute)
	fmt.Println("main finished")
}

func client(ctx context.Context) {
	tlsConfig := &tls.Config{
		NextProtos:         []string{"h3-29"},
	}
	session, err := quic.DialAddr("interop.seemann.io:443", tlsConfig, nil)
	checkErr(err)
	stream, err := session.OpenStreamSync(ctx)
	checkErr(err)
	fmt.Println("Client: Sending")
	time.Sleep(time.Second * 5)
	_, err = stream.Write([]byte("GET /"))
	checkErr(err)
	fmt.Println("client finished")
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

I turned off the network when I saw 'Client: Sending', and this is the output:

```
Client: Sending
client finished
main finished
```

How can I get error when no ACK received?

Or can I block in `Write()` until ACK received?

**Comment by marten-seemann** [comment]
> How can I get error when no ACK received?

QUIC streams are reliable, so when no ACK is received, QUIC will retransmit the data.

> Or can I block in Write() until ACK received?

No, there's no API for that. It would make any data transfer incredibly slow.

**Comment by StephanoGeorge** [comment]
I want to build an instant messaging APP, only when ACK is received, the message sent prompt can be displayed, so I want to have a function like `stream.WriteSync()` which block until the corresponding ACK arrives.

> It would make any data transfer incredibly slow

I can call each `WriteSync()` in a separate Goroutine.

**Comment by marten-seemann** [comment]
> I want to build an instant messaging APP, only when ACK is received, the message sent prompt can be displayed, so I want to have a function like stream.WriteSync() which block until the corresponding ACK arrives.

This seems to be an application-layer function, and would probably be better handled by an acknowledgement on the application layer.

> I can call each WriteSync() in a separate Goroutine.

That's racy. You can't have multipe `Write` calls at the same time. How would you determine ordering of the data?
