### ISSUE TITLE
Error: too many open streams

### ISSUE THREAD

**Issue by amulepeweichan** [lucas-clemente/quic-go#3371]
I'm working on a program where a client accepts streams from a server, basically in a loop like:
```
for {
        stream, err := session.AcceptStream(context.Background())
        if err != nil {
                return err
        }
        go func() {
                handleStream(stream)
                stream.Close()
        }
}
```
The client has the max concurrent stream count set to the default of 100, and after a few hundred streams opened and closed, it can't open anymore, getting the error: "too many open streams"
I added `io.Copy(ioutil.Discard, stream)` after `stream.Close()` and that solved the error. It seems like a bug that streams even after calling Close() count against your max concurrent stream count limit unless you explicitly read everything remaining from them after closing?

**Comment by marten-seemann** [comment]
`Close` only closes the write side of the stream. You need to either cancel the read side, or read the io.EOF.

**Comment by fbzhong** [comment]
@marten-seemann Could we document this behavior within the comments of the `Stream.Close()` function? This approach ultimately aided me in resolving the issue of having 'too many open streams'.
