### ISSUE TITLE
quic-go how to close retry and ecn??

### ISSUE THREAD

**Issue by yangqingyuan** [lucas-clemente/quic-go#3375]
Hi ,quic-go how to close retry and ecn ? i want to use xquic to be client. quic-go to be service ,but xquic do not support retry and ecn, so want to close retry and ecn for test

**Comment by yangqingyuan** [comment]
@ydnar @arashpayan @dunglas @ltucker

**Comment by marten-seemann** [comment]
If xquic doesn't support Retries, it is not spec compliant. You should file an issue with xquic to comply with the RFC.

That being said, the `AcceptToken` config option is probably what you're looking for.
