### ISSUE TITLE
INTERNAL_ERROR: tried to delete unknown outgoing stream

### ISSUE THREAD

**Issue by amulepeweichan** [lucas-clemente/quic-go#3376]
I have a program where a server repeatedly opens streams to a client. Sometimes if the server closes the stream almost immediately after starting it, the client gets that error. For the client, Close() returns fine without error. That error is returned by the next call the client makes to AcceptStream(), and it's of type qerr.TransportError which is package internal so I'm not sure how to gracefully handle it.

**Comment by marten-seemann** [comment]
That sounds like a quic-go bug. Which quic-go version are you using?

**Comment by amulepeweichan** [comment]
I was using v0.26 but upgraded to v0.27 and got the same error. But it's maybe just me not understanding properly quic or this library. I figured more exactly what is triggering it. It started after I added io.Copy(ioutil.Discard, stream) after my calls to stream.Close to not get error about too many open streams (https://github.com/lucas-clemente/quic-go/issues/3371). But when the side calling OpenStream does that discard after close, the side that called AcceptStream sometimes gets this internal error on it's next call to AcceptStream. When only the side that called AcceptStream does the discard, everything works with no errors, neither too many streams nor this unknown outgoing stream error. However I'm a little worried that the side calling OpenStream if it doesn't read/discard the final EOF the stream stays around and memory usage will continually grow?

**Comment by amulepeweichan** [comment]
https://gist.github.com/amulepeweichan/7a66a6c9b2637f9bb64cc43dd3d656f6
Here's a basic modified version of the quic-go example, it has client listen on tcp and forward the tcp connection to a new quic stream. In one terminal run:
`while true; do echo test | nc -N localhost 4040; done`
In another run that go program. Sometimes it will get stuck blocking on a connection, never receiving the close of the stream from the server, like:
```
$ go run echo.go 
2022/04/14 18:03:02 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022/04/14 18:03:02 Done reading from client
got stream:
test

closing
2022/04/14 18:03:02 Done reading from quic
2022/04/14 18:03:02 Done reading from client
got stream:
test

closing
```
If you understand why it blocks sometimes I'd appreciate it cause I have no idea, but anyway if it blocks just ctrl-C and rerun the go program and on the first try or after some tries you'll see the error:
```
$ go run echo.go 
2022/04/14 18:03:05 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022/04/14 18:03:05 Done reading from client
got stream:
test

closing
2022/04/14 18:03:05 Done reading from quic
2022/04/14 18:03:05 Done reading from client
got stream:
test

closing
2022/04/14 18:03:05 Done reading from quic
2022/04/14 18:03:05 Done reading from client
got stream:
test

closing
2022/04/14 18:03:05 Done reading from quic
panic: INTERNAL_ERROR: tried to delete unknown outgoing stream 8

goroutine 19 [running]:
main.echoServer()
        /....../echo.go:50 +0x288
```

**Comment by amulepeweichan** [comment]
ah I think I understand why it sometimes blocks forever, the io.Copy(ioutil.Discard, stream) reads the EOF, so then io.Copy(client, stream) doesn't have EOF to read and blocks forever? It seems the internal error only occurs when the quic client has two io.Copy statements reading from the stream, but it causes an error in the other side, which would be an independent program, it's just both the client and server in one in the example

**Comment by marten-seemann** [comment]
This is indeed a problem with your code. You're effectively calling `Read` concurrently:
```
go func() {
		io.Copy(stream, client)
		log.Print("Done reading from client")
		stream.Close()
		io.Copy(ioutil.Discard, stream)
	}()
	io.Copy(client, stream)
```

**Comment by amulepeweichan** [comment]
I realize that now, but there is also a bug in quic-go? For the example to be simple it's all in one file, but you can split it into separate programs and see it's the client that does that buggy concurrent Read, but it's the server that gets quic internal error

**Comment by marten-seemann** [comment]
It's not. The client experiences the INTERNAL_ERROR and closes the connection.

**Comment by amulepeweichan** [comment]
I split it into separate client and server, removed the unneeded tcp relay and made the client never block so it reliably causes error: https://gist.github.com/amulepeweichan/fcde30b236b02b3a327565e15efd4050
Run the server and then the client, sometimes one or the other gets INTERNAL_ERROR but usually they both get it
