### ISSUE TITLE
Golangci-lint error: failed to load package qtls

### ISSUE THREAD

**Issue by darkweak** [lucas-clemente/quic-go#3377]
Hello, when I run golangci-lint on https://github.com/caddyserver/cache-handler I got the following error in the CI and even reproductible in local environment using the golangci-lint container
```bash
level=error msg="Running error: 1 error occurred:
    * can't run linter goanalysis_metalinter: buildir: failed to load package qtls: could not load export data: no export data for "github.com/lucas-clemente/quic-go/internal/qtls"
"
```

Do you have any clues to fix that?

**Comment by marten-seemann** [comment]
No idea what that is about.

**Comment by darkweak** [comment]
I solved that with a rollback to a previous golangci-lint version because they use go 1.18 in the latest and this version is not supported yet in quic-go. 🙂

**Comment by marten-seemann** [comment]
> they use go 1.18 in the latest and this version is not supported yet in quic-go

Glad you could solve the problem, but the current release of quic-go does support Go 1.18.

**Comment by darkweak** [comment]
It was the v0.23 which one doesn't support 1.18.
