### ISSUE TITLE
"DoS attack on HTTP/3"

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#3390]
Hey Marten, I got an email today titled "DoS attack on HTTP/3" -- can I forward it to you in case it is related to the HTTP/3 implementation? What is a good email address?

**Comment by marten-seemann** [comment]
Sure. martenseemann@gmail.com works.

**Comment by mholt** [comment]
Thanks! Email sent. It doesn't have much info in it yet, but I wanted to loop you in anyway. Cheers

**Comment by hiqsociety** [comment]
possible for this email to be opened for public? curious coz i do hear some vulnerabilities on quic

**Comment by mholt** [comment]
It's not a protocol vulnerability. We haven't even confirmed it exists in this library yet. So far we're still having trouble reproducing it at all.
