### ISSUE TITLE
Optional close a Sending Stream for http3.RoundTripper

### ISSUE THREAD

**Issue by hareku** [lucas-clemente/quic-go#3396]
According to https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-02.html#section-5, a WebTransport session is considered terminated when:

>the CONNECT stream is closed, either cleanly or abruptly, on either side

However, quic-go's http3 RoundTripper closes the stream immediately by FIN flag after the writing request is completed.

Any good ideas for not closing the stream?

**Comment by marten-seemann** [comment]
Good catch! This won't be easy. We'd have to somehow add a `closeRequestStream` `bool` to the `http.Request`, but we can't modify that struct for obvious reasons.

Maybe we need to attach a value to the context? Not very clean, but I can't think of any better solution.

**Comment by marten-seemann** [comment]
@hareku Do you have any suggestion how to best solve this?

**Comment by hareku** [comment]
@marten-seemann 
Actually it's fine.
We can control the stream using `io.Pipe` like this, so quic-go doesn't have to do anything.

```go
req := &http.Request{
	Method: http.MethodConnect,
	Proto:  "webtransport",
}
pr, pw := io.Pipe()
req.Body = pr
rsp, err := roundTripper.RoundTripOpt(req, http3.RoundTripOpt{})

pw.Close() // the stream is not closed until pw.Close().
```

**Comment by marten-seemann** [comment]
Nice hack. This means that we're spawning the Go routine in `requestWriter.WriteRequest` and have it block on the `Body.Read` indefinitely. That's probably fine as we're only doing this once per WebTransport session.

**Comment by marten-seemann** [comment]
Alternatively, we could introduce a new `http3.RoundTripOpt`.
