### ISSUE TITLE
setReceiveBuffer question

### ISSUE THREAD

**Issue by dchaofei** [lucas-clemente/quic-go#3403]
> https://github.com/lucas-clemente/quic-go/blob/0a08d62dea3397740f1e45e0dc0e50583291f2a0/packet_handler_map.go#L105-L107

Hi, I'm not sure if there's a bug here, so ask a question, and if it's a bug, I'll be happy to fix it.

If the system's receive buffer is large enough, can we return immediately?
```
	if size >= protocol.DesiredReceiveBufferSize {
		logger.Debugf("Conn has receive buffer of %d kiB (wanted: at least %d kiB)", size/1024, protocol.DesiredReceiveBufferSize/1024)
		return
	}
```

**Comment by marten-seemann** [comment]
Sounds reasonable. Want to send us a PR?

**Comment by dchaofei** [comment]
Ok, I will send the PR.
