### ISSUE TITLE
ComposeVersionNegotiation()  function will never return an error

### ISSUE THREAD

**Issue by dchaofei** [lucas-clemente/quic-go#3408]
ComposeVersionNegotiation()  function will never return an error, but the return value defines the error type.

Looking at the commit history, the function used to return an error, but now it doesn't, Is it possible to delete the error type from the return value.

> https://github.com/lucas-clemente/quic-go/blob/0a08d62dea3397740f1e45e0dc0e50583291f2a0/internal/wire/version_negotiation.go#L38-L54

**Comment by marten-seemann** [comment]
Sounds reasonable. Want to submit a PR?

**Comment by dchaofei** [comment]
Ok, I will submit a PR.
