### ISSUE TITLE
implement BBR congestion control

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#341]

**Comment by glen-dai** [comment]
When will be quic-go support BBR congestion control?

**Comment by marten-seemann** [comment]
It's still on our list, but we have a lot of higher-priority issues at the moment.

**Comment by LibinLiu0189** [comment]
is BBR implemented in any quic-go branch now? Thanks a lot.

**Comment by marten-seemann** [comment]
No, and we're currently not planning to implement it anytime soon.

**Comment by LibinLiu0189** [comment]
> No, and we're currently not planning to implement it anytime soon.

Got it. Thanks.

**Comment by jinleileiking** [comment]
I do not know why this thing is not on the top list. Bbr is so critical in quic cc

**Comment by netroby** [comment]
any news on add it to quic-go？

**Comment by marten-seemann** [comment]
There’s no need to regularly ping us on this issue. It will be updated once we start working on it.

**Comment by moranno** [comment]
It's been almost 3 years...

**Comment by bt90** [comment]
https://github.com/lucas-clemente/quic-go/issues/3417#issuecomment-1127961210 still stands

**Comment by marten-seemann** [comment]
Update on BBR: We're not planning to implement BBR in quic-go. Over the years, BBR has been shown to not be the silver bullet to solve all of our performance problems. BBR remains a highly complex algorithm with an enormous set of magic configuration values. It has also not seen the widespread adoption that one might have expected after BBR's initial introduction.

In the mean time, different congestion controller algorithms have been explored by the congestion control community, with promising results. quic-go might experiment with those at some point in the future. Until then, there are lots of improvements outside of congestion control that will have a significant performance impact, for example #3526, #2482, #3563.

**Comment by marten-seemann** [comment]
BBRv3 support is now tracked in #4565.
