### ISSUE TITLE
Implement TCP BBR, again....

### ISSUE THREAD

**Issue by mfoxworthy** [lucas-clemente/quic-go#3417]
I saw that BBR was an option 6 years ago in this branch: https://github.com/lucas-clemente/quic-go/commit/2d1d40d8a870733e4338dcc8ba2fcb56dd20224c

I'm not the greatest golang programmer, I could give it a go but how hard would it be to resurrect that code and bring it into the current branch?

**Comment by marten-seemann** [comment]
BBR support would need a *comprehensive* testing environment. This is at least 10x the amount of work than actually writing the code.

Duplicate of #341.
