### ISSUE TITLE
Add ListenConfig supporting in quic

### ISSUE THREAD

**Issue by xieyuschen** [lucas-clemente/quic-go#3425]
# Summary
For now, there is no way to control the process after creating the network connection but before binding it to the operating system as the [net/ListenConfig](https://pkg.go.dev/net#ListenConfig). 
Could apply this feature in quic.

**Comment by marten-seemann** [comment]
What are you trying to achieve?

**Comment by xieyuschen** [comment]
> What are you trying to achieve?

Keep same with the net.ListenConfig which also our users can do something after creating the network connection but before binding it to the operating system.

**Comment by marten-seemann** [comment]
I appreciate the sentiment to make things consistent, but what are you actually trying to achieve?

**Comment by xieyuschen** [comment]
> I appreciate the sentiment to make things consistent, but what are you actually trying to achieve?

Thanks for your question. I have found a real case: we can use this config to setsockopt to optimize. For example, we could use the bind REUSEPORT option which allows multiple cpu cores bind the same up:port. It can optimize a lot on the multiple processor.

Thanks

**Comment by marten-seemann** [comment]
You don't need `ListenConfig` for that. You can just pass your own `net.PacketConn` into listen, after you applied all socket options that you like.

**Comment by xieyuschen** [comment]
Get it, thanks

**Comment by xieyuschen** [comment]
So if the documents is messy now, how about the code? 
I think that it's better for user to run our example without any flags.

(I would like to enhance the documents also, is it acceptable once it's up to the level wish?)
