### ISSUE TITLE
How to close a stream in client.

### ISSUE THREAD

**Issue by lanpoo** [lucas-clemente/quic-go#3438]
I am using quic-go to transfer a lot of small files, such as _100kb - 500Kb_. But the question is that, when the server transfer is complete, the server actively calls the **removeStream** function to close those streams that have completed the transfer. And the client won't do that. How do I get the client to close those streams as well? Thanks for your answer. Best wishes!

**Comment by marten-seemann** [comment]
You need to call `Close()` on both sides.

**Comment by hankai17** [comment]
situation unidirectional?
If certainly know 100kb - 500Kb content-length. Once client receives all this data then client upper should call Close()
