### ISSUE TITLE
don't open a new stream for requests with no data

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#344]
When answering a request with 304 (for example), we only need to send the header, there's no need to send any data.
At the moment, we're still opening and new stream, which gets closed immediately, such that we send a single `StreamFrame` with a `FinBit` to the client. Because the client doesn't want this `StreamFrame`, it sends us a `RstStreamFrame`.

```
GET quic.clemente.io/, on data stream 9
Responding with 304
-> Sending packet 0x2b (35 bytes)
	-> &frames.AckFrame{LargestAcked:0x19, LowestAcked:0x18, AckRanges:[]frames.AckRange(nil), DelayTime:231259, PacketReceivedTime:time.Time{sec:63613679060, nsec:170492771, loc:(*time.Location)(0x5b54a0)}}
	-> &frames.StreamFrame{StreamID: 3, FinBit: false, Offset: 0x6c, Data length: 0xa, Offset + Data length: 0x76}
-> Sending packet 0x2c (17 bytes)
	-> &frames.StreamFrame{StreamID: 9, FinBit: true, Offset: 0x0, Data length: 0x0, Offset + Data length: 0x0}
<- Reading packet 0x1a (41 bytes) for connection 4656bc9e7209f68c
	<- &frames.AckFrame{LargestAcked:0x2c, LowestAcked:0xb, AckRanges:[]frames.AckRange(nil), DelayTime:7000, PacketReceivedTime:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}
	Estimated RTT: 0ms
	<- &frames.StopWaitingFrame{LeastUnacked:0x1a, PacketNumberLen:0x0, PacketNumber:0x0}
<- Reading packet 0x1b (39 bytes) for connection 4656bc9e7209f68c
	<- &frames.RstStreamFrame{StreamID:0x9, ErrorCode:0x6, ByteOffset:0x0}
Ignoring error in session: RST_STREAM received for unknown stream
```

This issue is not really critical, since we ignore the `RstStreamFrame` anyway, but we can avoid some unnecessary frames (on both sides).

**Comment by marten-seemann** [comment]
The interesting thing is, Chrome sends us a `RstStreamFrame` even if we omit the emty `StreamFrame`.
This seems to be triggered by the destructor of `BidirectionalStreamQuicImpl`, which then calls `ReliableQuicStream::Reset()`.

**Comment by lucas-clemente** [comment]
There's discussion about changing hpack on the quic list: https://www.ietf.org/mail-archive/web/quic/current/msg00541.html

Let's revisit this issue once that clears up.

**Comment by marten-seemann** [comment]
I'm seeing the same behavior from the GFE when accessing www.youtube.de, which redirects to www.youtube.com with a 301.

```
<- Reading packet 0x6 (398 bytes) for connection 68c228c31593db5c @ 19:53:20.220
	<- &frames.StreamFrame{StreamID: 3, FinBit: false, Offset: 0x0, Data length: 0x165, Offset + Data length: 0x165}
	<- &frames.StreamFrame{StreamID: 5, FinBit: true, Offset: 0x0, Data length: 0x0, Offset + Data length: 0x0}
```

Notices the `StreamFrame` on stream 5 has zero length and the `FinBit` set.
