### ISSUE TITLE
setsockopt fails to set IP_MTU_DISCOVER in SOCK_SEQPACKET

### ISSUE THREAD

**Issue by nmldiegues** [lucas-clemente/quic-go#3445]
**Problem:**
Set up a QUIC client that dials to a server via a Unix Sequenced Packet socket (SOCK_SEQPACKET)
That triggers this error: https://github.com/lucas-clemente/quic-go/blob/master/sys_conn_df_linux.go#L32
`setting DF failed for both IPv4 and IPv6`

**Reproduce:**
Run this command to set up a SOCK_SEQPACKET: `socat -v UNIX-LISTEN:/tmp/uds,socktype=5 -`

Then run this main:
```
package main

import (
	"crypto/tls"
	"net"

	"github.com/lucas-clemente/quic-go"
)

func main() {
	remoteAddr := &net.UnixAddr{
		Net:  "unixpacket",
		Name: "/tmp/uds",
	}
	conn, err := net.DialUnix("unixpacket", nil, remoteAddr)
	if err != nil {
		panic(err)
	}

	tlsClientConfig := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"h3"},
	}
	quicConfig := &quic.Config{}
	_, err = quic.DialEarly(conn, conn.LocalAddr(), "example.com", tlsClientConfig, quicConfig)
	if err != nil {
		panic(err)
	}
}
```

That will fail with the above mentioned error.

This used to work in v0.24 but stopped working ever since: https://github.com/lucas-clemente/quic-go/pull/3328/files#diff-446dcd03f343ca7249e090d11da194b71c2524d2c2ed49540c9e2085c1236291

Should we not fail hard in that case?

**Comment by marten-seemann** [comment]
Any idea why setting DF fails in this case? I'm not familiar with SEQPACKET.

**Comment by tobyxdd** [comment]
> Any idea why setting DF fails in this case? I'm not familiar with SEQPACKET.

Because it's a unix domain socket for local IPC. The concept of fragmentation doesn't apply here.

Perhaps we should check whether `conn` is a real network connection, or simply ignore the error?

**Comment by marten-seemann** [comment]
> Perhaps we should check whether conn is a real network connection

That sounds like a good solution. The connection returned by `DialUnix` returns a `net.UnixAddr` on `LocalAddr`. We could run the DF code iff `LocalAddr` returns a `net.UDPAddr`. 

Does that sound reasonable? Want to submit a patch, @nmldiegues?

**Comment by nmldiegues** [comment]
> Want to submit a patch, @nmldiegues?

Will do.
