### ISSUE TITLE
Why the http/3 protocol cannot be rendered using IP addresses

### ISSUE THREAD

**Issue by xutao123777** [lucas-clemente/quic-go#3450]
Why the http/3 protocol cannot be rendered using IP addresses

package main

import (
	"fmt"
	"net/http"

	"github.com/lucas-clemente/quic-go/http3"
)

func main() {

	handle := func(w http.ResponseWriter, req *http.Request) {
		_, _ = fmt.Fprintf(w, "hello world")
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/", handle)

	err := http3.ListenAndServe(":4431", "server.crt", "server.key", mux)
	// err := http3.ListenAndServeQUIC("0.0.0.0:4431", "server.crt", "server.key", mux) // 只开通基于udp的QUIC 协议
	fmt.Println(err)
}

https://127.0.0.1:4431/
https://localhost:4431/

HTTP/3 200 OK
alt-svc: h3=":4431"; ma=2592000,h3-29=":4431"; ma=2592000

These two methods can present http/3 protocol in Firefox browser

HTTP/1.1 200 OK
Alt-Svc: h3=":4431"; ma=2592000,h3-29=":4431"; ma=2592000
Date: Wed, 15 Jun 2022 07:32:57 GMT
Content-Length: 11
Content-Type: text/plain; charset=utf-8
https://192.168.2.53:4431/

Why the http/3 protocol cannot be rendered using IP addresses

**Comment by marten-seemann** [comment]
I'm sorry, I don’t understand the question  / problem.

**Comment by 2391003262** [comment]
> 
I guess he said when when use "https://127.0.0.1:4431/" the browser only use http1.1 protocol, only use "localhost" it can real use http3

**Comment by xutao123777** [comment]
> I guess he said when he use "https://127.0.0.1:4431/" the browser only use http1.1 protocol, only use "localhost" it can real use http3

127.0.0.1 and localhost can use http/3 protocol instead of https://192.168.2.53:4431/ Using httt /1

**Comment by 2391003262** [comment]
> > I guess he said when he use "https://127.0.0.1:4431/" the browser only use http1.1 protocol, only use "localhost" it can real use http3
> 
> 127.0.0.1 and localhost can use http/3 protocol instead of https://192.168.2.53:4431/ Using httt /1
yes,I tested , he was wrong.
but I just donot understand,why http3 must use TLS. some times I donot want to , for example, I want to use http3 for remote call   ,it does not need any security
