### ISSUE TITLE
Cannot establish connection without ALPN

### ISSUE THREAD

**Issue by leoluk** [lucas-clemente/quic-go#3453]
quic-go fails to connect to a server when ALPN is disabled and the server offers no protocols, even when `NextProtos` is empty:

> Failed to dial: CRYPTO_ERROR (0x178): ALPN negotiation failed. Server didn't offer any protocols

Example client: https://gist.github.com/leoluk/6233dd17a41402536d4bbd32d40899af

This is because we always set `EnforceNextProtoSelection` here regardless of `NextProtos`:

https://github.com/lucas-clemente/quic-go/blob/6fbc6d951a4005d7d9d086118e1572b9e8ff9851/internal/handshake/crypto_setup.go#L276

With `EnforceNextProtoSelection: false`, a connection is successfully established.

**Comment by marten-seemann** [comment]
Works as expected and as spec'ed: https://datatracker.ietf.org/doc/html/rfc9001#section-8.1.

**Comment by leoluk** [comment]
The spec allows not using ALPN:

> Unless another
   mechanism is used for agreeing on an application protocol, endpoints
   MUST use ALPN for this purpose.

**Comment by marten-seemann** [comment]
IF you have another mechanism for agreeing, which makes you vulnerable to cross-protocol attacks, unless you’re 100% sure that this mechanism works flawlessly.

**Comment by leoluk** [comment]
I understand the protocol confusion concern - so while it's technically allowed, it's not something the project is interested in supporting?

**Comment by marten-seemann** [comment]
There are a lot of "unless"es in the spec, and we don't plan to expose a knob for each and every one of them. If there's a reasonable use case, that would be an option though.
