### ISSUE TITLE
Allow adjusting DesiredReceiveBufferSize

### ISSUE THREAD

**Issue by leoluk** [lucas-clemente/quic-go#3455]
There doesn't seem to be a way of adjusting the desired buffer sizing for use cases where a large receive buffer isn't required:

> 2022/06/19 12:31:02 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

There's a `QUIC_GO_DISABLE_RECEIVE_BUFFER_WARNING` environment variable, but that is (a) an odd API (you need to change global process state, not per-connection) and (b) doesn't allow for tuning.

**Comment by marten-seemann** [comment]
I don't see any reason to change this. First of all, it's just a warning. Second, there's already the environment variable.
