### ISSUE TITLE
Are there reasons to use two select blocks in baseServer run method

### ISSUE THREAD

**Issue by xieyuschen** [lucas-clemente/quic-go#3458]
There are two select blocks in the [baseServer run method](https://github.com/lucas-clemente/quic-go/blob/706a482340141f8edb26fefae993e96b1581b034/server.go#L231), could I ask that are there some reasons such as reserve a position to implement a new feature?

Is it possible to merge those two select blocks as this?
```go
func (s *baseServer) run() {
	defer close(s.running)
	for {
		select {
		case <-s.errorChan:
			return
		case p := <-s.receivedPackets:
			if bufferStillInUse := s.handlePacketImpl(p); !bufferStillInUse {
				p.buffer.Release()
			}
                default:
		}
	}
}
```

Thanks.

**Comment by marten-seemann** [comment]
See https://github.com/lucas-clemente/quic-go/pull/3459#issuecomment-1162744204.
