### ISSUE TITLE
Should quic provide api to set MaxAcceptQueueSize value?

### ISSUE THREAD

**Issue by xieyuschen** [lucas-clemente/quic-go#3468]
Quic server currently uses a constant to limit connection number. Shell we provide an API to set it for users to adjust the value?
https://github.com/lucas-clemente/quic-go/blob/f29dd273b40d37b6ea8206350b2d96e8779161e5/server.go#L442

https://github.com/lucas-clemente/quic-go/blob/f29dd273b40d37b6ea8206350b2d96e8779161e5/internal/protocol/params.go#L60

Regards.

**Comment by marten-seemann** [comment]
I don't know, should we? I haven't come across a convincing use case yet.

**Comment by xieyuschen** [comment]
It was raised when I read the project code. In my opinion, if the machine which is running the quic server is powerful and the limitation we set won't touch the bottleneck of the server, it would like to handle more quic connections with a larger limitation. If there is no API to set it, it might disturb the performance of the quic server.

However, I haven't come across it either. 
But we can make stress testing to trial whether the `MaxAcceptQueueSize` will block the server when it runs on a powerful machine. Have we developed such testing code before, if there is, could you give a link to me?

**Comment by xieyuschen** [comment]
> I don't know, should we? I haven't come across a convincing use case yet.

It was raised when I read the project code. In my opinion, if the machine which is running the quic server is powerful and the limitation we set won't touch the bottleneck of the server, it would like to handle more quic connections with a larger limitation. If there is no API to set it, it might disturb the performance of the quic server.

However, I haven't come across it either. 
But we can make stress testing to trial whether the `MaxAcceptQueueSize` will block the server when it runs on a powerful machine. Have we developed such testing code before, if there is, could you give a link to me?

**Comment by marten-seemann** [comment]
This doesn't assume that we're running on a powerful machine. Keeping 32 QUIC connections in a queue until the application can accept them is nothing that would even a Raspberry Pi wouldn't be able to handle.

This is more an assumption about how quickly the Go scheduler allows the application to accept new streams, as compared to incoming connections being established. Really, this channel _should_ never fill up

**Comment by xieyuschen** [comment]
> This is more an assumption about how quickly the Go scheduler allows the application to accept new streams, as compared to incoming connections being established. Really, this channel should never fill up.

Make sence, if user doesn't only accept once the channel will never fill up. If we have assumed `the channel should never fill up`, could I get the reason why we use `s.connQueueLen` to limit connection? The only reason I could know is mentioned at the beginning.
