### ISSUE TITLE
Merge all closedLocalSession goroutines

### ISSUE THREAD

**Issue by Stebalien** [lucas-clemente/quic-go#3477]
Currently, we spawn a goroutine per "dead" session. When we get a cascade of closed connections, this can spawn a bunch of goroutines.

It would be _nice_ incoming packets to closed connections could all be handled by a single handler, given that they're all handled in the same way.

**Comment by marten-seemann** [comment]
That handler would need a map of CONNECTION_CLOSE packets for each of the closed connections, and it would kind of be a second packet handler map. It's certainly doable, and would reduce the number of Go routines from N to 1.

> When we get a cascade of closed connections, this can spawn a bunch of goroutines.

Have you seen this problem in production? Every QUIC connection uses one Go routine for its `run` loop, so we're actually just replacing one Go routine with another.

**Comment by Stebalien** [comment]
> Have you seen this problem in production? Every QUIC connection uses one Go routine for its run loop, so we're actually just replacing one Go routine with another.

Yeah, it's just:

1. The cost of opening new goroutines when we're trying to free resources. Now that libp2p doesn't spawn goroutines in notifications, it would be nice to avoid spawning goroutines on close entirely.
2. The cost of keeping open a background goroutine per connection when you're trying to save resources.

NOTE: this probably isn't critical, it's just something I noticed. This likely wasn't causing the problems I was seeing.

**Comment by marten-seemann** [comment]
Thanks for the context. This seems like a worthwhile optimization.
