### ISSUE TITLE
dependence broken in go.mod @ v0.27 

### ISSUE THREAD

**Issue by airylinus** [lucas-clemente/quic-go#3478]
Steps for repetition :

1. import quic-go@0.27.0 in projects go.mod
2. go mod vendor

Expected:
process success 

Got:
`internal error: failed to find embedded files of github.com/marten-seemann/qtls-go1-18: //go:build comment without // +build comment`

I found something here : 

- quic-go@0.27.0 required  go version 1.16 in go.mod    https://github.com/lucas-clemente/quic-go/blob/v0.27.0/go.mod#L3
- imported qtls-go1-18 which required go version 1.18   https://github.com/lucas-clemente/quic-go/blob/v0.27.0/go.mod#L12

**Comment by marten-seemann** [comment]
Works on CI: https://github.com/lucas-clemente/quic-go/blob/f29dd273b40d37b6ea8206350b2d96e8779161e5/.github/workflows/lint.yml#L20-L23.

**Comment by airylinus** [comment]
Thanks for checking!

I still don't know why `go mod vendor` breaks.
In case someone else got the same problem, I added this line in `go.mod` then fixed it:

`exclude github.com/lucas-clemente/quic-go v0.27.0`
