### ISSUE TITLE
Is connection migration supported now?

### ISSUE THREAD

**Issue by zzhlong** [lucas-clemente/quic-go#3480]
Quic go is currently used
Start the long connection between the server and the client to communicate with each other
The client network switching will result in the inability to receive the server messages, and will disconnect after the timeout set by the client
Is there an example of connection migration?
I'm looking forward to it. It will help me a lot. Thank you !!

**Comment by marten-seemann** [comment]
No need to open a new issue: https://github.com/lucas-clemente/quic-go/issues/234

**Comment by zzhlong** [comment]
@marten-seemann  Releases v0.28.0 Is connection migration supported now?
I'm looking forward to it. It will help me a lot. Thank you !!

**Comment by marten-seemann** [comment]
@zzhlong Please stop the spam! It is not supported, otherwise #234 would be resolved.
