### ISSUE TITLE
Cannot reuse http3.Server for multiple listeners

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#3486]
I'm refactoring how Caddy sets up HTTP servers and its HTTP/3 server.

A single http.Server can be used to serve on multiple listeners using `http.Server.Serve(ln)` and it keeps track of the listeners for shutdown-time.

I see that `http3.Server.ServeListener(ln)` does something similar. However, this also means that we are now using the same http3.Server for multiple listeners. Thus, I no longer set the `Addr` field because there are multiple addresses. This leads to trouble when trying to set the Alt-Svc header:

```
no port can be announced, specify it explicitly using Server.Port or Server.Addr
```

I'm thinking that http3.Server should get the Alt-Svc info from the listener directly.

(Note that each listener might be serving different applications.)

**Comment by marten-seemann** [comment]
I'm not sure if I fully understand the issue. When you call `http3.Server.ServeListener` with multiple listeners, we (try to) generate an Alt-Svc containing all ports.

Are you saying that we shouldn't do that, because the listeners might be serving different applications?
On the other hand, if they're serving different applications, wouldn't it make sense to use separate `http3.Server`s?

**Comment by mholt** [comment]
> When you call http3.Server.ServeListener with multiple listeners, we (try to) generate an Alt-Svc containing all ports.

Ah, then maybe there is a bug, since that's not what I'm seeing. This code returns an error:

https://github.com/caddyserver/caddy/blob/83ab068eea66cb6beb576e4f98e4059503a95d3d/modules/caddyhttp/server.go#L155-L161

Here's where we call `ServeListener()`:

https://github.com/caddyserver/caddy/blob/83ab068eea66cb6beb576e4f98e4059503a95d3d/modules/caddyhttp/app.go#L374-L384

> Are you saying that we shouldn't do that, because the listeners might be serving different applications?

No, I don't think so -- I think that you should be generating the Alt-Svc from the listeners directly, not _only_ from Addr/Port config on the struct.

> On the other hand, if they're serving different applications, wouldn't it make sense to use separate http3.Servers?

I don't think it necessarily does. An `http3.Server` is "just" configuration (I know it's also state related to actually running the server too) -- and shouldn't care about the application running on it, right? If they all share the same configuration, I think it makes sense -- and should be more efficient -- to only use one Server instance.

**Comment by marten-seemann** [comment]
> No, I don't think so -- I think that you should be generating the Alt-Svc from the listeners directly, not only from Addr/Port config on the struct.

That's how it works - or at least that's how it _should_ work: https://github.com/lucas-clemente/quic-go/blob/d5efd340c79e5a19ac69a2523527b56be4371715/http3/server.go#L348-L369

The `Addr` and `Port` variables are intended as on override, in case you need more control over the Alt-Svc, for example if you're running behind an L4 proxy. It should not be necessary to set them in most cases: https://github.com/lucas-clemente/quic-go/blob/d5efd340c79e5a19ac69a2523527b56be4371715/http3/server.go#L139-L145

My suspicion is that extracting the port from the listeners fails in https://github.com/lucas-clemente/quic-go/blob/d5efd340c79e5a19ac69a2523527b56be4371715/http3/server.go#L389-L391
Could you check this? Alternatively, I can also help debugging this, if you could provide me a Caddy config that reproduces this problem.

**Comment by mholt** [comment]
Nope, you're so right. Thanks for pushing back on this. The error was my mistake, got caught between a refactoring and a branch and I was a bit tired.

Sorry for the noise/trouble! :sweat: As far as I can tell this is working just fine. :100:
