### ISSUE TITLE
Support Go 1.19?

### ISSUE THREAD

**Issue by andig** [lucas-clemente/quic-go#3491]
A couple of brew packages fail to build on Go 1.19 in https://github.com/Homebrew/homebrew-core/pull/107165 due to 

    github.com/lucas-clemente/quic-go@v0.27.0/internal/qtls/go119.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.19 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.19 yet. F...) as int value in variable declaration

Would that be fixed by upgrading to 0.28 after https://github.com/lucas-clemente/quic-go/pull/3460 or is 1.19 still unsupported?

**Comment by marten-seemann** [comment]
v0.28 builds with 1.19, and there were no changes regarding 1.19 support between that version and the final release.

**Comment by andig** [comment]
@marten-seemann sorry for the issue-spam. It seemed best to link here in case the same question comes up again.
