### ISSUE TITLE
EnsureMinimumWindowSize core when c.allowWindowIncrease is ni

### ISSUE THREAD

**Issue by zouzc** [lucas-clemente/quic-go#3492]
banch: master
source file : https://github.com/lucas-clemente/quic-go/blob/master/internal/flowcontrol/connection_flow_controller.go

when c.allowWindowIncrease is nil, EnsureMinimumWindowSize will panic. may change:
 if delta := newSize - c.receiveWindowSize; delta > 0 && (c.allowWindowIncrease == nil  || c.allowWindowIncrease(delta))

func (c *connectionFlowController) EnsureMinimumWindowSize(inc protocol.ByteCount) {
	c.mutex.Lock()
	if inc > c.receiveWindowSize {
		c.logger.Debugf("Increasing receive flow control window for the connection to %d kB, in response to stream flow control window increase", c.receiveWindowSize/(1<<10))
		newSize := utils.MinByteCount(inc, c.maxReceiveWindowSize)
		if delta := newSize - c.receiveWindowSize; delta > 0 && c.allowWindowIncrease(delta) {
			c.receiveWindowSize = newSize
		}
		c.startNewAutoTuningEpoch(time.Now())
	}
	c.mutex.Unlock()
}

**Comment by zouzc** [comment]
package flowcontrol

import "testing"

func TestEnsureMinimumWindowSize(t *testing.T){
	c := connectionFlowController{}
	c.EnsureMinimumWindowSize(10)
}


goroutine 6 [running]:
testing.tRunner.func1.2({0x55aec0, 0x67cb50})
        /home/abc/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /home/abc/go/src/testing/testing.go:1392 +0x39f
panic({0x55aec0, 0x67cb50})
        /home/abc/go/src/runtime/panic.go:838 +0x207
github.com/lucas-clemente/quic-go/internal/flowcontrol.(*connectionFlowController).EnsureMinimumWindowSize(0xc00015e000, 0xa)
        /mnt/f/go/src/git.yy.com/push/httpproxy/vendor/github.com/lucas-clemente/quic-go/internal/flowcontrol/connection_flow_controller.go:90 +0x19b
github.com/lucas-clemente/quic-go/internal/flowcontrol.TestEnsureMinimumWindowSize(0x0?)
        /mnt/f/go/src/git.yy.com/push/httpproxy/vendor/github.com/lucas-clemente/quic-go/internal/flowcontrol/a_test.go:7 +0x2f
testing.tRunner(0xc000112ea0, 0x58a348)
        /home/abc/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /home/abc/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    github.com/lucas-clemente/quic-go/internal/flowcontrol  0.044s

**Comment by zouzc** [comment]
package flowcontrol

import "testing"
import "github.com/lucas-clemente/quic-go/internal/utils"

func TestEnsureMinimumWindowSize(t *testing.T){
	c := connectionFlowController{}
	c.logger = utils.DefaultLogger
	c.maxReceiveWindowSize = 2
	c.EnsureMinimumWindowSize(10)
}

goroutine 6 [running]:
testing.tRunner.func1.2({0x55aec0, 0x67cb50})
        /home/abc/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /home/abc/go/src/testing/testing.go:1392 +0x39f
panic({0x55aec0, 0x67cb50})
        /home/abc/go/src/runtime/panic.go:838 +0x207
github.com/lucas-clemente/quic-go/internal/flowcontrol.(*connectionFlowController).EnsureMinimumWindowSize(0xc00015e000, 0xa)
        /mnt/f/go/src/git.yy.com/push/httpproxy/vendor/github.com/lucas-clemente/quic-go/internal/flowcontrol/connection_flow_controller.go:91 +0x126
github.com/lucas-clemente/quic-go/internal/flowcontrol.TestEnsureMinimumWindowSize(0x0?)
        /mnt/f/go/src/git.yy.com/push/httpproxy/vendor/github.com/lucas-clemente/quic-go/internal/flowcontrol/a_test.go:10 +0x69
testing.tRunner(0xc000112ea0, 0x58a318)
        /home/abc/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /home/abc/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    github.com/lucas-clemente/quic-go/internal/flowcontrol  0.189s

**Comment by marten-seemann** [comment]
Again, please use code formatting!

I still don't understand the issue. When does this happen in practice?
