### ISSUE TITLE
Raising the default MaxDatagramFrameSize to 65536 to send more data?

### ISSUE THREAD

**Issue by MikeeI** [lucas-clemente/quic-go#3497]
I try to send datagrams with a size, that is bigger than the ```const MaxDatagramFrameSize ByteCount = 1220``` in [params.go](https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/params.go)

In the chrome source code, the maximum datagram frame size is ```QuicByteCount kMaxAcceptedDatagramFrameSize = 65536;``` [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/quic_constants.h;l=53?q=datagramframesize&sq=&ss=chromium)

And Apple Developers suggest to also use it with the size ```65536``` [WWDC 2022 Video - Reduce networking delays for a more responsive app @ 6:43
 ](https://developer.apple.com/videos/play/wwdc2022/10078/)

![image](https://user-images.githubusercontent.com/13944905/183708453-2a600f9e-e9e8-44e7-9905-015f2c85b47e.png)

I tried to change the const in ```params.go``` while using golangs go.mod replace feature, but every datagram i send with chrome above ~1200 bytes fails. Golang is still a relative new language for me and i tried to debug it, but cannot quiet get to the source of the error.

Do you have suggestions for me how solve my problem, if it is possible to send more than the "default datagram frame size".

**Thank you.**

**Comment by marten-seemann** [comment]
You’ll never be able to transmit 64k over the public internet. Typical MTUs are around 1200 to 1500 bytes.
