### ISSUE TITLE
Link utilization of quic-go

### ISSUE THREAD

**Issue by larryliu2018** [lucas-clemente/quic-go#3502]
Hey there, through testing, I found that the utilization rate on the quic-go high-bandwidth link is very low, and I want to know why
![image](https://user-images.githubusercontent.com/35099991/184348270-ef793466-a6cb-45b3-a150-d05f4d6b224c.png)
[Image Source](https://media.net.in.tum.de/videoarchive/WS20/Oberseminar/2020+12+14_1600+Analysis+of+the+Pacing+Mechanism+in+Current+QUIC/priv/slides.pdf)

I tested it myself with the same result. I also increased the buffer size by following the instructions on the [link](https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size) ; but the result still did not change
@lucas-clemente @marten-seemann 
Looking forward to your answer, thank you

**Comment by marten-seemann** [comment]
Not sure what’s the limiting factor in your setup. The 3 most likely areas that might limit your transfer speed are:
1. CPU utilization
2. Congestion controller
3. Flow control

qlog would help you to identify congestion controller and flow control problems. You can record CPU profiles to see if that’s the limiting factor.

Please let us know if you find out anything of interest.

**Comment by larryliu2018** [comment]
The result of the operation shows that the throughput is only about **400Mbps**, that is, the link utilization rate is only 40%. I have given the usage of CPU and cache here. I initially think that CPU and cache should not be limited. After all, it is an 8-core and 12-core CPU. **The congestion window is quite large, but the Bytes in flight is not high.** The overall link utilization is still relatively low. I would like to know what is the specific reason for this, and which aspects can be optimized. I look forward to your answer, thank you.  @marten-seemann 
**(1)** To avoid throughput being limited by flow control, I set a larger DefaultInitialMaxStreamData. The specific setting parameters are as follows:
**const DefaultInitialMaxStreamData = (1 << 20) * 100**
const DefaultMaxReceiveStreamFlowControlWindow = 320 * (1 << 20)
const DefaultMaxReceiveConnectionFlowControlWindow = 640 * (1 << 20)
**(2)** Topological structure is: server-------switch-------client; **link bandwidth is 1000Mbps**, RTT is about 2ms

**(3)** Parameters of CPU:
server: 8 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
client: 12 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
switch:[ ax3600](https://www.mi.com/r3600/specs)
**(4)** Buffer setting
net.core.optmem_max=20480
net.core.rmem_default=16777216
net.core.rmem_max = 536870912
net.core.wmem_default=16777216
**net.core.wmem_max = 536870912**
net.ipv4.tcp_mem = 4096 131072 16777216
net.ipv4.tcp_rmem=4096 16777216 536870912
net.ipv4.tcp_wmem=4096 16777216 536870912
**net.ipv4.udp_mem = 184377 16777216 536870912**
net.ipv4.udp_rmem_min=4096
net.ipv4.udp_wmem_min=4096
**(5)** Screenshot of CPU and memory usage during runtime
server:
![image](https://user-images.githubusercontent.com/35099991/185825478-7d0f7000-5b7f-4342-9fcf-14cd0a5f47a0.png)
client:
![image](https://user-images.githubusercontent.com/35099991/185825505-6862e83f-4dde-46a5-bcd2-1e0ba52252df.png)

**(6)**  the qlog screenshot of the server
![image](https://user-images.githubusercontent.com/35099991/185825521-2b1545a7-0db5-4bdf-a6a7-9c9ef0e2dff8.png)

**(7)** Packet capture result of wireshark:
![image](https://user-images.githubusercontent.com/35099991/185825535-cd486ae3-325a-4ecd-afb5-5ac8dd761679.png)

**Comment by larryliu2018** [comment]
Could it be because the cache space is too large, the file has been transferred, is still filled in the cache, the application layer needs to wait time to read, so the connection has not been closed
