### ISSUE TITLE
How to set a fixed port on the quic-client?

### ISSUE THREAD

**Issue by MirkoGamerman** [lucas-clemente/quic-go#3503]
How to set a fixed port on the quic-client?
Port: 0 -> random

//client.go
func dialAddrContext(
	ctx context.Context,
	addr string,
	tlsConf *tls.Config,
	config *Config,
	use0RTT bool,
) (quicConn, error) {
	udpAddr, err := net.ResolveUDPAddr("udp", addr)
	if err != nil {
		return nil, err
	}
	udpConn, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4zero, Port: 0})
	if err != nil {
		return nil, err
	}
	return dialContext(ctx, udpConn, udpAddr, addr, tlsConf, config, use0RTT, true)
}

**Comment by marten-seemann** [comment]
Please consult the documentation before asking trivial questions: https://pkg.go.dev/github.com/lucas-clemente/quic-go#Dial.
