### ISSUE TITLE
Does quic-go provides both reno and cubic?

### ISSUE THREAD

**Issue by snopytas** [lucas-clemente/quic-go#3508]
Hi, I've read that quic-go uses NewReno by default. But I can see multiple references to cubic (e.g. in cubic_sender.go). Is cubic fully functional in quic-go and can I choose between these CC algorithms? Thanks

**Comment by marten-seemann** [comment]
No, we only implement NewReno, as described in the RFC. The file is called cubic_sender for historical reasons (sorry for the confusion!), but it doesn't actually provide a Cubic implementation.

**Comment by snopytas** [comment]
Thank you. I asked because there is a boolean variable called `reno` in cubic_sender and there are different code paths dependent on this variable. If I understand correctly, these 'alternative' code paths are probably for historical reasons, too?

**Comment by marten-seemann** [comment]
Yes, that's correct.

**Comment by snopytas** [comment]
Thank you very much
