### ISSUE TITLE
https://http3check.net/ is not happy

### ISSUE THREAD

**Issue by mpl** [lucas-clemente/quic-go#3509]
Hey,

In the context of investigating https://github.com/traefik/traefik/issues/8255 , I ran a trivial HTTP/3 server, such as:

```
package main

import (
	"net/http"

	"github.com/lucas-clemente/quic-go/http3"
)

type myhandler struct{}

func (mh myhandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("HELLO"))
}

func main() {
	http.Handle("/", myhandler{})
	http3.ListenAndServe(":443", "./cert.pem", "./key.pem", nil)
}

```

and it turns out that https://http3check.net/ is not happy about it, and it displays a result like:

![Screenshot 2022-08-18 at 18 11 01](https://user-images.githubusercontent.com/626071/185446644-0df84f0d-5863-4f72-9722-52dc5c6ecff3.png)

IMHO, this is a pretty bad report as they don't explain what the problem(s) actually are, but here we are.
My naive suspicion is maybe they expect higher draft versions (h3-30, h3-31, ... , h3-34) in the Alt-Svc, but who knows...
What do you think?

Relatedly, I'm puzzled by this part of your README:

`
It has support for HTTP/3 (RFC 9114), including QPACK (RFC 9204).
In addition the RFCs listed above, it currently implements the IETF QUIC draft-29.
`

I would think that when one has fully implemented RFC 9114, it supersedes the implementation h3-29, no? How can one say that "only" h3-29 is implemented (i.e. none of the later drafts), and at the same time that RFC 9114 is implemented?
Is it that I'm too literal, and would it be correct to say that "RFC 9114 is partially implemented, as none of h3-30, ... h3-34 are implemented" ?

Then again, it's completely possible that I misunderstood something, and I would be very happy to be enlightened on the subject. :-)

Thanks

**Comment by marten-seemann** [comment]
> How can one say that "only" h3-29 is implemented (i.e. none of the later drafts), and at the same time that RFC 9114 is implemented?

Nobody is saying that only h3-29 is implemented. quic-go implement h3-29, QUIC v1 and QUIC v2 at the same time.

The HTTP header looks correct, it shows QUIC v1 support (`h3=...`). This is probably a bug in http3check, not in quic-go. Might be worth raising an issue with them.

**Comment by mradalbert** [comment]
I shared link to this issue on their slack

**Comment by mpl** [comment]
> > How can one say that "only" h3-29 is implemented (i.e. none of the later drafts), and at the same time that RFC 9114 is implemented?
> 
> Nobody is saying that only h3-29 is implemented. quic-go implement h3-29, QUIC v1 and QUIC v2 at the same time.

Sorry, it looks like I haven't been able to make myself clear, so please allow me to reformulate. What's the difference in saying that:
- RFC 9114 is implemented
VS
- IETF QUIC draft-29 is implemented
VS
- IETF QUIC draft-34 is implemented
?

To me they are all different versions of the same thing, no?

> The HTTP header looks correct, it shows QUIC v1 support (`h3=...`). This is probably a bug in http3check, not in quic-go. Might be worth raising an issue with them.

Good to know, thanks.

**Comment by marten-seemann** [comment]
> To me they are all different versions of the same thing, no?

There's minor differences between these versions. A QUIC server is free to implement as many versions as it wants.

**Comment by mpl** [comment]
> > To me they are all different versions of the same thing, no?
> 
> There's minor differences between these versions. A QUIC server is free to implement as many versions as it wants.

Ah ok, so let me see if I finally fully understand: IETF QUIC draft-29 and RFC 9114 are indeed both specifications for HTTP/3, slightly different from one another (with RFC 9114 being the most recent one), and quic-go implements both of them? And it advertises it in the Alt-Svc, so that it can comply with a client that speaks either of them?

If yes, then I agree that it is no cause for http3check.net to "complain". I could see it reporting an error if quic-go implemented only draft-29, but since it also implements RFC 9114...

**Comment by marten-seemann** [comment]
> Ah ok, so let me see if I finally fully understand: IETF QUIC draft-29 and RFC 9114 are indeed both specifications for HTTP/3, slightly different from one another (with RFC 9114 being the most recent one), and quic-go implements both of them? And it advertises it in the Alt-Svc, so that it can comply with a client that speaks either of them?

Correct.

**Comment by marten-seemann** [comment]
@mpl Have you raised an issue with http3check? Is there anything left to do in quic-go?

**Comment by mpl** [comment]
No I haven't, and I won't be able to until tomorrow.
But I leave it up to your judgement if you want to close the issue right
away.

**Comment by marten-seemann** [comment]
I'll close the issue, but it would be cool if you post the link to the http3check issue here once you've opened it!

**Comment by mpl** [comment]
@marten-seemann welp, they don't seem to advertise any public repo or bug tracker, and @mradalbert already talked to them on slack apparently, so I don't think there's much more I can do for now. If they don't want open and public feedback, so be it...

**Comment by mholt** [comment]
(In my previous experiences it seems that http3check.net only has the interest of matching whatever LiteSpeed currently supports, which makes sense since they're owned by LiteSpeed Technologies.)

**Comment by otbutz** [comment]
LiteSpeed seems to have corrected its test page. Both tests are now successful for my website with caddy v2.6.4:

![grafik](https://github.com/quic-go/quic-go/assets/22315436/e7e412d9-2d6d-4da5-b823-558dd9f862ac)
