### ISSUE TITLE
How to add a new byte correctly in the ackframe?

### ISSUE THREAD

**Issue by Bbilyf** [lucas-clemente/quic-go#3515]
I added a new byte to AckFrame, and the program works fine when transferring small files such as 100kb, but when the transferred file becomes 10MB, the program has Packetpacker bug: Packet Too Large. I want to know what structural changes need to be made in order for this new byte to be added? 
thks a lot

**Comment by marten-seemann** [comment]
Not sure why you'd do that, but you'll probably need to make sure that the `Length` function returns the correct frame length: https://github.com/lucas-clemente/quic-go/blob/57650fca7a2345d01c2364033e40eb14b3ac9f34/internal/wire/ack_frame.go#L143-L164

**Comment by Bbilyf** [comment]
Thanks!!!
Now I konw what the problem is.
Thanks again
