### ISSUE TITLE
improve ACK algorithm

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#354]
We currently send ACKs only with other frames, or after 5ms have expired. Under some situations this can cause problems, since it massively delays the congestion window increase, see the attached traces. #340 is a workaround, but we should still fix this issue.

<img width="1667" alt="screenshot 2016-11-17 15 50 52" src="https://cloud.githubusercontent.com/assets/918034/20446792/b3843774-addb-11e6-971e-d5adb10287cf.png">
<img width="1673" alt="screenshot 2016-11-17 15 50 59" src="https://cloud.githubusercontent.com/assets/918034/20446793/b384612c-addb-11e6-8ee1-6cb7e7f669b6.png">

**Comment by marten-seemann** [comment]
We should fix this issue soon.

With the the client I'm now at a point (in the `wip-client` branch) where I can do `GET` requests, but client and server always end up sending each other ACKs indefinitely.
