### ISSUE TITLE
Is CONNECT-UDP RFC-9298 Supported?

### ISSUE THREAD

**Issue by magicalo** [lucas-clemente/quic-go#3543]
Hi,

Does this support CONNECT-UDP and more over does it have UDP/TCP proxy capability that CONNECT-UDP and CONNECT Methods enable?

thx

**Comment by marten-seemann** [comment]
If it was, it would be listed in the README. For proxying, see #3370.

**Comment by magicalo** [comment]
So the answer is no.  Are there plans to support CONNECT-UDP so that I can use this code for a Proxy Server that will support clients that attempt to Proxy through to a  UDP resource behind the go Proxy server.
[client]==============[http/3 quic proxy]-----------------[udp resource] (via CONNECT-UDP)

**Comment by RithvikChuppala** [comment]
@magicalo have you figured out how to proxy using QUIC-go?
