### ISSUE TITLE
Use 0-RTT after a 0-RTT Connection

### ISSUE THREAD

**Issue by Kinqdos** [lucas-clemente/quic-go#3546]
Is it possible to use have a 0-RTT Connection after a 0-RTT Connection. Im playing around with 0-RTT and when I make multiple connection (not simultaneously) it is always alternating between 0-RTT and normal connection establishment.
My question is, if make 5 connections behind each other. Is it possible to have one normal establishment and 4 time a 0-RTT establishment?

**Comment by marten-seemann** [comment]
For subsequent 0-RTT connections, you just need to make sure that you send and receive enough session tickets.

**Comment by Kinqdos** [comment]
Can I actively control this? And If so how?
