### ISSUE TITLE
Timegap in 0-RTT flow

### ISSUE THREAD

**Issue by Kinqdos** [lucas-clemente/quic-go#3551]
Hey I noticed a random gap of one Rount Trip Time in my transmissions. The picture is showing a part of the transmission. Ive marked the packet after this gap. Can somenone explain me why this is happening?
![Screenshot 2022-09-12 094436](https://user-images.githubusercontent.com/62080449/189600080-f13e4212-7757-4cb1-84d0-6bd93a6cffad.png)

**Comment by marten-seemann** [comment]
Could be a lot of things. Flow control, congestion control, amplification limit etc. you can record a qlog and debug it using qvis.
