### ISSUE TITLE
Data sent (includes retransmits) exceeds flow control limit

### ISSUE THREAD

**Issue by larryliu2018** [lucas-clemente/quic-go#3553]
(**1**)Use the server and client programs in the interop folder to test on a link with **100Mbps and minRTT of 20ms**, transfer **500MB files**, and obtain the following qlog test results.

**It shows the curves of Connection flow control limit and Sum of stream flow control limits, which will be lower than the curve of Data sent later,** and the transmission can continue, and the RFC document says that if the sender violates the recommended connection or the flow's flow control upper limit, the receiver MUST close the connection with an error of type FLOW_CONTROL_ERROR. Want to know why this is, is there an error in the graph drawing of qlog itself, or what?
Hope to get your answer, thank you.
@marten-seemann 
complete figure：
![image](https://user-images.githubusercontent.com/35099991/189884604-7aaec2ae-6465-4b7a-8d45-f05aca927107.png)

enlarged detail：
![image](https://user-images.githubusercontent.com/35099991/189884637-487ae0b8-b352-42b9-9dd9-a1c6e805468e.png)

(**2**)In addition, there is a second question, why does the following phenomenon occasionally occur, **the Connection flow control limit will suddenly become 0,** in this case, where should I find the reason, thank you for your answer.
![Image 3](https://user-images.githubusercontent.com/35099991/189887987-ae747749-c7fb-40f5-b257-f37d96917cd9.png)

**Comment by marten-seemann** [comment]
Retransmits don’t count towards flow control limits, since you only retransmit data that was sent previously.

**Comment by larryliu2018** [comment]
> why does the following phenomenon occasionally occur, **the Connection flow control limit will suddenly become 0,**
Thank you so much for your quick reply, I probably got it. In addition, regarding the second question, "why does the following phenomenon occasionally occur, the Connection flow control limit will suddenly become 0,", have you encountered it in the test, and want to know if this problem occurs because of a bug in the program itself , or I don't understand the flow control implementation well enough, thank you

**Comment by marten-seemann** [comment]
No idea what's going on there. Can you verify if this actually corresponds to a MAX_DATA frame sent with a zero offset? If so, this would be a bug in quic-go (one that doesn't have any consequences, but still a bug). Alternatively, this could just a bug in this qvis visualization.

**Comment by larryliu2018** [comment]
Thank you very much for your answer, I rechecked the logic of quic-go processing MaxDataFrame, and there is no problem with the running logic of quic-go. I myself added a statement to output frame.MaximumData in the quic-go code:

`func (s *connection) handleMaxDataFrame(frame *wire.MaxDataFrame) {
	s.connFlowController.UpdateSendWindow(frame.MaximumData)
        fmt.Printf("45	%d	%d\n", frame.MaximumData, time.Now().UnixNano()/1000) //us
}`


Then the result graph drawn is as follows, but it will occasionally appear as 0. There may be unknown bugs in quic-go during operation.
![image](https://user-images.githubusercontent.com/35099991/190039704-89c3cc11-c7fd-49b0-8f14-bfbc845111e3.png)
