### ISSUE TITLE
After the congestion window stabilizes on the wifi link, it stays the same

### ISSUE THREAD

**Issue by larryliu2018** [lucas-clemente/quic-go#3554]
The congestion control algorithm I set is CUBIC. The congestion window is tested on the wifi link, the link environment is 802.11n/300Mbps, and the 1000MB file is transferred. After stabilization, there is no zig-zag exploration growth like the CUBIC congestion control algorithm. And the transmission is always bounded by the congestion window. The result is as follows:

![image](https://user-images.githubusercontent.com/35099991/190171023-81f59b54-1646-4284-b2d7-ff58da99bfca.png)

@marten-seemann 
I would like to know what is the cause of this, can you please guide me in the direction of further investigation? Looking forward to your answer, thank you. 
I guess it is because the number of acks decreases under the wifi link. The following is a screenshot of the specific data. I don't know if it's correct.

![image](https://user-images.githubusercontent.com/35099991/190171102-6487d601-0870-470b-baa8-92eb0aca5666.png)

I tested further and found that -------func (c *Cubic) CongestionWindowAfterAck()---------- always chooses **c.estimatedTCPcongestionWindow**

**Comment by marten-seemann** [comment]
> The congestion control algorithm I set is CUBIC. 

You can't set any congestion control algorithm. There's also no Cubic implementation here to begin with...

1. An increase only occurs if the congestion window was fully utilized. You might want to check if that's the case, see https://github.com/lucas-clemente/quic-go/blob/17761bf35f0e91c82ce963d4138aacf90213768a/internal/congestion/cubic_sender.go#L253-L261
2. When an increase occurs, it just increases the cwnd by a single packet per RTT, so the increase might seem very small in the diagram.

**Comment by larryliu2018** [comment]
1. I see that in cubic_sender.go, there is a parameter **reno bool**
```
func NewCubicSender(
clock Clock,
rttStats *utils.RTTStats,
initialMaxDatagramSize protocol.ByteCount,
reno bool,
tracer logging.ConnectionTracer,
) *cubicSender {
return newCubicSender(
clock,
rttStats,
reno,
initialMaxDatagramSize,
initialCongestionWindow*initialMaxDatagramSize, //32*x
protocol.MaxCongestionWindowPackets*initialMaxDatagramSize, //1000*x
tracer,
)
}
```
In addition, there is the following function, which should be used to calculate the congestion window using reno or cubic in the congestion avoidance stage. So in my test, **I set the reno bool parameter to false, so here I say that I set the congestion control algorithm to CUBIC. I don't know if my understanding is correct**.

```
func (c *cubicSender) maybeIncreaseCwnd(
_ protocol.PacketNumber,
ackedBytes protocol.ByteCount,
priorInFlight protocol.ByteCount,
eventTime time.Time,
) {
if !c.isCwndLimited(priorInFlight) {
c.cubic.OnApplicationLimited()
c.maybeTraceStateChange(logging.CongestionStateApplicationLimited)
return
}
if c.congestionWindow >= c.maxCongestionWindow() {
return
}
if c.InSlowStart() {
c.congestionWindow += c.maxDatagramSize
c.maybeTraceStateChange(logging.CongestionStateSlowStart)
return
}
// Congestion avoidance
c.maybeTraceStateChange(logging.CongestionStateCongestionAvoidance)
if c.reno {
// Classic Reno congestion avoidance.
c.numAckedPackets++
if c.numAckedPackets >= uint64(c.congestionWindow/c.maxDatagramSize) {
c.congestionWindow += c.maxDatagramSize
c.numAckedPackets = 0
}
} else {
c.congestionWindow = utils.MinByteCount(c.maxCongestionWindow(), c.cubic.CongestionWindowAfterAck(ackedBytes, c.congestionWindow, c.rttStats.MinRTT(), eventTime))
}
}
```


Finally this function is called in **sent_packet_handler.go**,
```
func newSentPacketHandler(
initialPN protocol.PacketNumber,
initialMaxDatagramSize protocol.ByteCount,
rttStats *utils.RTTStats,
pers protocol.Perspective,
tracer logging.ConnectionTracer,
logger utils.Logger,
) *sentPacketHandler {
congestion := congestion.NewCubicSender(
congestion.DefaultClock{},
rttStats,
initialMaxDatagramSize,
false, // true will use Reno;;; false will use cubic, ============= is written as true by default. In subsequent tests, it will be changed to false and use cubic
tracer,
)
```

**Therefore, what I understand is that the two congestion control algorithms, reno or cubic, can be changed by setting the value of reno.**

2. Indeed, I checked the output in key places during the test, and found that the congestion window was indeed limited during the test, and also found that the window growth rate was very small.
(1) The first record:
```
func (c *cubicSender) isCwndLimited(bytesInFlight protocol.ByteCount) bool {
congestionWindow := c.GetCongestionWindow()
if bytesInFlight >= congestionWindow {
fmt.Printf("49 %d %d\n", 1, time.Now().UnixNano()/1000) // Take us, to determine whether the congestion window is limited
return true
}
```
availableBytes := congestionWindow - bytesInFlight
slowStartLimited := c.InSlowStart() && bytesInFlight > congestionWindow/2
return slowStartLimited || availableBytes <= maxBurstPackets*c.maxDatagramSize
}
(2) The second record
```
func (c *Cubic) CongestionWindowAfterAck(
ackedBytes protocol.ByteCount,
currentCongestionWindow protocol.ByteCount,
delayMin time.Duration,
eventTime time.Time,
) protocol.ByteCount {
...

fmt.Printf("415 %d %d\n", (targetCongestionWindow), time.Now().UnixNano()/1000) //Look at the changes of this window,
return targetCongestionWindow
}
```
Below is a graph of the results of the test:
The time is actually partially aligned, which shows that after the slow start, most of the time is limited by the congestion window, and the growth of the congestion window is very limited, only one byte is added each time, I don’t know if this phenomenon is correct.
![image](https://user-images.githubusercontent.com/35099991/190292673-540e759d-fb13-4770-89b1-7c8a6e1f2dd7.png)

![image](https://user-images.githubusercontent.com/35099991/190292736-d67253ac-406f-4549-91bc-29e5af4cbef3.png)

**The value in the red box is the value of the congestion window, in Bytes. Looking at the growth trend, it is basically a growth of one byte at a time.**

![image](https://user-images.githubusercontent.com/35099991/190292842-fe45883f-8a35-4792-ae99-4d48aae7d9d4.png)

**Comment by marten-seemann** [comment]
As I said, Cubic is not implemented. It used to be, but we deleted (most of) the code. I suggest you rerun your measurements using the Reno congestion controller that quic-go ships with.
