### ISSUE TITLE
question: Is there a way to allow self-signed certs to connect?

### ISSUE THREAD

**Issue by esumerfd** [lucas-clemente/quic-go#3555]
I am using Algernon to serve test responses in CI over http3. The flow requires SSL for CORS so needs a localhost self signed cert. I am looking for a way to complete the connection without cert trust validation.

I found InsecureSkipVerify config value but it appears to only control the client, and the server is still closing the connection with no response.

**Comment by marten-seemann** [comment]
InsecureSkipVerify is all you need to disable certificate verification. The server doesn't perform verification, it's only done by the client.
