### ISSUE TITLE
Upload file failed

### ISSUE THREAD

**Issue by Abilyf** [lucas-clemente/quic-go#3564]
I added the new upload code on the client, but when uploading, the connection failed and prompted Connection refused. When I open LocalHost in my browser and try to upload at the same way, I got this error:

http: TLS handshake error from [::1]:54984: remote error: tls: unknown certificate

It seems like that the client keeps trying to change different ports, but the result is the same error. What's the reason? Is it the certificate?

**Comment by marten-seemann** [comment]
This is not a QUIC issue. Your TLS configuration is probably at fault.
