### ISSUE TITLE
http3: handle http.ErrAbortHandler in panicking HTTP handlers

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#3572]
This error can be used to suppress log output. See https://github.com/caddyserver/caddy/issues/5125.

Go std lib: https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/http/server.go;l=1835;drc=cbd931c9c2705e0e3a44c3b299ac2bd3369f5eb5

This is where we'd need to make the change in the `http3` package: https://github.com/lucas-clemente/quic-go/blob/424a66389c01d10678bfb980cfe6faa8524b42b6/http3/server.go#L575-L588

**Comment by shade34321** [comment]
If possible I'd like to take a stab at this but I may need some help. If I'm understanding it correctly we just need to do what the stdlib is doing.

**Comment by marten-seemann** [comment]
That's correct. Want to submit a PR? I'm happy to review.

**Comment by shade34321** [comment]
Yeah, give me a bit. Don't have a ton of time during work but might be able to squeeze something in.

**Comment by shade34321** [comment]
@marten-seemann put up a quick PR but I feel like it might be incomplete. Just let me know if you think it is. I'll also look further into it later tonight/this weekend.

**Comment by shade34321** [comment]
Also I'm working on this for hacktoberfest. Is it possible you can opt into hacktoberfest so I can get credit for it please. Thank you!

https://hacktoberfest.com/participation/#maintainers
