### ISSUE TITLE
please support default http2.0,not http1.1 thanks

### ISSUE THREAD

**Issue by hktalent** [lucas-clemente/quic-go#3578]
please support default http2.0,not http1.1 thanks
```
func RunHttp3(addr, certFile, keyFile string, router *gin.Engine) (err error) {
	log.Printf("Listening and serving HTTPS on %s\n", addr)
	// tcp
	util.Wg.Add(1)
	go func() {
		defer util.Wg.Done()
		http3.ListenAndServe(addr, certFile, keyFile, router.Handler())
	}()
	util.Wg.Add(1)
	go func() {
		defer util.Wg.Done()
		// udp
		quicConf := &quic.Config{}
		// udp
		server := http3.Server{
			Handler:    router.Handler(),
			Addr:       addr,
			QuicConfig: quicConf,
		}
		err = server.ListenAndServeTLS(certFile, keyFile)
		log.Println("http3.0 is start")
	}()
	return
}

```
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/18223385/194694069-1153b15a-fb92-4a8a-8d23-b37acab4967a.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/18223385/194694056-88d617c9-9223-4eb8-9120-2496a083aaea.png">

**Comment by marten-seemann** [comment]
The TCP fallback uses the standard library HTTP handler.

**Comment by hktalent** [comment]
@marten-seemann thanks
That's weird, gin returns http2, I don't know why it shows http1.1
http3.ListenAndServe(addr, certFile, keyFile, router.Handler())
<img width="447" alt="image" src="https://user-images.githubusercontent.com/18223385/194709703-ebed4bc9-b5ae-4bfb-b165-62f0060a2eaa.png">
