### ISSUE TITLE
stellite  quic server and quic client

### ISSUE THREAD

**Issue by notedit** [lucas-clemente/quic-go#358]
i  just found  https://github.com/line/stellite,  this is a quic client and quic server.

may be helpful  to you.

this is not a bug.  you can just close this.

**Comment by lucas-clemente** [comment]
Thanks for the link :) Stellite is a wrapper for Google's QUIC implementation from Chromium, not an independent implementation of the protocol. Of course, this doesn't in any way decrease the value of the work that line is doing, but unfortunately we can't really learn that much from them.
