### ISSUE TITLE
closeForShutdown called when stream is already closed

### ISSUE THREAD

**Issue by kokes** [lucas-clemente/quic-go#3592]
In my scenario I connect to a QUIC server, open a bunch of streams, do some work, close all of them and then close the QUIC connection, sort of like this, in pseudo code:

```go
quicConn := newQuicConn()

for j:=0; j < 10; j++ {
    stream, _ := quicConn.OpenStreamSync()
    // send/receive data
    stream.Close()
}

quicConn.CloseWithError(noError) // application error, 0x100 I believe
```

The issue is that all the streams, despite being closed gracefully, get hosed down with the `CloseWithError` call (I presume `RESET_STREAM`, but I haven't checked in the upstream system). There seem to be a race condition of some sort there, because if I sleep for a second before the `CloseWithError`, it all ends gracefully (I even tried a millisecond and most streams got through, not all though).

I also tried telling `CloseWithError`, or, to be more precise, `closeForShutdown` in `send_stream.go`, to not emit errors if the stream is already closed, like so:

```diff
diff --git a/send_stream.go b/send_stream.go
index 3daf6781..a18dbe7e 100644
--- a/send_stream.go
+++ b/send_stream.go
@@ -480,6 +480,10 @@ func (s *sendStream) SetWriteDeadline(t time.Time) error {
 // The peer will NOT be informed about this: the stream is closed without sending a FIN or RST.
 func (s *sendStream) closeForShutdown(err error) {
        s.mutex.Lock()
+       if s.finishedWriting {
+               s.mutex.Unlock()
+               return
+       }
        s.ctxCancel()
        s.closedForShutdown = true
        s.closeForShutdownErr = err
```

And this _almost_ works, all but the last stream get closed gracefully. I also tried cancelling the context, calling `signalWrite` and setting `closedForShutdown` to true, all within the new if statement, but neither helped to gracefully close the last stream.

Am I using the APIs incorrectly or is there really a race condition of some sort?

**Comment by marten-seemann** [comment]
The receiver will return all `Read` calls from the stream with the error received in the CONNECTION_CLOSE frame. This is indeed racy: If the CONNECTION_CLOSE is received before the FIN bit of the stream, your `Read` call will return the error instead of `io.EOF`.

**Comment by kokes** [comment]
Noted. Is this fixable or is that by design, meaning that the connection close is built this way, so that it doesn't need to wait/block on any potentially clean stream closures? If it's the latter, feel free to close this.

**Comment by marten-seemann** [comment]
CONNECTION_CLOSE in QUIC is always causes an immediate close of the connection.
If you want to make sure that the client successfully read the EOF, you'll need to explicitly communicate this. This also applies in the general case, without an explicit signal you can never know when a client actually read the data out of the receive buffer.

**Comment by marten-seemann** [comment]
Closing this issue, since I think it has been resolved. Feel free to reopen.
