### ISSUE TITLE
http3: client response does not include request

### ISSUE THREAD

**Issue by Davincible** [lucas-clemente/quic-go#3605]
The stdlib client will include the original request in the response, as to provide some context. I found that the HTTP3 client does not include it. Not a terrible bug but would be nice to be compliant with this small thing as well.

Only thing that needs to change is adding `Request: req,` to this struct;

https://github.com/lucas-clemente/quic-go/blob/af30cef57c5c20ebcb599200a96d89f7c33c3d50/http3/client.go#L388-L393

If welcome I can create a PR

**Comment by Davincible** [comment]
Small side question;
After adding this I noticed the `req.Proto == "HTTP/1.1"`, why is it saying that?
Response does say `HTTP/3`

**Comment by marten-seemann** [comment]
> If welcome I can create a PR

Yes please :)

> After adding this I noticed the req.Proto == "HTTP/1.1", why is it saying that?

Not sure if we ever set it correctly on the request struct. If we return it, it should be set correctly though.
