### ISSUE TITLE
What is the right way to close a stream?

### ISSUE THREAD

**Issue by moralityfrill** [lucas-clemente/quic-go#3610]
Hi

I don't really understand what's going on with stream closing.

For example, lets look into the example of echo server

https://github.com/lucas-clemente/quic-go/blob/master/example/echo/echo.go

It works fine, but there is no any stream closing, so lets change several code lines of a server implementation.

Before:

```
func echoServer() error {
	listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
	if err != nil {
		return err
	}
	conn, err := listener.Accept(context.Background())
	if err != nil {
		return err
	}
	stream, err := conn.AcceptStream(context.Background())
	if err != nil {
		panic(err)
	}
	// Echo through the loggingWriter
	_, err = io.Copy(loggingWriter{stream}, stream)
	return err
}
```

After:

```
func echoServer() error {
	listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)
	if err != nil {
		return err
	}
	conn, err := listener.Accept(context.Background())
	if err != nil {
		return err
	}
	stream, err := conn.AcceptStream(context.Background())
	if err != nil {
		panic(err)
	}

	log.Println("writing 'hello'...")
	n, err := stream.Write([]byte("hello"))
	log.Printf("n: %d\n", n)
	log.Println("err:", err)

	log.Println("closing a stream...")
	err = stream.Close()
	log.Println("err:", err)

	return err
}
```

Also I've changed goroutine call to:

```
go func() { echoServer() }()
```

Now we have `stream.Write` and `stream.Close` calls.

My expectations are:

1. Message is written correctly.  I got `5` as a value for a variable `n` and `nil` for a `err`.
2. Stream is closed successfuly (`err` is nil). So I decreased a number of opened streams.
3. Client can read my message `hello` successfuly and can understand that the stream was closed.

Reality:

1. ok. I got `5` and `nil` as a result for the `stream.Write` call.
2. ok. I got `nil` for the `stream.Close` call.
3. not ok. Client sees no message. Gets io.EOF or io.UnexpectedEOF errors.

What's wrong? Any proper way to handle stream closing allowing client to read previously sent data?

**Comment by marten-seemann** [comment]
`Close` sends the FIN bit. You can record a qlog to debug what's going on on the wire.

**Comment by moralityfrill** [comment]
So when I (as a server) close a stream I (as a client) can not read any data sent before closing?

**Comment by moralityfrill** [comment]
Is there any way to handle this situation?

**Comment by marten-seemann** [comment]
> So when I (as a server) close a stream I (as a client) can not read any data sent before closing?

That's not how it works. Data is delivered reliably.
