### ISSUE TITLE
Any P2P filesharing examples

### ISSUE THREAD

**Issue by lonnietc** [lucas-clemente/quic-go#3617]
Hello,

I am researching QUIC for use in a P2P file sharing project but need to learn more about it and am wondering if there are any P2P examples or server-client file transfer examples?

I have also come across uTP which is supposed to be a more advanced Torrent protocol and was wondering if maybe a type of QUIC Torrent application could be possible to further make the transfer speeds higher than normal TCP and UDP implementations.

Just some thoughts that I had

**Comment by gedw99** [comment]
yomorun is one option . But not sure it can do p2p. You can ask in their GitHub

**Comment by marten-seemann** [comment]
You can use QUIC in a p2p fashion. For example, have a look at libp2p for more details.

**Comment by Willxn** [comment]
do you have ideas in quic p2p file sharing system now?
