### ISSUE TITLE
Any Examples of QUIC file server/clients

### ISSUE THREAD

**Issue by lonnietc** [lucas-clemente/quic-go#3637]
Hello,

I am experimenting with QUIC as I understand that it is supposed to be much faster and have been researching either and SSH/SFTP or (hopefully) a possible QUIC based solution but have not really come across anything.

The server would need to allow for many concurrent connections from many clients.

Are there any possible QUIC solutions?
Thanks

**Comment by marten-seemann** [comment]
Not sure what the question is. A server can handle multiple connections concurrently.

**Comment by lonnietc** [comment]
Hello @marten-seemann 

Sorry for not being clear on this.

The question that I have is mainly from the inexperience with QUIC and I was wondering if there was a complete fileserver example somewhere with a server and client available.  (i.e. an FTP server for QUIC).
