### ISSUE TITLE
issue with error message and check condition

### ISSUE THREAD

**Issue by mrtrkmn** [lucas-clemente/quic-go#3645]
In the interop client side of the project, I have seen this error message even though the check is as follows: 

```go
	if len(urls) != 1 {
		return errors.New("expected at least 2 URLs")
	}
```

https://github.com/lucas-clemente/quic-go/blob/d2512193dac18f24b31bb3f1f50ac60adb448ee4/interop/client/main.go#L111

Ideally, I would expect the check to be 

```go
	if len(urls) < 2 {
		return errors.New("expected at least 2 URLs")
	}
```

Just learning these stuff, I can create a PR for it, but wanted to point out here first.

**Comment by marten-seemann** [comment]
Not sure I understand the problem. This test isn't even executed as part of the interop runner suite at the moment, as far as I can tell.

**Comment by mrtrkmn** [comment]
The if statement is len(urls) != 1, and the error message is "expected at least 2 URLs". 

I thought that this is mistake, indeed If len of urls is not 1 then it will throw an error. Does this expected behavior ?

**Comment by marten-seemann** [comment]
Technically that's correct, but what's the problem you're trying to solve?

**Comment by mrtrkmn** [comment]
I am doing a project for a course, therefore I was reading through the code however could not give any reasoning to statement which is len(urls) != 1, and the error message is "expected at least 2 URLs".  So it will only bypass the error if len(urls) = 1. I expected to see len(urls) =< 2 or error message to be different.

**Comment by marten-seemann** [comment]
I agree that it's not correct, probably it's the error message that would need to change instead of the if though. I don't care though since the test is disabled anyway, see https://github.com/marten-seemann/quic-interop-runner.
