### ISSUE TITLE
drop support for QUIC 34

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#368]

**Comment by marten-seemann** [comment]
Chrome seems to (finally) make some progress on that: https://codereview.chromium.org/2677323002

**Comment by marten-seemann** [comment]
Chromium has been speaking QUIC 35 for quite some time now. @lucas-clemente, do you agree that we can drop 34 now?

**Comment by lucas-clemente** [comment]
We got feedback last time we dropped support that it was too early, since linux distributions take a while to update Chrome. If it's not too much of a hassle, I'd like to keep support for a month or so after release of a new version (or we could check Ubuntu / Debian manually).
