### ISSUE TITLE
I have questions about ack block that I would like to answer

### ISSUE THREAD

**Issue by xs-411** [lucas-clemente/quic-go#3928]
I would like to ask a question regarding the "ack frame block."   I would appreciate it if you could provide an answer.   Thank you.

As the receiver, I have received a sequence of packets from 1 to 5.   Suddenly, I received a packet with the number 8.   Is the following ACK reply correct?

```
{
Frame Type: ACK (0x0000000000000003)
Largest Acknowledged: 8
ACK Range Count: 1
First ACK Range: 5
{
gap: 2 (6-7)
length: 5 (1-5)
}
}
```

Afterward, if I receive a packet with the number 9, is the following approach correct?   Should I save the previous ACK Range block and continue with the reply?

```
{
Frame Type: ACK (0x0000000000000003)
Largest Acknowledged: 9
ACK Range Count: 0
First ACK Range: 1
}

{
Frame Type: ACK (0x0000000000000003)
Largest Acknowledged: 9
ACK Range Count: 1
First ACK Range: 1 (8)
{
gap: 2 (6-7)
length: 5 (1-5)
}
}

```
Largest Acknowledged: 9
How do I reply ack if I receive a packet number less than 9? Do you still need to reply?
I hope you can provide an example of an ACK.   Thank you very much.

**Comment by marten-seemann** [comment]
This seems to be unrelated to quic-go and a question about the RFC.

You'd update the ACK block, so that you send an ACK with two range (1-5 and 8-9).
