### ISSUE TITLE
only retransmit WINDOW_UPDATEs if it is necessary

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#394]
As Ian noted in https://github.com/quicwg/base-drafts/issues/114, there are conditions under which it is not necessary to retransmit a WINDOW_UPDATE.

The most obvious condition is when we've already sent a WINDOW_UPDATE advertising a higher byte offset. It's possible to think of some more complicated conditions (e.g. when we receive an ACK for the second copy of the WINDOW_UPDATE, or even when we receive data with an offset higher than the flow control window that the peer would have had without receiving the WINDOW_UPDATE), but I'm not sure that the additional tracking required is worth the effort.

**Comment by janaiyengar** [comment]
I don't think it's worth the complexity.

**Comment by marten-seemann** [comment]
I decided to implement the simplest version: We're skipping the retransmission of WindowUpdates if the stream is already closed (and garbage-collected) or we already queued (or sent) a WindowUpdate with a higher offset.

**Comment by janaiyengar** [comment]
Ah, interesting. It's a good optimization for sure. I'd like to fix the draft to allow this implementation choice, since it's surely better than blindly retransmitting. I'll take a stab at it.
