### ISSUE TITLE
downloads not possible when packets are lost

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#40]
Might be multiple bugs here.

**Comment by lucas-clemente** [comment]
Three issues so far:

- Truncated ACKs, implemented in #57 
- Sometimes the client sends a `Least unacked too small.` in response to a STOP_WAITING frame.
- Sometimes the server stops with an EOF.

**Comment by lucas-clemente** [comment]
Note that all of these are extremely unlikely when using a congestion window.

**Comment by marten-seemann** [comment]
Not necessarily. They are only unlikely on reliable connections when using congestion control, because that way we basically prevent any packet loss. But there are connections that are inherently lossy.

**Comment by lucas-clemente** [comment]
Closing in favor of #49.
