### ISSUE TITLE
implement a connection keep-alive

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#400]
We should implement an option to keep a connection alive. The API would look similar (identical?) to the `IdleConnTimeout` in a `http.Transport` (see [here](https://golang.org/pkg/net/http/#Transport)).

This requires us to send PING frames, as well as to correctly set the `idleTimeout` in the `Session` based on the defined value.

**Comment by lucas-clemente** [comment]
Closing this as a duplicate of #525.
