### ISSUE TITLE
Support custom SNI / Host / IP address in the QUIC client

### ISSUE THREAD

**Issue by pforemski** [lucas-clemente/quic-go#401]
Per discussion at https://github.com/lucas-clemente/quic-go/issues/310#issuecomment-273436968, I'd like to ask for a new feature in the QUIC client - being able to separately control:

1. the IP address we connect to,
2. the SNI string we send during connection setup,
3. and the Host header we send in the requests.

I need this in my project (a Google Public DNS client, issue https://github.com/pforemski/dingo/issues/6), where I want to be able to hide the traffic from SNI-based firewalls (e.g., sending www.google.com in SNI instead of dns.google.com, which, at least for now, results in the same server certificate). Apart of that, I'd like more control of the server IP address than whatever comes out from resolving dns.google.com.

Keep up the good work! :)

**Comment by lucas-clemente** [comment]
This should be resolved by #693, you can now specify the hostname that is sent as SNI separately from the addr to connect to using the `tls.Config.ServerName` field.

Let us know if this doesn't work for your case! :)

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Setting ServerName is good, but how to specify a static IP to make the QUIC client stream initiate to? Currently, it seems like this is not working and always requires a DNS name? That becomes an issue for the dingo project. Has a workaround been identified? The steps above don't seem to work for me.
