### ISSUE TITLE
move PublicHeader to separate packet

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#412]
It could be useful e.g. for building a QUIC proxy.

We have to think about how we make the packet number accessible, since the header itself just contains the shortened packet number.

**Comment by lucas-clemente** [comment]
I don't think the (exact) packet number matters for what most proxies will want to do (reverse proxy or test dropping every Nth packet like we do now).

**Comment by marten-seemann** [comment]
True. Maybe it's sufficient if we properly document that the `PacketNumber` field just contains the shortened packet number.

**Comment by lucas-clemente** [comment]
E.g. by naming it `ShortenedPacketNumber`? ;)

**Comment by marten-seemann** [comment]
Well, I thought about that, but we're using the same field in the `Write` method, where it's supposed to be the full packet number.

**Comment by lucas-clemente** [comment]
We could move the shortening logic out of `Write`.

**Comment by marten-seemann** [comment]
And pass a separate parameter determining the written packet number length to `Write`? Maybe that's not a bad idea.

**Comment by lucas-clemente** [comment]
I don't think we'll need a separate parameter. Just use the shorstest
possible representation for the number passed in.

**Comment by marten-seemann** [comment]
I don't think that's possible. There will be cases where we need to send a 2 byte packet number, but the shortened form is between 0 and 0xFF.

**Comment by marten-seemann** [comment]
Looking at the current implementation of the `PublicHeader`, I think all of this should be really easy. We're already setting the `PacketNumberLen` before calling `Write`, so there's nothing we need to change.
I'll create a PR tomorrow.

**Comment by marten-seemann** [comment]
As discussed with @lucas-clemente yesterday, it might be nicer to have all public API in one packet (the main packet `quic`). This would lead to nice naming as well, e.g. `quic.PublicHeader`, `quic.Session`, `quic.Stream`.

So we probably shouldn't fix this issue. We'll make a final decision after we merge the *new-api* branch though.

**Comment by marten-seemann** [comment]
Now that the new API is merged (#420), we decided to leave the `PublicHeader` in the `quic` packet.
