### ISSUE TITLE
nil pointer dereference when the data stream of a new request is closed too quickly

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#414]
Related Caddy issue: https://github.com/mholt/caddy/issues/1415

In the `h2quic.Server` we're getting the data stream in [h2quic/server.go#L153](https://github.com/lucas-clemente/quic-go/blob/142db0bae400646817cc0293841292588339604d/h2quic/server.go#L153). However, since the H2 header stream is handled in a separate goroutine, by the time we're trying to get the data stream, this stream can already be closed. Realistically, this will only happen in cases when the client **immediately** resets the stream after sending the request.

**Comment by mholt** [comment]
Thanks for taking care of this, @marten-seemann ! You do great work with this lib.
