### ISSUE TITLE
ask server to truncate connection ID in client

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#434]
The client should send the `TCID` tag during the crypto handshake, to allow the server to omit the connection ID.

Once we have a `quic.Config`, this should be a configurable option, but truncating should be the default in this direction (packets sent from server to client).

**Comment by marten-seemann** [comment]
I'd like to hear what @lucas-clemente thinks about this.

**Comment by lucas-clemente** [comment]
sgtm

**Comment by marten-seemann** [comment]
I meant the `quic.Config`.

**Comment by marten-seemann** [comment]
We need to find a general solution here. The problem is that using default values doesn't really seem to  work when we need different default values, e.g. a `true` for the server and a `false` for the client. We have this for connection ID truncation, but the same problem also occurs for a connection keep-alive parameter that we might want to add to the `quic.Config`.

**Comment by marten-seemann** [comment]
As discussed OOB with @lucas-clemente, this the `quic.Config` should default to `false`, since this is the there won't be any problems with NATs.
For HTTP2, we'll set this to `true` in the `h2quic` for clients.
