### ISSUE TITLE
Expose Server.LocalAddr

### ISSUE THREAD

**Issue by cretz** [lucas-clemente/quic-go#436]
The UDP addr is exposed for remotes on the session, but no way to get the local addr after it is resolved because it is not exposed. Add `quic.Server.LocalAddr` like `net.Conn` has.

**Comment by cretz** [comment]
Actually, I can call Serve directly (which makes the "addr" state worthless)

**Comment by lucas-clemente** [comment]
We currently have a PR under way with a major revision of our API (#420) that will add such a method, but as you said, you can achieve that today with Serve.
