### ISSUE TITLE
implement 0-RTT handshakes

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#438]
The server already handles 0-RTT connections correctly.
Most of the logic for 0-RTT handshakes is client-side. This is a proposal for implementing 0-RTT connections.

## quic package

We need a way to store `ServerConfig`s such that they can be reused between requests. A good way to that would be to offer a `ServerConfigPool` similar to the [x509.CertPool](https://golang.org/pkg/crypto/x509/#CertPool). Before establishing the connection, `Dial` would search the `ServerConfigPool` for matching `ServerConfig`s and attempt a 0-RTT if it finds one.

## h2quic package

There needs to be a way to mark requests as "0-RTT safe", while the default is that they are not (i.e. only get executed forward-secure). 
I see two options here:

1. Add a `Is0RTTSafe(*http.Request) bool` callback to the `QuicRoundTripper`, which defaults to returning `false`. In this callback, an application could for example inspect if the `http.Request.Method` and only execute GET-requests as 0-RTT requests.
2. Add an explicit function `DoAs0Rtt(*http.Request)` which would mark a single request as 0-RTT safe.

**Comment by glen-dai** [comment]
When will 0-RTT be available ? Any plan yet?

**Comment by marten-seemann** [comment]
We're planning to work on the [first implementation draft of the QUIC WG](https://github.com/quicwg/base-drafts/wiki/First-Implementation-Draft) very soon, which includes switching the handshake to TLS 1.3. The most important thing will be getting the 1-RTT handshake right (in fact, 0-RTT is not included in the first implementation draft), but this will be the starting point for implementing 0-RTT.

**Comment by sferlin** [comment]
do you have any plans to address the 0-RTT soon?

**Comment by marten-seemann** [comment]
There are currently a lot of other issues that have higher priority for me than this one. For IETF QUIC, this will require a bunch of changes in the server as well.
