### ISSUE TITLE
Make idle state timeout configurable

### ISSUE THREAD

**Issue by cretz** [lucas-clemente/quic-go#441]
I am using QUIC in a non-HTTP setup, and I need to alter the idle state timeout, but I cannot from what is exposed. Can this be made configurable? I hesitate to do it myself as it appears a lot of things just got upheaved in #420.

Also, is there a place for discussion besides these issues?

**Comment by lucas-clemente** [comment]
As part of #420 we have introduced a new struct, [`quic.Config`](https://godoc.org/github.com/lucas-clemente/quic-go#Config). We plan to add parameters for both client and server there, e.g. timeouts, the max number of streams, etc. Do you need any parameters apart from the idle state timeout right now?

Also, the new API is mostly done now, PRs are always welcome ;)

No place for discussion except the issues right now, feel free to open as many as you want or reach out by email.

**Comment by cretz** [comment]
Nope, that's the only one I need at the moment. But I would imagine other handshake parameters would be harmless. Thanks!

**Comment by lucas-clemente** [comment]
I've changed the title of this issue to cover the ICSL, and am filing new issues for the other options that make sense. Also re-adding the want-help label.

**Comment by marten-seemann** [comment]
There are two timeouts here: 
- `DefaultIdleTimeout`, currently 30s, which applies after the handshake completes.
- `InitialIdleTimeout`, currently 5s, which applies before the handshake completes.

We need to decide if (and how) we want to expose those two.

Furthermore, we currently have `MaxIdleTimeoutServer` and `MaxIdleTimeoutClient`, which are the maximum values we accept for the idle timeout when we negotiate the value. We have to decide what we do with these values.

**Comment by marten-seemann** [comment]
As discussed with @lucas-clemente oob, we decided to:

1. set the `InitialIdleTimeout` to `quic.Config.HandshakeTimeout / 2`
2. use the configured `DefaultIdleTimeout` as the maximum value that weäd accept in negotiation.
