### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#444]
We could think about wrapping os.Stdout in the default logger, or using a log.Logger.

**Comment by marten-seemann** [comment]
If that one supports putting the timestamp at the end.

**Comment by lucas-clemente** [comment]
Loggers usually put them in the front. Why doe sit matter where they are?

**Comment by marten-seemann** [comment]
We often have to read these log files for debugging. Should be as human-readable as possible.
