### ISSUE TITLE
remove the NonForwardSecurePacketSizeReduction

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#457]
The `NonForwardSecurePacketSizeReduction` was introduced in #449.

It forces packets that are not sent with forward secure encryption to be a certain amount (set to 50 bytes) smaller than the `MaxPacketSize`. This is intended to make sure that a retransmission of a handshake packet **always** fits into one packet, even if we suddenly need to send a longer packet number in the `PublicHeader` and since we need to include a STOP_WAITING in every retransmission.
We have this requirement because `packetPacker.PackPacket()` only returns a single packet to the `session`.

A better solution would be to handle handshake retransmission more similar to normal retransmissions. STREAM frames would then be passed to the `streamFramer` (`AddFrameForRetransmission` would then need to be informed about the encryption level as well).
We still have to pay a little bit attention, because according to the current WG draft, an unencrypted packet is not allowed to contain WINDOW_UPDATEs and is not allowed to contain an ACK for packets encrypted with a higher encryption level, so it might make sense to remove all frames except for STREAM frames from such a packet.

**Comment by marten-seemann** [comment]
I worked on the solution described above today, and I don't really like it. The `streamFramer` is getting quite complicated, and we'll have to be really careful to never send out data with a lower encryption level.

I think there's a better solution on the horizon. Since STOP_WAITINGs are going to be removed from the protocol, we should be able to retransmit handshake packets without modifying the payload: As long as we can make sure that the Public Header doesn't grow, we can just introduce a `packetPacker.RetransmitHandshakePacket`, which takes a packet, writes a new Public Header and re-seals `packet.raw`, without even looking at the frames. In order to guarantee that the Public Header doesn't grow, we'd just have to use the maximum packet number length in the Public Header as long as the handshake is not completed (which will be a property of the new Long Header in the QUIC WG draft anyway).

I'd suggest to postpone this issue until STOP_WAITINGs are dropped in Chrome (or rather as soon as we're allowed to send overlapping stream data, because then the STOP_WAITING doesn't necessarily need to be included in the same packet).

**Comment by lucas-clemente** [comment]
SGTM

**Comment by marten-seemann** [comment]
This was fixed a while ago.
