### ISSUE TITLE
detection of too large packets not working

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#468]
We're reading packets from the UDPConn into a buffer of the size `MaxPacketSize`. Thus, if a peer sends out a packet exceeding the `MaxPacketSize`, we'll cut the packet when reading it, never triggering the error condition for the `PacketTooLarge` error.

This applies to both server and client.

**Comment by lucas-clemente** [comment]
There's the possibility to do a second readfrom with MSG_PEEK set just ahead of the current one. But I'm not sure detecting this error is actually worth the double amount of syscalls, which would probably have a noticeable performance impact.

**Comment by marten-seemann** [comment]
I think it's definitely not worth that many syscalls, however, we could make the buffers we read into one byte bigger than the maximum allowed packet size, and see if a packet completely fills that buffer (and then send a `PacketTooLarge` error).

**Comment by marten-seemann** [comment]
We need to decide if we properly want to implement this check (as described above?). Otherwise we should remove the useless code.

**Comment by lucas-clemente** [comment]
I don't think we need to add that check, but I'd like to keep the if as a sanity check anyway.

**Comment by lucas-clemente** [comment]
This was bugging me, so I did some more research, and found a solution that doesn't require a second syscall: The syscall.MSG_TRUNC flag is set in the data returned by [ReadMsgUdp](https://golang.org/pkg/net/#UDPConn.ReadMsgUDP). That however doesn't work with net.PacketConn. Tbh I think this is an issue with net.PacketConn, but there's nothing we can do about that.

**Comment by marten-seemann** [comment]
I'll remove the check for too large packets. If a peer really decides to send us a too large packet, we will read the truncated version of it and process it normally. That means, this packet will end up being undecryptable, and will be dropped anyway. This way, a peer doing PMTUD will learn about our maximum packet size.

There's a better signaling for this on the horizon (see https://github.com/quicwg/base-drafts/issues/383), so we'll come back to this when the WG makes a decision here.
