### ISSUE TITLE
use a self-signed cert for integration tests

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#475]
We will need to generate a CA for that and add the cert to the root certs in Docker (for the tests with Chrome) and every system that the integration tests are run on (for the quic_client).
Then we can generate a self-signed cert for quic.clemente.io, allowing us to get rid of the private key in *example/*.

**Comment by lucas-clemente** [comment]
#417 made the proposed solution (adding it to docker) impossible. I don't see a clean way of doing this on travis (w/o sudo).
