### ISSUE TITLE
ipv6 address not supported?

### ISSUE THREAD

**Issue by MisssRain** [lucas-clemente/quic-go#478]
I used the example/main.go as a server and -bind \[ipv6 address\]:port like this
But the client side insists an ERR_QUIC_PROTOCOL_ERROR
What is the problem?
Does it have something to do with the TLS certificate offered in quic-go?

I could ping6 ipv6_address successfully.

**Comment by marten-seemann** [comment]
I don't think the certificate has anything to do with that, it is tied to the SNI and should be independent of the IP version used. 

Could you run the server with the *-v* option and post the log here?

**Comment by MisssRain** [comment]
Sorry, I double checked my test, I am wrong that I mistaken the host-resolver-rules....
This issue should be closed and quic-go works well with ipv6
THANK YOU~

**Comment by lucas-clemente** [comment]
Glad to hear :) Feel free to let us know if you find any other issues.
