### ISSUE TITLE
Should we return an error from Listener.Serve() when it is closed?

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#483]
The following code for a TCP connection

```go
addr, _ := net.ResolveTCPAddr("tcp", "localhost:1234")
ln, _ := net.ListenTCP("tcp", addr)

go func() {
	time.Sleep(time.Second)
	ln.Close()
}()

_, err = ln.Accept()
fmt.Println(err)
```

prints `accept tcp 127.0.0.1:1234: use of closed network connection`.

The equivalent for a QUIC connection returns a `nil` from `Listener.Serve()` (i.e. after `Listener.Close()` is called), because we're replacing all errors containing the substring "use of closed network connection" with `nil`.

**Comment by lucas-clemente** [comment]
Yes, that's a bug. I don't remember why we do the replacement right now, but it looks like we're overzealous with it.

**Comment by lucas-clemente** [comment]
Hm, looking at the PR I'm not sure anymore my previous comment was right. The difference is that Accept() would create a new connection, whereas Serve() just handles existing connections properly. Calling Accept after closing doesn't make any sense, same as calling Serve() after closing. But a Close is not an error condition where Serve() should return not-nil.

Maybe the better comparison would be http.ListenAndServe. Would you mind checking whether that returns an error if a normal Close is done?

**Comment by marten-seemann** [comment]
I guess you mean `http.Serve` instead of `http.ListenAndServe`.

This is my test code:
```go
addr, _ := net.ResolveTCPAddr("tcp", "localhost:1234")
ln, _ := net.ListenTCP("tcp", addr)

go func() {
	time.Sleep(time.Second)
	ln.Close()
}()

err = http.Serve(ln, nil)
fmt.Println(err)
```

It also prints `accept tcp 127.0.0.1:1234: use of closed network connection`.

**Comment by lucas-clemente** [comment]
Ok, approved the PR.
