### ISSUE TITLE
Example server and example client 

### ISSUE THREAD

**Issue by fl43** [lucas-clemente/quic-go#488]
I am not sure if this is the right way to address these issue, so please point me in the right direction if there is a better way to handle such issues.

Installed Go 1.8 on Windows 7 machine.
Got latest version of quic-go.

Had to get some dependencies manually (golang.org/x/net/http2, github.com/lucas-clemente/quic-clients and github.com/tebeka/selenium), but tests still do not run.

Then I tried to get the example server and client running, but failed so far.

Server command line:
C:\dev\go\src\edge\quic-go>go run example/main.go -www /var/www/

Client command line:
C:\dev\go\src\edge\quic-go>go run example\client\main.go https://127.0.0.1:6121
GET https://127.0.0.1:6121
Starting new connection to 127.0.0.1 (127.0.0.1:6121), connectionID 98e910e61bb0947f, version 36
Certificate validation failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
Closing session with error: ProofInvalid
Connection 98e910e61bb0947f closed.

Two issues:
1)
What do I have to do to get this working? The readme does not contain any hints.
2)
Client does not terminate in most cases.

**Comment by lucas-clemente** [comment]
QUIC doesn't work when connecting to IP addresses (or localhost for that matter), you need a certificate that is trusted by your browser. On unix I'd propose adding "quic.clemente.io 127.0.0.1" to your /etc/hosts and pointing the client to https://quic.clemente.io. I don't know the windows equivalent, but that should point you in the right direction.

**Comment by fl43** [comment]
Is the same under Windows.
