### ISSUE TITLE
client closing connection due to invalid stop waiting data

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#49]
Error message:

    [0503/232045:VERBOSE1:quic_connection.cc(1913)] Client: Closing connection: 16302095663918797941, with error: QUIC_INVALID_STOP_WAITING_DATA (60), and details:  Least unacked too small.

**Comment by lucas-clemente** [comment]
This causes the client error:

```
-> Sending packet 0x806f (580 bytes)
	-> &frames.StopWaitingFrame{Entropy:0xe, LeastUnacked:0x792f}
	-> &frames.StreamFrame{StreamID: 9, FinBit: false, Offset: 0x1521f3a, Data length: 0x219, Offset + Data length: 0x1522153}
```

**Comment by lucas-clemente** [comment]
<img width="933" alt="screenshot 2016-05-08 16 50 28" src="https://cloud.githubusercontent.com/assets/918034/15098400/024d6a98-153d-11e6-994b-f37ca0f276db.png">
