### ISSUE TITLE
Do we need better errors in Dial()?

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#490]
When dialing a TCP connection fails, `DialTCP` returns this error message `panic: dial tcp 127.0.0.1:1234: getsockopt: connection refused`.

```go
addr, _ := net.ResolveTCPAddr("tcp", "localhost:1234")
_, err = net.DialTCP("tcp", nil, addr)
fmt.Println(err)
```

in QUIC we return a `use of closed network connection` when `Dial` fails. This is because run into the handshake timeout, which closes the connection.

**Comment by lucas-clemente** [comment]
I don't have a strong opinion on this. Neither the stdlibs nor our errors are programmatically consumable, so it doesn't make a difference except from a logging perspective.

**Comment by marten-seemann** [comment]
Now that we have the new API (#613) the error returned is `Get https://example.org:443: NetworkIdleTimeout: No recent network activity.`. I like that a lot better than the previous error, so I don't think we need to do anything here.
