### ISSUE TITLE
Chromium flow control autotuning change

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#499]
Does this concern us? https://codereview.chromium.org/2745253006/

**Comment by marten-seemann** [comment]
Yes, we can implement it like this. Although to be honest, this feels a bit like over-optimizing things at this point.

**Comment by lucas-clemente** [comment]
Then let's not do it :)

**Comment by marten-seemann** [comment]
It's an easy fix, let's keep this issue.
