### ISSUE TITLE
Add support for big-endian encoding

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#500]
We can do some work on this (testing with our client & server) even before Chromium supports it.

**Comment by marten-seemann** [comment]
I don't see any advantage in doing those changes before we at least have a `quic_client` that supports that.

**Comment by lucas-clemente** [comment]
It's something we can start doing if we have free time, and it's sufficiently isolated that I don't thing we necessarily need integration tests from the beginning.

**Comment by marten-seemann** [comment]
Related: https://codereview.chromium.org/2761973002/

**Comment by marten-seemann** [comment]
Apparently this is coming in QUIC 39 (#530).
