### ISSUE TITLE
Re-enable skipped client test

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#506]
As of #503, the "doesn't return after version negotiation is established if no ConnState is defined" test is disabled.

**Comment by marten-seemann** [comment]
Why's that? Can we fix that before merging?

**Comment by lucas-clemente** [comment]
Sorry, missed this comment. The tests basically asserts that Dial doesn't return, but I don't see a way of getting it to return during shutdown.
