### ISSUE TITLE
rewrite benchmark test

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#512]
Now that we have a client implementation, there's no need to have two QUIC servers talk to each other (as in our current benchmark test).

**Comment by dineshappavoo** [comment]
@marten-seemann  @lucas-clemente  I am interested in contributing to this package. Is there any chat groups which I can follow? Also I am not sure if you are working with new contributors. If so, I can pick some starter issues and work on that.

**Comment by lucas-clemente** [comment]
We're always happy to welcome new contributors! :)

We don't have any chat groups, we try to coordinate everything through github. I've added a [want-help label](https://github.com/lucas-clemente/quic-go/issues?q=is%3Aopen+is%3Aissue+label%3Awant-help), though there currently aren't many issues that are just a "simple" fix :/ If you want, have a look at the other issues too, and if something look interesting or is unclear just leave a comment!

Is there anything you think we can do to make this easier for new contributors?

OT: This issue will probably soon be closed by the PR, but feel free to reply anyway!

**Comment by dineshappavoo** [comment]
@lucas-clemente Thanks for the response. sure. I will take a look at the `want-help` tagged issues and begin with some simple fix.

I will update the README if I get into any issues in the beginner setup.
