### ISSUE TITLE
Make handshake timeout configurable

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#521]
The handshake timeout is currently fixed in https://github.com/lucas-clemente/quic-go/blob/master/protocol/server_parameters.go#L131, we should make it configurable via [quic.Config](https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L60).

**Comment by AudriusButkevicius** [comment]
I think this should be part of SetDeadline for whatever stage the handshake happens (I am unfamiliar with how quic works but I suspect it's at Accept() Dial() stages)

**Comment by lucas-clemente** [comment]
I think I answered your question in #514? Feel free to ping me if I didn't do a good enough job ;)

**Comment by marten-seemann** [comment]
This would allow us to have a very nice integration test (when fixing #538) where we could assert the handshake timeout by setting it shorter than 3 times the RTT.

**Comment by marten-seemann** [comment]
Fixed by #630.
