### ISSUE TITLE
Make max incoming streams configurable

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#523]
The max number of incoming streams is currently fixed in the server parameters, we should make it configurable via [quic.Config](https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L148).

**Comment by marten-seemann** [comment]
This would be pretty useful for the integration tests. At the moment, we have a very slow test downloading a huge number of files (> 100), just to run into that limit. This test can be sped up a lot by making this configurable.
