### ISSUE TITLE
Make max flow control windows configurable

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#526]
The flow control windows are currently fixed in https://github.com/lucas-clemente/quic-go/blob/master/protocol/server_parameters.go#L42 and below, we should make them configurable via [quic.Config](https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L60).

See also https://github.com/golang/net/commit/906cda9512f77671ab44f8c8563b13a8e707b230.

**Comment by marten-seemann** [comment]
Fixed by #666.
