### ISSUE TITLE
Setting MTU on Server/Client

### ISSUE THREAD

**Issue by eliezedeck** [lucas-clemente/quic-go#536]
How does one set MTU, possibly different on the Server/Listener and the Client?

I'm tunneling inside existing protocol of different types, and the MTU for each is different, applies to both Server and Client. On the client, sending can be as low as just 150 bytes, and on the receiving it can be about 300 bytes.

Is this a possible setup for quick-go?

Thanks.

**Comment by marten-seemann** [comment]
Currently, we're sending packets with a maximum size of 1350 bytes (set in `protocol.MaxPacketSize`). This is the value that Chrome is using at the moment.

The QUIC protocol, as it is being standardized by the IETF, will not support MTUs smaller than 1280 bytes (see https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.9).
A peer can send larger packets when it does Path MTU Discovery (we have an issue for that, #94), but there won't be a way to go below that vlaue.

**Comment by eliezedeck** [comment]
Alright, thanks. That clarifies things.
