### ISSUE TITLE
Make integration tests race free

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#558]
The current setup with the start and stop functions is race-prone and pollutes Go's race detection output. We should figure out a way to run the tests without races.

**Comment by marten-seemann** [comment]
I'm not sure this is possible with the `gexec` package. `Start` and `Kill` seems to be inherently racy.

**Comment by marten-seemann** [comment]
make race free:
- [ ] the gquic tests
- [ ] the self tests
- [ ] the Chrome tests
- [ ] the tools

**Comment by marten-seemann** [comment]
The problem was not the `gexec` package, but how we were using it.
