### ISSUE TITLE
return an error in Dial() if the handshake fails

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#564]
Related to #563.

**Comment by marten-seemann** [comment]
We could make `session.run()` return an error as soon as the `runLoop` is closed. This would also allow us to get rid of the `closeCallback`.

**Comment by marten-seemann** [comment]
I just started working on this, and it seems more complicated than I thought.

If a `quic.Config` is given, `Dial` returns immediately after the version negotiation succeeded, i.e. before the crypto handshake. That means, we can't return any errors there. If no `quic.Config` is given, the suggested solution works fine.

One option would be to introduce a new `ConnState` for failed connections, e.g. `ConnStateHandshakeFailed` or `ConnStateConnectionClosed`. The problem is, that while we're at least able to notify the caller that *something* went wrong, there's no obvious way to pass an error.

**Comment by lucas-clemente** [comment]
Another (more drastic) option would be to get rid of the callback and
return a chan, which gets messages on various events.

**Comment by marten-seemann** [comment]
I don't yet see how that helps. The "message" we pass to the callback nowconsisits of the session and the ConnState. It seems like we need to add a third parameter, the error, here.
If we do that by adding another parameter to be ConnStateCallback signature, by bundling these three values in a struct and passing it to the callback, or passing such a struct down a channel, doesn't make a big difference, does it?

**Comment by lucas-clemente** [comment]
I was thinking of returning something along the lines of `(Session, chan ConnState, chan error)` from Dial.

Tbh I'm increasingly thinking we're overcomplicating things here. Maybe a simpler option in total would be to return (Session, error) when the handshake is complete, and have a callback `OnSecure func(Session)` in the config that can optionally do non-fw secure things?
