### ISSUE TITLE
Make QUIC versions configurable

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#565]
There should be a `quic.Config` options for QUIC versions, of type `[]protocol.VersionNumber`.
It determines which QUIC versions a server / client is willing to use. The default value is `protocol.SupportedVersions`.
For the client, the order of this slice determines the preference: The first version in the slice would be tried on the first dial attempt.

**Comment by lucas-clemente** [comment]
+10, this would make the inttests race-free.

**Comment by marten-seemann** [comment]
Is that what you meant with #558? I didn't know that the versions are the problem here.

**Comment by lucas-clemente** [comment]
It's one of the trickier issues, but not the only one.
