### ISSUE TITLE
Add an integration test that drops multiple packets in a row

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#575]
We currently only have tests for dropping packets where each packet is dropped independently from others. Dropping multiple packets in a row is a more realistic scenario, that could reveal separate bugs (e.g. I suspect this in #555).

**Comment by twdkeule** [comment]
Hi, I would like to work on this but I am having some issues with running integration test suite. 
I can run the tests, but I would like to be able to run just one (or a set of) test of the test suite, otherwise I have to run the whole suite each time.

**Comment by lucas-clemente** [comment]
Thanks for wanting to helping out! :)

New tests are always welcome, but we might need to disable this one until
the drop issue is fixed, in order to not kill the CI.

With ginkgo you can just add a "F" (think focus) in front of any test or
context (FIt(), FCo text()) to just run that one.

Let me know if you need any help!
