### ISSUE TITLE
Implement CloseNotifier interface

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#583]
Hi! :smile:

Is it trivial to implement a CloseNotify method on h2quic.ResponseWriter? I'm asking in reference to this issue: https://github.com/mholt/caddy/issues/1643

If so, I could potentially submit a pull request, I just need to know if this would be a no-op like Flush... or if it's more complicated maybe I should leave it to you too; I'm not super well versed in quic's operational requirements.

**Comment by lucas-clemente** [comment]
Thanks for raising this! I think a "real" implementation might be a bit tricky, but definitely not impossible. But, as you're saying, I think it should be fine to just throw it in as a NOP for now (returning a new chan each time). We can then figure out the proper implementation later.

**Comment by mholt** [comment]
Sounds good to me, PR is currently finishing up tests. Kinda sorry to add to your list of things to do. 😇 Thanks for all the great work you do though!
