### ISSUE TITLE
CryptoNoSupport error

### ISSUE THREAD

**Issue by bharatkrishna** [lucas-clemente/quic-go#588]
I am running the example client against a local server and I get this error:
`Closing session with error: CryptoNoSupport: KEXS`

I don't quite understand what this error means. Looks like the server doesn't support the cipher which the client requests? If so, how can I make a request with a different cipher?

**Comment by marten-seemann** [comment]
Currently, both server and client only support Curve25519 Key Exchange. The error is thrown if the server offered a different key exchange in https://github.com/lucas-clemente/quic-go/blob/master/handshake/server_config_client.go#L70.

Both quic-go and the Google toy quic_server support Curve25519, so we never had a problem with this. Which server implementation are you using?

**Comment by bharatkrishna** [comment]
Thanks for your reply. The server is a one we are building in house in my company based on google's. By default it was not using Curve25519. After changing some settings, I got it to use Curve25519. And could make a successful request.

**Comment by marten-seemann** [comment]
Ok, thanks.

I just discovered that if the server is offering multiple key exchange algorithms, we'd reject those, even if one of them is Curve25519. I fixed that in #589.

Please feel free to open new issues if you encounter any further problems.
