### ISSUE TITLE
Stream interface support half-close, just like TCP

### ISSUE THREAD

**Issue by glen-dai** [lucas-clemente/quic-go#596]
Quic stream is a reliable transport channel just like TCP, but TCP support shutdown(RD) and shutdown(WR) to create half-close state, so may be Quic Stream interface just add CloseRead() and CloseWrite() interface to support half-close state just like TCP? 

When using quic-go's stream to implement a TCP to QUIC proxy, I found when TCP half-close the link, there is no way I can pass the half close state through QUIC.

The data flows like this:
Client ---（TCP）----> Quic_Proxy_Client ------（QUIC）------->Quic_Proxy_Server----(TCP）---> Server

**Comment by lucas-clemente** [comment]
Thanks for the suggestion! We're aware of a difference here, but there's still a lot of discussion happening in the WG about how stream resets work (e.g. https://github.com/quicwg/base-drafts/issues/165 and https://github.com/quicwg/base-drafts/issues/175). I'd rather wait until the WG has converged to a solution and then implement that.

**Comment by marten-seemann** [comment]
Related: https://github.com/quicwg/base-drafts/issues/783

**Comment by marten-seemann** [comment]
The QUIC WG recently made comprehensive changes to the stream state machine: https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.10.

This is the state machine quic-go will implement, so you'll need to see how that fits the TCP model.
