### ISSUE TITLE
QUIC server requires SNI but Chromium does not provide it.

### ISSUE THREAD

**Issue by twdkeule** [lucas-clemente/quic-go#597]
When using QUIC (over localhost with self-signed certificate) the Caddy server aborts a connection setup with response "SNI required". However this not a required parameter for the QUIC protocol (from what I found, I'm not an expert) and chromium does not send the SNI for certain urls (pure IP and urls without top level domain (eg localhost)). 

SNI:
> SNI
> Server Name Indication (optional): the fully qualified DNS name of the server, canonicalised to lowercase with no trailing period. Internationalized domain names need to be encoded as A-labels defined in RFC 5890. The value of the SNI tag must not be an IP address literal.
> 

Fyi: this was all over localhost, but with an entry in /etc/hosts to have a specific url (which is in the certificate)

Client Hello:
> QUIC (Quick UDP Internet Connections)
>     Public Flags: 0x0d
>         .... ...1 = Version: Yes
>         .... ..0. = Reset: No
>         .... .1.. = Diversification nonce: Yes
>         .... 1... = CID Length: 8 Bytes
>         ..00 .... = Packet Number Length: 1 Byte (0x0)
>         .0.. .... = Multipath: No
>         0... .... = Reserved: 0x0
>     CID: 14127254023100437260
>     Version: Q035
>     Packet Number: 1
>     Message Authentication Hash: 1a57f56c70180a74870cde48
>     STREAM (Special Frame Type) Stream ID:1, Type: CHLO (Client Hello)
>         Frame Type: STREAM (Special Frame Type) (0xa0)
>             1... .... = Stream: True
>             .0.. .... = FIN: False
>             ..1. .... = Data Length: 2 Bytes
>             ...0 00.. = Offset Length: 0 Byte (0)
>             .... ..00 = Stream Length: 1 Byte (0)
>         Stream ID: 1
>         Data Length: 1300
>         Tag: CHLO (Client Hello)
>         Tag Number: 18
>         Padding: 0000
>         Tag/value: PAD (Padding) (l=974)
>             Tag Type: PAD (Padding)
>             Tag offset end: 974
>             [Tag length: 974]
>             Tag/value: 2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d...
>             Padding: 2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d...
>         Tag/value: VER (Version) (l=4) Q035
>             Tag Type: VER (Version)
>             Tag offset end: 978
>             [Tag length: 4]
>             Tag/value: 51303335
>             Version: Q035
>         Tag/value: CCS (Common Certificate Sets) (l=16)
>             Tag Type: CCS (Common Certificate Sets)
>             Tag offset end: 994
>             [Tag length: 16]
>             Tag/value: 01e8816092921ae87eed8086a2158291
>             Common certificate sets: 0x01e8816092921ae8
>             Common certificate sets: 0x7eed8086a2158291
>         Tag/value: MSPC (Max streams per connection) (l=4): 100
>             Tag Type: MSPC (Max streams per connection)
>             Tag offset end: 998
>             [Tag length: 4]
>             Tag/value: 64000000
>             Max streams per connection: 100
>         Tag/value: UAID (Client's User Agent ID) (l=74): Built on Ubuntu , running on Ubuntu 17.04 Chrome/58.0.3029.81 Linux x86_64
>             Tag Type: UAID (Client's User Agent ID)
>             Tag offset end: 1072
>             [Tag length: 74]
>             Tag/value: 4275696c74206f6e205562756e7475202c2072756e6e696e...
>             Client's User Agent ID: Built on Ubuntu , running on Ubuntu 17.04 Chrome/58.0.3029.81 Linux x86_64
>         Tag/value: TCID (Connection ID truncation) (l=4)
>             Tag Type: TCID (Connection ID truncation)
>             Tag offset end: 1076
>             [Tag length: 4]
>             Tag/value: 00000000
>             Connection ID truncation: 0 (0x00000000)
>         Tag/value: PDMD (Proof Demand) (l=4): X509
>             Tag Type: PDMD (Proof Demand)
>             Tag offset end: 1080
>             [Tag length: 4]
>             Tag/value: 58353039
>             Proof demand: X509
>         Tag/value: SRBF (Socket receive buffer) (l=4)
>             Tag Type: SRBF (Socket receive buffer)
>             Tag offset end: 1084
>             [Tag length: 4]
>             Tag/value: 00001000
>             Socket receive buffer: 1048576 (0x00100000)
>         Tag/value: SMHL (Unknown) (l=4)
>             Tag Type: SMHL (Unknown)
>             Tag offset end: 1088
>             [Tag length: 4]
>             Tag/value: 01000000
>             Unknown tag: 01000000
>             [Expert Info (Note/Undecoded): Dissector for QUIC Tag SMHL (Unknown) code not implemented, Contact Wireshark developers if you want this supported]
>                 [Dissector for QUIC Tag SMHL (Unknown) code not implemented, Contact Wireshark developers if you want this supported]
>                 [Severity level: Note]
>                 [Group: Undecoded]
>         Tag/value: ICSL (Idle connection state) (l=4)
>             Tag Type: ICSL (Idle connection state)
>             Tag offset end: 1092
>             [Tag length: 4]
>             Tag/value: 1e000000
>             Idle connection state: 30 (0x0000001e)
>         Tag/value: CTIM (Client Timestamp) (l=8)
>             Tag Type: CTIM (Client Timestamp)
>             Tag offset end: 1100
>             [Tag length: 8]
>             Tag/value: 002e105900000000
>             Client Timestamp: Feb  4, 1970 22:34:01.000000000 UTC
>         Tag/value: NONP (Client Proof Nonce) (l=32)
>             Tag Type: NONP (Client Proof Nonce)
>             Tag offset end: 1132
>             [Tag length: 32]
>             Tag/value: 2ef90efdd9954e51685c345496b6ae9fb2f8282dca751efb...
>             Client Proof nonce: 2ef90efdd9954e51685c345496b6ae9fb2f8282dca751efb...
>         Tag/value: MIDS (Unknown) (l=4)
>             Tag Type: MIDS (Unknown)
>             Tag offset end: 1136
>             [Tag length: 4]
>             Tag/value: 64000000
>             Unknown tag: 64000000
>             [Expert Info (Note/Undecoded): Dissector for QUIC Tag MIDS (Unknown) code not implemented, Contact Wireshark developers if you want this supported]
>                 [Dissector for QUIC Tag MIDS (Unknown) code not implemented, Contact Wireshark developers if you want this supported]
>                 [Severity level: Note]
>                 [Group: Undecoded]
>         Tag/value: SCLS (Silently close on timeout) (l=4)
>             Tag Type: SCLS (Silently close on timeout)
>             Tag offset end: 1140
>             [Tag length: 4]
>             Tag/value: 01000000
>             Silently close on timeout: 1 (0x00000001)
>         Tag/value: CSCT (Signed cert timestamp (RFC6962) of leaf cert) (l=0)
>             Tag Type: CSCT (Signed cert timestamp (RFC6962) of leaf cert)
>             Tag offset end: 1140
>             [Tag length: 0]
>             Tag/value: <MISSING>
>             Signed cert timestamp: <MISSING>
>         Tag/value: COPT (Connection options) (l=0)
>             Tag Type: COPT (Connection options)
>             Tag offset end: 1140
>             [Tag length: 0]
>             Tag/value: <MISSING>
>         Tag/value: CFCW (Initial session/connection) (l=4): 15728640
>             Tag Type: CFCW (Initial session/connection)
>             Tag offset end: 1144
>             [Tag length: 4]
>             Tag/value: 0000f000
>             Initial session/connection: 15728640
>         Tag/value: SFCW (Initial stream flow control) (l=4): 6291456
>             Tag Type: SFCW (Initial stream flow control)
>             Tag offset end: 1148
>             [Tag length: 4]
>             Tag/value: 00006000
>             Initial stream flow control: 6291456
>     PADDING Length: 19
>         Frame Type: PADDING (0x00)
>         [Padding Length: 19]
>         Padding: 00000000000000000000000000000000000000

Server Response:
>  QUIC (Quick UDP Internet Connections)
>     Public Flags: 0x18
>         .... ...0 = Version: No
>         .... ..0. = Reset: No
>         .... .0.. = Diversification nonce: No
>         .... 1... = CID Length: 8 Bytes
>         ..01 .... = Packet Number Length: 2 Bytes (0x1)
>         .0.. .... = Multipath: No
>         0... .... = Reserved: 0x0
>     CID: 14127254023100437260
>     Packet Number: 2
>     Message Authentication Hash: cf989ca6609c04e6212365ee
>     CONNECTION_CLOSE Error code: A crypto message was received with a mandatory parameter missing
>         Frame Type: CONNECTION_CLOSE (0x02)
>         Error code: A crypto message was received with a mandatory parameter missing (35)
>         Reason phrase Length: 12
>         Reason phrase: SNI required

**Comment by marten-seemann** [comment]
Without an SNI, no certificate can be selected. This is the same with the `quic_server`.

**Comment by lucas-clemente** [comment]
Strictly speaking you are right and QUIC doesn't require SNI right now (though it will in the future when TLS 1.3 is adopted). However, we decided to require SNIs, as that makes some implementation details simpler (and is, as you found out, only an issue for somewhat "artificial" setups). So no, we don't support IPs and "https://localhost".

What confuses me is that you mentioned adding an entry to /etc/hosts. If you do that and it's a normal domain for that your cert is valid, then everything should work. If that's the case, please feel free to reopen this issue :)

**Comment by twdkeule** [comment]
Yes, I use /etc/hosts but with a hostname of the form "foo" instead of "foo.bar"
I changed it too the second form (and changes all the certificates) and now it works!
Thanks for the fast responses
