### ISSUE TITLE
race condition when sending PublicReset

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#607]
`session.sendPublicReset` write to the underlying connection directly. `Write`s are not protected by a mutex, so there could be two concurrent `Write`s.

**Comment by lucas-clemente** [comment]
I'm not sure this is an issue. net.PacketConn says: "Multiple goroutines may invoke methods on a PacketConn simultaneously." BSD sockets also don't have an issue with concurrent writes.

**Comment by marten-seemann** [comment]
Ok, then the connection is not a problem. Maybe accessing the `session.lastRcvdPacketNumber` is though.
I already pushed a PR with a fix, which also fixes #600, so we should merge that regardless if there's an issue here with the PublicReset or not.
