### ISSUE TITLE
client switches to secure encryption only when receiving the SHLO

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#625]
It should do so when it receives a REJ that contains enough information.

**Comment by marten-seemann** [comment]
The AEADs have an interesting property, which is not immediately obvious to me.
The server can open messages sealed by a client that created his AEAD **without** a diversification nonce. However, this doesn't work the other way round: the client cannot read messages sealed by the server if he doesn't know the diversification nonce.

I created a little test that should make things obvious: https://gist.github.com/marten-seemann/03282d5175eff2c0c0458749d4c946fa

**Comment by lucas-clemente** [comment]
The diversification nonce only enters the server's encryption key, not its decryption key. See here: https://github.com/lucas-clemente/quic-go/blob/d5ec70fc7db3e498bbd3a7a8db33d2187a1e364c/crypto/key_derivation.go#L66

**Comment by marten-seemann** [comment]
Okay, that's not obvious, but it makes sense now looking at the key derivation code.

What that means for the client crypto setup is the following: We'll need to create two different `secureAEAD`s, one for sealing packets and for opening packets. The one for sealing is created right after sending the non-inchoate CHLO, and the one for opening is created when receiving a diversification nonce. That way we'll be able to send non-forward-secure requests one RTT before becoming forward-secure.

**Comment by marten-seemann** [comment]
The problem with this solution is that we'll need to expand the signaling to the session. At the moment, we try to decrypt undecryptable packets every time something is sent on the `aeadChanged` chan. However, we'd only send `EncryptionLevelSecure` on this channel when creating the `secureAEAD` for sealing (that's the one that doesn't require the diversification nonce), because that's the moment the application can send requests.

**Comment by marten-seemann** [comment]
This has been outdated for a long time.
