### ISSUE TITLE
implement some way to tell if a session is closed

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#632]
An application might want to know if a session is closed (e.g. in order to garbage-collect it). Our current `Session` API doesn't support that.

**Comment by lucas-clemente** [comment]
This doesn't affect h2quic, just other protocols?

Do you think a close callback – possibly with an err – is a good way to solve this?

**Comment by marten-seemann** [comment]
Either a callback, or a method that blocks until the session is closed (and then returns the error). 

I'm not really sure what the nicest solution is. There's nothing comparable in TCP, there the Read and Write calls would fail eventually when the connection is closed. The only comparable  indicicator our API provides at the moment is a failing AcceptStream call, but I don't see how you could use that with every application protocol.

**Comment by marten-seemann** [comment]
We decided OOB to implement a `WaitUntilClosed() error` function in the `Session`.
