### ISSUE TITLE
Wiki logging example not up to date

### ISSUE THREAD

**Issue by twdkeule** [lucas-clemente/quic-go#633]
The example on the wiki page does not use the standard library logging module, but the old one from quic-go/utils.

 ```
@@ -20,7 +20,7 @@
 	panic(err)
 }
 
-log.SetLogWriter(f)
+utils.SetLogWriter(f)
 utils.SetLogLevel(utils.LogLevelDebug)

@@ -33,6 +33,6 @@
 }
 writer := bufio.NewWriter(f)
 
-log.SetLogWriter(writer)
+utils.SetLogWriter(writer)
 utils.SetLogLevel(utils.LogLevelDebug)
 ```

**Comment by lucas-clemente** [comment]
Fixed. Also remove utils.SetLogLevel and replaced it with a hint to the env.

**Comment by lucas-clemente** [comment]
Also updated https://github.com/mholt/caddy/wiki/QUIC. Thanks for the report! :)

**Comment by twdkeule** [comment]
I can't get the logging to work with Caddy.
I used
```
log.SetOutput(f)
utils.SetLogLevel(utils.LogLevelDebug)
```
in caddy/caddy/main.go on both the file and a Buffered Writer, but nothing happens.
I also tried setting the environment variable, but to no avail.

**Comment by lucas-clemente** [comment]
Can you check that you have the latest version of quic-go? I think Caddy now vendors deps.

**Comment by twdkeule** [comment]
Ok, I removed lucas-clemente/ from caddy/vendor/github.com (and form vendor/manifest) and rebased my branch of quic-go on origin/master but this changes nothing. The logfile is still empty.

`go install -v github.com/mholt/caddy/caddy` lists `github.com/lucas-clemente/quic-go` so I assume it is using the correct repo.

Btw, is removing the files from caddy/vendor the correct method to unvendor?

**Comment by lucas-clemente** [comment]
That is unexpected. Are you seeing logs on stdout if you remove the SetOutput() call?

I haven't used vendoring so far, but that seems like a safe way to unvendor ;)

**Comment by twdkeule** [comment]
Nothing.
However if I add `utils.Debugf()` inside the caddy/caddy/main.go it does print debug messages:
```
Log level is debug: true
2017/06/06 10:56:59 DEBUG
2017/06/06 10:56:59 INFO
```
But nothing from quic-go

**Comment by lucas-clemente** [comment]
I see. Caddy seems to set the log writer on its own: https://github.com/mholt/caddy/blob/cbdd3a4f8e92cfadf1fc1e88edae6f0c2f51777c/caddy/caddymain/run.go#L61

So you have to pass `-log stdout` or similar. (Added that to the caddy wiki.)

**Comment by twdkeule** [comment]
I found out at the same time :) It works now. 
It might be interesting to be able to add a prefix (`[quic-go]` for example) to the log output as it now blends in with the log from Caddy. I'm using `utils.SetLogTimeFormat()` for it know, but this is counter-intuitive. I will start a PR if you are interested

**Comment by lucas-clemente** [comment]
I'm very much against exposing (or even documenting) anything in the utils package "officially", which is why we moved to the Go log package and the env for setting the log level.

That being said, I can see the utility of setting a quic-go prefix for the caddy use case. I'd like to get @marten-seemann's input, but I feel that adding a new ENV for that would be a low-cost solution for us API-wise.

**Comment by twdkeule** [comment]
About `QUIC_GO_LOG_LEVEL`: right now it is not very clear what the levels are (eg: is `0` debug, error or fatal?).
Just a small table in the wiki might be nice:
1 for Debug
2 for Info
3 for Error
4 for Disabled

**Comment by lucas-clemente** [comment]
Done :)

**Comment by marten-seemann** [comment]
We now have more intuitive log levels ("DEBUG", "INFO" and "ERROR"), please see https://github.com/lucas-clemente/quic-go/wiki/Logging.
