### ISSUE TITLE
Connect to the server from remote hosts

### ISSUE THREAD

**Issue by zhenyu-zhou** [lucas-clemente/quic-go#634]
Hello,

Following the guidance of README, I make it to use the quic_client (from chromium) to retrieve the data from 127.0.0.1:6121. 

The command for server is:
`go run example/main.go -www <site_path>`
And for client:
`quic_client --host=127.0.0.1 --port=6121 <url>`

However, when I'm trying to connect to the server from a remote host, the client said "QUIC_PEER_GOING_AWAY". The command I'm using is:
`quic_client --host=<public_ip> --port=6121 <url>`

I also tried to start the client at the same machine as the server and met the same problem.

It seems that the socket of the example server is only opened locally. Any idea how to make it work for the remote hosts?

Thanks in advance!

Zhenyu

**Comment by lucas-clemente** [comment]
Just to be sure, you're not pointing the client to an IP address, right? Because that won't work (quic requires certs).

If it's about the ports the server opens, you change that with the `-bind` flag, see https://github.com/lucas-clemente/quic-go/blob/master/example/main.go#L120.

**Comment by zhenyu-zhou** [comment]
Thanks for the reply!

I do have the ip address for the client:
`quic_client --host=**<public_ip>** --port=6121 <url>`

Here the **public_ip** is the ip address of the server and I'm pretty sure the remote host (where the client locates) could ping the host where the server locates. (Do I miss anything here? Is this enough to let the client know where the server is?)

I checked the server port by `netstat -anu` and find the port 6121 is indeed occupied by the server. And I can run a client locally (at the same machine of the server) and retrieve the data successfully. The problem is I cannot make it remotely, even if I provide server's public address to the client and the server is indeed on port 6121. (Note: only difference between the command of local and remote client is the ip address: 127.0.0.1 vs. the server's public ip. Please find the commands in my first post.) Hope this is more clear. Any ideas for this?


As for certs, I indeed didn't take care of it. The good news is that my server has a valid cert. Could you tell me how to setup the certs for the server?

Thanks!

**Comment by lucas-clemente** [comment]
A socket is bound to the pair of ip:port, so if you bind to 127.0.0.1:6121 (the default) you won't receive packets from non-localhost. Try `-bind 0.0.0.0:6121` instead.

As for the certs, there's a flag for that as well. Have a look at the example/main.go source. Alternatively, you could try out [Caddy](caddyserver.com).

**Comment by zhenyu-zhou** [comment]
Thank you so much! I'll try your suggestions soon.

**Comment by zhenyu-zhou** [comment]
It finally works now - thanks for your suggestion to change the binding address!

One more thing, I circumvent the cert check by modifying the code to make it work. It's not an issue for me now.

**Comment by lucas-clemente** [comment]
Happy to help – closing this issue.
