### ISSUE TITLE
quicbench : The QUIC load test and benchmark tool

### ISSUE THREAD

**Issue by yongboy** [lucas-clemente/quic-go#644]
Try it now:

```bash
git clone https://github.com/yongboy/quicbench.git
cd quicbench
go build quicbench
./quicbench -u https://localhost:6121/ -k=true -c 50 -r=10
```

More : https://github.com/yongboy/quicbench

**Comment by lucas-clemente** [comment]
Looks nice! This might be useful for profiling down the road.

I'm gonna close this issue here, but please feel free to reach out if you find any bugs or have questions :)
