### ISSUE TITLE
Retransmit 0-RTT data with FW security as soon as possible

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#656]
We stop accepting the non-FW encryption after receiving the first FW-secured packet in the server. The client should therefore retransmit 0-RTT data using FW encryption, not always with the same level as the initial transmission.

**Comment by marten-seemann** [comment]
We don't have 0-RTT implemented for the client, so I don't think this is an issue.

**Comment by lucas-clemente** [comment]
Okay, but I'd still like to keep this issue around as it's a non-obvious part of the change required for 0-RTT (#438).

**Comment by marten-seemann** [comment]
This is obsolete now that we moved to TLS.
