### ISSUE TITLE
Crypto stream is not send-flow controlled

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#657]
We shouldn't notice this with Chrome, but a peer might send us a very low initial stream level window.

**Comment by marten-seemann** [comment]
The draft now recommends what to do: https://github.com/quicwg/base-drafts/pull/1082
Before the completion of the handshake, flow control limits for stream 0 should be ignored (i.e. bytes are counted, but not limited). This is what we're doing with stream 0 all the time currently.

Fixing this issue requires two changes:

- [ ] turn on send flow control when the handshake completes
- [ ] don't check for receive flow control violations before completion of the handshake

**Comment by marten-seemann** [comment]
IETF QUIC doesn't have flow control for the crypto streams, and there's not been a single issue related to flow control of the gQUIC crypto stream. Considering that gQUIC is transitioning to IEtF QUIC, it seems safe to not fix this.
