### ISSUE TITLE
Don't count the crypto stream as incoming on the server

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#668]
We should fix this in the streams map.

**Comment by marten-seemann** [comment]
I don't think this is what GQUIC is doing.

**Comment by lucas-clemente** [comment]
Maybe, then I think their behavior is wrong. Anyway, it shouldn't cause any issues if we fix this, and I think the streams map is the right place to do this (as opposed to in the config).

**Comment by marten-seemann** [comment]
Not more issues than we currently have at least. The one stream should fall within the 10 streams / 10% tolerance anyway, so that won't hurt.
Can't wait to get the MAX_STREAM_ID frame.
