### ISSUE TITLE
Benchmark flaky when data size is increased to 500MB

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#674]
```
        <*qerr.QuicError | 0xc4673b6660>: {
            ErrorCode: 69,
            ErrorMessage: "Too many outstanding received ACK ranges",
        }
        TooManyOutstandingReceivedPackets: Too many outstanding received ACK ranges
```

**Comment by marten-seemann** [comment]
Can't reproduce it locally, neither on my Mac nor in the VM.
I remember seeing this error when running the benchmark test on Travis with the race detector enabled, so this would be super helpful if fixed.

**Comment by marten-seemann** [comment]
Closing this issue. There were a bunch of changes to the benchmark test recently, which might have solved the problem here.
