### ISSUE TITLE
Determine identity of connected client

### ISSUE THREAD

**Issue by paralin** [lucas-clemente/quic-go#685]
How can I determine the certificate the peer in a session presented? I need to check client certificates for identity verification.

**Comment by marten-seemann** [comment]
Unfortunately, that's not yet possible. The current QUIC crypto handshake doesn't have support for client certificates. Client authentication will be supported once we use TLS 1.3.

See #406 for details.

**Comment by paralin** [comment]
Cool, thank you for the quic response :)

Going to implement my own handshake in the meantime.
