### ISSUE TITLE
Calling utils.setLogLevel from external client.

### ISSUE THREAD

**Issue by f3z0** [lucas-clemente/quic-go#704]
Moving utils to internal (c0b09c8646235c7487c6e8b13f152c3e3e7a9c22) prevents access to utils.setLogLevel outside of the project.

**Comment by marten-seemann** [comment]
That was exactly the point of this commit ;)
utils was never intended as a public API and by marking it internal, we're enforcing that. 

Please have a look at https://github.com/lucas-clemente/quic-go/wiki/Logging for instructions how to enable logging now. Feel free to comment here or open a new issue if you run into any problems.
