### ISSUE TITLE
h2quic frames

### ISSUE THREAD

**Issue by twdkeule** [lucas-clemente/quic-go#717]
I have a quick question about the HTTP2 frames.
The frames defined in the [QUIC draft](https://quicwg.github.io/base-drafts/draft-ietf-quic-http.html#rfc.section.5) are different from the ones in the [HTTP2 standard](https://tools.ietf.org/html/rfc7540#section-4). 
For instance the length field is 3 bytes in HTTP2, but only 2 bytes in QUIC

While working on the PUSH_PROMISE I noticed quic-go uses the HTTP2 frames, not the ones defined in the QUIC draft.
Why is this?
And which ones should I use when implementing #372 ?

**Comment by twdkeule** [comment]
It appears the Google QUIC code base uses the HTTP2 code to construct PUSH_PROMISE frames, so they follow the HTTP2 standard for http over QUIC

**Comment by lucas-clemente** [comment]
We currently implement Google QUIC, which is by now somewhat different from IETF QUIC (what you see in the drafts). We will follow gQUIC as it moves towards IETF QUIC, but for now the newer IETF drafts aren't super helpful :/

**Comment by twdkeule** [comment]
It definitively makes more sense to implement the protocol that is actually being used :)
