### ISSUE TITLE
properly close QUIC connections from the h2quic.RoundTripper

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#735]
When using the (TCP-based) `http.Client`, the connection is closed (i.e. the TCP FIN is sent) when the program exits. When using QUIC, no CONNECTION_CLOSE is sent, but the connection is left open and will eventually run into the timeout set by the peer.

This would be an easy thing if we had destructors available in Go, but without those, things might get a bit tricky.

**Comment by marten-seemann** [comment]
I just learned about [runtime.SetFinalizer](https://golang.org/pkg/runtime/#SetFinalizer), but those are not guaranteed to be run when the program exits.

**Comment by lucas-clemente** [comment]
I don't think SetFinalizer is meant to run on exit, it's GC related. One option would be something like an [atexit](https://linux.die.net/man/3/atexit) call, but I don't think that works in Go.

Honestly though, if we provide the proper methods for closing (which we do), then I don't think there's much we can (or need to) do. What's the worst that could happen?

NB: (static) destructors in C++ only run when the program normally exits (by returning from main), not e.g. on SIGINTs.

**Comment by marten-seemann** [comment]
This is true for the h2quic.Server, but there's no way to call Close when you're using the h2quic.RoundTripper.

**Comment by marten-seemann** [comment]
Thinking about this a bit more, for the reason mentioned above this is only a client issue. However, it doesn't occur only when the program exits, but essentially everytime the `h2quic.RoundTripper` falls out of scope: In that case we can be sure that the QUIC connections won't be reused, so in order to be nice and friendly to the QUIC servers we have been talking to we should close the connection asap.

**Comment by lucas-clemente** [comment]
Okay, then finalizers are better than nothing. SGTM.

**Comment by marten-seemann** [comment]
It's better than nothing, but that's probably the only good think about the finalizer solution.
I'm wondering if there's a better solution. A finalizer is never guaranteed to execute at all, it **only** runs when the object is garbage collected. This doesn't happen when the program is closed or if sufficient stack memory is available.

**Comment by lucas-clemente** [comment]
Yeah, but that's what we have FC and timeouts for. I wouldn't worry about this too much.
