### ISSUE TITLE
implement DialContext in h2quic.RoundTripper

### ISSUE THREAD

**Issue by yinqiwen** [lucas-clemente/quic-go#747]
If set, 
1. Users can use other dns lib instead of the default one which may have  polluted dns result.
2. Log & monitor the handshake latency.

**Comment by lucas-clemente** [comment]
LGTM, though I'd argue for implementing only `DialContext`, as `DialAddr` is deprecated for on [http.Transport](https://golang.org/pkg/net/http/#Transport).

**Comment by marten-seemann** [comment]
What would the signature of our `DialContext` be?
```DialContext func(ctx context.Context, network, addr string) (quic.Session, error)```, right?

**Comment by lucas-clemente** [comment]
No, it should return a `net.PacketConn`.

**Comment by marten-seemann** [comment]
Makes sense. And this `net.PacketConn` would then be used for calling `quic.Dial`.

I'm marking this issue as want-help, since I don't think I will have the time to write a fix for this any time soon.

**Comment by marten-seemann** [comment]
I just wrote a fix for this, and came to the conclusion that returning a `quic.Session` is indeed the right thing to do. Please see #1120 for details.
