### ISSUE TITLE
Example integration with golang.org/x/crypto/acme/autocert

### ISSUE THREAD

**Issue by bradrydzewski** [lucas-clemente/quic-go#763]
I was wondering if / how this package could integrate with `golang.org/x/crypto/acme/autocert`. I am actively trying to figure this out and will happily post back once I have a working solution, but I figured I would ask here first in case someone has a snippet to share.

Perhaps an example could be included in the readme or example directory?

**Comment by lucas-clemente** [comment]
We implement the same logic as Go's standard library for the [tls.Config](https://golang.org/pkg/crypto/tls/#Config) passed to us in the Serve methods. That means that any code snippet you find for setting up the Config should apply yo us in the same way. If it doesn't, it's a bug :)

I don't know autocert, but it looks like it provides the `GetCertificate` callback for the tls.Config [here](https://godoc.org/golang.org/x/crypto/acme/autocert#Manager.GetCertificate). Let us know if you get it working!

**Comment by bradrydzewski** [comment]
Thanks, I managed to get it working. It roughly looks something like this:

```Go
funct main() {

	var dir string           // lets encrypt cache directory
	var host string          // your server hostname
	var handler http.Handler // your default http handler

	manager := autocert.Manager{
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist(host),
		Cache:      autocert.DirCache(dir),
	}

	httpServer := &http.Server{
		Addr:    ":443",
		Handler: handler,
		TLSConfig: &tls.Config{
			GetCertificate: manager.GetCertificate,
			NextProtos:     []string{"h2", "http/1.1"},
		},
	}
	
	quicServer := &h2quic.Server{
		Server: httpServer,
	}

	quicServer.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		quicServer.SetQuicHeaders(w.Header())
		handler.ServeHTTP(w, r)
	})

	conn, err := net.ListenPacket("udp", ":443")
	if err != nil {
		log.fatalf(err)
	}

	go run quicServer.Serve(conn)
	go run http.Serve(manager.Listener(), quicServer.Handler)
}
```

thanks for the library :)

**Comment by KempWatson** [comment]
This is certainly not the same way that http.ListenAndServeTLS works... I've tried doing the same, passing two empty strings to h2quic.ListenAndServeTLS. Standard library works with Let's Encrypt, QUIC does nothing.
