### ISSUE TITLE
Add support for HTTP/2 SETTINGS frame

### ISSUE THREAD

**Issue by twdkeule** [lucas-clemente/quic-go#775]
As far as I know there is no support for the HTTP/2 SETTINGS frame (https://quicwg.github.io/base-drafts/draft-ietf-quic-http.html#rfc.section.5.2.4).
This means we cannot disable/enable fro example server push. 

Google QUIC has it:
```
[0705/020214.964850:VERBOSE1:http2_frame_decoder_adapter.cc(160)] OnFrameHeader: length=6, type=SETTINGS, flags=, stream=0
[0705/020214.964936:VERBOSE1:http2_frame_decoder_adapter.cc(374)] OnSettingsStart: length=6, type=SETTINGS, flags=, stream=0
[0705/020214.965012:VERBOSE1:http2_frame_decoder_adapter.cc(383)] OnSetting: parameter=MAX_HEADER_LIST_SIZE, value=16384
[0705/020214.965060:VERBOSE1:http2_frame_decoder_adapter.cc(398)] OnSettingsEnd
```

**Comment by marten-seemann** [comment]
I'm not sure I understand. The IETF draft describes how to send a SETTINGS frame.

However, the important this for us a Google QUIC anyway at the moment. The relevant question here is how a Google server (or the toy quic_server) responds to a H2 settings frame sent on the header stream. Is that what the log here shows?

**Comment by twdkeule** [comment]
Yes, this is the proto-quic toy server receiving a SETTINGS frame. 
I added the draft, because not all parameters of the HTTP/2 SETTINGS frame are valid in QUIC.

**Comment by marten-seemann** [comment]
Yeah, iirc it's not possible to change SETTINGS once they are set, thus also removing the necessity for a SETTINGS_ACK (which would be quite challenging to implement given that this must work with arbitrary reordering of packets).

We should probably add SETTINGS support before merging #715, since a push to a client that doesn't accept push will result in a connection error. Do you agree?

**Comment by twdkeule** [comment]
The QUIC WG is changing a lot of things concerning Server Push and the settings frame: https://github.com/quicwg/base-drafts/pull/711

**Comment by marten-seemann** [comment]
I saw those. However, if we want to support Push before Chrome implements this part of the draft (which might take a while), we should implement the right SETTINGS frame for gQUIC.

**Comment by marten-seemann** [comment]
Obsolete with #1852.
