### ISSUE TITLE
Chrome sometimes doesn't reload pages

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#80]
Steps to reproduce:

- Open Chrome on a page
- Hit ⌘+⇧+R
- Reloading doesn't stop, although the server logs HTTP responses

**Comment by marten-seemann** [comment]
I can't reproduce the bug.
@lucas-clemente: Please reconfirm that it still exists.

**Comment by lucas-clemente** [comment]
Can't reproduce either. Probably this issue was fixed with #69.
