### ISSUE TITLE
Supported QUIC version?

### ISSUE THREAD

**Issue by neilstuartcraig** [lucas-clemente/quic-go#838]
Hi all

I was just wondering if there's an easy way to know which QUIC version(s) a release of `quic_go` supports - i didn't find anything obvious from a look around the repo. I use Caddy so this would feed in to when i should update that and what to expect.

Cheers
Neil

**Comment by marten-seemann** [comment]
Hi Neil,

you can find the currently supported versions here: https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/version.go#L21-L27.
We're adding support for new QUIC versions as soon as Chrome Canary or Chrome Beta adds them, and we're dropping old versions a couple of weeks after Chrome Stable drops them. That way, quic-go is always compatible with basically all Chrome version that are currently in use.

If you're running Caddy, there's even an easier way to see which QUIC versions are supported: Just look at the Alt-Svc HTTP Header, which will contain a list of the supported versions.

**Comment by neilstuartcraig** [comment]
Thanks for replying so quickly @marten-seemann - much appreciated. That's exactly the info i was looking for. 

The reason for asking is that i noticed when Chrome 61 came out this week that my website's QUIC support stopped working as it's doing QUIC/38- and Chrome stable now uses QUIC/39. I think i am on Caddy `0.10.8` so upgrading to `0.10.9` might fix that, i'll give it a look/try.

Thanks again
