### ISSUE TITLE
set FinBit in last StreamFrame

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#87]
Right now, we're sending out an empty StreamFrame just to set the FinBit.

**Comment by marten-seemann** [comment]
It probably makes sense to do this when refactoring the `Stream.Read`for #84.

**Comment by marten-seemann** [comment]
The spec says:

> A stream frame must always have either non-zero data length or the FIN bit set.

So we probably shouldn't fix it.

**Comment by marten-seemann** [comment]
The spec says:

> A stream frame must always have either non-zero data length or the FIN bit set.

So we're actually doing it right.

**Comment by zrlw** [comment]
> The spec says:
> 
> > A stream frame must always have either non-zero data length or the FIN bit set.
> 
> So we're actually doing it right.

outdated.
[current spec](https://www.rfc-editor.org/rfc/rfc9000.html#section-19.8)
```
The FIN bit (0x01) indicates that the frame marks the end of the stream. The final size of the stream is the sum of the offset and the length of this frame.
```

**Comment by marten-seemann** [comment]
> outdated.

Who could have thought that a (closed!) issue from 2016 might be outdated? I'm shocked!
