### ISSUE TITLE
Status and stability of master ?

### ISSUE THREAD

**Issue by chmike** [lucas-clemente/quic-go#906]
What is the status of this package ? Is it functional ? May I use it in  a project to transmit data (not web related) ? I see that master CI build is currently in error on linux.

Are there plans to keep master a production ready branch and use a develop branch  for commits that may break releases ? 

This is because go get fetches the master branch.

**Comment by lucas-clemente** [comment]
We are most certainly alive and actively working on quic-go :) Master is as production ready as it gets for us – which means there might still be breaking API changes from time to time as QUIC evolves. The implementation itself should be stable, with the caveat of the known issues in the bugtracker.

We have a quite extensive test suite and some hard-to-hunt-down bugs that are causing travis to be flaky, but I wouldn't worry about that too much.

Does that answer your questions?

**Comment by chmike** [comment]
Yes, thank you very much. I'm considering using QUIC for a Go program that will send FITS images from telescopes over long distances. I'm currently using tcp, but it is not convenient to adapt for long distances because of the need for users to adjust the buffer capacity. So I would be interested to use QUIC as a replacement for TCP for this app. 

Does QUIC-go self adjust its buffer needs for long distance connections (e.g 1Gbit/s &250ms RTT) ?

Is there another method to communicate with you to avoid creating issues ? 

What you do is a great work. Thank you very much.

**Comment by lucas-clemente** [comment]
I think it would definitely interesting to give QUIC a shot. We're seeing better performance than TCP in a lot of benchmarks, and it's much easier to adapt the congestion to your specific requirements.

The receive buffer can be adjusted in our [config](https://godoc.org/github.com/lucas-clemente/quic-go#Config) (via the flow control receive window parameters).

Let us know if you get any interesting results! Feel free to reach out via email (it's on my github profile).

**Comment by chmike** [comment]
My throughput measurement was not serious. I just measure the average speed for sending a 64MB file from connection opening to connection close. If BBR is used, the throughput should increase as QUIC seeks the optimal throughput. If BBR is used, the optimal throughput should be in an internal variable, as well as the minimal RTT. 

I saw that the MSS was set to 1200. It is often 1500. It might be interesting to add it to the set of configuration variables. 1200 could be a default value. Is it constant or adjusted ?

**Comment by marten-seemann** [comment]
We're currently not using BBR, but a Cubic version adopted for QUIC.

According the QUIC spec, the maximum packet size is 1200 bytes (unless an implementation does PMTUD). That's why we can't introduce a configuration option to set that value. You can try to increase it manually in the constants and see if it changes anything.

**Comment by marten-seemann** [comment]
@chmike, I'm closing this issue. Please feel free to open a new issue if you have any further questions.
