### ISSUE TITLE
HandleCryptoStream errorChan not always read

### ISSUE THREAD

**Issue by Eichhoernchen** [lucas-clemente/quic-go#953]
Hi,

quic-go is leaking goroutines in `HandleCryptoStream` (https://github.com/lucas-clemente/quic-go/blob/master/internal/handshake/crypto_setup_client.go#L111).

I haven't quite figured out what chain of events trigger this leak but I started to notice that my quic-go enabled application consumes more and more memory.

I used pprof and delve and found that I have many outstanding goroutines:
`github.com/lucas-clemente/quic-go/internal/handshake(*cryptoSetupClient).HandleCryptoStream.func1+0x122`
This is the goroutine that parses handshake messages.

Upon debugging with delve I found that these routines hang on sending on the error channel in `HandleCryptoStream`. It seems that the `cryptoSetupClient` has already been freed (so the session is closed and `HandleCryptoStream` has exited). So at this point and there is no one left to read the error from the error channel causing the block in the goroutine to write to the channel effectively leaking the routine.

I think `HandleCryptoStream` should make sure that the goroutine has finished before exiting.
For example, if `maybeUpgradeCrypto` or `sendCHLO` fail, the goroutine could still process data and fail (also on success the `messageChan` would block) and cause leaks.

Best
 Jan

**Comment by Eichhoernchen** [comment]
Could it already help to create the errorChan with a capacity of 1 such that the operation won't block? I think the goroutine will ever only write once to the channel, this should remove the deadlock  or not?

**Comment by Eichhoernchen** [comment]
I changed this locally, it seems to resolve the issue, after 10 M QUIC connections, quic-go returns to its original state and memory consumption

**Comment by marten-seemann** [comment]
Hi Jan, I haven't had the time to look into this yet, I only read your comments here. Seems like you already put a fair amount of debugging effort into this, thanks for that!
Could you send us a PR with your fix?

**Comment by Eichhoernchen** [comment]
Hi Marten,

I filed a PR (#955).
I'll close this issue one it is pulled.
