### ISSUE TITLE
go fmt the code

### ISSUE THREAD

**Issue by AudriusButkevicius** [lucas-clemente/quic-go#957]
It makes any go developers eyes bleed.

**Comment by marten-seemann** [comment]
The code is go fmted.

**Comment by AudriusButkevicius** [comment]
but gofmt uses tabs, you guys use 2 spaces.

**Comment by marten-seemann** [comment]
We don't.

**Comment by AudriusButkevicius** [comment]
Which means the code is not go fmt'ed, as go fmt provides a consitent formatting.

**Comment by AudriusButkevicius** [comment]
Actually you are right, I am not sure why github shows it in such an unreadable way.

**Comment by AudriusButkevicius** [comment]
Ok, github respects .editorconfig which makes the code ackward looking.

**Comment by AudriusButkevicius** [comment]
Whats the reason behind that?
It makes this project stand out and make it hard to read in github.
