### ISSUE TITLE
Ask about quic-go v0.6

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#959]
Hi guys,
Any body know when the quic-go v0.6 will be released?

**Comment by marten-seemann** [comment]
We don't have any plans about this, since tags don't matter in Go anyway. You can just use the master.

**Comment by LFlare** [comment]
Hello @marten-seemann,

I would like to point out that the guys over at Caddy are really just waiting for you to tag a release for `0.6.0` before updating their side of things to allow for QUIC 39. https://github.com/mholt/caddy/issues/1858

**Comment by marten-seemann** [comment]
That's unfortunate, they shouldn't wait. I commented on the issue there.

**Comment by LFlare** [comment]
Thanks for clarifying on the issue, glad you helped to clear things up over there as well, I've been sitting dry without QUIC for awhile now. :)
