### ISSUE TITLE
implement a sanity check for the RTT calculation using the ACK delay

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#965]
There seems to be a vulnerability, where a peer could send us ACK delays designed to keep our RTT estimate close to 0. There's a fix for that on the way in https://github.com/quicwg/base-drafts/pull/975, which we should implement asap.

**Comment by lucas-clemente** [comment]
That’s only a problem for pacing, or do you see any other issues a zero RTT
estimate could cause?

**Comment by marten-seemann** [comment]
We'd increase our congestion window and our receive buffers due to flow control autotuning.

**Comment by marten-seemann** [comment]
Chrome recently implemented this: https://chromium-review.googlesource.com/c/chromium/src/+/873930
